- docs/fides/docs/index.md
Updated to include video asset.
* Added embedded Youtube video
* Updated index.md
> Documentation updates to add video

- docker-compose.yml
- fidesctl/Dockerfile
- fidesctl/src/fidesapi/crud.py
- fidesctl/src/fidesapi/db_session.py
- fidesctl/src/fidesapi/errors.py
- fidesctl/src/fidesapi/main.py
- fidesctl/src/fidesctl/cli/cli.py
- fidesctl/src/fidesctl/core/api_helpers.py
- fidesctl/tests/core/test_api.py
Closes #212 
Closes #233 
The [FastAPI documentation on error handling](https://fastapi.tiangolo.com/tutorial/handling-errors) defines the `HTTPException` as the best way to handle errors and return useful information to the caller.
> Improve API Error Handling

- docs/fides/docs/development/code_style.md
- docs/fides/docs/development/documentation.md
- docs/fides/docs/development/overview.md
- docs/fides/docs/development/releases.md
- docs/fides/docs/installation/pypi.md
Closes #188 
Closes #234 
Closes #142 
This PR is focused on concretely stating some of the decisions we've made as a core team (within multiple GitHub discussions)
> Discussion results docs update

- fidesctl/src/fidesapi/main.py
- fidesctl/src/fidesapi/view.py
- fidesctl/tests/data/failing_declaration_taxonomy.yml
Closes #237 
* Add a new router endpoint which displays evaluations list
* Style this page?
> Add a simple page for evaluations

- fidesctl/Dockerfile
- fidesctl/requirements.txt
- fidesctl/setup.py
Closes #217 
This PR loosens the requirements a bit so that someone with a python project could more easily integrate it
> Loosen requirements for fidesctl

- fidesctl/src/fidesapi/view.py
- fidesctl/src/fideslang/models.py
> Fix evaluations page after evaluation model refactor

- docs/fides/docs/tutorial/pass.md
> fix: spelling typo

- docs/fides/docs/guides/generate_dataset.md
- docs/fides/docs/guides/scan_resource.md
- docs/fides/docs/tutorial/add.md
- docs/fides/docs/tutorial/dataset.md
- docs/fides/docs/tutorial/google.md
- docs/fides/docs/tutorial/pass.md
- docs/fides/docs/tutorial/policy.md
- docs/fides/docs/tutorial/system.md
Closes #297 
Ran `make docs-serve` to spin it up locally and confirmed that it looks good.
I updated the tutorial's Google Analytics step to have the *correct* **incorrect** policy to set it up for the next step. 
Additionally, I found a formatting issue and resolved it, where the bold typeface didn't work right.
👀 I'm looking to get a second set of eyes on the Google Analytics change, to make sure that the error I found is wrong and that I fixed it correctly.
> RK Tutorial Content and Formatting Edits

- README.md
We're exploring the option of offering a free, hosted version of Fidesctl, and are looking to gauge community interest in this offering!
> added cta for hosted ctl waitlist

- docs/fides/docs/guides/generate_resources.md
Closes #343
Should have been part of https://github.com/ethyca/fides/pull/387
> Add documentation for filtering AWS resources

- README.md
Closes #353 
updating README with feedback from @banagale to reduce repetition and increase readability
> Updated README expansion title

- docs/fides/docs/css/fides.css
Color updates to reflect brand specific colors and to ensure all copy meets accessibility guidelines.
> CSS updates to reflect brand colors on docs 

- fidesctl/setup.py
- fidesctl/src/fidesctl/core/apply.py
> Add `(s)` to the apply command

- fidesctl/src/fidesctl/cli/utils.py
- fidesctl/tests/cli/test_cli_utils.py
> Change the version exception to a warning

- README.md
> Fix badge links to point to actions 

- .github/pull_request_template.md
- CHANGELOG.md
- docs/fides/docs/development/releases.md
Closes #481 
As the project matures and gains traction, we need to also iterate on our processes to give our users a more stable and reliable experience. All PRs from here on will require a `CHANGELOG.md` addition and a final PR will be merged before each release to properly format the changelog for that release
While this is a slightly more manual process than I would generally like, I feel that this level of manual care is worth it and important to the overall quality of the project.
> Create a CHANGELOG.md and update processes

- CHANGELOG.md
- README.md
- docs/fides/docs/quickstart/docker.md
- docs/fides/docs/quickstart/local_full.md
- docs/fides/docs/quickstart/local_standalone.md
- docs/fides/docs/tutorial/add.md
- src/fidesctl/cli/commands/util.py
- src/fidesctl/cli/utils.py
> Send an `AnalyticsEvent` on `fidesctl init` execution

- CHANGELOG.md
- src/fidesctl/cli/commands/annotate.py
- src/fidesctl/cli/commands/core.py
- src/fidesctl/cli/commands/crud.py
- src/fidesctl/cli/commands/db.py
- src/fidesctl/cli/commands/export.py
- src/fidesctl/cli/commands/generate.py
- src/fidesctl/cli/commands/scan.py
- src/fidesctl/cli/commands/util.py
- src/fidesctl/cli/commands/view.py
- src/fidesctl/cli/utils.py
Closes #393
As is, the changes should equate to the same behavior but using the new decorator now. This could still use some tests, last thing im looking into.
> Refactor with_analytics function into a decorator

- CHANGELOG.md
- docs/fides/docs/development/releases.md
> Update Release Steps

- .github/workflows/docker.yaml
- .github/workflows/publish_docs.yaml
Closes <issue>
Fix some small issues that cropped up in workflows that get run on merge to main
> Fix Merge Workflows

- docker-compose.yml
I goofed and committed something I shouldn't have!
> Restore volume mount

- .github/workflows/frontend_pr_checks.yml
- clients/admin-ui/package.json
Closes https://github.com/ethyca/fides/issues/643
The workflow file only looks for frontend changes. This is essentially a copy of the same thing I did over in fidesops https://github.com/ethyca/fidesops/pull/510
> Add github action for frontend code

- docs/fides/docs/js/matomo.js
- docs/fides/mkdocs.yml
Adding matomo analytics to provide anonymized data about site visits
> Matomo analytics

- clients/admin-ui/src/features/common/Icon/StepperCircle.tsx
- clients/admin-ui/src/features/common/Icon/StepperCircleCheckmark.tsx
- clients/admin-ui/src/features/common/Icon/VerticalLine.tsx
- clients/admin-ui/src/features/common/Icon/index.tsx
- clients/admin-ui/src/features/common/Stepper.tsx
- clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
> [747] Stepper updates

- clients/admin-ui/package-lock.json
- clients/admin-ui/package.json
- clients/admin-ui/src/features/common/form/inputs.tsx
- clients/admin-ui/src/features/dataset/EditCollectionOrFieldForm.tsx
Closes https://github.com/ethyca/fides/issues/770
Here's a small test case I made to develop on:
https://user-images.githubusercontent.com/24641006/173940158-313d34dc-ff04-4844-8482-e71f123a36e5.mov
> Multiselect component

- clients/admin-ui/src/features/common/NavBar.tsx
- clients/admin-ui/src/pages/dataset/index.tsx
- clients/admin-ui/src/pages/taxonomy/index.tsx
Removes WIP features to prepare for 1.7.0 release 🎉 
After discussing with @mfbrown , we decided to do the following to get ready for release:
> Remove wip features

- clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
- clients/admin-ui/src/features/config-wizard/ViewYourDataMapPage.tsx
- clients/admin-ui/src/features/config-wizard/constants.tsx
> [#599]Finish page

- requirements.txt
- src/fidesapi/database/database.py
Closes -
~* [ ] Update `CHANGELOG.md`~
Preparation for [831](https://github.com/ethyca/fides/issues/831)
> Add fideslib and update other dependencies

- CHANGELOG.md
- docs/fides/docs/development/releases.md
> Document the patch release process

- docs/fides/docs/installation/configuration.md
> logging section table format fix

- clients/ctl/admin-ui/cypress/e2e/datasets.cy.ts
- clients/ctl/admin-ui/cypress/e2e/taxonomy.cy.ts
- clients/ctl/admin-ui/cypress/fixtures/data_categories.json
- clients/ctl/admin-ui/cypress/fixtures/data_qualifiers.json
- clients/ctl/admin-ui/cypress/fixtures/data_subjects.json
- clients/ctl/admin-ui/cypress/fixtures/data_uses.json
- clients/ctl/admin-ui/cypress/fixtures/dataset.json
- clients/ctl/admin-ui/cypress/fixtures/datasets.json
There have been a few updates to fideslang, so this updates the Cypress fixtures to have up to date data. Unfortunately some of the tests relied on fields that no longer exist in fideslang, so there were quite a few updates to be made to the tests too.
> Update cypress fixtures

- .github/workflows/publish_docker.yaml
- .github/workflows/publish_package.yaml
- .github/workflows/release_event.yml
- docker-compose.yml
Closes <issue>
Quick update that lets us start playing with `unified-fides` build artifacts (`docker` and `pypi`)
> Update workflows to push unified artifacts

- CHANGELOG.md
- clients/ctl/admin-ui/src/features/common/Header.tsx
Closes #1043
A truly "I'm doing my part" PR that fixes the help link in the header
> Fix header help link

- .fides/dataset.yml
- CHANGELOG.md
- requirements.txt
- src/fidesctl/api/ctl/migrations/versions/6bd93cb0603d_add_egress_and_ingress_to_systems.py
- src/fidesctl/api/ctl/sql_models.py
Related to ethyca/fidesctl-plus#101
> Bump fideslang to 1.3.0

- CHANGELOG.md
- clients/ctl/admin-ui/cypress/e2e/systems.cy.ts
- clients/ctl/admin-ui/cypress/support/stubs.ts
- clients/ctl/admin-ui/src/app/store.ts
- clients/ctl/admin-ui/src/features/common/form/inputs.tsx
- clients/ctl/admin-ui/src/features/system/DescribeSystemStep.tsx
- clients/ctl/admin-ui/src/features/system/DescribeSystemsFormExtension.tsx
- clients/ctl/admin-ui/src/features/system/ManualSystemFlow.tsx
- clients/ctl/admin-ui/src/features/system/PrivacyDeclarationAccordion.tsx
- clients/ctl/admin-ui/src/features/system/PrivacyDeclarationForm.tsx
- clients/ctl/admin-ui/src/features/system/PrivacyDeclarationStep.tsx
- clients/ctl/admin-ui/src/features/system/ReviewSystemStep.tsx
- clients/ctl/admin-ui/src/features/system/SystemCard.tsx
- clients/ctl/admin-ui/src/features/system/form.ts
- clients/ctl/admin-ui/src/features/system/system.slice.ts
Closes https://github.com/ethyca/fides/issues/1035
https://user-images.githubusercontent.com/24641006/191358638-cc9712bd-71f4-4baf-b2ce-b43bc9342962.mov
> Edit system UI

- CHANGELOG.md
> Prepare changelog for 1.9.0 release

- CHANGELOG.md
- requirements.txt
Related to ethyca/fidesctl-plus#133
> Bump fideslang to 1.3.1

- CHANGELOG.md
- requirements.txt
Related to ethyca/fidesctl-plus#133
> Prepare 1.9.1 release

- docker-compose.yml
Closes #1138 
* put vault environment variables in docker-compose for `fides` container
1. nox -s dev -- shell
2. pytest tests/ops/integration_tests/saas/test_stripe_task.py -k test_stripe_connection_test
> [Unified Fides] add vault environment variables to docker-compose container

- CHANGELOG.md
- clients/ops/privacy-center/components/ConsentItemCard.tsx
Closes #1161 
* Fix issue with width of the consent item cards
* Add a new consent preference with a very short description
Update the width to grow to the width of the parent container.
> Fix styling issue with consent items

- scripts/create_test_data.py
- src/fides/api/ops/models/connectionconfig.py
- src/fides/api/ops/models/manual_webhook.py
- src/fides/api/ops/task/graph_task.py
> Fix seed_test_data

- noxfiles/ci_nox.py
- tests/ops/fixtures/saas/hubspot_fixtures.py
- tests/ops/integration_tests/saas/test_adobe_campaign_task.py
- tests/ops/integration_tests/saas/test_auth0_task.py
- tests/ops/integration_tests/saas/test_hubspot_task.py
- tests/ops/integration_tests/saas/test_outreach_task.py
- tests/ops/integration_tests/saas/test_salesforce_task.py
- tests/ops/integration_tests/saas/test_segment_task.py
- tests/ops/integration_tests/saas/test_sendgrid_task.py
- tests/ops/integration_tests/saas/test_shopify_task.py
- tests/ops/integration_tests/saas/test_stripe_task.py
- tests/ops/integration_tests/saas/test_zendesk_task.py
> Updating call to core config for SaaS connector tests

- .github/workflows/backend_checks.yml
- CHANGELOG.md
- Dockerfile
- dev-requirements.txt
- docs/fides/Dockerfile
> Upgrading mypy

- clients/privacy-center/components/ConsentItemCard.tsx
- clients/privacy-center/features/consent/helpers.ts
- clients/privacy-center/features/consent/types.ts
A few type errors were introduced by https://github.com/ethyca/fides/pull/1364, this cleans that up to get `main` building cleanly again.
> Fix Typescript errors for consent cookie

- src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_doordash.py
Closes #1471
There are a couple other open PRs that contain this fix, but they are unrelated to this issue and only contain the fix to resolve the mypy error. Because they are for different topics they could take longer to get reviewed and merged so I am opening this PR to fix the error quicker.
> Fix mypy error

- tests/ctl/api/test_ui.py
Closes <issue>
Temporarily xfail the failing ui test while we find a solution.
> Xfail test while we look for a solution

- clients/admin-ui/cypress/e2e/config-wizard.cy.ts
- clients/admin-ui/src/flags.json
Closes [Update Config Wizard flag to false by default#1539](https://github.com/ethyca/fides/issues/1539)
> set configWizardFlag to false 

- clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
Closes #1575 
- Updated the privacy-requests.slice.ts to short circuit the `errorRequests.length` snippet from returning undefined when being referenced.
> 1575-unhandled-runtime-error

- CHANGELOG.md
- clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
Closes #1592 
- Updated privacy-requests.slice.ts (getAllPrivacyRequests method)
> 1592-Remove thrown exception from getAllPrivacyRequests method

- docs/fides/docs/guides/generate_datamaps.md
Fix the data map export command referenced in the docs.
> Fix the export command in the datamap docs

- clients/admin-ui/cypress/e2e/config-wizard.cy.ts
- clients/admin-ui/src/features/config-wizard/AddSystemForm.tsx
- clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx
- clients/admin-ui/src/features/config-wizard/ScanResultsForm.tsx
> Revert "1479/systems without declarations default"

- src/fides/api/ops/service/saas_request/__init__.py
Closes #1638 
* add import statement missed in unified fides merge. see issue for more details.
> add missing firebase auth override import

- src/fides/cli/commands/util.py
- src/fides/cli/utils.py
- src/fides/ctl/core/deploy.py
This builds on top of https://github.com/ethyca/fides/pull/1643 to finish up a few remaining items:
* prompts for registration during `fides init`
* prompts for registration during `fides deploy`
* re-prompts for consent if registration is unset
* fixes a few minor issues along the way
This'll merge directly into the branch for https://github.com/ethyca/fides/pull/1643, just opening it here as a record to see the differences in isolation.
> Update fides init & fides deploy to use new registration prompt

- requirements.txt
> Bump fideslib from 3.1.4 to 3.1.5

- CHANGELOG.md
- optional-requirements.txt
- requirements.txt
Closes #1682 
Got a slew of CI errors despite having pinned versions for requirements, thinking it might be something to do with the OpenSSL issues recently. Bumping various versions to figure out the fix
> Update OpenSSL-affected requirements

- CHANGELOG.md
- clients/admin-ui/src/features/system/DescribeSystemStep.tsx
Closes #1533 
* Updated **System key** tooltip text (Please reference https://ethyca.github.io/fideslang/resources/system/)
1. Click **Systems**
2. Click the **Create New System** button
3. Click the **Manually generate a system** button
4. Hover your cursor over the **System key** question mark icon
> 1533 - Update system fides_key tooltip text

- CHANGELOG.md
- clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx
- clients/privacy-center/config/config.json
- clients/privacy-center/package-lock.json
- clients/privacy-center/package.json
- scripts/create_test_data.py
- src/fides/api/ops/schemas/redis_cache.py
- tests/ops/api/v1/endpoints/test_consent_request_endpoints.py
- tests/ops/api/v1/endpoints/test_drp_endpoints.py
- tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py
- tests/ops/fixtures/application_fixtures.py
- tests/ops/models/test_privacy_request.py
Closes [1730](https://github.com/ethyca/fides/issues/1730)
> 1730 phone identity validation

- docs/fides/docs/development/release_checklist.md
n/a
n/a
Adds a bit of structure and documents a few post-release steps for our 2.x process.
> Update release checklist

- CHANGELOG.md
- src/fides/__init__.py
- src/fides/api/main.py
- src/fides/ctl/core/config/security_settings.py
- src/fides/ctl/core/config/utils.py
- src/fides/data/sample_project/docker-compose.yml
- src/fides/data/sample_project/fides.toml
- tests/ops/api/test_ratelimit.py
* Only check for required variables when the webserver is run
* make the "required" config values optional
* refactor the error message and place it at the start of the webserver function
* update the changelog
* fix static checks
* fix the fides deploy check
Closes <issue>
> Only check for required variables when the webserver is run (#1811)

- CHANGELOG.md
- noxfiles/dev_nox.py
- src/fides/__init__.py
- src/fides/api/main.py
- src/fides/ctl/core/config/security_settings.py
- src/fides/ctl/core/config/utils.py
- src/fides/data/sample_project/docker-compose.yml
- src/fides/data/sample_project/fides.toml
- tests/ops/api/test_ratelimit.py
> Release 2.1.0

- CHANGELOG.md
- src/fides/api/ctl/database/seed.py
- src/fides/api/main.py
- tests/ctl/api/test_seed.py
Closes #1832 
* handle base case of same parent user credentials on startup
* add some test coverage around this case
* make sure errors in parent user creation are at least logged
* Check issue description
> 1832 error parent user creation

- clients/admin-ui/cypress/e2e/config-wizard.cy.ts
- clients/admin-ui/src/features/config-wizard/AddSystemForm.tsx
- clients/admin-ui/src/features/config-wizard/constants.tsx
- clients/admin-ui/src/features/datastore-connections/add-connection/constants.ts
- clients/admin-ui/src/features/system/constants.ts
Closes https://github.com/ethyca/fidesctl-plus/issues/339
> Update copy on `Scan for Systems` page

- CHANGELOG.md
- src/fides/api/ops/models/privacy_request.py
- src/fides/api/ops/service/connectors/saas_query_config.py
Closes https://github.com/ethyca/fides/issues/1901
> filters out identity pairs where val is none or empty string

- clients/admin-ui/src/features/plus/plus.slice.ts
This PR adds the authentication token to previously unauthenticated `fidesplus` API calls.
> Fidesplus API auth

- .github/workflows/release_event.yml
https://github.com/ethyca/fides-helm/pull/6
* Add dispatch event, adding Fides-helm as another downstream dependency
> Add fides-helm release dispatch event

- tests/ops/conftest.py
Collateral improvements from a recent debug, this PR fixes a long standing typo in fixtures.
> fixes a long standing typo in fixtures

- clients/admin-ui/src/constants.ts
- src/fides/api/ops/util/oauth_util.py
> Fix regressions in user management

- CHANGELOG.md
> Release Fides v2.2.1

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.2.2

- .github/pull_request_template.md
Closes DOX-240
* Update the PR template to ensure the new docs repo is included in the review checklist
> update the PR template to reference fidesdocs

- docker/docker-compose.integration-timescale.yml
- tests/ops/fixtures/timescale_fixtures.py
> pin timescale to previous version

- CHANGELOG.md
> Match changelog to release branch

- clients/admin-ui/src/features/common/features.slice.ts
* Setting the nav 2 flag to false 
> set nav 2 flag to false

- .fides/fides.toml
- CHANGELOG.md
- src/fides/data/test_env/fides.test_env.toml
closes https://github.com/ethyca/fides/issues/2059
> Adds notifications section to toml

- CHANGELOG.md
- clients/admin-ui/cypress/e2e/auth.cy.ts
- clients/admin-ui/cypress/e2e/config-wizard-plus.cy.ts
- clients/admin-ui/cypress/e2e/config-wizard.cy.ts
- clients/admin-ui/cypress/e2e/datasets-classify.cy.ts
- clients/admin-ui/cypress/e2e/datasets.cy.ts
- clients/admin-ui/cypress/e2e/nav-bar.cy.ts
- clients/admin-ui/cypress/e2e/systems.cy.ts
- clients/admin-ui/cypress/e2e/taxonomy.cy.ts
> Skipping Cypress tests due to nav bar 2.0

- CHANGELOG.md
> update the changelog for 2.4.0 release

- docs/fides/docs/development/release_checklist.md
Closes #2074 
* minor updates to release checklist doc for clarity
-- added a few reviewers for redundancy, don't need a review from everyone!
> small release checklist updates

- src/fides/api/ctl/sql_models.py
Initial table for https://github.com/ethyca/fidesplus/issues/493
> add custom field value list table

- CHANGELOG.md
Closes n/a
Changelog updates for release!
> Updated changelog for 2.5.0

- codecov.yaml
* Increased the number of reports required before codecov reports back to prevent early low number being reported.
> Up the reports required number

- CHANGELOG.md
* Set changelog version for `2.6.0` and create a new `unreleased`
* n/a
Changelog updates for release
> Updated CHANGELOG.md for release 2.6.0

- CHANGELOG.md
* Updated CHANGELOG.md file with new release version.
> Updated CHANGELOG.md for release 2.6.1

- CHANGELOG.md
~~Add any new tables/columns to the [database diagram](https://github.com/ethyca/fides/blob/5a485387d8af247ec6479e4115088cbbb8394d77/docs/fides/docs/development/update_erd_diagram.md) if they have not already been added~~
```
fides status
fides …
```
> update changelog for 2.7.0 release

- src/fides/api/ops/api/v1/endpoints/privacy_request_endpoints.py
> [#2433] Log error class on privacy request failure

- CHANGELOG.md
- clients/admin-ui/cypress/e2e/taxonomy.cy.ts
- clients/admin-ui/src/features/taxonomy/TaxonomyTabs.tsx
- clients/admin-ui/src/features/taxonomy/hooks.tsx
Closes #2518
* Remove hook, tab info, and tests.
We'll always have this in the git log if we return tot his feature.
> ui/taxonomy: Remove identifiablity (data qualifier) editor

- CHANGELOG.md
- clients/admin-ui/cypress/e2e/systems.cy.ts
- clients/admin-ui/package-lock.json
- clients/admin-ui/package.json
- clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationAccordion.tsx
- clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationForm.tsx
- clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationManager.tsx
- clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationStep.tsx
Closes https://github.com/ethyca/fides/issues/2605
https://user-images.githubusercontent.com/24641006/220710818-dce05c15-b002-45a0-aee0-d00808e51d45.mov
> Delete privacy declarations

- src/fides/data/test_env/privacy_center_config/config.json
Closes [Thread](https://ethyca.slack.com/archives/C043URV1KLL/p1677269794556939)
`config.json` - Love to maintain it. The GPC settings are new and I didn't add them to the test env.
> test_env/pc: Add GPC settings to test env privacy center config

- CHANGELOG.md
- change `Unreleased` --> `2.8.0`
- add new `Unreleased` section
> update changelog for 2.8.0 release

- clients/admin-ui/src/features/common/custom-fields/hooks.ts
Closes #2761
A follow on issue will be created to re-clean this up
> Fix Custom Fields Overwriting

- CHANGELOG.md
```
fides status
exit
```
Next, run the following checks against the environment you've spun up using `fides deploy up --no-pull`:
Run these from within `nox -s dev -- shell`
> release 2.8.1

- CHANGELOG.md
Closes n/a
- changelog update for 2.8.2 release
- include line item for migration fix that'd been missed when merging
> update CHANGELOG.md for release 2.8.2

- src/fides/core/export.py
```
fides status
exit
```
Next, run the following checks against the environment you've spun up using `fides deploy up --no-pull`:
Run these from within `nox -s dev -- shell`
> release 2.8.2

- clients/admin-ui/src/features/common/SystemsCheckboxTable.tsx
Closes https://github.com/ethyca/fides/issues/2783
> Add data test id to select all

- CHANGELOG.md
Updates the changelog to prepare for 2.9.0 🎉 
> Update CHANGELOG.md for release 2.9.0

- clients/admin-ui/src/features/common/Restrict.tsx
- clients/admin-ui/src/features/user-management/PermissionsForm.tsx
- clients/admin-ui/src/features/user-management/RoleOption.tsx
Closes https://github.com/ethyca/fides/issues/2856
> Restrict non-owners from being able to assign owner role and systems

- CHANGELOG.md
Preparing for the 2.10.0 release 👍
> Update CHANGELOG to prepare for 2.10.0

- CHANGELOG.md
> Update changelog with fix from fides#2953

- src/fides/data/sample_project/privacy_center/config/config.json
* ~[ ] Update `CHANGELOG.md`~ (n/a)
Tiny change to keep the sample project on the latest-and-greatest styling options added by https://github.com/ethyca/fides/pull/2943
> Update Cookie House (sample project) privacy center to new config.json format

- data/dataset/mongo_example_test_dataset.yml
- src/fides/data/sample_project/fides.toml
- src/fides/data/sample_project/sample_resources/mongo_example_test_dataset.yml
- tests/ops/integration_tests/test_mongo_task.py
- tests/ops/service/connectors/test_queryconfig.py
This is a few local changes I made while completing the release checklist here: #2948.
> Update test data for Mongo, CLI, etc.

- CHANGELOG.md
Preparing for the 2.11.0 release!
> Updated CHANGELOG.md to prepare for release 2.11.0

- clients/admin-ui/src/features/datamap/constants.ts
- clients/admin-ui/src/features/datamap/datamap.slice.ts
Closes https://github.com/ethyca/fidesplus/issues/810
> Update source/destination copy and hide system dependency column

- CHANGELOG.md
Fix changelog to consolidate sections and add some missed work.
> Fix 2.11.0 Changelog

- docs/fides/docs/development/developing_fides.md
- noxfile.py
> Fix Nox Docs Link

- clients/admin-ui/cypress/e2e/custom-fields.cy.ts
- clients/admin-ui/src/features/custom-fields/CustomFieldsTable.tsx
- clients/admin-ui/src/features/custom-fields/cells.tsx
Closes N/A
* Run the cypress tests!
> Custom fields cypress tests

- CHANGELOG.md
- clients/admin-ui/src/flags.json
> Allow users to toggle privacy notice flag

- CHANGELOG.md
Closes N/A
Changelog review ahead of 2.12.0 as part of https://github.com/ethyca/fides/pull/3182
> Changelog Updates Pre-2.12.0 Release

- CHANGELOG.md
Closes n/a
‼️ Will need to cherry-pick into `release-2.12.1` branch
> update changelog for 2.12.1 hotfix

- CHANGELOG.md
> Update changelog for turborepo changes

- src/fides/api/ops/api/v1/endpoints/connection_type_endpoints.py
- tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
> Increasing default page size for the connection type endpoint to 100

- CHANGELOG.md
Closes n/a
changelog organization fix
n/a
purely cosmetic
> remove split changed section in 2.14.0 changelog

- clients/fides-js/src/components/fides.css
Closes https://github.com/ethyca/fides/issues/3457
> Minor CSS cleanup on banner and modal

- CHANGELOG.md
- requirements.txt
> Update Psycopg2-binary version

- clients/fides-js/src/fides.ts
- clients/fides-js/src/lib/consent-types.ts
- clients/privacy-center/app/server-environment.ts
- clients/privacy-center/components/consent/ConsentToggles.tsx
- clients/privacy-center/cypress/e2e/consent-banner.cy.ts
- clients/privacy-center/cypress/e2e/consent-notices.cy.ts
- clients/privacy-center/cypress/fixtures/consent/test_banner_options.json
- clients/privacy-center/cypress/support/commands.ts
- clients/privacy-center/features/common/settings.slice.ts
- clients/privacy-center/pages/api/fides-js.ts
- clients/privacy-center/public/fides-js-components-demo.html
Closes https://github.com/ethyca/fides/issues/3494
> Wrap new consent components with feat switch, rename env var

- CHANGELOG.md
- clients/fides-js/.eslintrc.json
- clients/fides-js/src/components/CloseButton.tsx
- clients/fides-js/src/components/ConsentBanner.tsx
- clients/fides-js/src/components/ConsentModal.tsx
- clients/fides-js/src/components/Divider.tsx
- clients/fides-js/src/components/NoticeToggles.tsx
- clients/fides-js/src/components/Overlay.tsx
- clients/fides-js/src/components/Toggle.tsx
- clients/fides-js/src/components/fides.css
- clients/fides-js/src/lib/hooks.ts
- clients/privacy-center/components/consent/NoticeDrivenConsent.tsx
- clients/privacy-center/features/consent/helpers.ts
Closes N/A
Addresses the comments I left in https://github.com/ethyca/fides/pull/3411
* Everything still works!
> Privacy component feature cleanup

- clients/fides-js/src/fides.ts
- clients/fides-js/src/lib/consent-utils.ts
> Minor todo comment cleanups

- src/fides/data/privacy_notices/privacy_experience_config_defaults.yml
- src/fides/data/privacy_notices/privacy_notice_templates.yml
Some small adjustments to the defaults here based on some testing!
> Adjust default language and configuration for privacy notices/experiences

- CHANGELOG.md
Update changelog for release 2.15.0
> update changelog for release 2.15.0

- clients/admin-ui/src/features/datastore-connections/datastore-connection.slice.ts
> Fix saas creation failure

- clients/admin-ui/src/features/datastore-connections/system_portal_config/TestConnection.tsx
- clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParameters.tsx
Closes #3533 
https://github.com/ethyca/fides/assets/17103888/09d476a4-84d7-42bc-a951-cf71ac979670
> Fix testing connectors within the integrations tab

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.15.0

- CHANGELOG.md
Updated CHANGELOG.md for release 2.16.0
> Updated CHANGELOG.md for release 2.16.0

- CHANGELOG.md
No issue, this is a minor docs update.
* Updates fides 2.16.0 changelog to include vulnerability fixes for:
* https://github.com/ethyca/fides/security/advisories/GHSA-g95c-2jgm-hqc6
* https://github.com/ethyca/fides/security/advisories/GHSA-3rw2-wfc8-wmj5
> Update 2.16.0 changelog to include file upload vulnerability fixes

- clients/privacy-center/features/consent/consent.slice.ts
- clients/privacy-center/pages/index.tsx
Closes #3416 
Adding support for a geolocation override in the Privacy Center. Adding a `geolocation=US-CA` query parameter will spoof the location and allow a user to demo privacy notices for a location other than where they are physically located.
If you are in a state with consent laws (US-CA, US-CO, US-CT, US-IA, US-UT, US-VA)
If you are NOT in a state with consent
> Adding location override

- CHANGELOG.md
Updated CHANGELOG.md for release 2.17.0
> Updated CHANGELOG.md for release 2.17.0

- clients/admin-ui/src/types/api/models/PrivacyNoticeRegion.ts
- src/fides/api/models/privacy_notice.py
Closes https://github.com/ethyca/fides/issues/3926
> Add Canadian Provinces to Privacy Notice Regions

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.19.0

- clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationForm.tsx
> title and casing fix for special category data 

- clients/admin-ui/src/features/system/SystemInformationForm.tsx
Hiding `Unique ID` field from system form during system creation.
> Hiding unique ID field on system creation

- src/fides/api/main.py
Ever-increasing server time has become a big issue, so we need a way to track it consistently.
> Log Server Setup/Startup Time

- CHANGELOG.md
- clients/admin-ui/src/features/common/form/inputs.tsx
- clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationForm.tsx
- Fixes placeholder value on "features" field to properly indicate that it's not meant to be a true select field
- Updates "retention period" to be a text input instead of a number field
> Privacy declaration form fixes

- requirements.txt
- src/fides/api/alembic/migrations/versions/3038667ba898_update_system_legal_basis_fields.py
- src/fides/api/models/sql_models.py
- tests/ctl/core/test_api.py
Part of #3974 
‼️ contains migration
‼️ ensure `requirements.txt` is pinned to actual `fideslang` version once released
See issue for context/motivation. 
> fides - update system.legal_basis_for_transfers and system.legal_basis_for_profiling

- src/fides/api/api/v1/endpoints/admin.py
> fix: pylint

- .github/workflows/publish_docker.yaml
- CHANGELOG.md
- noxfiles/docker_nox.py
- noxfiles/test_docker_nox.py
This reverts commit 95ca9191d01d434ded31dc5a6cbe0a507be5f487.
> Revert "Fix Parallel Docker Platform Builds (#4013)"

- data/saas/config/adobe_sign_config.yml
[] added doc links
[] updated tooltips to be consistent
> update with docs link and tooltips

- src/fides/api/models/messaging_template.py
Updating email template labels
> Updating labels

- CHANGELOG.md
> Changelog 2.19.1

- CHANGELOG.md
- clients/admin-ui/src/features/system/form.ts
- clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationFormTab.tsx
Closes #4062 
https://github.com/ethyca/fides/assets/17103888/7d024811-0dab-493b-a12b-58669a909848
> Fix data flow saving issue

- clients/admin-ui/src/features/privacy-experience/JavaScriptTag.tsx
> Right align and vertically center clipboard button

- src/fides/api/alembic/migrations/versions/ad2e3f9a6850_adding_custom_privacy_request_field_table.py
> Fix downrev of custom privacy request field migration.

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.20.0

- CHANGELOG.md
> include fideslang 2.0 upgrade in changelog

- CHANGELOG.md
changelog update for hotfix.
this change is already in `release-2.20.1` branch - i'd made it when cherry-picking a commit into that branch and got a conflict in the changelog 👍
> update changelog for 2.20.1 release

- src/fides/data/privacy_notices/privacy_experience_config_defaults.yml
Closes #https://github.com/ethyca/fides/issues/4152
Updates the default language of the TCF Overlay Experience Config (which is the resource that stores "copy")
Bring up http://localhost:3001/fides-js-demo.html with TCF enabled, an applicable system setup, and put your VPN in the EEA:
> TCF Overlay Experience Description

- CHANGELOG.md
> Update changelog for 2.20.2 release

- src/fides/api/service/connectors/saas/connector_registry_service.py
Fixing boolean statement to account for scenarios when authentication is not defined for a client config
> Fix authorization check

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.21.0

- CHANGELOG.md
- clients/fides-js/src/components/ExternalLink.tsx
- clients/fides-js/src/components/InfoBox.tsx
- clients/fides-js/src/components/fides.css
- clients/fides-js/src/components/tcf/TcfFeatures.tsx
- clients/fides-js/src/components/tcf/TcfOverlay.tsx
- clients/fides-js/src/components/tcf/TcfPurposes.tsx
- clients/fides-js/src/components/tcf/TcfTabs.tsx
- clients/fides-js/src/components/tcf/TcfVendors.tsx
- clients/fides-js/src/components/tcf/VendorInfoBanner.tsx
- clients/fides-js/src/lib/tcf/types.ts
- clients/fides-js/src/lib/tcf/vendors.ts
- clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
Closes https://github.com/ethyca/fides/issues/4166
https://www.loom.com/share/bedab0c3615e47df8f48127279ec96e3
* Set up a TCF environment
* Verify all the issue reqs are met (lots of little things in this one!)
> Various TCF fixes

- tests/ops/models/test_custom_asset.py
Updating enum for `CustomAssetType` in unit tests
> Fixing unit tests

- src/fides/data/gvl.json
- tests/ops/util/test_tc_string.py
Closes N/A
New vendor list is released weekly. For this release, we have a hardcoded gvl.json file.  In a future release, we will be using live updates and get rid of this hardcoded piece.
> Update gvl.json to version 20

- clients/privacy-center/pages/api/fides-js.ts
Fixing bug where custom CSS couldn't be refreshed after it was initially set
> Fixing custom CSS refresh logic

- CHANGELOG.md
> Update changelog for #4200

- clients/fides-js/README.md
Closes N/A
Updates the README for `fides-js`.
> Update fides-js readme

- CHANGELOG.md
- clients/fides-js/src/components/fides.css
- clients/fides-js/src/components/tcf/DoubleToggleTable.tsx
- clients/fides-js/src/components/tcf/TcfTabs.tsx
Small copy and CSS changes that came up during review
> Copy updates and minor css changes

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.22.0

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.22.1

- CHANGELOG.md
> update changelog with 2.22.1 CVE ids

- CHANGELOG.md
> Fixing change log

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.23.0

- clients/admin-ui/src/features/config-wizard/AddSystem.tsx
This is a quick follow up to update the card copy
> Update copy for `add multiple systems` card

- CHANGELOG.md
- clients/admin-ui/src/features/common/form/inputs.tsx
- clients/admin-ui/src/features/system/dictionary-form/DictSuggestionInputs.tsx
- clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationForm.tsx
Closes https://ethyca.atlassian.net/browse/PROD-1279
| Before | After |
|--------|--------|
| ![image](https://github.com/ethyca/fides/assets/24641006/91895a93-38dd-4191-b4cd-465d502b9d2a)  | ![image](https://github.com/ethyca/fides/assets/24641006/43986a80-5697-4b21-97d7-a17e6722d34a) |
> Flexible legal basis input styling

- clients/admin-ui/cypress/e2e/systems-plus.cy.ts
- clients/admin-ui/cypress/fixtures/plus_health.json
- clients/admin-ui/cypress/fixtures/systems/system.json
- clients/admin-ui/cypress/fixtures/systems/systems_with_data_uses.json
- clients/admin-ui/src/features/system/SystemFormTabs.tsx
- clients/admin-ui/src/features/system/VendorSelector.tsx
Closes https://github.com/ethyca/fides/issues/4288
Most of the tests that were failing just needed to be updated for the type ahead component. 
The other one that was giving lots of trouble was `can switch between tabs after populating from dictionary`. It turns out this just needed the fixture to pass along a consistent `fides_key` 👍
> Fix vendor tests

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.23.1

- .fides/db_dataset.yml
- CHANGELOG.md
- src/fides/api/alembic/migrations/versions/3cc39a6ce32b_cookie_system_unique_constraint.py
- src/fides/api/alembic/migrations/versions/842790fa918a_add_compass_system_sync.py
- src/fides/api/api/v1/endpoints/system.py
- src/fides/api/db/base.py
- src/fides/api/db/system.py
- src/fides/api/models/sql_models.py
- src/fides/api/models/system_compass_sync.py
- tests/ctl/core/test_system_compass_sync.py
- tests/ctl/core/test_system_history.py
Closes https://ethyca.atlassian.net/browse/PROD-1332
Add table to high-level track automatic compass system syncs and add unique constraint on cookie name/system id.
- Update _audit_system_changes to return whether the system/privacy declaration was updated.
- Update "update_system" to return a tuple, of the updated system, and then whether the system was updated.
- Add a new SystemCompassSync table with model methods
- Add a unique constraint on cookie name and system id, deleting duplicates first.
> High Level Track Compass System Sync

- CHANGELOG.md
> update changelog for 2.23.3

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.24.0

- CHANGELOG.md
Unticketed. Updates changelog for 2.24.0 release based on recent cherry-picked commits from `main` into release branch
> update changelog for 2.24.0 release

- CHANGELOG.md
- clients/admin-ui/cypress/e2e/systems-plus.cy.ts
- clients/admin-ui/cypress/fixtures/systems/system-vendors.json
- clients/admin-ui/src/features/common/table/v2/FidesTable.tsx
- clients/admin-ui/src/features/common/table/v2/PaginationBar.tsx
- clients/admin-ui/src/features/common/table/v2/RowSelectionBar.tsx
- clients/admin-ui/src/features/common/table/v2/cells.tsx
- clients/admin-ui/src/features/plus/plus.slice.ts
- clients/admin-ui/src/features/system/add-multiple-systems/AddMultipleSystems.tsx
Closes [#PROD-1292](https://ethyca.atlassian.net/browse/PROD-1292)
Improve the UX of the bulk vendor add table
UAT ENV here: https://fides-plus-nightly-fmg5dfemx-ethyca.vercel.app/add-systems/multiple
> Bulk vendor add table ux fixes

- CHANGELOG.md
Closes n/a
Updates changelog for `2.24.1` hotfix
> update changelog for hotfix 2.24.1

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.25.0

- clients/admin-ui/src/features/common/modals/FilterModal.tsx
- clients/admin-ui/src/features/configure-consent/ConsentManagementFilterModal.tsx
This is just a PR with style suggestions for https://github.com/ethyca/fides/pull/4456
> Style suggestions

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.26.0

- CHANGELOG.md
- data/saas/config/iterate_config.yml
Closes #PROD-1527
_Corrected a field mapping to resolve errors:_
At least one param_value references an invalid field for the 'update' request of user.
has been reported several times.
> Fides prod 1527 iterate fix

- CHANGELOG.md
- clients/fides-js/src/lib/tcf.ts
Closes https://ethyca.atlassian.net/browse/PROD-1530
Sets one of the flags on `tcModel` to false
> Set supportsOOB on tcModel to false

- CHANGELOG.md
Updates changelog for release 2.27.0
> Updated CHANGELOG.md for release 2.27.0

- clients/admin-ui/src/features/locations/locations.slice.ts
https://ethyca.slack.com/archives/C04S7K0T2V7/p1704303131908149?thread_ts=1704204034.350499&cid=C04S7K0T2V7
> Remove trailing slash from locations slice

- CHANGELOG.md
Missed a changelog entry for #4549, whoops! This adds the missed entry back to the changelog.
> update missed changelog entry

- CHANGELOG.md
> Update changelog for v2.28.0

- clients/admin-ui/src/pages/consent/reporting/index.tsx
Closes #[1537](https://ethyca.atlassian.net/browse/PROD-1537)
> Update consent reporting title

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.29.0

- CHANGELOG.md
Updated CHANGELOG.md for release 2.30.0
> Updated CHANGELOG.md for release 2.30.0

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.31.0

- CHANGELOG.md
- clients/fides-js/src/components/Overlay.tsx
- clients/fides-js/src/components/notices/NoticeOverlay.tsx
- clients/fides-js/src/components/tcf/TcfOverlay.tsx
- clients/fides-js/src/components/types.ts
- clients/fides-js/src/fides-ext-gpp.ts
- clients/fides-js/src/fides-tcf.ts
- clients/fides-js/src/fides.ts
- clients/fides-js/src/lib/consent-utils.ts
- clients/fides-js/src/lib/consent-value.ts
- clients/fides-js/src/lib/consent.ts
- clients/fides-js/src/lib/cookie.ts
- clients/fides-js/src/lib/extensions.ts
- clients/fides-js/src/lib/initialize.ts
- clients/fides-js/src/lib/preferences.ts
- clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts
- clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
- clients/privacy-center/cypress/e2e/consent-banner.cy.ts
Closes PROD-1780
This reverts some of the changes made in #4527 so that the `Fides.consent` value will be reliably populated with defaults from either:
1. Saved user preferences in an existing `fides_consent` cookie
2. Default preferences from the `privacy-experience` API
We should do some general regression for Fides CMP including:
> Initialize Fides.consent with default values from experience when saved consent cookie (fides_consent) does not exist

- src/fides/api/alembic/migrations/versions/14acee6f5459_translation_data.py
- src/fides/api/alembic/migrations/versions/32497f08e227_translation_cleanup.py
- src/fides/api/alembic/migrations/versions/a1e23b70f2b2_add_notice_and_exp_translations.py
- src/fides/api/models/privacy_experience.py
- src/fides/api/models/privacy_notice.py
- src/fides/api/service/saas_request/override_implementations/oracle_responsys_request_overrides.py
- tests/fixtures/saas/oracle_responsys_fixtures.py
- tests/ops/integration_tests/saas/connector_runner.py
- tests/ops/integration_tests/saas/test_oracle_responsys_task.py
Closes Unticketed, minor changes from a skim of backend files changed
- Adds logging to migrations
- Clarifies docstrings
> Backend Multitranslation cleanup

- src/fides/api/alembic/migrations/versions/14acee6f5459_translation_data.py
Untested - but proposed update to forcibly keep new OOB Canadian experiences disabled on a migration.
Pending product decision on what the desired behavior is here. See thread [here](https://ethyca.slack.com/archives/C04RQV78ZN2/p1710274428190829?thread_ts=1710163850.015309&cid=C04RQV78ZN2) for more contxt
~Please test before merging!~ Tested by Dawn
Keeps Canadian Experience Configs and Quebec Experience Configs disabled by default.
> Keep Canada Experiences Disabled

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.32.0

- CHANGELOG.md
- clients/fides-js/README.md
- clients/fides-js/package.json
Add script to watch for changes and recompile when you're working on fides-js
> PROD-1875 Add script to recompile after code changes

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.33.0

- CHANGELOG.md
> update changelog for release 2.33.1

- CHANGELOG.md
Updates changelog for `2.34.0` release
N/A
> update changelog for 2.34.0 release [fides]

- clients/admin-ui/src/features/privacy-experience/PrivacyExperienceTranslationForm.tsx
> PROD-1977 Small text change

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.35.0

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.36.0

- .gitignore
- .vscode/settings.json
Adds a shared vscode settings file to increase our consistency in code formatting and to help enabling eslint in a consistent way for anyone using vscode.
* no longer ignoring .vscode/settings.json
* Add .vscode/settings.json with some formatting rules and eslint mappings.
> Update .gitignore and add vscode settings

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.37.0

- clients/admin-ui/src/pages/consent/privacy-experience/index.tsx
Closes #[PROD-2018](https://ethyca.atlassian.net/browse/PROD-2018)
[PROD-2018]: https://ethyca.atlassian.net/browse/PROD-2018?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update Privacy Experience page copy

- .github/workflows/frontend_checks.yml
https://docs.github.com/en/actions/learn-github-actions/expressions#example
> Fix frontend checks

- CHANGELOG.md
- clients/package-lock.json
- clients/privacy-center/__tests__/app/server-environment.test.ts
- clients/privacy-center/app/server-environment.ts
- clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx
- clients/privacy-center/config/config.json
- clients/privacy-center/cypress/e2e/privacy-request.cy.ts
- clients/privacy-center/cypress/fixtures/config/config_custom_request_fields.json
- clients/privacy-center/cypress/fixtures/privacy-request/success.json
- clients/privacy-center/package.json
- clients/privacy-center/types/config.ts
Add new query_param_key property to custom privacy request fields. When used, privacy center will look at the url and find a matching query param key, and will fill the request fill with that value.
It can be used for both visible and hidden request fields.
> PROD-2068 Privacy center can fill custom request fields with query parameters

- .github/workflows/backend_checks.yml
- .github/workflows/cli_checks.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/cypress_e2e.yml
- .github/workflows/frontend_checks.yml
- .github/workflows/publish_docker.yaml
- .github/workflows/publish_docs.yaml
- .github/workflows/publish_package.yaml
- No linked issue, this is a chore 
- Bumps the following deprecated GitHub Actions versions
- [actions/checkout](https://github.com/actions/checkout) from `v3` to `v4`
- [actions/setup-python](https://github.com/actions/setup-python) from `v4` to `v5`
- [actions/upload-artifact](https://github.com/actions/upload-artifact) from `v3` to `v4`
- [actions/download-artifact](https://github.com/actions/upload-artifact) from `v3` to `v4`
- [docker/build-push-action](https://github.com/docker/build-push-action) from `v4` to `v5`
- [docker/setup-buildx-action](https://github.com/docker/setup-buildx-action) from `v2` to `v3`
- [actions/setup-node](https://github.com/actions/setup-node) from `v3` to `v4`
- [cypress-io/github-action](https://github.com/cypress-io/github-action) from `v5` to `v6`
- …
> Bump GitHub actions from deprecated to supported versions (fides)

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.38.0

- CHANGELOG.md
I had incorrectly added both of these to the released section, whereas they belong in the unreleased for now.
> fix CHANGELOG sections

- src/fides/api/api/v1/endpoints/messaging_endpoints.py
- src/fides/api/schemas/messaging/messaging.py
- src/fides/api/service/messaging/message_dispatch_service.py
- src/fides/api/service/messaging/messaging_crud_service.py
- tests/ctl/core/test_api.py
- tests/ops/api/v1/endpoints/test_messaging_endpoints.py
- tests/ops/service/messaging/test_messaging_crud_service.py
> Formatting fixes

- CHANGELOG.md
> update changelog for 2.38.1 release

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.39.0

- CHANGELOG.md
> update changelog for 2.39.1 release

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.40.0

- clients/admin-ui/src/features/datamap/CytoscapeGraph.tsx
Fix high mouse wheel sensitivity when using data lineage with a mouse
> Fix data lineage mousewheel behvior

- docker-compose.integration-tests.yml
> mysql integration test fix: looks like we do need this

- Dockerfile
Same issues that were fixed in https://github.com/ethyca/fidesplus/pull/1511
> Remove extra install keyword

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.41.0

- CHANGELOG.md
- clients/fides-js/src/lib/events.ts
mark all FidesJS events for performance monitoring
> mark events for performance monitoring

- src/fides/api/api/v1/endpoints/privacy_request_endpoints.py
- src/fides/api/db/seed.py
- src/fides/api/schemas/connection_configuration/connection_secrets_bigquery.py
- src/fides/api/schemas/connection_configuration/connection_secrets_google_cloud_sql_mysql.py
- src/fides/api/schemas/connection_configuration/connection_secrets_google_cloud_sql_postgres.py
- src/fides/api/schemas/redis_cache.py
- src/fides/core/evaluate.py
- src/fides/core/push.py
- tests/ctl/core/test_evaluate.py
- tests/ctl/core/test_system.py
- tests/fixtures/google_cloud_sql_postgres_fixtures.py
- tests/fixtures/snowflake_fixtures.py
- tests/ops/task/test_filter_results.py
- tests/ops/task/traversal_data.py
A branch to track any misc changes I need to make as part of the Pydantic v2 migration review
> Pydantic v2 migration (misc fixes)

- CHANGELOG.md
CHANGELOG entry was missed in https://github.com/ethyca/fides/pull/5136
> Update changelog for PROD-2426

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.42.0

- CHANGELOG.md
> Changelog 2.42.1

- CHANGELOG.md
- check spelling and formatting 
> Updated CHANGELOG.md for release 2.43.0

- README.md
Update a command with quotes where it needs them.
None.
> Update command with required quotes.

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.43.1

- clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx
previous commit was not formatted correctly using the Prettier script
> Fix Prettier issue on ConnectorParametersForm.tsx

- clients/admin-ui/src/features/datastore-connections/system_portal_config/ConsentAutomationForm.tsx
Updating copy for consent automation section based on feedback from Design.
> Updating copy for consent automation section

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.44.0

- data/saas/config/attentive_config.yml
- data/saas/dataset/attentive_dataset.yml
- tests/ops/integration_tests/test_attentive_task.py
Example of how to handle optional identities + misc cleanup suggestions
> Attentive suggestions

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.45.0

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.45.1

- .vscode/settings.json
- CHANGELOG.md
- clients/admin-ui/.eslintrc.cjs
- clients/admin-ui/package.json
- clients/admin-ui/postcss.config.js
- clients/admin-ui/src/features/common/TaxonomiesPicker.tsx
- clients/admin-ui/src/features/common/nav/v2/nav-config.ts
- clients/admin-ui/src/features/common/nav/v2/routes.ts
- clients/admin-ui/src/features/common/table/v2/FidesTable.tsx
- clients/admin-ui/src/features/data-discovery-and-detection/tables/cells/EditCategoryCell.tsx
- clients/admin-ui/src/pages/_app.tsx
- clients/admin-ui/src/pages/_document.tsx
- clients/admin-ui/src/pages/ant-poc.tsx
- clients/admin-ui/src/pages/login.tsx
- clients/admin-ui/src/theme/ant.ts
- clients/admin-ui/src/theme/tailwind.css
- clients/admin-ui/tailwind.config.js
- clients/fidesui/package.json
- clients/fidesui/src/FidesUIProvider.tsx
- clients/fidesui/src/index.ts
- clients/package-lock.json
Closes [PROD-2790](https://ethyca.atlassian.net/browse/PROD-2790)
Initialize Ant, Tailwind and configs in Admin UI in preparation for Design System migration.
* Run Admin UI locally (in development environment)
* At the bottom of the nav you should see a new Developer group, expand that and click on the POC nav link
* Check that the POC is up and running with Jack's latest config colors
[PROD-2790]: https://ethyca.atlassian.net/browse/PROD-2790?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prod 2790 initialize ant design

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.46.0

- CHANGELOG.md
> update changelog for 2.46.1

- CHANGELOG.md
> update changelog for 2.46.2

- CHANGELOG.md
- Dockerfile
> Updated CHANGELOG.md and docker file for release 2.47.0

- clients/admin-ui/src/features/common/custom-reports/CustomReportTemplates.tsx
fix missing space in "empty" custom reports popover.
> fix missing space

- clients/admin-ui/src/features/common/custom-reports/CustomReportTemplates.tsx
- clients/admin-ui/src/theme/ant.ts
- clients/fidesui/src/FidesUITheme.tsx
Styling updates for the Reports popover UI + some theme updates
> Report popover styling

- CHANGELOG.md
> Updated CHANGELOG.md for release 2.48.0

- clients/admin-ui/src/theme/ant.ts
This reverts some changes from commit 99f1c58ddb8a72c92ab23bf6ab2cb290cd33e390.
> Revert changes to component theming

- clients/fides-js/docs/interfaces/FidesExperienceConfig.md
- clients/fides-js/src/docs/fides-experience-config.ts
Minor adjustment to docs for better alphabetization.
> alphabetize better

- CHANGELOG.md
> update changelog 2.48.2

- CHANGELOG.md
_update changelog_
1.  _verify versions are correct_
> Updated CHANGELOG.md for release 2.49.0

- CHANGELOG.md
1. check spelling and formatting
> update changelog for 2.49.1

- clients/fides-js/__tests__/lib/gpp/stub.ts
- clients/fides-js/__tests__/lib/gpp/us-notices.ts
- clients/fides-js/package.json
- clients/fides-js/rollup.config.mjs
- clients/fides-js/src/fides-ext-gpp.ts
- clients/fides-js/src/lib/gpp/constants.ts
- clients/fides-js/src/lib/gpp/us-notices.ts
- clients/package-lock.json
- clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts
- **Update GPP package.**
- **Update tests.**
Closes FIDES-1554
Update to newest version of GPP package.
* Update tests.
> FIDES-1554: Update GPP Package

- src/fides/api/service/saas_request/override_implementations/shopify_request_override.py
> GraphQL formatting recommendation

- README.md
Update readme with new link for fides docs
> Update fides docs link in readme

- CHANGELOG.md
* _update to change log_
1.  _verify version in the change log_
> Updated CHANGELOG.md for release 2.51.0

- CHANGELOG.md
1.  Check spelling / formatting
> Update changelog release 2.51.1

- .fides/fides.toml
- CHANGELOG.md
_update to CHANGELOG.md_
* _update to CHANGELOG.md_
_verify version is correct_
> Update changelog release 2.52.0

- clients/admin-ui/src/features/taxonomy/components/TaxonomyInteractiveTree.tsx
- clients/admin-ui/src/pages/taxonomy/index.tsx
Fix 2 bugs reported:
- Nodes sometimes disappear after adding a new one
- The screen sometimes isn't centered properly after switching to a new taoxnomy
* Remove timeout for the removal of the draft input
* Add some timeout to screen centering
> Taxonomy UI fixes

- CHANGELOG.md
- src/fides/data/sample_project/sample_resources/postgres_example_test_dataset.yml
_updating changelog_
1.  _verify versions are correct_
> Update changelog release 2.53.0

- CHANGELOG.md
- clients/fides-js/__tests__/lib/gpp/stub.ts
- clients/fides-js/__tests__/lib/gpp/us-notices.ts
- clients/fides-js/package.json
- clients/fides-js/src/fides-ext-gpp.ts
- clients/fides-js/src/lib/gpp/constants.ts
- clients/package-lock.json
- clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts
Closes [HJ-348]
Upgrade to 3.1.5 and tweak unit tests for support
1. In fidesplus, make sure the following environment variable is set to true: `FIDESPLUS__GPP__ENABLED=true`
2. Start fidesplus (slim is fine)
3. Start Clients (using turbo run dev).
4. Set up in Admin UI: 
5. Add a new custom system
* Give it a data use of `marketing.advertising.third_party.targeted`
* Give it _any_ data category
* Give it a legal basis of “Consent”
6. Visit `/settings/consent`.
* For US consent, you’ll have to choose “state-by-state”
* Check "All transactions covered by MSPA"
* Toggle "Enable MSPA service provider mode" to ON.
7. Visit `/consent/privacy-notices`.
* Enable at least one of the GPP framework notices that is available.
8. Visit `/consent/privacy-experience`.
* enable the “US Modal” experience …
> Upgrade gpp library to v3.1.5

- CHANGELOG.md
_updating change log for new version 2.54.0_
1.  _verify the version change is correct_
> Updated CHANGELOG.md for release 2.54.0

- CHANGELOG.md
_update changelog_
1.  _Verify change_
> Updated CHANGELOG.md for release 2.55.0

- clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts
Account for the other part of the date in the test string. One date is for "Created Date" this one is for "Last Updated Date"
> Fix GPP test string for TCF to account for dates

- CHANGELOG.md
Updates changelog for `2.55.4` hotfix release
n/a
n/a
> update changelog 2.55.4

- CHANGELOG.md
_update CHANGELOG to reflect new version_
1.  _verify changes are correct_
> Updated CHANGELOG.md for release 2.56.0

- clients/admin-ui/src/features/integrations/add-integration/allIntegrationTypes.tsx
- clients/admin-ui/src/features/integrations/integration-type-info/mySQLInfo.tsx
- src/fides/api/schemas/connection_configuration/connection_secrets_mysql.py
https://github.com/ethyca/fidesplus/pull/1886
> Implement MySql Monitor.

- CHANGELOG.md
> HA-466: MySQL Monitor Changelog

- clients/fides-js/rollup.config.mjs
- clients/fides-js/src/components/tcf/RecordsList.tsx
- clients/fides-js/src/components/tcf/TcfPurposes.tsx
- clients/fides-js/src/lib/tcf/types.ts
1. Create a TCF Notice
2. Create a notice, mark it as NOTICE_ONLY
3. Put that experience on a TCF experience
4. Load TCF experience and see if the toggle is disabled
> Custom TCF purposes respect NOTICE_ONLY.

- CHANGELOG.md
changelog updates for `2.56.2`
> update changelog for 2.56.2

- CHANGELOG.md
_update changelog_
1.  _verify the changes are correct_
> Updated CHANGELOG.md for release 2.57.0

- tests/ops/conftest.py
The `fideslang_data_categories` fixture in Fides is a bit noisy since it logs exceptions if the data it tries to create already exists. This can be misleading so I've updated the fixture to check if the data categories exist before attempting to create them.
* Check if the data categories exist before trying to create them to avoid the exception logs
1.  No user-facing impact, the tests should just pass
> Fixing data category errors on tests startup

- clients/admin-ui/src/features/privacy-requests/RequestDetails.tsx
Fix extra space in subject email in the request details page
* move extra space to inside the (Unverified) text so it's added only when needed
> Fix extra space in subject email

- .cursorignore
Adds `.cursorignore` to repo to prevent `.env` files from being shared with Cursor and models
* Initializes `.cursorignore`
1.  n/a, this is a no-op from a fides perspective. developer usage changes only
> chore(security): add .cursorignore to prevent sharing sensitive files

- CHANGELOG.md
Updates changelog for the 2.57.1 release
> Update changelog for 2.57.1 release

- clients/fides-js/docs/interfaces/Fides.md
I forgot to do a full build after editing the docs, so this PR is just to commit the published version of those docs.
> Publish latest version of TS docs

- clients/admin-ui/src/pages/policies.tsx
- clients/admin-ui/src/pages/policies/[policyKey].tsx
- dev-requirements.txt
- docker-compose.yml
- src/fides/api/api/v1/endpoints/generic_overrides.py
- src/fides/api/graph/traversal.py
- src/fides/cli/__init__.py
- src/fides/cli/commands/pull.py
- src/fides/cli/commands/ungrouped.py
- src/fides/common/utils.py
- src/fides/config/__init__.py
- src/fides/core/api.py
- src/fides/core/dataset.py
- src/fides/core/pull.py
- src/fides/core/push.py
- src/fides/service/dataset/dataset_config_service.py
- src/fides/service/dataset/validation_steps/traversal.py
- tests/ops/api/v1/endpoints/test_dataset_config_endpoints.py
- tests/ops/api/v1/endpoints/test_generic_overrides.py
- tests/ops/graph/conftest.py
- tests/ops/graph/example_datasets/internal_references.yml
- tests/ops/graph/test_node_filters.py
- tests/ops/graph/test_policy_aware_traversal.py
- tests/ops/task/test_create_request_tasks.py
- tests/ops/task/test_deprecated_graph_task.py
> [Demo] Dataset cli improvements

- CHANGELOG.md
_changelog.md updates_
* _update to changelog.md for version 2.58.0_
1.  __verify the versions are correct__
> Updated CHANGELOG.md for release 2.58.0

- clients/admin-ui/src/features/common/nav/nav-config.test.ts
- clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx
- clients/admin-ui/src/features/test-datasets/DatasetEditorSection.tsx
- clients/admin-ui/src/features/test-datasets/helpers.ts
- src/fides/api/schemas/connection_configuration/connection_config.py
- src/fides/core/api.py
> [Demo] Dataset testing for API integrations

- clients/fides-js/docs/interfaces/Fides.md
- clients/fides-js/src/docs/fides.ts
- clients/fides-js/src/integrations/gtm.ts
- clients/fides-js/src/lib/consent-types.ts
Closes [LJ-613]
Updates GTM interface docs to include new options added in https://github.com/ethyca/fides/pull/5917
[LJ-613]: https://ethyca.atlassian.net/browse/LJ-613?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Document new GTM options

- src/fides/api/schemas/connection_configuration/connection_config.py
part of HA-514
pulls out secrets masking into a schema mixin to allow reuse from other API schemas
- extract `secrets`-relevant attributes and validator into a `ConnectionConfigSecretsMixin` class
> provide mixin for secrets masking to allow reuse

- .fides/db_dataset.yml
- .github/workflows/backend_checks.yml
- CHANGELOG.md
- noxfiles/ci_nox.py
- noxfiles/run_infrastructure.py
- noxfiles/setup_tests_nox.py
- src/fides/api/alembic/migrations/versions/6e565c16dae1_add_tcf_publisher_restrictions.py
- src/fides/api/db/base.py
- src/fides/api/models/tcf_publisher_restrictions.py
- tests/api/models/test_tcf_publisher_restrictions.py
Closes [LJ-591](https://ethyca.atlassian.net/browse/LJ-591)
Adds new models `TCFConfiguration` and `TCFPublisherRestriction` 
* Adds new models `TCFConfiguration` and `TCFPublisherRestriction` 
* Adds migration to create the new tables
* Adds `test_tcf_publisher_restrictions.py` to test the model validations on create 
1.  Run migration, you should see the new tables
2. Downgrade to previous revision, tables should be deleted OK 
[LJ-591]: https://ethyca.atlassian.net/browse/LJ-591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add TCFConfiguration and TCFPublisherRestriction models

- CHANGELOG.md
Update changelog for 2.58.2 hotfix
> Updated CHANGELOG.md for release 2.58.2

- CHANGELOG.md
- clients/admin-ui/src/features/common/CommonHeaders.ts
- clients/fides-js/src/services/api.ts
- clients/privacy-center/common/CommonHeaders.ts
Reverts ethyca/fides#5993
Discussions are pending on the Implementation of this feature
> Revert "LJ-619 Removing Unescape-Safestr header"

- CHANGELOG.md
Update changelog for 2.59.1 release
> Updated CHANGELOG.md for release 2.59.1

- CHANGELOG.md
- clients/admin-ui/src/features/integrations/integration-type-info/postgreSQLInfo.tsx
> Fix postgres monitor info text.

- CHANGELOG.md
1.  check all items in patch are included 
2. links are correct
3. spelling and formatting 
> Updated CHANGELOG.md for release 2.59.2

- CHANGELOG.md
_update change log_
1.  _verify changes in the CHANGELOG.md_
> Updated CHANGELOG.md for release 2.60.0

- .github/workflows/cypress_admin-ui.yml
- clients/admin-ui/cypress.config.ts
Addresses the provided path error
> Add videos to Admin UI Cypress tests

- clients/admin-ui/cypress/e2e/systems-plus.cy.ts
- clients/admin-ui/cypress/support/stubs.ts
Addresses some flaky tests that have been failing recently
> fix flaky tests

- clients/admin-ui/src/app/middleware.ts
- clients/admin-ui/src/app/store.ts
> Exclude error logger in test.

- src/fides/api/schemas/redis_cache.py
- tests/ops/schemas/test_identity_schema.py
Closes [ENG-151](https://ethyca.atlassian.net/browse/ENG-151)
Added class to handle Unverified identitiies endpoint payloads
1.  CI tests are passing
[ENG-151]: https://ethyca.atlassian.net/browse/ENG-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Add UnverifiedIdentity class

- CHANGELOG.md
_update to CHANGELOG.md_
* _version update to 2.62.0_
1.  _verify version is correct_
> Updated CHANGELOG.md for release 2.62.0

- CHANGELOG.md
_update CHANGELOG.md_
* _updated version to 2.63.0_
1.  _verify the version is correct_
> Updated CHANGELOG.md for release 2.63.0

- tests/ops/models/test_request_task.py
Fixing the tests by correcting the `mock.patch` path
1.  Tests should pass
> Fixing tests

- CHANGELOG.md
Updates changelog for release 2.63.3
> Updated CHANGELOG.md for release 2.63.3

- CHANGELOG.md
- clients/fides-js/src/integrations/shopify.ts
Closes https://ethyca.atlassian.net/browse/ENG-744
Adds config for sale_of_data default in Fides Shopify integration
Follow-up ticket for docs updates- https://ethyca.atlassian.net/browse/ENG-764
* Update Shopify.ts to handle new config option for `sale_of_data_default`
1. In `fides-js-components-demo.html`, add the following code after Fides init (L:220):
```
window.Shopify = {
customerPrivacy: {
setTrackingConsent: function (consent) {
// This function is used to test the Shopify integration.
// It will be called by the Shopify platform script.
console.log(
"Shopify customer privacy function called with consent:",
consent,
);
},
},
};
Fides.shopify({ sale_of_data_default: false });
```
2. Nav to `http://localhost:3001/fides-js-components-demo.html`, and open up console
3. Reload page to …
> ENG-744: Adds config for sale_of_data default in Fides Shopify integration

- src/fides/api/alembic/migrations/versions/aadfe83c5644_add_manual_task_to_connectiontype_enum.py
- src/fides/api/models/connectionconfig.py
- src/fides/common/api/v1/urn_registry.py
- tests/api/models/manual_tasks/test_manual_task.py
- tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
Issue [ENG-668](https://ethyca.atlassian.net/browse/ENG-668)
Adding Manual Tasks to list list of ConnectionConfig types. 
* Added `manual_task` to the enum
* Added `manual_task` to the mapping and human readable mapping
* Added `manual_task` to the urn registry.
1. Verify that you can create a manual task connection and that it saves with no errors.
[ENG-668]: https://ethyca.atlassian.net/browse/ENG-668?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-668 Updated connection config for manual tasks

- CHANGELOG.md
> update changelog for `2.64.1`

- clients/fides-js/src/integrations/shopify.ts
- clients/fides-js/src/lib/consent-constants.ts
Closes [ENG-804]
Add new flag to marketing to shopify for shared key support.
[ENG-804]: https://ethyca.atlassian.net/browse/ENG-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-804: Add new flag to marketing for Shopify

- CHANGELOG.md
Updates CHANGELOG for upcoming release `2.64.2`: https://github.com/ethyca/fides/pull/6279
> Updated CHANGELOG.md for release 2.64.2

- CHANGELOG.md
Updated CHANGELOG.md for release 2.65.0
1.  check release numbers, spelling, and formatting are correct 
> Updated CHANGELOG.md for release 2.65.0

- CHANGELOG.md
- clients/fides-js/src/components/fides.css
Closes [ENG-830]
Duplicate styles used for Vendor Count so that it's the same for any link added as HTML in the description when HTML rendering is enabled in the experience.
* Enhanced link style and merged with link button styles (which is used for vendor count)
1. In a TCF experience, add an html link to the description
2. Ensure the style matches that of the vendor count link (__VENDOR_COUNT_LINK__)
[ENG-830]: https://ethyca.atlassian.net/browse/ENG-830?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Fix styles of html links added to descriptions

- CHANGELOG.md
- clients/fides-js/package.json
- clients/package-lock.json
Upgrades RollupJS to latest version.
* I've read through their migration docs and all of the potential issues called out are with features we do not use.
* Tests all pass and no issues spotted in manual testing.
* **Trims ~0.7k from each of our build sizes!**
> Upgrade RollupJS to latest

- CHANGELOG.md
- clients/admin-ui/cypress/fixtures/privacy-requests/with-logs.json
- clients/admin-ui/src/features/privacy-requests/events-and-logs/ActivityTimeline.tsx
- clients/admin-ui/src/features/privacy-requests/events-and-logs/EventLog.tsx
- clients/admin-ui/src/features/privacy-requests/events-and-logs/LogDrawer.tsx
- src/fides/api/task/graph_task.py
Closes [ENG-1028](https://ethyca.atlassian.net/browse/ENG-1028)
Adds record count to the event log entries. Adds a grand total to the `Request finished` timeline entry.
1.  Start Fides, Admin UI, and Privacy Center
2. Submit and access and erasure request
3. Verify the counts in the event log section
[ENG-1028]: https://ethyca.atlassian.net/browse/ENG-1028?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-1028 Adding record counts to privacy request activity timeline

- CHANGELOG.md
- clients/admin-ui/cypress/e2e/systems/plus/asset-list.cy.ts
- clients/admin-ui/cypress/e2e/systems/plus/bulk-vendor-add.cy.ts
- clients/admin-ui/cypress/e2e/systems/plus/metadata.cy.ts
- clients/admin-ui/cypress/e2e/systems/plus/permissions.cy.ts
- clients/admin-ui/src/features/system/VendorSelect.tsx
- clients/admin-ui/src/features/system/add-multiple-systems/AddMultipleSystems.tsx
Closes [ENG-974]
Adding the vendor id to the vendor list to resolve ambiguity with the names in compass.
- Adding the actual vendor id to the vendor list table
1. Enable TCF
2. Visit `consent/configure/add-vendors`
3. Confirm that the vendor id is correctly displayed in the table
[ENG-974]: https://ethyca.atlassian.net/browse/ENG-974?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> feat: add vendor ids to vendor list [ENG-974]

- CHANGELOG.md
1.  check spelling and formatting 
> Updated CHANGELOG.md for release 2.67.0

- CHANGELOG.md
> update changelog for 2-67.1 release

- CHANGELOG.md
Changelog update for 2.67.2 release
> update changelog 2.67.2

- CHANGELOG.md
1.  check spelling and formatting
> Updated CHANGELOG.md for release 2.68.0

- src/fides/api/models/detection_discovery/core.py
https://ethyca.atlassian.net/browse/ENG-1209
Add logs to help debug the performance of the detection task.
* Add debug logs
> ENG-1209 - Add logs to debug detection task

- CHANGELOG.md
Closes [ENG-782]
Updates changelog to reflect removal of beta flags on orgs and SSO
[ENG-782]: https://ethyca.atlassian.net/browse/ENG-782?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ENG-782: Update changelog

- CHANGELOG.md
Updated CHANGELOG.md for release 2.69.0
1.  check spelling and formatting 
> Updated CHANGELOG.md for release 2.69.0

- clients/admin-ui/src/features/consent-settings/PublisherSettings.tsx
- clients/admin-ui/src/features/integrations/configure-monitor/ConfigureWebsiteMonitorForm.tsx
- clients/package-lock.json
- clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx
- clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx
- clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestModal.tsx
- clients/privacy-center/components/modals/privacy-request-modal/RequestSubmitted.tsx
- clients/privacy-center/components/modals/verification-request/VerificationForm.tsx
Closes [ENG-1295]
Fixing some visual oddities with Ant updates
- Reducing description text spacing in modal forms
- Reducing submit button spacing in modal forms
- Including additional input feedback styles
- Applying consistent button sizes in modal forms
- Fixing location input width in Publisher Settings
[ENG-1295]: https://ethyca.atlassian.net/browse/ENG-1295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: modal and form styling [ENG-1295]

- CHANGELOG.md
- clients/admin-ui/src/features/user-management/NewPasswordModal.tsx
- clients/admin-ui/src/features/user-management/UpdatePasswordModal.tsx
- src/fides/api/api/v1/endpoints/user_endpoints.py
- src/fides/api/models/client.py
- src/fides/api/models/fides_user.py
- src/fides/api/oauth/utils.py
- tests/ctl/core/test_api.py
- tests/ops/api/v1/endpoints/test_user_endpoints.py
This reverts commit e71d028b25613f2a320062d30e699b7580648e9f.
> Revert ENG-681 - password reset session invalidation

- src/fides/api/api/v1/endpoints/oauth_endpoints.py
- tests/ops/schemas/test_user_permission.py
Fixes lints in main from merged security vulnerability
> clean pylints

- CHANGELOG.md
Update changelog for 2.69.1 release
> Update changelog for 2.69.1 release

- src/fides/api/alembic/migrations/versions/fd7571bef683_adds_new_fields_to_messagingconfig_for_.py
Fixing down revision for migration
1.  Tests should pass
> Fixing downrev

- CHANGELOG.md
1.  Check spelling and formatting
> Updated CHANGELOG.md for release 2.70.3

- CHANGELOG.md
- src/fides/api/api/v1/endpoints/generic_overrides.py
- src/fides/service/dataset/dataset_service.py
- tests/ops/service/dataset/test_dataset_service.py
Closes [ENG-1530](https://ethyca.atlassian.net/browse/ENG-1530)
Prevents datasets from being deleted if they are linked to an integration.
* Service layer and endpoint updates with tests
1. Create a Postgres dataset 
2. Create a system and add a Postgres integration
3. Link the dataset to the integration
4. Go back to the dataset page and try to delete the dataset. You should see a user-friendly message 
[ENG-1530]: https://ethyca.atlassian.net/browse/ENG-1530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Prevent deleting linked datasets

- CHANGELOG.md
1.  Check spelling and formatting
> Updated CHANGELOG.md for release 2.71.1
