ethyca/fides

README.md
View the rendered `README.md` at the root of the repository in GitHub.
https://github.com/ethyca/fides/blob/rkeyser-readme-formatting/README.md
GitHub flavored MD can be finicky about blending MD with HTML. For the Summary/Description blocks, some of the code references were not displaying properly. Instead, they were showing unformatted with surrounding backticks. To resolve this, I changed inline ones to `<code> ... </code>` blocks and added an extra line between some content.
It originally looked like this:
And now it looks like this:
=> Fix formatting for nested code elements in README.md

README.md
Closes <issue>
* Repointed `https://ethyca.github.io/fides/tutorial/overview/` to `https://ethyca.github.io/fides/tutorial/`
* Repointed `https://ethyca.github.io/fides/tutorial/ci/` to `https://ethyca.github.io/fides/deployment/#step-5-install-fidesctl-cli-on-ci-build-server`
* Repointed `https://ethyca.github.io/fides/tutorial/evaluate/` to `https://ethyca.github.io/fides/tutorial/pass/#evaluate-the-fidesctl-policies`
View the README.md file in this branch and confirm the links work.
Changed the broken links that were in the first paragraph and elsewhere to valid URLs. These might not be the final URLs, but they work.
=> Fixed Tutorial Links

docs/fides/docs/api/index.md, docs/fides/docs/getting_started/docker.md, fidesctl/Dockerfile, fidesctl/src/fidesapi/crud.py, fidesctl/src/fidesapi/database.py, fidesctl/src/fidesapi/main.py, fidesctl/src/fidesctl/cli/cli.py, fidesctl/src/fidesctl/core/api.py, fidesctl/tests/conftest.py
Closes #202
Closes #204
- The two endpoints added to the API are `/admin/db/{action}` where `action` may be either `init` or `reset`
- As a security best practice, and before this is merged, the `database_url` value should be passed from the CLI to the API via `POST` body, _not_ via query param (as it is at the time of opening this PR).
=> Run migrations on API initialization, add `/admin/db/{action}` endpoints

fidesctl/src/fideslang/manifests.py
Closes #169 
Type-checking missed that the `yaml.load`/`yaml.safe_load` functions return `Any` type, but downstream code always expects a `Dict`.
=> Skip invalid manifest files

Makefile, docs/fides/docs/installation/installation.md, docs/fides/docs/installation/pypi.md, docs/fides/docs/quickstart/local_full.md, docs/fides/docs/quickstart/local_standalone.md, docs/fides/docs/quickstart/overview.md, docs/fides/mkdocs.yml, fidesctl/demo_resources/demo_policy.yml, fidesctl/src/fidesctl/cli/__init__.py, fidesctl/src/fidesctl/cli/cli.py, fidesctl/src/fidesctl/core/config.py, fidesctl/src/fidesctl/core/evaluate.py, fidesctl/src/fideslang/models.py, fidesctl/src/fideslang/validation.py, fidesctl/tests/cli/test_cli.py, fidesctl/tests/conftest.py, fidesctl/tests/core/test_evaluate.py, fidesctl/tests/data/passing_declaration_taxonomy.yml, fidesctl/tests/lang/test_relationships.py, fidesctl/tests/test_bad_config.toml
Closes #210 
The overall purpose of this PR is to allow people to run evaluations without needing to have a webserver and database spun up. This lowers the barrier to entry, especially on simpler projects and creates a faster "getting started". It is functionally similar to --dry but also prevents checking the server for missing resources. It will throw an error if a resource is referenced but not found locally (since otherwise it would have to check the server)
There is a new config option under the `cli` section called `local_mode`. If this is set to `true`, then the CLI will only show/run commands that can be run without any API/Database calls.
```sh
(base) PS C:\Users\tal10\Documents\Git> fidesctl --local
Usage: fidesctl [OPTIONS] COMMAND1 [ARGS]... [COMMAND2 [ARGS]...]...
The parent …
```
=> Add a local mode for Evaluations

docs/fides/docs/cli/cli.md, docs/fides/docs/cli/evaluate.md, docs/fides/docs/tutorial/add.md, docs/fides/docs/tutorial/google.md, docs/fides/docs/tutorial/policy.md
Closes #227 
Small update of link in cli docs
=> updating links in documentation

docs/fides/docs/ci_reference.md, docs/fides/mkdocs.yml
Closes #143 
Adds example files for several popular CI/CD pipeline management tools (GitLab CI, Jenkins, CircleCI).
=> Add CI/CD Reference Documentation

fidesctl/src/fidesctl/core/api.py
There are three instances where an "an" is used instead of a "a" in fidesctl/src/fidesctl/core/api.py
This is very much a drive-by pull request. The Fides project is very exciting to me and was browsing the codebase when I found some grammar errors. Totally fine if tiny PRs like these are not accepted. Best wishes to the Ethyca team 👍
=> Fix small grammar errors

.github/workflows/publish_docs.yaml, docs/fides/mkdocs.yml, docs/fides/requirements.txt
Closes #260 
Footer functionality is currently overwritten by our theme, but mkdocs supports all of the functionality we want without needing to add it explicitly to the footer. Here is a list of the changes:
* Top-right corner now has a link to our GitHub repository and also shows release version, stars and forks
* there is now a pencil icon at the top of every page that links directly to that page on github for easier editing
* The bottom of every page now has a `Last update: December 2, 2021` style footer that shows the last time the file was updated according to git. This is turned off when running locally because no git information exists, but when built for prod this will be included.
=> Add additional functionality to docs

.pre-commit-config.yaml, docs/fides/docs/development/code_style.md
Closes #229 
This PR adds the option to use pre-commit hooks while developing fidesctl. It requires the `pre-commit` package to be installed. Notes have also been added to the `development` section of the docs describing how to set it up
=> Fix the pre-commit configuration

README.md, docs/fides/docs/language/resources/policy.md, docs/fides/docs/tutorial/policy.md, fidesctl/demo_resources/demo_policy.yml, fidesctl/fides_resources/policy.yml, fidesctl/src/fidesctl/core/evaluate.py, fidesctl/src/fideslang/models.py, fidesctl/tests/conftest.py, fidesctl/tests/core/test_evaluate.py, fidesctl/tests/data/failing_dataset_collection_taxonomy.yml, fidesctl/tests/data/failing_dataset_field_taxonomy.yml, fidesctl/tests/data/failing_dataset_taxonomy.yml, fidesctl/tests/data/failing_declaration_taxonomy.yml, fidesctl/tests/data/passing_declaration_taxonomy.yml, fidesctl/tests/lang/test_models.py, fidesctl/tests/lang/test_relationships.py
Closes #150
Completely removes the `action` field from Policy manifests, since only `REJECT` was ever a valid value. Going forward, all policies will be assumed to `REJECT`. Also enables the `OTHER` match type, for privacy declarations not included in the list for the given Policy.
=> Remove the `action` field from Policy manifests, add an `OTHER` match type

fidesctl/src/fidesapi/main.py
Closes N/A
The auto-generated openapi docs are incorrect, due to where the routes are configured in `main.py`. This PR fixes that by calling it whenever the module is imported instead of whenever the app is started up
=> adjust where routes are configured

.github/workflows/pr_checks.yml, Makefile, docs/fides/docs/development/testing.md, docs/fides/docs/guides/scan_resource.md, fidesctl/setup.py, fidesctl/src/fidesctl/core/generate_dataset.py, fidesctl/tests/core/test_generate_dataset.py, fidesctl/tests/data/example_sql/snowflake_example.sql
Closes #253 
Created a `FIDESCTL` user and role in Snowflake which only has access to edit the database `FIDESCTL_TEST`. This was done with the following queries:
```
GRANT USAGE ON WAREHOUSE COMPUTE_WH TO ROLE FIDESCTL;
GRANT ALL ON DATABASE FIDESCTL_TEST TO ROLE FIDESCTL;
GRANT ALL ON SCHEMA FIDESCTL_TEST.PUBLIC TO ROLE FIDESCTL;
GRANT ALL ON FUTURE TABLES IN SCHEMA FIDESCTL_TEST.PUBLIC to ROLE FIDESCTL;
```
This is safe way to grant our CI access to a Snowflake user without risking anything else in our ethyca account. Also added some documentation for excluding external tests if needed(maybe if repo is forked or something like that)
Verified creating a database `EARMENDA_TEST` with a `public` schema generated the expected dataset:
```
fidesctl generate-dataset …
```
=> Integration with SnowFlake connector

fidesctl/src/fidesctl/cli/__init__.py, fidesctl/src/fidesctl/cli/cli.py, fidesctl/src/fidesctl/core/export.py, fidesctl/tests/cli/test_cli.py, fidesctl/tests/core/test_export.py
Closes #299 
As part of the crawl state, we want to be able to at least export some of the existing resources currently maintained in fides as csv.
I spent some time (probably too much tbf) looking at different options to try and flatten out the nested lists of data into something that aligned with the examples provided in the design/feature docs. Initially I thought this would be fairly straight forward to do using `json_normalize` in [pandas](https://pandas.pydata.org/docs/reference/api/pandas.json_normalize.html#). It ended up looking a bit over complicated by the time I had it (mostly) working so ended up using a list of tuples as records. I am not certain this is the right path forward by any means but as a starting point it felt the most clear. I'd love to learn more about if there …
=> Export System & Dataset as csv

docs/fides/docs/language/resources/dataset.md, docs/fides/docs/language/resources/organization.md, docs/fides/docs/language/resources/policy.md, docs/fides/docs/language/resources/registry.md, docs/fides/docs/language/resources/system.md, docs/fides/docs/language/taxonomy/data_categories.md, docs/fides/docs/language/taxonomy/data_subjects.md, docs/fides/docs/language/taxonomy/data_uses.md, fidesctl/src/fideslang/validation.py, fidesctl/tests/lang/test_validation.py
Closes #334 
Due to the very common nature of hyphens in hostnames and potentially table/database names, fides_key valid character list has been expanded to include hyphens
=> Allow hyphens in fides_key

fidesctl/src/fidesctl/cli/generate_commands.py, fidesctl/src/fidesctl/cli/scan_commands.py
Closes #361 
* Changed help text in Scan and Generate-dataset to correct spelling of style in "SQLAlchemy-stlye"
* `fidectl --help` should show correct spelling
Changes made to text within strings, should be fairly low-risk.
=> Help text edit: scan and generate-dataset

fidesctl/demo_resources/demo_system.yml
vengeance for #366 @screwlewse
* ~updated the attribute "data_use" --> "data_uses"~
Updated the `demo_system.yml` to use the previously identified `data_use` of `advertising`. 
This was originally changed as part of the work around an extended `data_use` and _should_ have been updated accordingly. Some testing to ensure future updates to the demo_resources have no unintended impacts (i.e. quickstart) should be handled in a follow-on issue to get this shipped.
=> Update demo_system.yml to make the quickstart work again

Makefile, fidesctl/src/fidesctl.egg-info/entry_points.txt, fidesctl/tests/cli/test_cli.py
Closes #378 
Small change to make sure we don't regress and break the webserver being run from the CLI
=> Add an additional check for running the webserver from the CLI

Makefile, fidesctl/tests/core/test_api.py
Closes #375 
Docker Compose version 2.2.2 used to guess whether to set the `no-TTY` flag when running the `docker compose run` command. As of 2.2.3 the flag is never set for you. 
See the related PR - [docker-compose-9035](https://github.com/docker/compose/pull/9035)
To understand the flag better, see the following:
https://stackoverflow.com/questions/30137135/confused-about-docker-t-option-to-allocate-a-pseudo-tty
What I think was happening before was that when github actions ran our `docker compose run` command it would set the `no-TTY` flag for us, and when running locally it would not. 
I can't say i 100% understand how this flag works or why we don't see output without it but setting it should be the equivalent of our previous behavior.
=> Update make commands to set no-TTY flag

fidesctl/src/fidesctl/cli/scan_commands.py, fidesctl/src/fidesctl/core/system.py, fidesctl/tests/core/test_system.py
Closes #341 
Will add some sample output here. 
Given a manifest file which contains all the resources in a given aws account:
```
root@a713a3eed1dc:/fides/fidesctl# fidesctl scan system aws --manifest-dir manifest.yml
Loading resource manifests from: manifest.yml
Taxonomy successfully created.
Scanned 2 resources and all were found in taxonomy.
Resource coverage: 100%
```
Given an AWS account with two redshift clusters which are not found in taxonomy:
```
root@a713a3eed1dc:/fides/fidesctl# fidesctl scan system aws 
Scanned 2 resource(s) and found 2 missing resource(s).
Missing Redshift Clusters:
arn:aws:redshift:us-east-1:910934740016:namespace:a3f04b4e-b044-4ba5-9aa9-57cddac54305
arn:aws:redshift:us-east-1:910934740016:namespace:057d5b0e-7eaa-4012-909c-3957c7149176
Resource coverage: 0% …
```
=> Implement scan system aws command

fidesctl/src/fidesctl/cli/generate_commands.py, fidesctl/src/fidesctl/cli/scan_commands.py, fidesctl/src/fidesctl/core/system.py, fidesctl/tests/core/test_system.py
Closes #342 
* One weird thing is that RDS has a concept for clusters and instances. Clusters are made up of instances but an instance does not necessarily have to be part of a cluster. To account for both we create a system for every cluster and for any instances which are not part of a cluster. 
Sample generate command
```
generate system aws manifest.yml
```
```
- fides_key: database-2
organization_fides_key: default_organization
name: database-2
description: 'Fides Generated Description for RDS Cluster: database-2'
fidesctl_meta:
resource_id: arn:aws:rds:us-east-1:910934740016:cluster:database-2
endpoint_address: database-2.cluster-ckrdpkkb4ukm.us-east-1.rds.amazonaws.com
endpoint_port: '3306'
system_type: rds_cluster
privacy_declarations: []
administrating_department: Not defined
- …
```
=> Add RDS as an aws source

.github/workflows/publish_docs.yaml, docs/fides/requirements.txt
Closes #406
New step in job:
```
- name: Install fidesctl
run: pip install -e fidesctl/
```
=> Install fidesctl from source instead of pulling from pypi

Makefile, docker-compose.yml, fidesctl/requirements.txt, fidesctl/src/fidesctl/cli/__init__.py, fidesctl/src/fidesctl/cli/utils.py, fidesctl/src/fidesctl/core/config/cli_settings.py
Closes #401
With `FIDESCTL__CLI__ANALYTICS_ID` set in your local ENV:
With `FIDESCTL__CLI__ANALYTICS_ID` **not** set in your local ENV:
- AND no `analytics_id` value in your config file:
- AND an `analytics_id` value of `""` in your config file:
- AND a valid `analytics_id` value already in your config file:
We require the ability to distinguish `AnalyticsEvent`s written by users performing local development on fidesctl. This change ensures that if fidesctl is started with `FIDESCTL__CLI__ANALYTICS_ID` set to `"True"`, any generated `AnalyticsEvent`s are flagged as "developer" events.
=> Send "developer" analytics events in test mode

docs/fides/docs/schemas/config_schema.json, docs/fides/requirements.txt
Closes #415
* update mkdocs version to be compatible with recent jinja2 release 
Mkdocs pushed [a patch](https://github.com/squidfunk/mkdocs-material/releases/tag/8.2.7) to limit the jinja version range. Updating the pinned version in the docs' `requirements.txt` will resolve the issue for now, but might not be the best strategy for versioning in the future.
=> update mkdocs-material version (#415)

docs/fides/docs/guides/generate_resources.md, docs/fides/docs/language/resources/dataset.md, docs/fides/docs/tutorial/add.md, docs/fides/docs/tutorial/dataset.md, fidesctl/src/fidesctl/cli/generate_commands.py, fidesctl/src/fidesctl/cli/scan_commands.py, fidesctl/src/fidesctl/core/dataset.py, fidesctl/tests/cli/test_cli.py, fidesctl/tests/core/test_dataset.py
Closes #398
This change was already made for the infrastructure scanning work but needed to be made for older dataset commands as well. 
Old Commands:
```sh
./venv/bin/fidesctl generate dataset \
postgresql://postgres:postgres@localhost:5432/flaskr \
fides_resources/flaskr_postgres_dataset.yml
```
```sh
./venv/bin/fidesctl scan dataset \
postgresql://postgres:postgres@localhost:5432/flaskr 
```
New Commands:
```sh
./venv/bin/fidesctl generate dataset db \
postgresql://postgres:postgres@localhost:5432/flaskr \
fides_resources/flaskr_postgres_dataset.yml
```
```sh
./venv/bin/fidesctl scan dataset db \
postgresql://postgres:postgres@localhost:5432/flaskr 
```
* Also it looks like the `generate dataset` was previously broken due to a parameter filename which was incorrectly named. I added new …
=> Refactor generate/scan dataset commands so dataset is a command group

fidesctl/tests/core/test_config.py
Closes N/A
I saw [this test](https://github.com/ethyca/fides/blob/014b4e5f90dac4a0c04f28f656314abd9e00a6c4/fidesctl/tests/core/test_config.py#L32) had a `TODO` that it was not working and needed to be fixed. This PR makes the test pass.
=> Fix test_config_from_env_vars tests

fidesctl/src/fidesapi/database/crud.py, fidesctl/src/fidesapi/database/database.py, fidesctl/src/fidesapi/routes/crud.py, fidesctl/src/fidesctl/cli/core_commands.py, fidesctl/src/fidesctl/cli/options.py, fidesctl/src/fidesctl/core/api.py, fidesctl/src/fidesctl/core/apply.py, fidesctl/tests/core/test_api.py, fidesctl/tests/core/test_apply.py
=> `fidesctl apply` "upserts" resources

docs/fides/docs/css/fides.css
Fixing the navbar error where the tags didn't show up, and removing #0861ce from the navbars as it's being retired from the brand. I also added a couple of QOL copy updates to align with the style of text on our blogs.
=> Updating navbars to brand guidelines

fidesctl/MANIFEST.in, fidesctl/src/fidesctl/core/export_helpers.py
Closes #452 
To validate this, the following steps were followed:
1. Pull this branch and run `make api`
2. Create a separate directory and virtual environment, then locally pip install this branch (i.e. `pip install -e ../fides/fidesctl/.`) - the subsequent steps are all in this new virtual env/directory
3. **Note:** I also needed to run `pip install okta`
4. Include the files from `demo_resources/` in the new directory
5. Apply the new resources `fidesctl apply demo_resources/`
6. Export the new resources `fidesctl export datamap demo_resources/`
This would previously have failed if installing the latest version from pip instead of the local branch (`pip install fidesctl==1.4.2`)
=> FileNotFound from pip install

docs/fides/docs/installation/pypi.md, fidesctl/src/fidesctl/cli/commands/generate.py, fidesctl/src/fidesctl/cli/commands/scan.py
Closes #451 
Add a check to catch if someone forgot to install the AWS dependencies before running the commands. Also updates the docs to list the `aws` option
```txt
root@2b4764366623:/fides/fidesctl# pip uninstall boto3
Found existing installation: boto3 1.20.54
Uninstalling boto3-1.20.54:
Would remove:
/usr/local/lib/python3.8/site-packages/boto3-1.20.54.dist-info/*
/usr/local/lib/python3.8/site-packages/boto3/*
Proceed (Y/n)? y
Successfully uninstalled boto3-1.20.54
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv 
root@2b4764366623:/fides/fidesctl# fidesctl scan system aws
Packages not found, try: pip install …
```
=> Check for boto before running AWS commands

docs/fides/docs/guides/generate_resources.md
=> Fix --manifest-dir usage documentation

docker-compose.yml, fidesctl/.fides/fidesctl.toml, fidesctl/tests/core/test_config.py
Closes #394 
This fix makes sure that running `make cli` and running fidesctl commands won't break even if the default value of `localhost` or some other value is set within the config file.
=> Set the server host via a compose env var

fidesctl/src/fidesctl/connectors/okta.py, fidesctl/tests/connectors/test_okta.py
Closes #469 
An application can be deactivated in Okta before it is deleted. These inactive applications should not be tracked.
=> Filter Okta datasets so only applications with ACTIVE status are accounted for

fidesctl/src/fidesctl/core/export.py, fidesctl/src/fideslang/models.py
Closes #458 
Originally we thought this may be resolved by setting the default to use the enum value, however this caused type issues with `mypy`
This config option should do it [per the pydantic docs](https://pydantic-docs.helpmanual.io/usage/model_config/#:~:text=hashable.%20(default%3A%20False)-,use_enum_values,-whether%20to%20populate)
To validate the new output, use the command from the issue:
`fidesctl generate system aws manifest.yml`
There are a few other places that this could likely be implemented (and provide some consistency) but feel like that can be a separate targeted PR as it will touch a bit more of the export functionality.
=> Set Default data_responsibility_title with generate system

fidesctl/src/fidesctl/cli/commands/generate.py, fidesctl/src/fidesctl/cli/commands/scan.py, fidesctl/src/fidesctl/core/dataset.py, fidesctl/src/fidesctl/core/system.py
Closes #474 
Found when trying to run the `fidesdemo` using 1.5.0
To test the fix:
```sh
$ python3 -m venv env && source env/bin/activate
$ pip install git+https://github.com/ethyca/fides.git@SteveDMurphy-missing-init#subdirectory=fidesctl
$ fidesctl --help
```
To see the error, just replace the pip installation with `1.5.0`
=> add missing __init__.py

fidesctl/src/fidesctl/cli/__init__.py
Closes #475 
This was discovered while resolving the missing commands for a pip installation. It appears that the server/cli check was running when trying to use the init command. This caused an error to be returned when using the quickstart. 
I'd also like to do some further testing against fidesdemo.
=> move init to LOCAL_COMMANDS

fidesctl/src/fidesctl/cli/__init__.py, fidesctl/src/fidesctl/cli/commands/util.py, fidesctl/src/fidesctl/cli/utils.py
=> Clarify log output from `fidesctl status`

fidesctl/src/fidesctl/cli/__init__.py
Closes n/a
A Xenon failure foiled our CI checks, potentially from two bug PRs passing each other in the night. This is currently impacting any open PR, this should be a relatively simple modification that can unblock the open PRs
=> Resolve Xenon Failure

Makefile
Closes #417 
This PR changes `make clean` to be less destructive to resources outside of the project. It leverages docker compose to remove all of the resources specific to our project and then removes any dangling cached layers. Removing dangling cached layers would potentially get rid of resources from other projects but given that they're dangling it shouldn't be a big issue 
I went to the fidescls repo, spun up the container there, then went back to fidesctl and ran the `make clean` command and confirmed that the fidescls image was untouched
=> `make clean` target should only clean up fidesctl-related resources

fidesctl/tests/core/test_export_helpers.py
Closes #497
This prevents a potentially incorrectly passing test as described in the issue.
=> Correct assertion in test

fidesctl/src/fidesctl/core/export.py, fidesctl/src/fidesctl/core/export_helpers.py, fidesctl/tests/core/test_export_helpers.py
Closes #484
1.  Update the demo_marketing_system to include:
```yaml
third_country_transfers:
- USA
````
2. `fidesctl apply demo_resources/`
3. `fidesctl export datamap demo_resources/`
4. Verify the row for that resource in the data map shows `USA`
I found a couple issues. Sometimes `system.third_country_transfers` contains an empty string `""`. In this case the empty string gets concatenated resulting in `, USA`. When the specific case mentioned in the issue the `N\A` value was kept even when a country was present.
When working on this I realized that the current code takes two passes through all the data in order to generate the third party country strings. I included a small refactor here to only need one pass through.
=> Fix third country formatting on data map

fidesctl/src/fidesctl/core/export.py, fidesctl/src/fidesctl/core/export_helpers.py
Closes #455 
The duplication stemmed primarily from other populated properties that, when joined, would have a one to many relationship. Removing any non-essential values and cleaning the data seemed like an appropriate step here to keep iterating on this and resolve the issue.
Additionally, we needed to add some filtering for when a data category exists on both a system and dataset. We prefer the more detailed dataset in this scenario.
To validate the changes work for the `fidesdemo` resources, I ended up doing the following:
1. `make cli`
2. Copy the resources from the [fidesdemo pr for 1.5](https://github.com/ethyca/fidesdemo/pull/11) into a new directory (`fidesdemo/`)
3. `fidesctl apply fidesdemo && fidesctl export datamap fidesdemo`
4. Validate the duplication from 1.5.2 no longer …
=> Handle potential duplication in data map

fidesctl/requirements.txt, fidesctl/src/fidesctl/cli/commands/util.py, fidesctl/src/fidesctl/cli/utils.py
Related to ethyca/fideslog#50
Related to ethyca/fideslog#51
Fideslog v1.1.3 includes the following changes
- The `AnalyticsClient.send` interface automatically executes the request in a separate event loop. There is no longer a need to manually wrap the call in `asyncio.run` or similar.
- `AnalyticsException` has been renamed to `AnalyticsError`, to better align with Python convention
- The SDK's `utils.py` file now separately exposes `OPT_OUT_COPY` and `OPT_OUT_PROMPT`, to better enable non-CLI applications to display `OPT_OUT_COPY` without automatically assuming a user will respond with their keyboard.
=> Bump fideslog to v1.1.3, update usage patterns

CHANGELOG.md, requirements.txt
Closes #513
On Windows:
Fideslog 1.1.4 includes a change to detect when the SDK is run in a Windows process, and sets the event loop policy as needed in order to avoid a bug in Python 3.8+.
=> Bump fideslog to 1.1.4

CHANGELOG.md, src/fidesapi/main.py, src/fidesctl/core/config/api_settings.py
Closes #326
```
2022-04-27 00:09:14.674 [DEBUG] (main:setup_server:54): Configuration options in use | {'api_config': '{"database_user": "postgres", "database_host": "fidesctl-db", "database_port": "5432", "database_name": "fidesctl", "test_database_name": "fidesctl_test", "log_destination": "", "log_level": "DEBUG", "log_serialization": ""}'}
```
The original goal involved differentiating between default/unset values (logged at the `WARNING` level) and user-defined options (logged at the `DEBUG` level). It was difficult and verbose to create log entries this way, so the server simply logs all of the `APISettings` in use at startup time.
=> Log in-use API server config values on startup

CHANGELOG.md, src/fidesctl/cli/commands/util.py
Relates to #512
The server port is included in the values to includes, however since it does not have a default value it doesn't get added to the resulting file. I included it anyways in case a default value is ever added, that way the resulting file will include it. I am not sure if #512 can be closed with this or not. The issue of the protocol being doubled seems to be fixed even without this update so I think it can.
=> Modify default cli fields in fidesctl.toml on init

CHANGELOG.md, src/fidesctl/core/export_helpers.py, tests/core/test_export_helpers.py
Closes #539
This was found to be failing in #533, however the root cause of the failure was implemented in #510. Removing the parentheses loads the enum values properly for inspection.
This ended up being a fairly simple change to solve this problem. It may make sense to cut a minor release for this bug.
=> Properly Load Enum Values for DataSubjectRightsEnum

CHANGELOG.md, requirements.txt
Closes #608
Fideslog v1.1.5 includes a fix for an issue where some exceptions thrown by the SDK are not wrapped in the `AnalyticsError` type, breaking the intended exception handling workflow for consumers.
For a complete changelog, see: https://github.com/ethyca/fideslog/compare/v1.1.4...v1.1.5
=> Update fideslog to v1.1.5

noxfiles/docs_nox.py
Closes n/a
This was missed in #558 as part of the static code validation updates. Updating the param should fix the docs build failure, no update to the check should be necessary at this point.
=> update the type param for docs_build nox command

CHANGELOG.md, docs/fides/docs/css/fides.css, docs/fides/docs/schemas/config.md, docs/fides/mkdocs.yml, generate_docs.py
=> clean up docs (config, css)

.gitignore, CHANGELOG.md, Dockerfile, src/fidesapi/main.py, tests/core/test_api.py
Closes https://github.com/ethyca/fides/issues/560
Adds a path where static files can be served from our existing python webserver.
=> Serve static files

CHANGELOG.md, tests/core/test_dataset.py
Relates to #658 
Add character quoting to connection strings in `test_dataset.py`, originally found when testing #548
=> complex character handling in test_dataset.py

src/fidesctl/core/export_helpers.py, tests/cli/test_cli.py
Closes #651
This is a near-term workaround until we include all resources on the server as part of the export. This fix will ensure that the default_organization is included at minimum, which is in line with our documentation around being able to utilize default_organization behind the scenes.
This will unblock users from currently hitting an error when trying to utilize an organization not defined in the manifest directory.
=> Include default_organization in data map export if no Organization found

CHANGELOG.md, src/fidesctl/core/evaluate.py, tests/cli/test_cli.py, tests/core/test_evaluate.py
Closes #683 
The way that we were merging taxonomies for evaluations was incorrect and causing some overwrites. Typically this wouldn't cause an issue as the taxonomy would be able to rehydrate via the server, but this bug surfaced in `local` mode.
There is now a separate function that merges the taxonomies in a more specific way so as not to clobber user-defined elements
=> Fix local demo_resources evaluation

CHANGELOG.md, noxfiles/ci_nox.py, src/fidesapi/routes/util.py, src/fidesctl/cli/utils.py, src/fidesctl/core/api.py, src/fidesctl/core/utils.py, tests/cli/test_cli_utils.py, tests/core/test_api.py
Closes #681 
This PR fixes the import issue that would cause the CLI to be broken if not installed with certain optional dependencies. It also updates an existing CI check to catch this bug if it were to happen again
=> Fix Installation Check to catch uninstalled module errors

CHANGELOG.md, setup.py
=> Sync version of fastapi in setup.py with optional-requirement.txt

CHANGELOG.md, src/fidesctl/core/export.py, src/fidesctl/core/export_helpers.py, tests/core/test_export.py
Closes #720
This went through a few iterations trying to find the right placement and balance for the formatting of the taxonomy components. In the end moving them as close to their uses seemed to make the most sense. This change should allow for improved reuse of the core functions and helpers that exist as part of exporting resources data from fides.
=> Refactor Export to remove CLI specific request methods

.github/workflows/docker.yaml, CHANGELOG.md
Closes #731 
Docker will now only build and push on tagged release versions. Additionally I'll go through and clean up our dockerhub to get rid of the dirty versions
=> Update to only push to Docker on tagged releases

CHANGELOG.md, clients/admin-ui/__tests__/features/dataset-helpers.test.tsx, clients/admin-ui/src/features/common/form/inputs.tsx, clients/admin-ui/src/features/dataset/DatasetCollectionView.tsx, clients/admin-ui/src/features/dataset/DatasetFieldsTable.tsx, clients/admin-ui/src/features/dataset/EditFieldDrawer.tsx, clients/admin-ui/src/features/dataset/constants.ts, clients/admin-ui/src/features/dataset/dataset.slice.ts, clients/admin-ui/src/features/dataset/helpers.ts, clients/admin-ui/src/mocks/data.ts, clients/admin-ui/src/pages/dataset/index.tsx
Closes https://github.com/ethyca/fides/issues/703
https://user-images.githubusercontent.com/24641006/171722112-c6118f5e-8482-4a4b-b245-61441d079843.mov
There's some odd logic going on in this PR that is a result of `collections` and `fields` not having a unique key associated with them. It appears possible to add collections/fields of the same name. This means the only way to determine which field or collection the user has clicked on is to use the index in the array that the object is in. This is fairly cumbersome, but should mostly be isolated to a few helper functions I added. 
However, this is still an issue, since React requires `keys` for components that are rendered via arrays, and discourages using indexes. Not having unique keys makes React act funky. …
=> Create form for editing dataset fields

.github/workflows/code_checks.yml, .github/workflows/pr_checks.yml
Closes <issue>
Noticed that PR checks were running in docs-only/markdown-only changes, this seemed unnecessary so I made this PR to fix it
=> Ignore Docs/README changes in certain workflows

CHANGELOG.md, src/fidesctl/core/dataset.py, src/fidesctl/core/utils.py, tests/core/test_utils.py
Closes #749
This bug was found while working with a design partner. Further steps may include looking at if the `fides_key` already exists and providing an option to accept all suggested values.
After chatting with the team, decided against providing a manual intervention option at this time. Two questions remain prior to merging:
1. Do we also apply this to the different `generate` command options (i.e. `systems`)
2. Can we put this in a minor release `1.6.1`
=> Handling an invalidly generated fides_key

CHANGELOG.md, docs/fides/docs/development/releases.md
Closes n/a
These are the steps that I followed for `1.6.1`, not necessarily what we should do exactly for future minor releases. Would love further opinions or ideas here!
=> 1.6.1 changelog and docs updates

clients/admin-ui/package.json, docker-compose.yml
Closes #794 
Small update to fix the problem of `nox -s dev` not working on a first install due to the packages not being installed yet. One caveat here is that spinning up the UI still takes a long time and I'm not sure why, but it does work. As far as I can tell it isn't related to the `install` step, but instead the actual `run dev` step.
=> Fix `nox -s dev` to be able to run without first installing the node modules

docs/fides/docs/guides/generate_resources.md
Closes #528
* Quick fix to add a link out to the sqlalchemy documentation to assist in finding your db connection string.
=> add example connection string formatting for convenience

CHANGELOG.md, clients/admin-ui/src/features/common/form/inputs.tsx
Wrap the select and tooltip in a flexbox so that they are in the same grid column.
I wonder if this was the result of a merge conflict that made a `Box` wrapping go away 🤔 . The multi-select does it correctly.
Before: 
After:
=> ui/form: Fix select tooltip wraping grid row

CHANGELOG.md, clients/admin-ui/src/features/common/form/inputs.tsx, clients/admin-ui/src/features/dataset/EditDatasetForm.tsx
Quick fix for the case where a third_party_transfer does not exist on a dataset which was causing an error to be thrown
This is a better solution than the one I stuffed in https://github.com/ethyca/fides/pull/827 (and which @ssangervasi had the right intuition on! https://github.com/ethyca/fides/pull/827/files#r911347651)
=> Handle case of undefined third_party_transfer

CHANGELOG.md, README.md, docs/fides/docs/development/overview.md, docs/fides/docs/installation/installation.md, docs/fides/docs/installation/pypi.md, docs/fides/docs/quickstart/local_full.md, docs/fides/docs/quickstart/local_standalone.md, docs/fides/docs/tutorial/add.md
Closes #862 
* Update all the docs uses of `pip` to recommend, link to, or also include `pipx` installations.
=> [#862] recommend/replace pip installs with pipx

.github/workflows/frontend_pr_checks.yml, clients/admin-ui/package.json
* New package script for build & serve in test mode
* Start cypress with that instead of dev
I ran into a surprise failure with on a PR and I got curious. Then I noticed [this comment](https://github.com/ethyca/fides/blob/40294f297f8f27209f26a82687af956a47bca231/clients/admin-ui/cypress/e2e/datasets.cy.ts#L36) where a timeout was happening because of routing I got a hunch: maybe next dev mode is hot loading routes is slowing it down. [This next documentation](https://nextjs.org/docs/testing#running-your-cypress-tests) also suggests running cypress against the built app.
👨‍🔬🧪 Experiment time (running cypress locally)
| App start |  Cypress time | Note |
| --- | --- | --- |
|`next dev` |~ 75 seconds | Faster after first run. Cache? |
|`next build && next start` | ~ …
=> github/frontend: Run cypress in CI with app built

CHANGELOG.md, clients/admin-ui/src/features/common/helpers.ts, clients/admin-ui/src/features/dataset/DatabaseConnectForm.tsx, clients/admin-ui/src/features/dataset/DatasetYamlForm.tsx, clients/admin-ui/src/features/dataset/dataset.slice.ts, clients/admin-ui/src/types/api/index.ts, clients/admin-ui/src/types/api/models/DatabaseConfig.ts, clients/admin-ui/src/types/api/models/Generate.ts, clients/admin-ui/src/types/api/models/ValidTargets.ts
Closes https://github.com/ethyca/fides/issues/829
One thing I'm not sure how to approach is that we need an organization key to use the generate endpoint. I hard coded `default_organization` for now, but I'm not sure how we plan to go about getting that in the future (potentially related to config UI work? is it possible we can always have an organization key around, similar to how we'd have a user around?)
Success state
https://user-images.githubusercontent.com/24641006/178360582-79eb3996-149a-4f36-b7c7-2c21d889c2ee.mov
Errors
https://user-images.githubusercontent.com/24641006/178360701-15bc74bf-c103-42b3-9ce7-d257c21679cf.mov
Error if the string just doesn't work (not sure if the backend can give a better error than just a 500, or if there's any validation we …
=> Integrate generating a dataset from a database connection

CHANGELOG.md, requirements.txt
Closes #816 
Quick fix for a bug reported by an internal user, turns out to be an issue the M1 macs specifically and this should fix it, as suggested by [this thread](https://github.com/sqlalchemy/sqlalchemy/issues/7714)
=> Fix SQLAlchemy M1 `greenlet` missing bug

CHANGELOG.md, clients/admin-ui/package-lock.json, clients/admin-ui/package.json, clients/admin-ui/src/features/common/helpers.ts, clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx, clients/admin-ui/src/features/config-wizard/DescribeSystemsForm.tsx, clients/admin-ui/src/features/config-wizard/OrganizationInfoForm.tsx, clients/admin-ui/src/features/config-wizard/PrivacyDeclarationForm.tsx, clients/admin-ui/src/features/dataset/EditDatasetDrawer.tsx, clients/admin-ui/src/types/errors/api.ts, clients/admin-ui/src/types/errors/index.ts, clients/admin-ui/src/types/errors/models.ts
Closes 803
- Use standard error message helpers everywhere
- Standard location for API error type checking
- ui/package.json: Add narrow-minded 1.1.0
- This is a general-purpose tool for typechecking objects.
This introduces a new set of files for defining API error interfaces and functions for checking whether a response matches one of the known types. The error message helpers then use these type checkers to cleanly dig through an RTK result to find a user-visible string. There will be more cases to handle, but this should be extensible.
=> [803] ui/errors: Standard location for API error type checking

.github/workflows/docker.yaml, .github/workflows/publish_docs.yaml, CHANGELOG.md, noxfiles/docker_nox.py
Closes #807
Spent some time in a test repo to ensure the workflow updates should work for us.
I'm unsure still if the nox changes are sufficient, or if there should be a separate constant used for the current working version.
Another additional question is if we want to retroactively publish docs versions that were missed 🤔
=> CI Production Workflows for Docker and Docs

CHANGELOG.md, src/fidesctl/api/routes/util.py, src/fidesctl/cli/utils.py, src/fidesctl/core/api.py, src/fidesctl/core/utils.py, tests/cli/test_cli_utils.py, tests/core/test_api.py
Closes <issue>
`API_PREFIX` was originally duplicated in fidesctl/core/utils.py because the `api` was installed as an extra, and when it was not installed the `API_PREFIX` was not available causing an error. Now that `api` has been moved into fidesctl and is always included this is no longer needed, and removing the duplicate makes maintenance easier.
=> Remove duplicate API_PREFIX

clients/admin-ui/.eslintrc.json, clients/admin-ui/src/features/organization/constants.ts, clients/admin-ui/src/features/taxonomy/helpers.ts, clients/admin-ui/src/mocks/browser.ts, clients/admin-ui/src/mocks/handlers.ts, clients/admin-ui/src/mocks/server.ts, clients/admin-ui/src/test-utils.tsx
We keep bumping into this rule with utility modules, so it's doing more harm than good. I considered using [overrides](https://eslint.org/docs/latest/user-guide/configuring/rules#:~:text=syntactically%20valid%20JavaScript.-,Using%20configuration%20files,-To%20disable%20rules) to re-enable the rule for `.tsx` component files, but that's a bit tricky and I personally don't feel that strongly about that pattern anyway. We make good use of index files and `import { Foo as Bar }` when necessary which is usually more ergonomic.
=> ui/eslintrc: Turn off "import/prefer-default-export"

CHANGELOG.md, clients/admin-ui/__tests__/features/taxonomy-transform.test.tsx, clients/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/admin-ui/src/features/common/AccordionTree.tsx, clients/admin-ui/src/features/common/CheckboxTree.tsx, clients/admin-ui/src/features/common/DataTabs.tsx, clients/admin-ui/src/features/common/types.tsx, clients/admin-ui/src/features/dataset/DataCategoryInput.tsx, clients/admin-ui/src/features/taxonomy/DataCategoryChecklist.tsx, clients/admin-ui/src/features/taxonomy/TaxonomyTabContent.tsx, clients/admin-ui/src/features/taxonomy/helpers.ts, clients/admin-ui/src/features/taxonomy/types.ts, clients/admin-ui/src/mocks/data.ts
Closes https://github.com/ethyca/fides/issues/853
Only thing outstanding is this bit of CSS I'm struggling with: https://github.com/ethyca/fides/pull/910#discussion_r922477720
Other than that, good to review!
https://user-images.githubusercontent.com/24641006/179609287-cc68eceb-0652-4d88-a228-3051334e61c3.mov
=> Taxonomy nested dropdown

CHANGELOG.md, requirements.txt, src/fidesctl/api/deps.py, tests/conftest.py
Closes <issue>
The `USER_PASSWORD_RESET` scope was missing form the `SCOPES` list so I temporarily patched the list with the value. v3.0.1 now contains the value so the patch is no longer needed.
=> Bump fideslib to 3.0.1 and remove patch code

CHANGELOG.md, src/fidesctl/core/config/__init__.py, src/fidesctl/core/config/utils.py
Closes #932
Another hangup that keeps being found here is the need to manually add the port to the default config. Maybe worth taking a look there to ease startup steps/pain?
I think a good test for this may be to try and validate the webserver without passing the config, but not sure if that makes sense or not as of yet
Testing this PR requires a running db, so executing `docker compose up -d fidesctl-db` is a prereq
=> Replace config file string with a constant of the path

.github/workflows/release_event.yml, CHANGELOG.md
Related to ethyca/fidesctl-plus#27
Blocks ethyca/fidesctl-plus#44
There is no way for a GH Actions workflow to read the releases in another repository. In order for an issue to be automatically created in the fidesctl-plus repository whenever a new fidesctl release is published, the act of publishing the fidesctl release must dispatch a repository event to the fidesctl-plus repo. This event is used to trigger a separate GH Actions workflow in the fidesctl-plus repository, which creates the desired issue.
=> Dispatch a repository event on new published releases

CHANGELOG.md, README.md, docs/fides/docs/cicd/overview.md, docs/fides/docs/guides/generating_datamap.md, src/fidesctl/cli/__init__.py, src/fidesctl/cli/commands/core.py, src/fidesctl/ctl/core/push.py, tests/ctl/cli/test_cli.py, tests/ctl/core/test_apply.py
Closes #923 
I looked into using something fancy to solve this but it doesn't really seem worth it. This [library](https://github.com/click-contrib/click-aliases) provides the ability to add an alias to a command but the downside is that there is no option to deprecate the command. 
Open to trying a more complex change but this feels like a good bridge to eventually remove the `apply` command. 
```
fides> fides apply
DeprecationWarning: The command 'apply' is deprecated.
Use the 'push' command instead.
Loading resource manifests from: .fides/
Taxonomy successfully created.
----------
Processing system resource(s)...
PUSHED 1 system resource(s).
----------
Processing policy resource(s)...
PUSHED 2 policy resource(s).
----------
Processing dataset resource(s)... …
```
=> Add push command to deprecate apply

CHANGELOG.md
=> Update CHANGELOG.md after 1.7.1 release

.dockerignore, .github/workflows/publish_package.yaml, CHANGELOG.md, Dockerfile, MANIFEST.in, clients/admin-ui/package.json, setup.cfg, setup.py, src/fidesctl/api/ctl/routes/util.py, src/fidesctl/api/ctl/ui.py, src/fidesctl/api/main.py
Closes https://github.com/ethyca/fides/issues/940
Via just building and installing the Python package
Via docker
Via pypi
Haven't been able to fully test this yet, as I don't want to upload to the real pypi yet, and the creds don't seem to work in testpypi. But in theory you'd just do a `pip install fidesctl` and then you'd be able to run `fidesctl webserver` right away
Fairly sure that the publish package workflow will work, since it got as far as uploading to twine before it failed (403) https://github.com/ethyca/fides/runs/7547449743?check_suite_focus=true
=> Bundle UI static files with the python package

.github/workflows/publish_docs.yaml
Closes #947 
https://github.com/ethyca/fides/pull/901 Fixed the docker release not working. This was not working before because the docker logic was depending on a release event github.event.release.tag_name. This didnt work because the docker event is actually a push event, not a release event. Unfortunately this fix was also applied to the docs workflow but this one actually is triggered by a release event.
=> Remove usage of event.ref in release workflow for publishing docs

CHANGELOG.md, Dockerfile, dev-requirements.txt, docs/fides/Dockerfile
Closes #935 
This is being done for security reasons, as `buster` is EOL this month
=> Update base images from buster to bullseye

CHANGELOG.md, src/fidesctl/cli/utils.py, src/fidesctl/ctl/core/config/__init__.py, tests/ctl/cli/test_cli.py, tests/ctl/conftest.py, tests/ctl/core/test_config.py, tests/ctl/test_config.toml, tests/ctl/test_deprecated_config.toml
Closes #957 
This PR adds a special handler function that will update new config values with older, deprecated ones. This is a short-term stop-gap solution until we implement a proper procedure for deprecating config values or other code features.
Note specifically that if the `database` section exists, this overwrite will get skipped, however if the `api` section (the deprecated one) exists and the `database` section does _not_ exist than the API values will get mapped to the new database section.
This PR is designed to also be minimally invasive, so this should be a pretty safe change to make to support our users. Tests have been updated accordingly to make sure things are being written as intended.
As a side note, I realized that `fides view config` was broken …
=> Re-add deprecated API settings for backwards compatibility

.github/workflows/publish_package.yaml, CHANGELOG.md, docker-compose.yml, docs/fides/docs/quickstart/docker.md, docs/fides/docs/tutorial/add.md, setup.cfg
=> Remove old env vars

.github/workflows/code_checks.yml, .github/workflows/frontend_pr_checks.yml, .github/workflows/publish_package.yaml, .gitignore, CHANGELOG.md, Dockerfile
Closes #961 
There are two fundamental bugs fixed in this PR:
1. Whenever the git folder gets copied into the docker container it busts the git cache and then git thinks that _every_ file is new. A new docker build step has been added to fix this
2. When publishing the pypi package, the `sdist` build modifies a file so that when the `wheel` gets built it shows up as a dirty version. This is due to the `egg-info` file getting modified. This has been fixed by running a `git reset --hard` after the `sdist` builds
=> Fix `fides --version` showing dirty in releases

.github/workflows/code_checks.yml, .github/workflows/frontend_pr_checks.yml, .github/workflows/publish_package.yaml, .gitignore, CHANGELOG.md, Dockerfile, docker-compose.yml, docs/fides/docs/development/releases.md, docs/fides/docs/quickstart/docker.md, docs/fides/docs/tutorial/add.md, setup.cfg, src/fidesctl/ctl/core/config/__init__.py, tests/ctl/core/test_config.py
=> Merge Release v1.8.1 branch

.github/workflows/code_checks.yml, .github/workflows/publish_package.yaml, CHANGELOG.md, Dockerfile, README.md, docs/fides/Dockerfile, docs/fides/docs/installation/prerequisites_dependencies.md, docs/fides/docs/tutorial/index.md, setup.py
Closes #973 
Upgrade to 3.9, not expecting any changes that break backwards compatibility. Gets us in a better position to merge with fidesops
=> Bump Python version to 3.9 in Docker and setup.py

README.md
=> [#981] update readme subsections to display as plain text

CHANGELOG.md, dev-requirements.txt
Closes <issue>
setuptools 64.0.2 includes a fix to the editable install error with versioneer.
=> Add setuptools to dev-requirements to fix versioneer error

clients/ctl/admin-ui/src/features/taxonomy/EditTaxonomyForm.tsx, clients/ctl/admin-ui/src/features/taxonomy/types.ts, clients/ctl/admin-ui/src/types/api/index.ts, clients/ctl/admin-ui/src/types/api/models/AccessToken.ts, clients/ctl/admin-ui/src/types/api/models/BigQueryConfig.ts, clients/ctl/admin-ui/src/types/api/models/DataCategory.ts, clients/ctl/admin-ui/src/types/api/models/DataQualifier.ts, clients/ctl/admin-ui/src/types/api/models/DataSubject.ts, clients/ctl/admin-ui/src/types/api/models/DataUse.ts, clients/ctl/admin-ui/src/types/api/models/Generate.ts, clients/ctl/admin-ui/src/types/api/models/KeyfileCreds.ts, clients/ctl/admin-ui/src/types/api/models/Page_UserResponse_.ts, clients/ctl/admin-ui/src/types/api/models/UserCreate.ts, clients/ctl/admin-ui/src/types/api/models/UserCreateResponse.ts, clients/ctl/admin-ui/src/types/api/models/UserLogin.ts, clients/ctl/admin-ui/src/types/api/models/UserLoginResponse.ts, clients/ctl/admin-ui/src/types/api/models/UserPasswordReset.ts, clients/ctl/admin-ui/src/types/api/models/UserResponse.ts, clients/ctl/admin-ui/src/types/api/models/UserUpdate.ts, clients/ctl/admin-ui/src/types/api/models/ValidTargets.ts, clients/ctl/admin-ui/src/types/api/models/ValidateRequest.ts, clients/ctl/admin-ui/src/types/api/models/ValidationTarget.ts
Closes https://github.com/ethyca/fides/issues/988
Should just be a small types related change, so nothing noticeable. It looks like we haven't run the generate command in a bit though, so there are a few new models that are unrelated to taxonomy.
=> Update typescript types for taxonomy `is_default`

CHANGELOG.md, demo_resources/demo_system.yml, src/fidesctl/api/ctl/routes/datamap.py, src/fidesctl/ctl/core/export.py, src/fidesctl/ctl/core/export_helpers.py
Closes #987
This is not pretty but wanted to get a start out for this quickly as it sounds like a potential blocking item
=> include fides_key in datamap api output

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/ctl/admin-ui/cypress/fixtures/data_subjects.json, clients/ctl/admin-ui/cypress/fixtures/data_uses.json, clients/ctl/admin-ui/src/features/common/form/inputs.tsx, clients/ctl/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx, clients/ctl/admin-ui/src/features/taxonomy/TaxonomyTabContent.tsx, clients/ctl/admin-ui/src/features/taxonomy/forms/TaxonomyFormBase.tsx, clients/ctl/admin-ui/src/features/taxonomy/hooks.tsx
Closes https://github.com/ethyca/fides/issues/998
* https://github.com/ethyca/fides/issues/1001
https://github.com/ethyca/fides/pull/977 was clever about reusing the same component and isolating unique attributes to hooks. This worked well back when the edit form was the same across every taxonomy type. Now that they're no longer the same, we are still able to use the same pattern, but it might make things a little harder to grok, in exchange for cleaner components.
DataCategory and DataQualifier forms still look the same.
=> Update taxonomy forms

src/fidesctl/api/ctl/routes/datamap.py
I noticed that the long description of the fides key column is almost always going
to be truncated in the UI. This is true for other columns, but they all try to be
concise and put most important words first (no "the") which is easier to follow
when hunting for information in a table.
Long-term we'll probably need to introduce a way of embedding help text in this API,
or another API/constants file with the column titles seperate fromt the help text.
Before:
After:
=> fidesctl/datamap: Concise heading of Fides Key columns

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/ctl/admin-ui/src/features/common/AccordionTree.tsx, clients/ctl/admin-ui/src/features/data-qualifier/data-qualifier.slice.ts, clients/ctl/admin-ui/src/features/data-subjects/data-subject.slice.ts, clients/ctl/admin-ui/src/features/data-use/data-use.slice.ts, clients/ctl/admin-ui/src/features/taxonomy/ActionButtons.tsx, clients/ctl/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx, clients/ctl/admin-ui/src/features/taxonomy/TaxonomyTabContent.tsx, clients/ctl/admin-ui/src/features/taxonomy/data-categories.slice.ts, clients/ctl/admin-ui/src/features/taxonomy/hooks.tsx, clients/ctl/admin-ui/src/features/taxonomy/types.ts
Closes https://github.com/ethyca/fides/issues/859
* https://github.com/ethyca/fides/issues/1005
https://user-images.githubusercontent.com/24641006/186188681-8f9ef046-b3d8-4bce-9489-ce2481cb879c.mov
Error state
https://user-images.githubusercontent.com/24641006/186188950-3f03be3d-bc8e-4cf2-b46f-fafaaa8aa2d1.mov
Parent nodes do not render the delete button
=> Delete taxonomy UI

CHANGELOG.md, src/fidesctl/ctl/core/config/cli_settings.py, src/fidesctl/ctl/core/config/logging_settings.py, src/fidesctl/ctl/core/config/user_settings.py
Closes <issue>
This is to fix the failing mypy tests that have started showing up in CI.
=> Fix mypy error

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/ctl/admin-ui/cypress/fixtures/data_uses.json, clients/ctl/admin-ui/src/features/common/constants.tsx, clients/ctl/admin-ui/src/features/common/form/inputs.tsx, clients/ctl/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx, clients/ctl/admin-ui/src/features/taxonomy/TaxonomyTabContent.tsx, clients/ctl/admin-ui/src/features/taxonomy/hooks.tsx
Closes https://github.com/ethyca/fides/issues/1001
https://user-images.githubusercontent.com/24641006/187709355-6bd6307b-e6df-452f-bb17-c26dc69ca8fb.mov
=> Add boolean fields and use them in taxonomy forms

CHANGELOG.md, noxfiles/ci_nox.py, src/fidesctl/ctl/core/push.py
Closes #985
The output of a clean push still feels a little rough, would love some input (or maybe this can be improved later)
To test this, I followed the steps below:
1. `nox -s dev`
2. `fides db reset -y`
3. `fides push demo_resources/`
4. `fides push demo_resources/ --diff` (should result in nothing being reported)
5. Update the name of the organization defined in `demo_resources/demo_organization.yml`
6. `fides push demo_resources/ --diff` (should result in the diff for the organization)
```
root@24fc18ebfce7:/fides# fides push --diff
Loading resource manifests from: .fides/
Taxonomy successfully created.
----------
Processing dataset resource(s)...
Updated resource with fides_key: public
{}
PUSHED 1 dataset resource(s).
----------
Processing system …
```
=> remove exclude_unset=True to return clean diff

requirements.txt
Should be able to revert after fideslang figures out why the latest pydantic causes failures
See https://github.com/ethyca/fideslang/pull/79
=> Set pydantic < 1.10.0 to fix CI issues with fideslang functions

noxfiles/ci_nox.py
Closes <issue>
* Nox session for building the fidesctl package within docker.
* `nox -s 'python_build(wheel)'`
Finding myself testing the building of fctl so that I can test installing it into fctl+. Here's how it's done.
This seemed to fit in the "ci" file, but I'm unsure if we'd also want to use this in our github workflow. Right now it looks like we're building directly in the GH machine, which is a different environment from our dockerfile's slim-bullseye.
=> noxfiles: Session for building fidesctl python package

CHANGELOG.md, src/fidesctl/api/ctl/ui.py, src/fidesctl/api/main.py, tests/ctl/api/test_ui.py
Closes #942 
- Adapt generate_route_file_map from Ops and unit test it
- Serve static files using route maps
* Should just work with regular export. Maybe throw something into admin-ui that makes it clear you're serving what was exported
* I have a branch with a nox command for building the package in docker: https://github.com/ethyca/fides/compare/ssangervasi/nox-python-build
* And a branch with a make command that installs local wheel into fidesctl-plus: https://github.com/ethyca/fidesctl-plus/compare/ssangervasi/local-python-build
* So, build _this_ branch's wheel using that nox command (or equivalent), then build Plus using that make command.
* http://localhost:8080/taxonomy
* http://localhost:8080/dataset/demo_users_dataset
* http://localhost:8080/datamap (in Plus)
* Documentation …
=> [942] fctl/api: Serve static files using route maps

CHANGELOG.md, src/fidesctl/cli/utils.py, src/fidesctl/ctl/core/evaluate.py, tests/ctl/core/test_evaluate.py
Closes #1048 
Quick fix for a small bug caused by a refactor of the `pretty_echo` function
=> Fix truncated evaluation error messages

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/ctl/admin-ui/src/features/taxonomy/ActionButtons.tsx, clients/ctl/admin-ui/src/features/taxonomy/TaxonomyTabContent.tsx, clients/ctl/admin-ui/src/pages/taxonomy/index.tsx, dev-requirements.txt, pyproject.toml, src/fidesctl/api/ctl/database/crud.py, tests/ctl/conftest.py, tests/ctl/core/test_api_helpers.py, tests/ctl/database/test_crud.py, tests/ctl/types.py
Closes https://github.com/ethyca/fides/issues/1005
New warning message
https://user-images.githubusercontent.com/24641006/188721798-36ae05ce-d64e-40b0-8d3f-155bb4704fea.mov
=> Cascade delete taxonomy children

clients/ctl/admin-ui/cypress/e2e/nav-bar.cy.ts, clients/ctl/admin-ui/src/features/common/nav/NavBar.tsx
Closes #1059 
Quick update to make the UI look less unfinished. Since we're releasing at any time we need to make sure at any time our UI is looking complete and usable.
*Old*
*New* (With systems though too)
=> Remove disabled Nav Buttons

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/datasets.cy.ts, clients/ctl/admin-ui/cypress/e2e/systems.cy.ts, clients/ctl/admin-ui/cypress/fixtures/system.json, clients/ctl/admin-ui/src/features/YamlForm.tsx, clients/ctl/admin-ui/src/features/common/types.tsx, clients/ctl/admin-ui/src/features/config-wizard/DescribeSystemsForm.tsx, clients/ctl/admin-ui/src/features/dataset/DatasetYamlForm.tsx, clients/ctl/admin-ui/src/features/system/SystemCard.tsx, clients/ctl/admin-ui/src/features/system/SystemYamlForm.tsx, clients/ctl/admin-ui/src/features/system/SystemsManagement.tsx, clients/ctl/admin-ui/src/features/system/system.slice.ts, clients/ctl/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx, clients/ctl/admin-ui/src/features/taxonomy/hooks.tsx, clients/ctl/admin-ui/src/features/taxonomy/types.ts, clients/ctl/admin-ui/src/pages/system/index.tsx, clients/ctl/admin-ui/src/pages/system/new/index.tsx
Closes https://github.com/ethyca/fides/issues/1032
https://user-images.githubusercontent.com/24641006/189423716-029d78df-bd5d-42d2-9a06-d6d593a62c08.mov
Because we're using the same yaml validators/forms as `DatasetYamlForm.tsx` did, the error rendering is exactly the same.
=> Form to add a system via yaml

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/datasets-classify.cy.ts, clients/ctl/admin-ui/src/features/common/form/inputs.tsx, clients/ctl/admin-ui/src/features/dataset/DatabaseConnectForm.tsx
Closes #1055
[Epic overview](https://github.com/ethyca/fides/issues/1041)
* New CustomSwitch component to wrap Chakra's Switch.
* New `classify` field on the generate form which is available in Plus only.
In fidesctl:
With the fidectl-plus backend
For the tooltip I adapted some language from [our docs](https://ethyca.github.io/fidescls/0.9.2/)
=> ui/dataset: "Classify" toggle for fidesctl-plus

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/datasets-classify.cy.ts, clients/ctl/admin-ui/cypress/fixtures/classification/list.json, clients/ctl/admin-ui/src/features/common/features.slice.ts, clients/ctl/admin-ui/src/features/common/plus.slice.ts, clients/ctl/admin-ui/src/features/dataset/DatasetTable.tsx, clients/ctl/admin-ui/src/features/dataset/constants.ts, clients/ctl/admin-ui/src/pages/dataset/index.tsx
Closes #1073
- New column in datasets table
- For now it's shown whether or not Plus is available
- Fallback is "unknown"
- The table uses the query hook instead of passing the prop through index page.
- Must be done through cypress to mock the endpoints
- In non-plus, the status should just be "unknown"
=> [1073] ui/dataset: Show status badge for datasets using classification results

src/fides/api/main.py, src/fides/cli/__init__.py, src/fides/ctl/core/config/__init__.py
Closes #1065 
This PR makes the standard CLI logging less verbose, removes duplicate logging messages, etc.
```
fides> fides
Startup configuration: reloading = False, dev_mode = False
Startup configuration: pii logging = False
Loading config from: .fides/fides.toml
Loading config from: .fides/fides.toml
Usage: fides [OPTIONS] COMMAND [ARGS]...
The parent group for the Fides CLI.
```
```
fides> fides    
Loading config from: .fides/fides.toml
Usage: fides [OPTIONS] COMMAND [ARGS]...
The parent group for the Fides CLI.
```
=> Make CLI startup logging cleaner

.github/workflows/code_checks.yml, Dockerfile, optional-requirements.txt, requirements.txt, setup.py, src/fides/api/ops/util/collection_util.py
Closes #1017 
We want to expand our official support for both newer and older versions of Python by formally testing multiple versions in CI.
Python `3.8`, `3.9` and `3.10` will be our officially supported versions, and we can add 3.11 so that list when it comes out and we can test it. `3.7` is unable to be included due to some important requirements being incompatible.
__Note__:
Working as intended! Found some bugs on different versions that I fixed here as well
=> Test multiple Python versions

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/systems.cy.ts, clients/ctl/admin-ui/src/features/common/helpers.ts, clients/ctl/admin-ui/src/features/system/SystemCard.tsx, clients/ctl/admin-ui/src/features/system/system.slice.ts, clients/ctl/admin-ui/src/types/errors/api.ts, clients/ctl/admin-ui/src/types/errors/models.ts
Closes https://github.com/ethyca/fides/issues/1036
https://user-images.githubusercontent.com/24641006/190722639-42eb5ddd-616a-4487-b73f-43fdd9262f85.mov
=> UI to delete a system

CHANGELOG.md, clients/ctl/admin-ui/cypress/e2e/systems.cy.ts, clients/ctl/admin-ui/src/features/config-wizard/PrivacyDeclarationForm.tsx
I thought the behavior of the privacy declaration form was odd, so tried to make it more intuitive and like other forms I've used. Consider this form:
Old behavior:
* Fill out the form
* Clicking 'Add another declaration' adds the filled out declaration as an accordion to the top area (where privacy declarations 'one' and 'asdf' are)
* However, if instead of clicking 'Add another declaration', you click "Confirm and Continue", this _also_ adds the declaration in the next screen. In other words, it takes whatever is filled out in the form and considers it done and should be added
* This makes things a little weird when, if you only have one declaration, you click 'Add another declaration', you're kind of stuck, since you can't "Confirm and Continue" with a blank declaration since it's …
=> Separate 'next' and 'add' logic in PrivacyDeclarationForm

clients/ctl/admin-ui/cypress/e2e/datasets.cy.ts, clients/ctl/admin-ui/src/features/dataset/DatabaseConnectForm.tsx, clients/ctl/admin-ui/src/features/dataset/DatasetCollectionView.tsx, clients/ctl/admin-ui/src/features/dataset/DatasetFieldsTable.tsx, clients/ctl/admin-ui/src/features/dataset/DatasetTable.tsx, clients/ctl/admin-ui/src/features/dataset/DatasetYamlForm.tsx, clients/ctl/admin-ui/src/features/dataset/EditCollectionDrawer.tsx, clients/ctl/admin-ui/src/features/dataset/EditDatasetDrawer.tsx, clients/ctl/admin-ui/src/features/dataset/EditFieldDrawer.tsx, clients/ctl/admin-ui/src/features/dataset/dataset.slice.ts, clients/ctl/admin-ui/src/features/dataset/types.ts, clients/ctl/admin-ui/src/pages/dataset/index.tsx
- Track dataset by fides key instead of object copy and nulls
- Previously we've stored a copy of the dataset returned by the get-by-key query,
but only every use its key property. With this change we only store the key and
use the object from the query directly.
- As part of this, I also converted a lot of `null` to `undefined`. There different
opinions on this, but undefined is generally more useful in a TS codebase because:
1. It plays nicely with optional function arguments.
2. It can be represented by a single question mark in interfaces. (See the State
changes in this commit.)
3. It doesn't have null's `typeof null === "object"` confusion.
- Single state for edit drawer
- This resolves some naming inconsistencies and also makes it explicit that only one drawer can ever be open.
- …
=> ui/datasets: Refactor selectors

.github/workflows/frontend_pr_checks.yml, CHANGELOG.md, clients/ctl/admin-ui/cypress.config.ts, clients/ctl/admin-ui/cypress/components/DataCategoryInput.cy.tsx, clients/ctl/admin-ui/cypress/support/component-index.html, clients/ctl/admin-ui/cypress/support/component.ts, clients/ctl/admin-ui/cypress/tsconfig.json, clients/ctl/admin-ui/jest.config.js, clients/ctl/admin-ui/tsconfig.json
Cypress introduced [component testing](https://docs.cypress.io/guides/component-testing/writing-your-first-component-test) a few versions ago. While thinking about the classify features which don't have endpoints to test with yet, I thought it would be useful to explore component testing. They're easier to build out in isolation, and are much faster than e2e tests
Component testing is kind of like a mix of storybook and jest tests: like storybook, it renders your component in a browser, but like jest, you can actually test things (although you can use cypress commands, which we already know and love). It looks like storybook now also has [interaction testing](https://storybook.js.org/docs/react/writing-tests/interaction-testing) which might be the same thing except for within storybook. …
=> Set up cypress component testing

CHANGELOG.md, src/fidesctl/ctl/core/export.py, tests/ctl/core/test_export.py
Closes #1123 
Fixed a bug where the datmap dataframe join was dropping rows
=> Fix bug causing missing datamap rows

CHANGELOG.md
Closes n/a
n/a
Unable to merge `tags/1.8.6` to `main` directly so opening this PR to keep the changelog aligned. Both changes were already merged to `main` prior to the patch release
=> Update CHANGELOG.md for 1.8.6

clients/ctl/admin-ui/cypress/e2e/datasets.cy.ts
This test was failing in electron. It became more apparent on the branch off of unified-fides, for some reason. But I can reproduce reliably when making Cypress run via electron instead of chrome locally. 
It might be vaguely related to this? https://github.com/cypress-io/cypress/issues/8055
I figured the test doesn't really care about the order, just that both requests happen, so I made it collect both requests then sort and then compare to what we expect.
=> Do not rely on order for checking intercept results

.github/workflows/backend_checks.yml, noxfiles/ci_nox.py, noxfiles/dev_nox.py
=> Make nox test name sessions more logical

CHANGELOG.md, clients/ctl/admin-ui/__tests__/features/dataset-helpers.test.tsx, clients/ctl/admin-ui/cypress/e2e/datasets-classify.cy.ts, clients/ctl/admin-ui/cypress/e2e/datasets.cy.ts, clients/ctl/admin-ui/cypress/fixtures/classify/create.json, clients/ctl/admin-ui/cypress/fixtures/classify/list.json, clients/ctl/admin-ui/cypress/fixtures/classify/update.json, clients/ctl/admin-ui/cypress/support/stubs.ts, clients/ctl/admin-ui/package-lock.json, clients/ctl/admin-ui/package.json, clients/ctl/admin-ui/src/features/common/plus.slice.ts, clients/ctl/admin-ui/src/features/dataset/ApproveClassification.tsx, clients/ctl/admin-ui/src/features/dataset/DatabaseConnectForm.tsx, clients/ctl/admin-ui/src/features/dataset/DatasetCollectionView.tsx, clients/ctl/admin-ui/src/features/dataset/DatasetHeading.tsx, clients/ctl/admin-ui/src/features/dataset/DatasetTable.tsx, clients/ctl/admin-ui/src/features/dataset/helpers.ts, clients/ctl/admin-ui/src/mocks/data.ts, clients/ctl/admin-ui/src/pages/dataset/[id].tsx
Closes #1076 
- "Approve classification" button for datasets that need review
- This makes two API calls: the normal dataset update call and then a new endpoint for tracking this status.
- There is a unit-tested function for creating the dataset update body. This uses immer as an explicit dependency,
but it was already pulled in by RTK.
- Move classify status field to be per-dataset
- Discussion: https://github.com/ethyca/fidesctl-plus/pull/106#discussion_r980343600
- This required some selector restructuring. It's kind of nice we usually only need the
ClassifyDataset instead of the instance itself.
- https://github.com/ethyca/fides/issues/1120
Before click:
While loading:
Success:
=> [1076] ui/plus: Approve dataset classification button

clients/admin-ui/package.json, docker-compose.yml
Lots of people were getting a problem when spinning up `nox -s dev -- ui` where `node_modules` might be halfway filled out, so the `test -d node_modules` would succeed, but it wouldn't actually work since not everything was installed properly. This might have happened from the docker-compose timing out while bringing the services up (a few of us had to up the `retries` count to let the healthcheck be happy).
Instead of making `test -d node_modules` more sophisticated, we can just tell docker-compose not to override `node_modules` (since the docker container [already installs everything](https://github.com/ethyca/fides/blob/aking-make-docker-ui-better/Dockerfile/#L11-L14). it's just this will happen when the user doesn't have node modules on their local machine) …
=> Make local docker UI better

tests/ops/conftest.py
Closes #1152 
These unit tests should now be passing:
FAILED tests/ops/service/privacy_request/request_runner_service_test.py::TestPrivacyRequestsManualWebhooks::test_manual_input_not_required_for_erasure_only_policies
FAILED tests/ops/service/privacy_request/request_runner_service_test.py::TestPrivacyRequestsManualWebhooks::test_pass_on_manually_added_input
FAILED tests/ops/service/privacy_request/request_runner_service_test.py::TestPrivacyRequestsManualWebhooks::test_pass_on_partial_manually_added_input
FAILED tests/ops/service/privacy_request/request_runner_service_test.py::TestPrivacyRequestsManualWebhooks::test_pass_on_empty_confirmed_input
Fixes #1152 
We also could mock the email send portion of these particular tests, but I also think these fixtures are a …
=> [Unified Fides] Restore Autouse Email Fixtures to Disable Email Send in Testing [#1152]

CHANGELOG.md, clients/ctl/admin-ui/__tests__/checkbox-tree.test.tsx, clients/ctl/admin-ui/src/features/common/CheckboxTree.tsx
While working on taxonomy dropdowns, I found a small 🐛 where checking `user.biometric` would also check `user.biometric_health` even though they are siblings to each other. This was because of some scrappy `startsWith` comparisons we were doing. This PR firms up that comparison so it is a little more sophisticated. 
Before:
https://user-images.githubusercontent.com/24641006/192631885-fe800c06-2cc0-4311-89bb-d803ade0b0c3.mov
After:
https://user-images.githubusercontent.com/24641006/192631683-c4dc2271-e995-4986-a2ad-dcdde2b28d2e.mov
=> Restrict startsWith comparisons in CheckboxTree more

src/fides/api/ops/service/email/email_crud_service.py
=> [Unified Fides] Wrong Config Resource Passed into Email Create/Update [#1139]

clients/admin-ui/package.json
The `copy-export` command is helpful when you want to test that the static build assets are correctly served by the [catchall route](https://github.com/ethyca/fides/blob/a2cc9b0d4402531b3e58ef4bc9c1abeff36f9a68/src/fides/api/main.py#L283). Otherwise you have to [rebuild the prod image](https://github.com/ethyca/fides/blob/b2cacbfe58e0a4f6c1be8984d9afd432b9233c44/Dockerfile#L99-L100) and run it.
=> ui/package: restore copy-export command

CHANGELOG.md, MANIFEST.in, pyproject.toml, setup.py
=> Make `optional-requirements.txt` a source of version truth

src/fides/api/ops/service/connectors/base_connector.py
Closes #1143 
Logging query parameters for the BaseConnector in fidesops is tied to whether "test mode" is True.  It is currently "True" by default in Fides, where it was "False" by default in Fidesops.  This is causing too much PII to be logged when running a privacy request.
Instead, tying this field to look at "dev mode" instead of "test mode".  We'd like to separately get rid of "test mode" altogether.
=> [Unified Fides] Logging too much PII because Test Mode is True by Default

src/fides/api/main.py, src/fides/api/ops/api/deps.py
Re-add SaaS template update script on startup that had been removed accidentally in merging over to unified Fides.
Closes #1195 
* execute update script in startup hook
* include a new session getter dependency function to allow a session to be retrieved directly, as is needed for the update script execution
* create a sample connector instance from template (i chose hubspot as an example)
* update the template config or dataset for your given connector, and increment the version number in the saas config template
* restart the fides app (don't clear your db), allow it to fully boot-up
* make an API call (e.g. `{{host}}/connection/[instance_key]/dataset` or `{{host}}/connection/[instance_key]/saas_config`) to retrieve the config/dataset of your sample connector instance and confirm that …
=> Re-add SaaS template update script to startup hook

.dockerignore, clients/ops/privacy-center/Dockerfile, clients/ops/privacy-center/__tests__/RequestModal.test.tsx, clients/ops/privacy-center/config/__mocks__/config.json, clients/ops/privacy-center/config/config.json, clients/ops/privacy-center/constants/index.ts, docker-compose.yml, docs/fides/docs/ui/privacy_center.md, noxfiles/dev_nox.py, noxfiles/docker_nox.py
Closes #1164 
Closes #1141
Note that I ended up using `git cherry-pick` to grab commits from https://github.com/ethyca/fides/pull/1145, which this PR replaces.
This makes the privacy center a "first-class" service in the build, whereas historically it's only been developed with using `npm` commands in the sub-directory. It's still a bit slow to build and could use additional TLC, but this is a big improvement.
=> Add Privacy Center to the default development build

src/fides/api/ops/api/v1/endpoints/connection_endpoints.py, tests/ops/api/v1/endpoints/test_connection_config_endpoints.py
Closes #1276 
- accept basic `str` inputs as well as `ConnectionType` enum for `connection_type` query param
- perform filter on `ConnectionConfig.saas_config.type` field for values that are not `ConnectionType`s
* automated tests cover new functionality
* or, to test manually, spin up `fides` on this branch, make a new connector of type `sentry` (for exmaple) using the UI, then the following request should give you filtered results, i.e. only the one connector you've created: `/api/v1/connection?connection_type=sentry`
=> 1276 update get connections API to support specifying saas types

.github/workflows/release_event.yml, CHANGELOG.md
Closes #1242
Once the -plus codebases have been merged into the fidesplus repo, most (but not all) of these changes can be reverted, such that only fidesplus is notified.
=> Notify fidesctl-plus and fidesops-plus on new releases

src/fides/api/ops/api/v1/endpoints/connection_type_endpoints.py, src/fides/api/ops/schemas/connection_configuration/connection_config.py, src/fides/api/ops/util/saas_util.py, tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
Closes #1231 
Follow up ticket for front-end work is: https://github.com/ethyca/fides/issues/1413
* Adds `encoded_image` field to the response body schema of `api/v1/connection_types`, and the field includes a base64 encoded image binary for the connector's icon image. 
* The field is currently only populated for SaaS connectors; other connectors have `None` for the field.
* Sample response payload: [sample_response_encoded_icon_base64.json.txt](https://github.com/ethyca/fides/files/9766824/sample_response_encoded_icon_base64.json.txt) (github doesn't seem to allow `.json` uploads...)
=> Include base64 encoded icon image data in connection_type response

noxfiles/dev_nox.py, noxfiles/utils_nox.py
Closes #1428 
These version checks are a better way to let users know if their Docker versions are out of date.
__Warning__: Because I'm not sure when certain features got introduced, I've biased to making these versions _very_ recent. This will most likely force anyone who is not continually updating their Docker to immediately update
=> Add docker version checks to Nox

clients/admin-ui/src/app/store.ts
This was driving me crazy debugging while working on the config wizard. The persist code merged in, but the necessity of excluding these reducers was missed:
https://github.com/ethyca/fidesops/pull/1409#discussion_r984880236
I'm actually a bit surprised ctl stuff has been working okay at all. Maye there are some bug issues I haven't seen yet.
=> ui/store: Do not persist API stores for Ctl code either

data/saas/config/doordash_config.yml, data/saas/dataset/doordash_dataset.yml, data/saas/saas_connector_registry.toml, noxfiles/ci_nox.py, noxfiles/constants_nox.py, pyproject.toml, src/fides/api/ops/service/saas_request/__init__.py, src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_doordash.py, tests/ops/conftest.py, tests/ops/fixtures/postgres_fixtures.py, tests/ops/fixtures/saas/doordash_fixtures.py, tests/ops/fixtures/saas/external_datasets/doordash.sql, tests/ops/fixtures/timescale_fixtures.py, tests/ops/integration_tests/saas/test_doordash_task.py, tests/ops/integration_tests/setup_scripts/postgres_setup.py, tests/ops/integration_tests/setup_scripts/timescale_setup.py, tests/ops/test_helpers/db_utils.py
Adds an example config and dataset to configure a SaaS connection to the Doordash API.
- The `delivery` entities are retrieved by `delivery_id` which are provided to the Doordash connector via the `doordash_delivery_id` external dataset reference.
**Note:** The Doordash API does not support updates or erasures for completed deliveries. Erasures must be configured separately via a maildrop connector.
- Adds SaaS config and Dataset
- Adds tests to verify access requests return the expected number of results and fields
- Updates the `pytest_ops(saas)` to include an external Postgres database to test the external dataset references.
Fixes #1301
=> Doordash (Access)

CHANGELOG.md, clients/privacy-center/__tests__/features/consent/helpers.test.ts, clients/privacy-center/config/config.json, clients/privacy-center/config/types.ts, clients/privacy-center/features/consent/cookie.ts, clients/privacy-center/features/consent/helpers.ts, clients/privacy-center/features/consent/types.ts, clients/privacy-center/jest.config.js, clients/privacy-center/package-lock.json, clients/privacy-center/package.json, clients/privacy-center/pages/consent.tsx, clients/privacy-center/tsconfig.json, clients/privacy-center/types/index.ts
Closes #1220 
- Main change: Set cookie with a configurable mapping cookie keys to consent value.
- Supporting commits:
- TS and Jest config for absolute imports
- Extract "Consent" types and fix spelling
- Extract consent items logic to helper and unit test it
- Initial implementation Data Use Fides Keys as the cookie keys.
- The cookie will only be tied to that domain
- Other pages on that domain (and subdomains) should be able read the cookie as well.
- You can find the cookie under the "Application" tab of the browser tools.
This change assigns a browser cookie whenever the user updates their consent options. This cookie is highly configurable: 
- The cookie name defaults to `fides_consent` but can be configured under `config.json > consent > cookieName`.
- …
=> [1220] privacy-center: Set cookie with mapping of data use to consent

noxfiles/utils_nox.py
Closes #1437
Older versions of docker-compose follow a different versioning format, and therefore were breaking the version check function.
Additionally, version checking was flawed and is now fixed to handle semver comparisons properly.
=> Fix docker compose version check on older versions

.github/CODEOWNERS, CHANGELOG.md
=> Remove superfluous `CODEOWNERS`

CHANGELOG.md, clients/admin-ui/__tests__/index.test.tsx, clients/admin-ui/src/features/common/nav/NavBar.tsx, clients/admin-ui/src/flags.json, clients/admin-ui/src/pages/config-wizard/index.tsx
Closes https://github.com/ethyca/fides/issues/1453
This change allows you to hide/show the config wizard.
=> add configWizardFlag to hide nav bar and send to 404 page

CHANGELOG.md, clients/admin-ui/cypress/e2e/config-wizard.cy.ts, clients/admin-ui/cypress/fixtures/generate/system_to_review.json, clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx, clients/admin-ui/src/features/config-wizard/ScanResultsForm.tsx, clients/admin-ui/src/features/config-wizard/SuccessPage.tsx, clients/admin-ui/src/features/config-wizard/config-wizard.slice.ts, clients/admin-ui/src/features/config-wizard/setup.tsx, clients/admin-ui/src/features/system/DescribeSystemStep.tsx, clients/admin-ui/src/features/system/ManualSystemFlow.tsx, clients/admin-ui/src/features/system/system.slice.ts, clients/admin-ui/src/pages/config-wizard/index.tsx, clients/admin-ui/src/pages/system/new/index.tsx
Closes #904 
- Show & review scanner result systems
- Reset wizard state instead of relying on routing
- Improved checking of system create vs editing
- DescribeSystemStep was already querying the existing systems. This info can be used to check if the system that was passed in (if any) already exists (by fides key). This also disable the fides key field so that the user can't accidentally switch to _creating_ a new system by modifying that field.
- Describe step accepts system object
- ui/system: Reset active system when navigating from the "new" page
1. Go through the wizard flow through the AWS scanner (fidesctl-integration-test credentials)
2. Select multiple systems from the scan results table
3. Fill out the system review forms
4. The success page should show which have been …
=> ui/config-wizard: Show & review scanner result systems

clients/privacy-center/config/config.json, noxfiles/dev_nox.py
In some local testing I found it was possible for initial setup scripts to fail and conflict if the local dev database was already populated or in an unexpected state. This forces the test environment to clear out existing volumes before starting.
While doing this testing, I also noticed that, by default, the privacy center won't work without some optional configuration (identity verification). So I disabled consent in the privacy center defaults to ensure the default image is stable.
=> Improve test environment reliability

docs/fides/docs/development/release_checklist.md, docs/fides/mkdocs.yml
This PR updates the release checklist, so that we have a baseline of quality for every single release, including the initial release of unified-fides
=> Update release checklist

src/fides/ctl/core/parse.py, src/fides/ctl/core/utils.py
Closes #1485 
Closes #1484 
@nicolas-ethyca found a bug in the `parse` logic that fails if no manifest exist. This is not the expected behavior, as `fides pull` was specifically designed to fill an empty repo. We should also be more lenient in regards to running with git available/in a git repo
=> Don't parse an empty dir

docs/fides/docs/saas_connectors/saas_pagination.md, src/fides/api/ops/schemas/saas/strategy_configuration.py, src/fides/api/ops/service/pagination/pagination_strategy_offset.py, tests/ops/service/pagination/test_pagination_strategy_offset.py
=> Making offset limit optional

CHANGELOG.md, clients/admin-ui/cypress/e2e/datasets.cy.ts, clients/admin-ui/src/features/dataset/DatasetCollectionView.tsx, clients/admin-ui/src/features/dataset/dataset.slice.ts
Closes #1436 
* Test that replicates the collection switch.
* Easy fix! 
1. Edit a dataset with multiple collections
2. Select a collection other than first.
3. Edit and save any field.
4. Result: The same collection should be shown, which shows the updated field.
This is a case where multiple action dispatch is more error prone than having a single reducer that understands how the state should be updated.
=> ui/dataset: Only reset collection index on actual dataset update

clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx
Closes [this issue](https://github.com/ethyca/fidesctl-plus/issues/233).
Note: I don't believe the runtime scanner is available yet to add to the scanner list page? Please correct me if I'm wrong @mfbrown 
=> 233/Update AWS scanner page header

tests/ops/integration_tests/setup_scripts/postgres_setup.py, tests/ops/integration_tests/setup_scripts/timescale_setup.py
Closes #1577 
More info here: https://ethyca.slack.com/archives/CBKK8TS74/p1666815665895189?thread_ts=1666814870.893109&cid=CBKK8TS74
Please note: this approach is not DRY, and not ideal for the long term. Local integration tests are effectively blocked until this is solved so it makes sense to ship this first.
=> remove the need for package level imports in db setup scripts

.fides/dataset.yml, CHANGELOG.md, src/fidesctl/api/ctl/migrations/versions/6b9885e68cbb_add_plus_system_scans_table.py, src/fidesctl/api/ctl/sql_models.py, src/fidesctl/ctl/core/utils.py
Closes #1396
Adds the `plus_system_scans` relation to the fides database, and a corresponding `SystemScans` model. Any associated APIs will be added in fidesctl-plus, as a part of ethyca/fidesctl-plus#195.
=> Add a `plus_system_scans` table to the database

src/fides/api/ops/api/v1/endpoints/user_permission_endpoints.py, tests/ops/api/v1/endpoints/test_user_permission_endpoints.py
Required for #1480 
* This change updates the GET USER_PERMISSIONS endpoint to only require the USER_PERMISSION_READ scope when requesting the permissions for _another_ user. If the User Id of the client credentials matches the User Id of the request, the scope check is skipped.
* Cleaned up tests for the endpoint and added case for current-user case
* The test functions were inconsistent about creating the user and permissions object that needed to be queried.
* Some were using a `url` fixture that was an invalid string - it contained `{user_id}` instead of actually passing the id.
Issue #1480 highlights that we never re-validate the auth token saved in localStorage. Requests that require auth return `403` if the token gets invalidated on the backend, but this …
=> api/permissions: Allow user to GET their own permissions

clients/admin-ui/cypress/e2e/datasets.cy.ts, clients/admin-ui/cypress/e2e/nav-bar.cy.ts, clients/admin-ui/cypress/e2e/systems.cy.ts, clients/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/admin-ui/cypress/support/stubs.ts
Cypress tests were failing on main. This seems to be because we were trying to call `/privacy-request`, whose result, if it failed, was not caught. This adds an intercept to cypress tests that call the home page to return empty privacy request data so that the home page can still load ok
=> Fix cypress tests

.fides/fides.toml, src/fides/ctl/core/config/notification_settings.py, src/fides/data/sample_project/fides.toml, src/fides/data/test_env/fides.test_env.toml
In my testing over the last week or two, I've run into a few surprising defaults, and this was one I forgot to pop open a change for earlier! It doesn't make sense for us to enable email notifications by default - this means that, out of the box, privacy requests can't be processed even in testing/demos... because you first need to configure emails!
We haven't noticed this issue before since all our test config files explicitly disable these notifications. An end-user won't know to do that though, so this is just a footgun I'd like to remove from the code before it surprises someone!
=> Disable privacy request email notifications by default

src/fides/api/main.py, src/fides/data/sample_project/fides.toml, src/fides/data/test_env/fides.test_env.toml
Our analytics middleware is too expansive - it runs on all routes, which in turn means it generates events for every GET. This is OK in most cases, but in a production deployment we also serve up all the UI assets from the server, which means every GET for JS files, image files, CSS snippets, etc. are all generating analytics events. These are uninteresting noise in our analytics, but they also bog down the Python event loop, and since we've not enabled much concurrency in our server yet, it leads to noticeable sluggishness in the Admin UI when running a release image.
This is a pretty simple performance improvement: only run analytics on the API routes, ignoring everything else. I also included `/health` in here explicitly, since that is a common "ping" API that …
=> Disable analytics middleware on non-API routes, enable in testing

CHANGELOG.md, src/fides/ctl/core/export.py, tests/ctl/core/test_export.py
Closes #1414
Originally discovered as part of a plus feature where systems are generated without privacy declarations.
=> Show systems without privacy declarations on data map

CHANGELOG.md, src/fides/api/main.py, src/fides/api/ops/api/v1/endpoints/masking_endpoints.py, src/fides/api/ops/schemas/masking/masking_api.py, src/fides/api/ops/schemas/policy.py, src/fides/cli/commands/util.py, src/fides/ctl/core/config/redis_settings.py, tests/ops/api/v1/endpoints/test_masking_endpoints.py
Closes 
Note that specifying multiple masking strategies may feel contrived in core fides, but this work is to support combining multiple `plus` strategies.
**PUT masking/mask**
```json
{
"values": [
"111-111-1111",
"customer-1@example.com"
],
"masking_strategy": [
{
"strategy": "random_string_rewrite",
"configuration": {
"length": 20,
"format_preservation": {
"suffix": "@masked.com"
}
}
},
{
"strategy": "hash",
"configuration": {
"a": [
[
"b"
]
]
}
}
]
}
```
The old git merge strategy across repos isn't working anymore, so it's back to the hard way...
Luckily not much needs to get copy/pasted over, just those two PRs worth of changes. I've confirmed that everything before that was merged in the previously by manually checking the code changes against fides `main`
=> Fidesops -> Unified Fides final merge

data/saas/config/adobe_campaign_config.yml, src/fides/api/ops/service/saas_request/__init__.py, src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_adobe.py, src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_adobe_campaign.py, tests/ops/fixtures/saas/adobe_campaign_fixtures.py
=> 1629 custom auth strategy adobe campaign

CHANGELOG.md, requirements.txt
Closes #1660
1. Buy a Windows machine
1. Using the Windows machine, start fides
1. Observe that errors are no longer thrown when sending analytics events **synchronously**
=> Bump fideslog to v1.2.10

.github/workflows/cli_checks.yml
Closes #1680 
Quick PR to prevent indefinite jobs from wasting CI minutes and covering up errors
=> Add timeouts for CLI checks

CHANGELOG.md, clients/admin-ui/src/app/store.ts
I was wondering why we need to manually open up localStorage when we have redux-persist configured to do that for us now. Removed this and the log in/out still works as expected. So I think this was just a lingering from changeover.
Similar to this block that was left over from the fidesops merge: https://github.com/ethyca/fides/pull/1569/files#diff-3071c1012e5bece4441d5b7643c083188c22fbfe96caea78da1f09fdeeeb1599L59
=> ui/auth: Remove lingering local storage parsing

.github/workflows/backend_checks.yml, .github/workflows/cli_checks.yml, .github/workflows/frontend_checks.yml, .github/workflows/static_code_checks.yml
Closes #1662 
This PR updates code checks to run on pushes to `main` in addition to their runs during PRs. This helps us keep a more clear picture of the stability of `main` as well as more easily tracking down what merges potentially broke which things
=> Run all checks on merges to `main`

CHANGELOG.md, src/fides/api/ops/api/v1/endpoints/user_permission_endpoints.py, src/fides/api/ops/util/oauth_util.py, tests/ops/api/v1/endpoints/test_user_permission_endpoints.py, tests/ops/conftest.py
Closes #1637
- Allow the root user to query their own permissions.
- Test fixtures root user!
The special-casing of `root_user` goes all the way into [fideslib](https://github.com/ethyca/fideslib/blob/4b1fd0c50dcf07a7244152f3bedf12f39ecdfef7/fideslib/models/client.py#L97). This solves our login problem, and my change to `get_current_user` may prove helpful, but this will probably continue to be weird.
https://user-images.githubusercontent.com/2236777/200084386-4413e2a4-d4b5-4220-9286-0a684faaa8b1.mp4
=> [1637] api/permissions: Allow the root user to query their own permissions

CHANGELOG.md, clients/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/admin-ui/src/features/common/form/inputs.tsx, clients/admin-ui/src/features/taxonomy/hooks.tsx
Closes #1504 
* Use `isClearable` during `onChange` in forms.
* Apply this to taxonomy Data Use
* [Video of clearing multiple.](https://user-images.githubusercontent.com/2236777/200447047-c585b93d-42b6-4283-bb28-c1bd0fac81da.mp4)
The single-select clearing functionality already existed, but we hadn't tried it anywhere. The only thing it was missing was assigning the value to a "cleared" value. `react-select` doesn't want to use `null` or `undefined` for this state, which is reasonable since the native HTML way of doing it is to set an empty string (whenever the value would not match one of the option elements). 
This empty-string case then needs to be handled when transforming the form into an object to submit to the server.
I looked for other uses of …
=> ui/taxonomy: CustomSelect isClearable - handle empty string selection

README.md, docs/fides/docs/dsr_quickstart/basic_setup.md, docs/fides/docs/getting-started/sample_project.md
Closes #1727 
* updated the required version of python in the readme and docs to specify any version between 3.8 and 3.10 (so excluding 3.11)
* build the docs and view!
=> update required python version in readme, docs

pyproject.toml, src/fides/api/ops/models/privacy_request.py, src/fides/api/ops/util/identity_verification.py, tests/ops/api/v1/endpoints/test_consent_request_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py
This PR is branched off from https://github.com/ethyca/fides/pull/1734
=> Expire OTP tokens after a configurable threshold for DSRs

CHANGELOG.md, docs/fides/docs/development/postman/Fides.postman_collection.json, src/fides/api/ops/api/v1/endpoints/privacy_request_endpoints.py, src/fides/api/ops/models/messaging.py, src/fides/api/ops/schemas/messaging/messaging.py, src/fides/api/ops/service/_verification.py, src/fides/api/ops/service/connectors/email_connector.py, src/fides/api/ops/service/messaging/message_dispatch_service.py, src/fides/api/ops/service/privacy_request/request_runner_service.py, tests/ops/api/v1/endpoints/test_messaging_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py, tests/ops/integration_tests/test_integration_email.py, tests/ops/service/messaging/message_dispatch_service_test.py, tests/ops/service/privacy_request/request_runner_service_test.py, tests/ops/service/processors/post_processor_strategy/test_post_processor_strategy_filter.py
Closes [1467](https://github.com/ethyca/fides/issues/1467)
```
[notifications]
notification_service_type = "twilio_text"
```
=> 1467 twilio sms identity verification

CHANGELOG.md, demo_resources/demo_system.yml, src/fides/api/ctl/routes/datamap.py, src/fides/ctl/core/export.py
Closes #1669
1. `fides push demo_resources`
1. `curl --location --request GET 'http://0.0.0.0:8080/api/v1/datamap/default_organization' \`
Need to confirm the new values are only required as part of the API and not exporting to a flat file
=> Populate Ingress/Egress on datamap

CHANGELOG.md, src/fides/api/ops/service/saas_request/override_implementations/authentication_strategy_adobe_campaign.py
Closes #1753 
correct treatment of `expires_in` in adobe JWT response as milliseconds value, not seconds.
=> treat  response from adobe jwt appropriately, as milliseconds

CHANGELOG.md, src/fides/api/ops/api/v1/endpoints/privacy_request_endpoints.py, src/fides/api/ops/service/messaging/message_dispatch_service.py
Closes [1468](https://github.com/ethyca/fides/issues/1468)
```
[notifications]
notification_service_type = "twilio_text"
send_request_receipt_notification = true
```
=> 1468 - Implements all subject notifications using SMS

.pre-commit-config.yaml
Closes #1497 
The purpose of these changes is to enable devs to detect hardcoded secrets before accidentally publishing them. It leverages [the pre-commit framework](https://pre-commit.com/) and [Gitleaks](https://github.com/zricethezav/gitleaks).
=> Add pre-commit & pre-push Gitleaks secrets detection hooks

src/fides/__init__.py, src/fides/ctl/core/config/utils.py
Closes #1787 
In the current draft state this PR serves as a starting point to get a conversation going. This solution is harder to maintain for developers but _hopefully_ offers a great user experience by immediately displaying all of the missing required configs vars. The output should look like this when no config is provided.
It works by running before the pydantic code tries to load everything in. It circumvents catching `MissingConfig` exceptions by manually checking for config vars. It also makes it very easy to display helpful error messages.
I'm open to a more automated solution but I want to minimize how much work is done for this increment when fides config is about to receive a big overhaul (#1760). I think this adds a good amount of value while being …
=> Add helper function to debug required config vars

CHANGELOG.md, src/fides/api/ctl/view.py, src/fides/api/main.py
Reverts ethyca/fides#1703
Turns out this code wasn't actually dead, and we use the "view evaluations" page for some demos and testing!
=> Revert "Remove dead "view" code from the backend"

CHANGELOG.md, src/fides/__init__.py, src/fides/api/main.py, src/fides/ctl/core/config/security_settings.py, src/fides/ctl/core/config/utils.py, src/fides/data/sample_project/docker-compose.yml, src/fides/data/sample_project/fides.toml, tests/ops/api/test_ratelimit.py
Closes #1810 
Quick fix to make the CLI usable without the "required" webserver variables
Note that this will only fail only `fides webserver`, our compose setup that runs the app directly will not throw this error
Note that this also doesn't have tests, so let's be diligent in our manual review 🙂 
---
```
test> fides webserver
Loading config from: .fides/fides.toml
Directory './.fides' already exists.
Configuration file already exists: ./.fides/fides.toml
To learn more about configuring fides, see:
https://ethyca.github.io/fides/installation/configuration/
C:\Users\tlapiana\anaconda3\lib\site-packages\snowflake\connector\options.py:96: UserWarning: You have an incompatible version of 'pyarrow' installed (6.0.1), please install a version that adheres to: …
```
=> Only check for required variables when the webserver is run

.fides/db_dataset.yml
Closes #1606 
This PR removes descriptions for the generic fields `id`, `created_at` and `updated_at`, and adds descriptions where otherwise possible. The collections still in need of attention are:
=> [#1606] Adds description fields for datasets where appropriate

CHANGELOG.md, clients/admin-ui/src/features/dataset/EditCollectionDrawer.tsx, clients/admin-ui/src/features/dataset/EditCollectionOrFieldForm.tsx, clients/admin-ui/src/features/dataset/EditDatasetDrawer.tsx, clients/admin-ui/src/features/dataset/EditDatasetForm.tsx, clients/admin-ui/src/features/dataset/EditDrawer.tsx, clients/admin-ui/src/features/dataset/EditFieldDrawer.tsx
This has been bothering me for a while and I've finally leveled up enough to fix it 😅 
The EditDrawers always had weird styling that I was only able to get around by using `vh`. This caused some inconsistency though and made some elements cut off unexpectedly at times. 
In addition, it was annoying that the Cancel/Save buttons were not included in the `EditDrawer` wrapper. This was mostly because I thought the "submit" buttons had to be inside a `<form> `element. It turns out you can just [associate a submit button with a form via ID](https://stackoverflow.com/questions/52577141/how-to-submit-form-from-a-button-outside-that-component-in-react/53573760#53573760) though and it'll figure itself out regardless of hierarchy 🎉 
_Write some things here about the changes …
=> Fix EditDrawer styling and move save/cancel buttons to DrawerFooter

CHANGELOG.md, docs/fides/docs/installation/configuration.md
since the SQL Alchemy Connection String URI no longer works as an override, we can remove it from the docs.
* Typo -- postgres
* Remove documentation about the connection string override
=> docs: fix typo in Postgres, remove connection string

CHANGELOG.md, src/fides/ctl/core/dataset.py, src/fides/ctl/core/utils.py, tests/ctl/core/test_utils.py
Closes [fidesplus-licensing#62](https://github.com/ethyca/fidesplus-licensing/issues/62)
Currently this is geared heavily towards datasets but could be more agnostic to allow for uniqueness in other resources (i.e. Systems) as well
=> Generated dataset fides_keys are unique

CHANGELOG.md, clients/admin-ui/cypress/e2e/config-wizard-plus.cy.ts, clients/admin-ui/cypress/e2e/config-wizard.cy.ts, clients/admin-ui/src/features/config-wizard/OrganizationInfoForm.tsx
Closes https://github.com/ethyca/fides/issues/1826
```
UPDATE ctl_organizations SET name = null, description = null where fides_key='default_organization';
```
https://user-images.githubusercontent.com/24641006/203392719-892cd444-b31f-4893-a32f-b6a5e9ef52ab.mov
=> Bypass the organization form if organization name and description are already filled out

docs/fides/docs/guides/email_communications.md
Closes #1847 
* update email guide in our docs
* `nox -s docs_serve`
* navigate to http://0.0.0.0:8000/fides/guides/email_communications/#add-the-messaging-configuration-secrets
Found while going through steps in an implementation guide (cc @NevilleS)
=> update email communication guide to use PUT for secret update

src/fides/api/ops/tasks/__init__.py
This PR expedites part of our fix for https://github.com/ethyca/fides/issues/1842 to aid @RobertKeyser in some debugging.
=> use `loguru` to stop logs being swallowed in Celery instantiation

CHANGELOG.md, requirements.txt, src/fides/api/ops/common_exceptions.py, src/fides/api/ops/service/privacy_request/request_service.py, tests/ops/conftest.py, tests/ops/service/privacy_request/test_request_service.py
Closes #1749
* Added httpx as a dependency in order to preform async requests.
* Added a `poll_server_for_completion` function to poll for completion.
=> Add function to poll privacy_request for completion

clients/admin-ui/src/features/dataset/ApproveClassification.tsx, clients/admin-ui/src/features/dataset/DatasetCollectionView.tsx
Closes #1277 
* Remove the space-between flex for the dataset controls
* Instead fill the space with the paragraph that can grow, or a [Spacer](https://chakra-ui.com/docs/components/flex#using-the-spacer) when that section isn't needed.
Wide res:
Narrow res still okay:
Without classify section still okay:
=> [1277] Flex dataset controls so that only the classify paragraph grows

CHANGELOG.md, clients/admin-ui/src/features/system/ClassifySystemsTable.tsx
Closes https://github.com/ethyca/fidesplus/issues/342
=> Remove description column from classify systems table

clients/admin-ui/src/features/common/hooks/useInterzoneNav.ts, clients/admin-ui/src/features/config-wizard/ScanResults.tsx, clients/admin-ui/src/features/config-wizard/SuccessPage.tsx, clients/admin-ui/src/pages/classify-systems/index.tsx
Closes https://github.com/ethyca/fides/issues/1854
=> Classification flow redirect

clients/privacy-center/.gitignore, clients/privacy-center/packages/fides-consent/README.md, clients/privacy-center/packages/fides-consent/package.json, clients/privacy-center/packages/fides-consent/rollup.config.js, clients/privacy-center/packages/fides-consent/src/fides-consent.ts, clients/privacy-center/packages/fides-consent/src/index.ts, clients/privacy-center/packages/fides-consent/src/lib/cookie.ts, clients/privacy-center/packages/fides-consent/src/lib/index.ts
Start of #1801 
* Move `src/index.ts` to `src/fides-consent.ts` to make it clearer it becomes `dist/fides-consent.js`
* Move `src/cookie.ts` to `src/lib/cookie.ts`
* Add `src/lib/index.ts` and use it as the root of the module build, so that if we want to add other code that isn't specifically for cookies (like a Shopify helper) we can have multiple files.
* Nothing should change 🙂 
=> pc/consent: Restructure consent src dir to make modle/browser distinction clearer

CHANGELOG.md, clients/admin-ui/src/pages/classify-systems/index.tsx
Closes https://github.com/ethyca/fidesplus/issues/368
Turns out this was pretty easy, thanks to some [built in RTK polling functionality](https://redux-toolkit.js.org/rtk-query/usage/polling) 🎉 
I couldn't think of a good way to cypress test this one since it depends on waiting quite a while for the next poll to happen.
=> Poll for classification updates

CHANGELOG.md, src/fides/data/sample_project/cookie_house/src/components/Landing/index.tsx, src/fides/data/sample_project/cookie_house/src/pages/landing.tsx
Now that we're living in a post-2.0 world, the version number in the heading is a bit misleading 👍
Here's the updated version:
=> Update sample project landing page copy to be version-agnostic

CHANGELOG.md, src/fides/api/ops/api/v1/endpoints/privacy_request_endpoints.py, src/fides/api/ops/service/connectors/fides/fides_client.py, src/fides/api/ops/service/connectors/fides_connector.py, src/fides/api/ops/service/privacy_request/request_runner_service.py, src/fides/api/ops/task/filter_results.py, tests/ops/service/connectors/test_fides_connector.py
Closes #1966 
* Reach out to child's privacy_request_data_transfer endpoint immediately after polling in the FidesConnector's main retrieve_data method
* Make one retrieval per rule in the provided policy, and store each result as an entry in a dict keyed by the rule.key
* Unpack this dict with some special-cased post-processing for Fides connectors at the framework level, depending on the rule whose results we are processing/persisting to storage
* Update tests as needed
* Ran thru privacy request execution with a child, manually (steps in https://github.com/ethyca/fides/pull/1861)
=> Retrieve child results during fides connector execution

.github/workflows/publish_docs.yaml
This is an attempt to fix #1968
* Specify Python 3.10 for the docs build action.
=> Specify python 3.10 for docs build in GitHub actions

.fides/celery.toml, .fides/fides.toml, data/config/celery.override.toml, src/fides/api/ops/tasks/__init__.py, src/fides/ctl/core/config/__init__.py, src/fides/ctl/core/config/execution_settings.py, tests/ops/tasks/test_celery.py
Closes #1591 
Quick change that adds the celery configuration values as part of the `fides.toml` instead of placing them in a separate file
This change does _not_ enable users to configure the celery values via env vars via the fides configuration logic, as I'm assuming Celery will handle that itself. If this assumption is incorrect I can make that change
__NOTE:__ branchception
=> Merge `celery` subsection to `fides.toml`

src/fides/api/ops/api/v1/endpoints/connection_endpoints.py, src/fides/api/ops/service/connectors/fides/fides_client.py
Closes #1999 
* removes the `async` keyword for the methods that define our connection endpoints that actually test a connection
* adds a timeout into the fides client's connection test call, so that unexpected hanging from the "child" fides will be more gracefully handled
* see issue for detailed repro steps. i went through those and confirmed we no longer hold up the web server in the case where the connection test hangs
* i also confirmed that the new 5 second timeout is respected in these cases, and we get a clean error logged on the parent (as well as a clear connection test response that indicates a faiulre)
Note that another option to resolve this issue would be to keep the endpoints as `async` functions and instead ensure that all of our connection tests …
=> 1999 connectors connection test endpoints can clog up the whole server

CHANGELOG.md, src/fides/cli/__init__.py, src/fides/cli/commands/crud.py, src/fides/ctl/core/api_helpers.py, tests/ctl/core/test_api_helpers.py
Closes #1989 
This change standardizes the output of CLI commands to use YAML when displaying `fides` resources, and furthermore are properly formatted to be used for a subsequent `fides push`
=> Change CLI Crud operations to use YAML

CHANGELOG.md, src/fides/api/ops/service/messaging/message_dispatch_service.py, src/fides/api/ops/service/storage/storage_uploader_service.py
Closes <issue>
* Remove unused `PrivacyRequest` import
* Add type ignore to mypy error
Fixes mypy and pylint errors showing up in #2012 that are unrelated to that PR.
=> Fix mypy and pylint errors showing up in CI

CHANGELOG.md, src/fides/api/ops/service/connectors/fides/fides_client.py, src/fides/api/ops/service/connectors/fides_connector.py, tests/ops/service/connectors/fides/test_fides_client.py
Closes #2011 
* return empty dict if we error on the transfer endpoint, so that we just do not add results to the aggregate data result
* put in a simple test case around this scenario
* improve some logging in fides connector and client
See issue
=> 2011 distributed fides better handle children with no access results

.github/CODEOWNERS, CHANGELOG.md, README.md
Updates the readme to link to the new docs site, and removes docsauthors as a codeowner.
=> update readme to use new docs

CHANGELOG.md, noxfile.py
Closes #1618
Using the standard `nox` command to list out all available sessions is nice and all, but it only shows the first line and isn't practical for showing in-depth information. Many session should contain a lot of usage information due to the complexity of the command given and this new session will allow us to do just that.
No posargs provided
```
fides> nox -s usage 
Docker version 20.10.21, build baeda1f
nox > Running session usage
nox > Re-using existing virtual environment at .nox\usage.
nox > Session usage aborted: Please provide a session name.
```
Invalid session name provided
```
fides> nox -s usage -- foo
Docker version 20.10.21, build baeda1f
nox > Running session usage
nox > Re-using existing virtual environment at .nox\usage.
nox > Session …
```
=> Add a "usage" session to nox

src/fides/cli/__init__.py, src/fides/cli/commands/util.py, src/fides/cli/utils.py
Closes #1661
The side-effect of having the `fides.toml` _always_ be created whether it exists or not is a bit redundant and potentially error-prone (see the attached issue for more discussion). As such, the config file should only be created when a user specifically runs the `fides init` command
Due to this change though, we also needed to update how `analytics_opt_out` is handled, given that before we always expected the user to have a file-based configuration file to update. The behaviour is now that we assume analytics is false if there is no config file, but will prompt the user for it when they run `fides init`. This means we defaulting to `opt-out` and are no longer prompting the user every time they use the CLI to update this. I think this is no longer a …
=> Do not always create a `fides.toml` by default

CHANGELOG.md, data/dataset/remote_fides_example_test_dataset.yml, docker-compose.child-env.yml, src/fides/api/ops/api/v1/endpoints/privacy_request_endpoints.py, src/fides/api/ops/service/privacy_request/request_runner_service.py, src/fides/api/ops/tasks/__init__.py
Closes #1710 
* remove `async` keyword from privacy request endpoints, as it is one contributing reason that reprocessed privacy requests are being executed concurrently when running without a worker, which is _not_ a state we expect/handle
* update the order in which a reprocessed privacy request cache entry is cleared, to prevent requests that encounter another error on re-processing from getting into an unrecoverable state
* make a small tweak to celery app instantiation to ensure worker properly picks up privacy requests
The steps in the issue describe how to reproduce the problem while using `fides deploy up`. But we won't have the fix available in that workflow until we merge this PR, since it requires an update `ethyca-fides` package on pypi - so we're in a bit of a catch 22 there. …
=> 1710 dsr bulk reprocess not working with 20 demo

CHANGELOG.md, clients/admin-ui/cypress/e2e/auth.cy.ts, clients/admin-ui/cypress/e2e/datasets-classify.cy.ts, clients/admin-ui/cypress/e2e/datasets.cy.ts, clients/admin-ui/cypress/e2e/nav-bar.cy.ts, clients/admin-ui/cypress/e2e/systems-classify.cy.ts, clients/admin-ui/cypress/e2e/systems.cy.ts, clients/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/admin-ui/cypress/support/e2e.ts, clients/admin-ui/src/features/auth/ProtectedRoute.tsx, clients/admin-ui/src/features/common/CommonSubscriptions.tsx, clients/admin-ui/src/features/common/features.slice.ts, clients/admin-ui/src/features/datastore-connections/datastore-connection.slice.ts, clients/admin-ui/src/features/plus/plus.slice.ts, clients/admin-ui/src/features/system/ClassifySystemsTable.tsx, clients/admin-ui/src/features/system/DescribeSystemStep.tsx, clients/admin-ui/src/features/system/SystemRegisterSuccess.tsx, clients/admin-ui/src/features/system/system.slice.ts, clients/admin-ui/src/pages/_app.tsx
Necessary for https://github.com/ethyca/fides/issues/1909 and https://github.com/ethyca/fides/issues/1864
- New component loaded at _app level: CommonSubscriptions
- `useGetHealthQuery`
-  `useGetAllSystemsQuery` 
-  `useGetAllDatastoreConnectionsQuery` - Requests an un-filtered handful of connections just to see if there are any.
- Replace calls to `useGetAllSystemsQuery` with selection from global cache (where possible)
- `useFeatures` hook  uses global cache
-  `systemsCount`
- `connectionsCount`
This change introduces the CommonSubscriptions component which subscribes to the redux store a few queries for every page. These queries are used to detect which "features" are enabled, such as whether the server is Fidesplus or if the user has populated their system …
=> ui: Common Subscriptions for app-wide data and feature checks

CHANGELOG.md, src/fides/api/ops/task/graph_task.py
Closes #2048 
* default to an empty list `[]` if, in the beginning of erasure request execution, no access result cache entry is found for the given collection
* See issue description steps to reproduce, and ensure that requests no longer error in this scenario, but instead go to `COMPLETE`
* Also can confirm that the `Event Details` for the step associated with the disabled connector show all of its events with `skipped` status
Passing in the empty list is effectively a no-op here, just a way to prevent an error. This is because the list doesn't actually get used, as the erasure request execution will not proceed because the connector is disabled.
=> avoid error if access results key is not found for erasures

CHANGELOG.md, clients/admin-ui/__tests__/features/common/zones/config.test.ts, clients/admin-ui/package-lock.json, clients/admin-ui/package.json, clients/admin-ui/src/features/common/Layout.tsx, clients/admin-ui/src/features/common/features.slice.ts, clients/admin-ui/src/features/common/nav/NavLink.tsx, clients/admin-ui/src/features/common/nav/v2/NavLink.tsx, clients/admin-ui/src/features/common/nav/v2/NavSideBar.tsx, clients/admin-ui/src/features/common/nav/v2/NavTopBar.tsx, clients/admin-ui/src/features/common/nav/v2/hooks.ts, clients/admin-ui/src/features/common/nav/v2/nav-config.test.ts, clients/admin-ui/src/features/common/nav/v2/nav-config.ts, clients/admin-ui/src/features/common/nav/zone-config.ts, clients/admin-ui/src/features/config-wizard/setup.tsx, clients/admin-ui/src/pages/add-systems/index.tsx
Closes #1909 
* Installed latest fidesui components
* Gated Nav 2.0 behind a `features.slice` flag.
* NavTopBar, NavSideBar, and link components that use primary/secondary styling accordingly.
* `nav/v2/nav-config` contains the logic for including/excluding:
- Plus links
- Groups that requires DSR Connections
- Groups that require Systems.
- Unit tests!
1. Only "Home" and "Management" should show in the header
2. Until https://github.com/ethyca/fides/issues/1864 is merged, "Home" is still privacy requests
3. Clicking on Management navigates to the taxonomy page
4. A sidebar shows taxonomy active and has a link to user management
1. If there are systems, "Data map" shows in the top nav.
2. Clicking "Data map" navigates to the systems list
3. If there are DSR connections, "Privacy requests" …
=> ui/nav: Nav 2.0: Top Bar, Side Bar, and configuration for groups

CHANGELOG.md, clients/privacy-center/packages/fides-consent/src/lib/cookie.ts
Closes #2070
This has one major issue, which is that it'll only work for "normal" TLDs like ".com", ".co", etc., but will calculate the root domain incorrectly for sites that use second-level domains like "example.co.uk" or "example.co.jp", etc.
=> Store fides_consent cookie on the root domain of the Privacy Center

src/fides/lib/oauth/api/routes/user_endpoints.py, tests/lib/conftest.py, tests/lib/test_client_model.py, tests/lib/test_fides_user_permissions.py, tests/ops/api/v1/endpoints/test_user_endpoints.py
Closes #2077 
This regression was caused by the removal of the `fideslib` references from our codebase. `fideslib` was designed to have a common override pattern (with safe backstop) for the `verify_oauth_client` API dependency — which is not being overridden correctly now that the code is in the main codebase. This PR switches out the version of that method designed to be overloaded with the current method in use by the rest of the codebase.
=> Fix user creation as root

CHANGELOG.md, src/fides/api/ctl/database/database.py
Closes #2088 
* Better handle decryption errors on server bootup to prevent people from getting too far with a bad encryption key
* run `nox -s dev `
* update your `fides.toml` to change a character in the `app_encryption_key` property
* trigger a restart of your server by trivially changing a source code file, by re-running `nox -s dev`, etc.
* look for the new logging around the decryption problems on startup
See the issue for some ideas around _further_ guardrails/handling of this. I'm a bit unsure about how far we should go, and how important it is. But this change here seems like some trivial low hanging fruit that will hopefully make things a bit smoother if this happens to come up in the wild.
=> specifically handle and report decryption errors on server bootup

.github/pull_request_template.md, CHANGELOG.md, src/fides/cli/commands/core.py, src/fides/ctl/core/pull.py
Closes #1988 
`fides pull` was hardcoded to only export systems, datasets, and policies, but we have users for whom this is not sufficient. Some users have also modified their default taxonomies, stored evaluations, and more. This PR will update `fides pull` to be able to export _all_ `ctl` resources from the database,  not only making it good for keeping local objects in-sync, but also adding the "grey market" use-case of being able to fully "backup" a `ctl` instance as a set of files.
=> Support exporting _all_ resources via `fides pull`

CHANGELOG.md
I updated the CHANGELOG wrong in #2071, since the release branch was already active. Sorry!
=> Fix CHANGELOG for 2.3.1

docs/fides/docs/development/release_checklist.md, src/fides/__init__.py
=> Release 2.4.0

CHANGELOG.md, src/fides/api/ops/util/identity_verification.py, tests/ops/models/test_privacy_request.py
Closes #2104 
* use `redis.identity_verification_code_ttl_seconds` config property when setting the verification code in the cache
* provide some test coverage
look at issue description
=> use verification ttl property when setting in cache

CHANGELOG.md, clients/privacy-center/__tests__/RequestModal.test.tsx, clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx, clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx, clients/privacy-center/config/config.json, clients/privacy-center/types/config.ts, src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py, src/fides/api/ops/service/messaging/message_dispatch_service.py, tests/ops/api/v1/endpoints/test_consent_request_endpoints.py
Closes https://github.com/ethyca/fides/issues/1853
=> 1853 id verification consent sms

CHANGELOG.md, docs/fides/docs/development/postman/Fides.postman_collection.json, docs/fides/docs/getting-started/storage.md, scripts/setup/s3_storage.py, src/fides/api/ops/schemas/storage/storage.py, src/fides/api/ops/tasks/storage.py, tests/ops/api/v1/endpoints/test_storage_endpoints.py, tests/ops/models/test_base.py, tests/ops/models/test_storage.py, tests/ops/service/storage_uploader_service_test.py
Closes https://github.com/ethyca/fides/issues/1458
=> Removes unused object_name field on s3 storage

CHANGELOG.md, clients/admin-ui/src/pages/subject-request/[id].tsx
Closes #[497](https://github.com/ethyca/fidesplus/issues/497)
* Updated the **SubjectRequestDetails** component
1. Click the **View Details** menu option for a given DSR record
2. Click the `Privacy Requests` breadcrumb hyperlink which should navigate the user to http://localhost:3000/privacy-requests
- Updated the `Privacy Requests` breadcrumb hyperlink
=> 497- Nav bug: clicking on Privacy Request breadcrumb takes me to Home instead of /privacy-requests

src/fides/core/deploy.py
=> update docs location

clients/admin-ui/src/features/common/Header.tsx
=> ui/header: Remove extra menu divider when ff off

CHANGELOG.md, src/fides/api/ctl/routes/crud.py, src/fides/api/ops/api/v1/endpoints/dataset_endpoints.py, src/fides/api/ops/schemas/dataset.py, tests/ctl/core/test_api.py
Closes https://github.com/ethyca/fides/issues/2134
👉  Note branch is against `unified-fides-resources`
CTL Datasets could use some increased validation before they are saved to the database.  These are things I'm running into when testing `unified-fides-resources`
1) Upserting crud resources are not getting validated against the relevant pydantic model.  So when we upsert a CTL Dataset, it is very possible it is missing something, and this breaks later when we try to use it once it's linked to a DatasetConfig. 
2) On the ops side, we were validating data categories on the dataset before we saved to the db.  Now that datasets are no longer saved on DatasetConfigs, add this validation before saving a CTL Dataset.
=> Add Increased CTL Dataset Validation [#2115]

pyproject.toml, src/fides/api/ops/graph/data_type.py, src/fides/api/ops/tasks/__init__.py
* Added `pragma: no cover` to `if __name__ == "__main__:"` code
* Excluded migrations from coverage 
In thinking about #2135 I am adding some exclusions from coverage here. The `migrations` are used by alembic and not by fides code directly, the only reason we have them in a directory under coverage is so plus can access them.
We could probably jump through some hoops and find a way to test the ``if __name__ == "__main__:"`` sections, but doing so would be for the sake of coverage and not meaningful.
=> Exclude untestable code from coverage

CHANGELOG.md, src/fides/api/main.py
=> Importing custom request overrides in main.py

CHANGELOG.md, docker-compose.yml
Closes #1434
* Changed `:-` to `-` when defaulting to an empty string.
```console
WARN[0000] The "VAULT_ADDR" variable is not set. Defaulting to a blank string.                                                                                                                                                                                                            
WARN[0000] The "VAULT_TOKEN" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FIDES__CLI__ANALYTICS_ID" variable is not set. Defaulting to a blank string. 
WARN[0000] The "VAULT_NAMESPACE" variable is not set. Defaulting to a blank string. 
WARN[0000] The "FIDES__CLI__ANALYTICS_ID" variable is not set. Defaulting to a blank string. 
```
_Write some things here about the changes and any potential …
=> Remove warning when env vars default to blank strings in docker-compose

CHANGELOG.md, clients/privacy-center/.eslintrc.json, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/packages/fides-consent/README.md, clients/privacy-center/packages/fides-consent/src/fides-consent.ts, clients/privacy-center/packages/fides-consent/src/integrations/gtm.ts, clients/privacy-center/packages/fides-consent/src/integrations/shopify.ts
Closes #2052 
Doc: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2579038241/Shopify+fides-consent.js
* Fides.shopify integration function
* Extract fides-consent integrations into their own files
* [Readme ](https://github.com/ethyca/fides/blob/4fb315df40d9b6cef36786e8c322d458600f8943/clients/privacy-center/packages/fides-consent/README.md#integrations) with more detail on integrations.
* https://github.com/ethyca/fides/issues/2160
This covers the limited consent options Shopify supports, with their async-loaded API feature. It's still up to the organization to decide what data use counts as "tracking".
=> pc/consent: Fides.shopify integration function

clients/admin-ui/cypress/e2e/auth.cy.ts, clients/admin-ui/cypress/e2e/config-wizard-plus.cy.ts, clients/admin-ui/cypress/e2e/config-wizard.cy.ts, clients/admin-ui/cypress/e2e/datasets-classify.cy.ts, clients/admin-ui/cypress/e2e/datasets.cy.ts, clients/admin-ui/cypress/e2e/taxonomy.cy.ts
=> Reenable most cypress tests

CHANGELOG.md, pyproject.toml, requirements.txt, src/fides/api/ops/schemas/messaging/messaging.py, src/fides/api/ops/service/messaging/message_dispatch_service.py, tests/ops/api/v1/endpoints/test_messaging_endpoints.py
Closes https://github.com/ethyca/fides/issues/1975
**Note**-  this ticket does not include support for fides templates through sendgrid.
```
FIDES__EXECUTION__SUBJECT_IDENTITY_VERIFICATION_REQUIRED=true
FIDES__NOTIFICATIONS__NOTIFICATION_SERVICE_TYPE="twilio_email"
FIDES__NOTIFICATIONS__SEND_REQUEST_COMPLETION_NOTIFICATION=true
FIDES__NOTIFICATIONS__SEND_REQUEST_RECEIPT_NOTIFICATION=true
FIDES__NOTIFICATIONS__SEND_REQUEST_REVIEW_NOTIFICATION=true
```
```
{
"key": "twilio_email_key",
"name": "twilio_email",
"service_type": "twilio_email",
"details": {
"twilio_email_from": "your_sender_email_in_sendgrid@email.com"
}
}
```
```
{
"twilio_api_key": "your-api-key"
}
```
=> Adds support for twilio email (sendgrid) dispatch

CHANGELOG.md, clients/admin-ui/cypress/e2e/connectors.cy.ts, clients/admin-ui/cypress/fixtures/datasets.json, clients/admin-ui/src/app/store.ts, clients/admin-ui/src/features/common/api.slice.ts, clients/admin-ui/src/features/dataset/dataset.slice.ts, clients/admin-ui/src/features/datastore-connections/add-connection/DatasetConfiguration.tsx, clients/admin-ui/src/features/datastore-connections/add-connection/forms/YamlEditorForm.tsx, clients/admin-ui/src/features/datastore-connections/datastore-connection.slice.ts
Closes https://github.com/ethyca/fides/issues/2114
Using the dropdown
https://user-images.githubusercontent.com/24641006/211687577-d15544a6-4ed1-4fd8-b27b-91840857f52b.mov
Using the yaml editor
https://user-images.githubusercontent.com/24641006/211687670-72ddcd58-c9b9-4319-b864-659f38f8e692.mov
=> Connector dataset dropdown

.fides/fides.toml, data/saas/dataset/recharge_dataset.yml, scripts/quickstart.py, scripts/setup/dataset.py, tests/ops/fixtures/saas/friendbuy_nextgen_fixtures.py, tests/ops/fixtures/saas/recharge_fixtures.py
Closes N/A
Get tests passing on `unified-fides-resources` branch after update with main.
Also: Remove remaining uses of ops dataset endpoints in fides that we'd like to eventually deprecate (not a blocker for `unified-fides-resources`): deprecation will happen as a follow-up in the future: https://github.com/ethyca/fides/issues/2092.  These endpoints still work, but are riskier because a dataset is upserted in the background, and we don't want people to unintentionally override their datasets.
-  Instead of a patch to /connection/connection_key/dataset do a post to /dataset/upsert and then a patch to /connection/connection_key/datasetconfig in both the test env setup and the quickstart
=> [Unified Fides Resources] Update Test Env Setup and Quickstart

CHANGELOG.md, src/fides/data/sample_project/sample_resources/sample_systems.yml
This modifies the Cookie House YAML declarations to be more accurate and consistent, removes the reference to the missing demo_users_dataset, and makes it easier to quickly experiment with Fides policies!
Goal here is just to have a built-in demo of the CI policies baked into the Cookie House sample project too - we're close, but since the declarations aren't quite internally consistent it doesn't serve as a useful demo of those features yet.
=> Update sample project resources for `fides evaluate` usage in `fides deploy`

CHANGELOG.md, clients/privacy-center/README.md, clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx, clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx, clients/privacy-center/constants/index.ts, clients/privacy-center/types/config.ts
Closes https://github.com/ethyca/fides/issues/2259
=> Make identity_inputs optional

CHANGELOG.md, dev-requirements.txt, requirements.txt
Closes #2272
Found in #2263 and #2226
=> Move `packaging` to requirements.txt to fix `check_install`

CHANGELOG.md, src/fides/data/sample_project/cookie_house/src/components/PurchaseModal/index.tsx
Closes #2138 
This is a subtle one - but technically the `product` prop is only valid for this modal until the purchase is made, so when the modal is fading out the "Error" text would display. Rather than fight with some additional state here, the safest change is to just not render a dynamic title on the modal.
See quick video here: 
https://www.loom.com/share/a050cfa7cce14d42b7f01d1086481ff1
...and updated screenshot:
=> Fix Cookie House purchase modal flashing 'Error' in title

CHANGELOG.md, src/fides/core/config/__init__.py
Closes #2164 
This is a quick PR to make one of the config-related logging messages less scary/confusing.
```
test> fides view config
No config file found.
Using default configuration values.
```
```
test> fides view config
Using default configuration values.
```
=> Remove unclear config warning

docs/fides/mkdocs.yml, docs/fides/overrides/404.html
Closes #2275 
This is a quick PR to have a more helpful 404 message now that some of our marketing content will be pointing to pages that no longer exist.
It should be noted that I couldn't figure out how to only override that one part of the 404 page in a timely manner, so I've gone ahead and copy/pastad the whole built 404 page and directly updated the text as an override. This isn't a perfect solution, but given that these are no longer the primary docs I feel ok with this compromise for now.
=> Add graceful 404 override

clients/admin-ui/cypress/README.md, docs/fides/docs/development/release_checklist.md, scripts/quickstart.py
- To check for the new tables/columns that have been added in the release, look for new migration files in the `src/fides/api/ctl/migrations` directory and inspect their contents
- If found, look at the latest database diagram, and check whether it contains the tables/columns that were added in these migrations
- If the diagram is not up to date, follow the steps in the link above to generate a new database diagram with the up-to-date schema, ensuring that all tables and their relationships can be clearly seen
```
fides status
exit 
```
Next, run the following checks …
=> Release 2.5.0

CHANGELOG.md, clients/admin-ui/src/features/common/DaysLeftTag.tsx, clients/admin-ui/src/features/privacy-requests/RequestDetails.tsx, clients/admin-ui/src/features/privacy-requests/RequestRow.tsx
=> Don't display remaining days for terminal requests

clients/privacy-center/cypress/tsconfig.json, clients/privacy-center/tsconfig.json
I was getting a bunch of red underlines in vs code when opening jest tests. I remember having to do this before for admin-ui, it's a careful tsconfig dance https://stackoverflow.com/questions/58999086/cypress-causing-type-errors-in-jest-assertions
=> Fix tsconfigs so cypress types do not override jest types

CHANGELOG.md, src/fides/api/ctl/ui.py, src/fides/api/main.py, tests/ctl/api/test_ui.py
The catchall path should only serve paths found nested inside the UI directory
Closes https://github.com/ethyca/security-issues/issues/9
=> Add a check on the catchall path

CHANGELOG.md, clients/admin-ui/src/features/dataset/ApproveClassification.tsx, clients/admin-ui/src/features/dataset/helpers.ts, clients/admin-ui/src/flags.json
Closes [fidesplus#539](https://github.com/ethyca/fidesplus/issues/539)
[loom video](https://www.loom.com/share/f17c5ab1c8cb48d78559d881ff1e0b8c) of feature flag in action!
=> Feature flag dataset UX changes

CHANGELOG.md, Dockerfile, requirements.txt
Closes #514
Here is the payload I used to test this change
```json
{
"name": "My Main Postgres DB",
"fides_key": "hello_world",
"system_type": "postgres",
"key": "postgres_db_1",
"connection_type": "postgres",
"access": "write",
"privacy_declarations": [
{
"data_use": "testing123",
"data_subjects": [],
"data_categories": []
}
]
}
```
Update fideslang to 1.3.3. This will make `PrivacyDeclation.name` optional. It allows privacy declarations to only need the use, categories, and subjects which matches the data model described in #514
=> Update fideslang version

CHANGELOG.md, clients/privacy-center/config/config.json, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/packages/fides-consent/README.md, clients/privacy-center/packages/fides-consent/src/fides-consent.ts, clients/privacy-center/packages/fides-consent/src/integrations/gtm.ts, clients/privacy-center/packages/fides-consent/src/integrations/meta.ts, clients/privacy-center/public/fides-consent-demo.html
Closes #2160
Doc: https://ethyca.atlassian.net/wiki/spaces/EN/pages/2583789680/Facebook+fides-consent.js
- Reverse engineered the `fbq` shimming process that FB just wants you to [paste into pages](https://developers.facebook.com/docs/meta-pixel/get-started). Somehow worse than GTM.
- Added some basic global variable tests to the cypress demo page.
It's been tough to integrate with Meta because:
- I'm unable to create a test account/business to see the API track/not-track end-to-end
- `fbq` doesn't have an API for _reading_ what its state is, so you just have to hope a lack of error messages means something happened
- Whack-a-mole documentation
That said, the options I've provided for this function cover the cases that _were_ documented, leaning towards privacy-by-default …
=> pc/consent: Fides.meta integration function

CHANGELOG.md, clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx, clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx, clients/privacy-center/components/modals/validation.ts, clients/privacy-center/cypress/e2e/privacy-request.cy.ts
Closes https://github.com/ethyca/fides/issues/2220
* Extracted Yup conditionals to a helper module.
* Gave the fields validation rules, but are explicitly optional when they should be.
* Cypress test.
- The only invalid input that the phone field accepted seemed to be really long (>15 char) digits.
With the default config, phone is optional but it's been input with too many digits:
=> pc/modals: Validate phone and email even when they're optional

src/fides/api/ctl/routes/admin.py, tests/ctl/api/test_admin.py, tests/ctl/conftest.py
Closes #2319 
I opted to use `dev_mode` here instead of adding a new configuration variable to work against config. bloat, but I'm happy to change if anyone has a compelling reason to.
=> [#2319] Don't allow db resets unless `config.dev_mode` is `True`

src/fides/api/ctl/migrations/versions/392992c7733a_add_user_id_as_a_provided_identity_type.py, src/fides/api/ops/models/privacy_request.py, src/fides/api/ops/schemas/redis_cache.py, tests/ops/api/v1/endpoints/test_consent_request_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py, tests/ops/models/test_consent_request.py
Patches up https://github.com/ethyca/fides/pull/2304 after some more conversation with @pattisdr 
Will also need to update https://github.com/ethyca/fides/pull/2337
=> Rename `user_id` --> `ga_client_id`

data/saas/config/google_analytics_config.yml, tests/ops/fixtures/saas/google_analytics_fixtures.py, tests/ops/integration_tests/saas/test_google_analytics_task.py
Unticketed
❗ Depends on https://github.com/ethyca/fides/pull/2356
Update google analytics user deletion request to delete by client id instead of user id.
=> GA: Delete by Client ID instead of by User Id

clients/privacy-center/__tests__/common/browser-identities.ts, clients/privacy-center/common/browser-identities.ts, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/pages/consent.tsx
Closes https://github.com/ethyca/fidesplus/issues/519
* This is meant to be extended and potentially refactored once there are other services we'd like to integrate with besides GA. For now, it is hard coded to look for GA cookie values, but it could be extended to look through `config.json` for more cookie values/regexes
=> Pass GA cookie from privacy center

CHANGELOG.md, clients/admin-ui/src/features/common/RequestType.tsx, clients/admin-ui/src/features/privacy-requests/RequestDetails.tsx, clients/admin-ui/src/features/privacy-requests/RequestRow.tsx
Closes #2282 
Quick change to display the request type in the privacy requests table
The request details page still looks correct because the margin was moved.
=> Show request type instead of policy name

clients/privacy-center/common/CommonHeaders.ts, clients/privacy-center/features/common/api.slice.ts, clients/privacy-center/pages/index.tsx
The request done by the index page [wasn't](https://github.com/ethyca/fides/pull/2300/files#diff-8a8754ffd864b1b78f7740b3bab4da785a47767ec93102493ff4feef95283544L53) adding common headers, so when I used it as my first example for RTK queries I also left out that part. The most important header is probably the one that allows cross-origin requests, which probably too liberal but is necessary with Fides on a different domain.
=> pc/api: Add common headers to base query

clients/privacy-center/components/FormErrorMessage.tsx, clients/privacy-center/components/modals/VerificationForm.tsx, clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx, clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx
Closes #2281
- pc/modals: Use chakra isRequired instead of string asterisk
- pc/modals: FormErrorMessage that always takes up space
I don't particularly love how much space is reserved, but it solves the problem. I've definitely had this UX challenge before.
Here's the cancel action:
And here's some more switching between validation:
=>  pc/modals: FormErrorMessage that always takes up space

CHANGELOG.md, src/fides/api/ops/service/masking/strategy/masking_strategy_aes_encrypt.py, src/fides/api/ops/service/masking/strategy/masking_strategy_hash.py, src/fides/api/ops/service/masking/strategy/masking_strategy_hmac.py, src/fides/api/ops/service/masking/strategy/masking_strategy_random_string_rewrite.py, tests/ops/service/masking/strategy/test_masking_strategy_aes_encrypt.py, tests/ops/service/masking/strategy/test_masking_strategy_hash.py, tests/ops/service/masking/strategy/test_masking_strategy_hmac.py
Closes: #2391
Several of our masking strategies are set up to expect values to be strings.  There are some early exits if the input value is None, but since most inputs are now a list of values, even a list of one value, so that's not likely to be True.
If an array of values are passed in, if the original index is None, do nothing to that index.  Also try to coerce the original value to a string.
=> Masking Strategies: Handle Null Values and Non-Strings

clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx, clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx, clients/privacy-center/components/phone-input.tsx
Closes #2361 
* Extracted the duplicate PhoneInput code to its own file
* Import and pass the flag icons directly to the JS.
Once you click on a card, the input modal shows up. At that time the chunk that includes the icons loads in:
And then you can see the SVG src is right in the page (no network request for icon):
=> pc/modals: PhoneInput component with bundled flag icons

.dockerignore, CHANGELOG.md, Dockerfile
We've all noticed that our local Docker development is slow, resource-intensive, and requires a *lot* of rebuilding (and often lots of cleaning out Docker files!).
In my own local testing I inspected the *size* of my local dev image and was pretty shocked that it was 2.3 GB! After some tinkering and troubleshooting I realized that all the local build artifacts from both Python (e.g. `*.pyc` files) and NextJS (e.g. `.next/`) were getting copied into the local image, which has at least two painful consequences:
1. Bloats the size of the dev images locally, which increases RAM utilization, eats up Docker disk space, and generally slows down performance
2. Busts the cache of the `COPY . fides/` command in the webserver build, forcing unnecessary rebuilds
The culprit here is …
=> Reduce size of local Docker images by fixing `.dockerignore` patterns

CHANGELOG.md, clients/admin-ui/src/features/privacy-requests/RequestDetails.tsx
Closes #2288 
Simple change to display the policy key on the request details page.
=> Display policy key on request details page

CHANGELOG.md, clients/admin-ui/cypress/e2e/user-management.cy.ts, clients/admin-ui/cypress/fixtures/user-management/permissions.json, clients/admin-ui/cypress/fixtures/user-management/user.json, clients/admin-ui/cypress/fixtures/user-management/users.json, clients/admin-ui/src/constants.ts, clients/admin-ui/src/features/common/form/validation.ts, clients/admin-ui/src/features/user-management/EditUserForm.tsx, clients/admin-ui/src/features/user-management/NewPasswordModal.tsx, clients/admin-ui/src/features/user-management/PasswordManagement.tsx, clients/admin-ui/src/features/user-management/UpdatePasswordModal.tsx, clients/admin-ui/src/features/user-management/UserForm.tsx, clients/admin-ui/src/features/user-management/UserManagementTable.tsx, clients/admin-ui/src/features/user-management/user-management.slice.ts, clients/admin-ui/src/types/api/index.ts, clients/admin-ui/src/types/api/models/UserForcePasswordReset.ts
Closes https://github.com/ethyca/fides/issues/2208
1. `nox -s dev` and `npm run dev` to start up the admin ui
2. Log in as `root_user`
3. Click "Management" > "Users" and create a new user. You should see a new scope "Reset another user's password" which can be assigned
4. Create a new user with this reset another user's password scope, as well as view/create/read/update users, assign/update/read permissions. Give the user a password you'll remember ;) 
5. Create another user with the same perms as above, but without the reset password perm
6. Log out and sign in as the user you made in step 4. You should be able to edit the user made in step 5's password by clicking on the new Reset password button. remember this new password!
https://user-images.githubusercontent.com/24641006/214920218-e …
=> Admin reset password frontend

CHANGELOG.md, clients/privacy-center/components/modals/VerificationForm.tsx, clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx, clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx
Closes #2219
* Use `isSubmitting` on all of these forms to prevent repeat clicks
* Remove the `isLoading` loading state which is redundant and not implemented correctly.
I couldn't actually reproduce the error banner from the ticket - repeat clicks would send multiple requests but they would respond 200. I tried with and without `require_manual_request_approval` enabled  in `fides.test_env.toml`. 
But either way there's no reason to submit multiple. These modals should all have smart submit buttons.
My screen recorder shows my fast clicks as that animated circle:
https://user-images.githubusercontent.com/2236777/214980028-3bc9b69d-f1ec-403a-8683-de30d783f412.mp4
Also added the loading state:
=> pc/modals: Disable submit buttons on when Formik isSubmitting

.github/workflows/backend_checks.yml, CHANGELOG.md, Dockerfile
Closes #2440 
[GitHub Actions Issue](https://github.com/actions/runner-images/issues/6775)
=> Fix CI git permissions

tests/ops/api/v1/endpoints/test_user_endpoints.py
* Refactored the looped inserts to use a list comprehension and directly insert the records rather than going through the endpoint to setup the tests data.
* General cleanup of `test_user_endpoints` tests.
In testing I noticed that `test_get_filtered_users` and `test_get_users` were significantly slower than all the other tests. `test_get_filtered_users` (our slowest test) averages ~ 1 minute and 20 seconds to run, with `test_get_users` not far behind. This change results in a runtime reduction for `test_get_filtered_users` of ~ 83% (to ~14 seconds) and cuts ~2 minutes off the total test suite run time.
=> Improve test performance

data/saas/config/google_analytics_config.yml, src/fides/api/ops/schemas/saas/saas_config.py, src/fides/api/ops/service/connectors/saas_connector.py, src/fides/api/ops/service/connectors/saas_query_config.py, tests/ops/integration_tests/saas/test_google_analytics_task.py, tests/ops/integration_tests/saas/test_mailchimp_transactional_task.py, tests/ops/service/connectors/test_saas_connector.py, tests/ops/service/connectors/test_saas_queryconfig.py
Closes #2375 
Add a new SaasRequest.skip_missing_param_values to indicate whether we should skip an http request when we can't map all the param values in the request body rather than fail.  
For example, we pull the google analytics client id from the browser for the google analytics consent connector but it isn't always guaranteed to exist.  Rather than having that request fail, we should just skip it.
Functionality added for retrieve_data, mask_data, and run_consent_request, although this is unlikely to be needed for read requests.  (It affects when we can't place param values in the body only)
=> Skip Missing Param Values

CHANGELOG.md, clients/admin-ui/src/features/common/ConfirmationModal.tsx, clients/admin-ui/src/features/privacy-requests/ApprovePrivacyRequestModal.tsx, clients/admin-ui/src/features/privacy-requests/RequestRow.tsx
Closes #2289 Closes #2291 
Adds new approval modal and disables the approve/deny buttons in the background while a request is happening.
https://user-images.githubusercontent.com/17103888/215832468-64313a70-2811-44e7-a8b1-1dc645ee0bf8.mov
=> Privacy request approval modal

CHANGELOG.md, noxfiles/docker_nox.py
Closes #2301
`nox -s "push(dev)"` runs on every push to `main` and releases meaning we were just duplicating the `dev` tags!
=> Include `latest` tag on privacy-center and sample-app images

clients/privacy-center/types/config.ts, tests/ops/integration_tests/saas/request_override/test_firebase_auth_task.py
Policy key can be optional in privacy center config.json
=> Make policy_key optional for consent

Dockerfile
Closes #2491
* Removes the `ui-build` directory after the wheel build is completed
=> Remove ui-build after building wheel

CHANGELOG.md, src/fides/api/ops/service/messaging/message_dispatch_service.py, src/fides/api/ops/service/privacy_request/request_runner_service.py, src/fides/api/ops/tasks/__init__.py, src/fides/api/ops/worker/__init__.py, src/fides/cli/commands/util.py, tests/ctl/cli/test_cli.py
Closes #2482 
Closes #2486 
* create a new db `Session` per celery task _invocation_
* ensure a common `Engine` and `sessionmaker` are reused across invocations to keep db connection resources in check
* update worker "main" module to ensure saas request overrides are added to worker runtime
* the important line here is https://github.com/ethyca/fides/pull/2489/files#diff-8ad3421e67c70da2822e09434a416a583e1b18d9dd58e87938820f9a07466542R3 - `from fides.api.ops.service.saas_request.override_implementations import *`
* also needed to split out worker "main" into its own module to avoid circular dependency issues from `tasks/__init__.py` once the above import was added
- for #2482 fix, run _without_ a worker (e.g. `nox -s 'fides_env(dev)'`) and approve multiple privacy requests in quick …
=> 2482 privacy requests approved in quick succession error when not running worker

clients/privacy-center/pages/404.tsx
* Changes 404 page on privacy center to use the configured logo image rather than the default "Acme Logo" one
(I'm assuming that the default logo wasn't left in intentionally; I noticed the alt text was "FidesOps Logo" but assuming that's a holdover and wasn't meant to e.g. brand it with fides)
=> Use logo from config on privacy center's 404 page

src/fides/api/ctl/migrations/versions/216cdc7944f1_add_datasetconfig_ctl_datasets_fk.py
Closes [#2509](https://github.com/ethyca/fides/issues/2509)
=> Migration Fix: Dataset.meta key not guaranteed to exist

CHANGELOG.md, clients/admin-ui/cypress/e2e/datasets-classify.cy.ts, clients/admin-ui/cypress/e2e/privacy-requests.cy.ts, clients/admin-ui/cypress/fixtures/privacy-requests/approve.json, clients/admin-ui/cypress/fixtures/privacy-requests/deny.json, clients/admin-ui/cypress/fixtures/privacy-requests/list.json, clients/admin-ui/cypress/support/commands.ts, clients/admin-ui/cypress/support/stubs.ts, clients/admin-ui/src/features/common/ConfirmationModal.tsx, clients/admin-ui/src/features/common/RequestStatusBadge.tsx, clients/admin-ui/src/features/privacy-requests/ApprovePrivacyRequestModal.tsx, clients/admin-ui/src/features/privacy-requests/DenyPrivacyRequestModal.tsx, clients/admin-ui/src/features/privacy-requests/PrivacyRequest.tsx, clients/admin-ui/src/features/privacy-requests/RequestDetails.tsx, clients/admin-ui/src/features/privacy-requests/RequestRow.tsx, clients/admin-ui/src/features/privacy-requests/RequestTable.tsx, clients/admin-ui/src/features/privacy-requests/buttons/ApproveButton.tsx, clients/admin-ui/src/features/privacy-requests/buttons/DenyButton.tsx, clients/admin-ui/src/features/privacy-requests/buttons/StyledButton.tsx, clients/admin-ui/src/features/privacy-requests/hooks/useMutations.ts
Closes #2290
- Request details Approve & Deny button group
- ApproveButton component
- DenyButton component
- Tests for approve & deny buttons
- General improvements:
- StyledButton for shared button styles
- Use "on" for props and "handle" for handler functions
- Fix `returnFocusOnClose`
- Initial tests for requests table and details pages
- getByTestIdPrefix Cypress command
* Approve a request
* Deny a request with reason modal
* Should be verified as well because the components were refactored
* Approve a request
* Deny a request with reason modal
_Updated video_ after resolving https://github.com/ethyca/fides/pull/2443 merge conflicts:
<video src="https://user-images.githubusercontent.com/2236777/216207332-394757b4-500d-4f8a-b0d7-5512edbb0a94.mp4" />
With the buttons …
=> [2290] Request details Approve & Deny button group

CHANGELOG.md, clients/admin-ui/src/features/privacy-requests/types.ts
(screenshot showing this in action using `fides_env(test)` locally)
The frontend type for `ActionType` has lagged behind the valid values from the Python model - this updates the Admin UI to support the "consent" and "update" types.
See the Python enum that defines these: https://github.com/ethyca/fides/blob/main/src/fides/api/ops/models/policy.py#L40
=> Update Admin UI to show all action types (access, erasure, consent, update)

src/fides/api/ctl/migrations/versions/216cdc7944f1_add_datasetconfig_ctl_datasets_fk.py
Closes #2509
n/a
The fix in https://github.com/ethyca/fides/pull/2510 isn't quite right - it's also possible for `dataset.get("meta", {})` to return `None` if someone defines a Dataset with a `meta` key but keeps it `null`. This can be hard to do locally but happens in practice.
=> Handle case where legacy dataset has meta: null

.github/workflows/frontend_checks.yml, CHANGELOG.md, clients/privacy-center/README.md, clients/privacy-center/config/config.json, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/features/consent/helpers.ts, clients/privacy-center/jest.config.js, clients/privacy-center/packages/fides-consent/README.md, clients/privacy-center/packages/fides-consent/rollup.config.js, clients/privacy-center/packages/fides-consent/src/fides-consent.ts, clients/privacy-center/packages/fides-consent/src/lib/consent-config.ts, clients/privacy-center/packages/fides-consent/src/lib/consent-context.ts, clients/privacy-center/packages/fides-consent/src/lib/consent-value.ts, clients/privacy-center/packages/fides-consent/src/lib/cookie.ts, clients/privacy-center/packages/fides-consent/src/lib/index.ts, clients/privacy-center/public/fides-consent-demo.html, clients/privacy-center/types/config.ts
Closes #2227 
This might cover #2228 but I'll need to run through the AC more before closing it.
- pc/fides-consent: ConsentValue with ConsentContext to support GPC
- pc/consent: Resolve ConsentValue with ConsentContext.
- pc/config: Default data_sales consent to false for GPC
I'm going to comment on some relevant sections of the refactor.
=> pc/fides-consent: ConsentValue with ConsentContext to support GPC

clients/privacy-center/components/ConsentItemCard.tsx, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/features/consent/consent.slice.ts, clients/privacy-center/pages/consent.tsx, clients/privacy-center/types/api/index.ts, clients/privacy-center/types/api/models/Consent.ts, clients/privacy-center/types/api/models/ConsentPreferences.ts, clients/privacy-center/types/api/models/ConsentPreferencesWithVerificationCode.ts, clients/privacy-center/types/api/models/ConsentWithExecutableStatus.ts, clients/privacy-center/types/api/models/Identity.ts
Spun out while working on #2230
pc/types: API models for consent preferences
pc/consent: Use RTK queries for consent verification and preferences
pc/consent: Draft consent changes with consistent state management
* https://github.com/ethyca/fides/issues/2299
For #2230 I need to toggle more UI elements based on whether a data use has been opted in/out (and the window's GPC flag). Testing this with `fetch` async functions is painful, so I'm continuing the spread of RTK into the PC. I split this into its own PR to keep things tidy.
=> pc/consent: Use RTK queries for consent verification and preferences

clients/privacy-center/package-lock.json, clients/privacy-center/package.json, clients/privacy-center/types/api/models/ConsentPreferences.ts, clients/privacy-center/types/api/models/ConsentPreferencesWithVerificationCode.ts
Looks like in https://github.com/ethyca/fides/pull/2341 the API models didn't git hit by prettier. `lint-staged` is great for covering all modified files, so I've added that here as well.
And yeah, these model files could just be prettier-ignored, but it looks like we're formatting them in the admin-ui too.
=> pc/format: Configure lint-staged and run prettier on api models

CHANGELOG.md, src/fides/api/ops/api/deps.py, src/fides/api/ops/tasks/__init__.py, src/fides/core/config/database_settings.py, src/fides/core/config/utils.py, src/fides/lib/db/session.py, tests/ops/api/test_deps.py, tests/ops/tasks/test_celery.py
Closes #2507 
Doc updates are in https://github.com/ethyca/fidesdocs/pull/52
* provide `database` config properties to allow user configurability of `pool_size` and `max_overflow` tunings for the app db engines used by fides
* a separate pair of settings for both types of engines that our application creates: the engine used generally by the fides API (`database.api_engine_pool_size` and `database.api_engine_max_overflow`), and the engine used by specific celery tasks/processes (`database.task_engine_pool_size` and `database.task_engine_max_overflow`)
* set respective config values in your `fides.toml` or via environment variable and confirm the db engine that's created is using the set values
* the test script mentioned here https://github.com/ethyca/fides/pull/2489#issuecomment-141487286 …
=> provide config overrides for db engine pool params

CHANGELOG.md, src/fides/core/config/database_settings.py, src/fides/lib/db/session.py
Closes Issue: N/A
Quick follow-up to https://github.com/ethyca/fides/pull/2511. Bump pool_size and max_overflow to 50 each as defaults to start.
=> Increase Default Pool Size and Max Overflow

src/fides/api/ops/service/connectors/saas_connector.py
Issue: None
Similar to https://github.com/ethyca/fides/pull/2157, if there's an issue with a masking override, the error is too vague for troubleshooting.
=> Improve Readability for Custom Masking Override Exceptions 

CHANGELOG.md, tests/ops/integration_tests/test_mongo_task.py
Relates to #2178
* Switch from `randint` to `uuid` in mongo tests
* verify mongo tests pass
The random int used in mongo tests is random, but not unique. The mongo tests don't clear out records between tests so by chance it is possible to have a clash in ids. This PR changes the use of random ints to using uuids. This is one of the causes mongo tests are flaky in CI, but I suspect it isn't the only reason so there is probably more to do here.
=> Switch mongo tests from randint to uuid

.fides/fides.toml, CHANGELOG.md, docs/fides/docs/development/postman/Fides.postman_collection.json, src/fides/api/ops/api/v1/endpoints/messaging_endpoints.py, src/fides/api/ops/api/v1/urn_registry.py, src/fides/api/ops/email_templates/get_email_template.py, src/fides/api/ops/email_templates/template_names.py, src/fides/api/ops/email_templates/templates/test_message.html, src/fides/api/ops/schemas/messaging/messaging.py, src/fides/api/ops/service/messaging/message_dispatch_service.py, tests/ops/api/v1/endpoints/test_messaging_endpoints.py, tests/ops/service/messaging/message_dispatch_service_test.py
Closes #2457
* Added a route to all sending a test message.
* Configure a messaging service
* Go to http://localhost:8080/docs#/messaging/send_test_message_api_v1_messaging_config_test_post
* Enter either a phone number or email address, matching the type of message service setup
* Verify the message was received
=> Add messaging test route

CHANGELOG.md, data/saas/config/firebase_auth_config.yml, tests/ops/integration_tests/saas/request_override/test_firebase_auth_task.py
=> Updating Firebase Auth to delete user

CHANGELOG.md, clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts, clients/admin-ui/cypress/fixtures/taxonomy/custom-metadata/allow-list/create.json, clients/admin-ui/cypress/fixtures/taxonomy/custom-metadata/allow-list/list.json, clients/admin-ui/cypress/fixtures/taxonomy/custom-metadata/custom-field-definition/create.json, clients/admin-ui/cypress/fixtures/taxonomy/custom-metadata/custom-field-definition/list.json, clients/admin-ui/cypress/fixtures/taxonomy/custom-metadata/custom-field/list.json, clients/admin-ui/cypress/fixtures/taxonomy/custom-metadata/custom-field/update-party.json, clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx, clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx, clients/admin-ui/src/features/common/custom-fields/helpers.ts, clients/admin-ui/src/features/common/custom-fields/hooks.ts, clients/admin-ui/src/features/common/custom-fields/index.ts, clients/admin-ui/src/features/common/custom-fields/types.ts, clients/admin-ui/src/features/common/form/inputs.tsx, clients/admin-ui/src/features/plus/plus.slice.ts, clients/admin-ui/src/features/system/DescribeSystemStep.tsx, clients/admin-ui/src/features/system/form.ts, clients/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx, clients/admin-ui/src/features/taxonomy/TaxonomyTabContent.tsx, clients/admin-ui/src/features/taxonomy/hooks.tsx, clients/admin-ui/src/features/taxonomy/types.ts
Closes #2545
* This is a large refactor to get taxonomy and custom fields working together. See description below and my line comments.
- Might be spun out: https://github.com/ethyca/fides/issues/2545#issuecomment-1429021292
- https://github.com/ethyca/fides/issues/2612
=> ui/custom-metadata: Refactor taxonomy to use a single form submission flow

MANIFEST.in
Closes #2616
* Removed `optional-requriments.txt` from the `MANIFEST.in` file
=> Remove optional-requirements.txt from manifest

CHANGELOG.md, clients/privacy-center/__tests__/common/browser-identities.ts, clients/privacy-center/common/browser-identities.ts, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/pages/consent.tsx
Part of https://github.com/ethyca/fides/issues/2458
=> Add sovrn cookie to privacy center

CHANGELOG.md, clients/privacy-center/__tests__/features/consent/helpers.test.ts, clients/privacy-center/app/store.ts, clients/privacy-center/components/ConsentItemCard.tsx, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/features/common/config.slice.ts, clients/privacy-center/features/consent/GpcMessages.tsx, clients/privacy-center/features/consent/consent.slice.ts, clients/privacy-center/features/consent/helpers.ts, clients/privacy-center/features/consent/types.ts, clients/privacy-center/package-lock.json, clients/privacy-center/package.json, clients/privacy-center/packages/fides-consent/src/lib/consent-context.ts, clients/privacy-center/pages/consent.tsx, clients/privacy-center/public/fides-consent-demo.html
Closes #2230
- pc/fides-consent: support globalPrivacyControl query param directly
- Take a look at the screenshots below
- pc/consent: Refactor consent local state into RTK store
- pc/consent: helpers now only needs makeCookieKeyConsent
- pc/package.json: Update fidesui dependencies to match admin-ui
- The icons were out of date
- pc/consent: Show GPC banner and how it affects individual consent choices
- pc/consent: Cypress tests for GPC defaults and overrides in consent UI
* I extracted the confirmation modal to a ticket: https://github.com/ethyca/fides/issues/2597
(These are a bit zoomed out so I could capture the URL and the whole page)
GPC enabled:
GPC disabled:
=> pc/consent: Show GPC banner and how it affects individual consent choices

CHANGELOG.md, clients/admin-ui/src/features/common/custom-fields/CreateCustomFields.tsx, clients/admin-ui/src/features/common/custom-fields/CustomFieldSelector.tsx, clients/admin-ui/src/features/common/form/inputs.tsx, clients/admin-ui/src/features/plus/plus.slice.ts, clients/admin-ui/src/flags.json
Closes #2624 
* Added **isRequired** attribute to `CustomSelect` component. When value is true, a red asterisk is displayed to the right of the html label indicating that this input is required.
* Added **isDisabled** attribute to Chakra `Select` component nested in `CustomSelect` parent component
* Updated the `CustomFieldSelector` component to set the **Formik** field value accordingly if the custom field value is a string or an array.
* Added optional **menuPosition** attribute to `CustomSelect` component
**FidesPlus**
1. Execute `make server` command from Terminal prompt
**Fides Admin UI**
1. Execute `npm i` command from **clients > admin-ui** Terminal prompt
2. Execute `npm run dev` command from same Terminal prompt
3. Open browser tab and navigate to http://localhost:3000
4. Login …
=> Custom metadata UI updates

clients/admin-ui/src/features/common/health.slice.ts, clients/admin-ui/src/features/config-wizard/scanner.slice.ts, clients/admin-ui/src/features/data-qualifier/data-qualifier.slice.ts, clients/admin-ui/src/features/data-subjects/data-subject.slice.ts, clients/admin-ui/src/features/data-use/data-use.slice.ts, clients/admin-ui/src/features/organization/organization.slice.ts, clients/admin-ui/src/features/system/system.slice.ts, clients/admin-ui/src/features/taxonomy/taxonomy.slice.ts
https://github.com/ethyca/fides/pull/2588 enforces auth on all routes. previously many of our old ctl routes didn't include auth headers. this makes them include them.
This is a lot of inelegant copy/pasta-ing, but I can live with it considering we've got this ticket in the pipeline https://github.com/ethyca/fides/issues/1386
(once that ticket is in, we'd only need the one `prepareHeader`
=> Add auth to all slices

CHANGELOG.md, src/fides/cli/commands/util.py, src/fides/core/deploy.py, tests/ctl/cli/test_deploy.py
Example warning:
```
~/git/sandbox/fides-deploy-test% fides deploy up
Using default configuration values.
Using default configuration values.
in check_virtualenv(), /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9, /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
WARNING: Your 'fides' CLI is installed outside of a virtual environment at: /usr/local/opt/python@3.9/Frameworks/Python.framework/Versions/3.9
Docker may not have permission to access this path, so if you encounter issues with Docker mounts, try reinstalling 'ethyca-fides' using a virtual environment (see https://docs.python.org/3/library/venv.html).
If you did install using a virtual environment, check your PATH. You may have a global version of 'ethyca-fides' installed that is taking …
```
=> Add warning to 'fides deploy' when installed outside of a virtual environment

src/fides/api/ops/models/privacy_request.py, src/fides/api/ops/util/cache.py, tests/ops/util/test_cache.py
Closes #2633
* Replaces pickle with json encoding for cache.
* Handles cases where old cache pickle values are still present.
=> Switch from pickle to json for cache

.fides/fides.toml, CHANGELOG.md, docker-compose.child-env.yml, docker-compose.yml, docker/docker-compose.minimal-config.yml, docker/redis/redis.conf, noxfiles/dev_nox.py, src/fides/api/ops/util/cache.py, src/fides/core/config/redis_settings.py, src/fides/data/test_env/fides.test_env.toml
Closes #2665
I used my local Docker setup to test the following configs:
For testing the Redis server with an ACL, I created this file at `./docker/redis/redis.conf`:
```
user redisadmin on ~* +@all >redispassword
```
I then modified `docker-compose.yml` to configure the `redis` service as:
```
redis:
image: "redis:6.2.5-alpine"
command: redis-server /usr/local/etc/redis/redis.conf
expose:
- 6379
ports:
- "0.0.0.0:6379:6379"
volumes:
- type: bind
source: ./docker/redis
target: /usr/local/etc/redis
read_only: False
```
And updated the `.fides/fides.toml` settings like:
```
[redis]
host = "redis"
user = "redisadmin"
password = "redispassword"
port = 6379
charset = "utf8"
default_ttl_seconds = 604800
db_index = 0
ssl = false
ssl_cert_reqs = "required"
```
* Added: …
=> Fix support for "redis.user" setting when authenticating to the Redis cache

src/fides/api/ops/api/v1/endpoints/messaging_endpoints.py, src/fides/api/ops/schemas/messaging/messaging.py, tests/ops/api/v1/endpoints/test_messaging_endpoints.py
As noticed by @ssangervasi in https://github.com/ethyca/fides/pull/2674, on `main` we stopped accepting lowercased `service_type` values in our basic messaging config endpoints. this was an unintended side effect of a change made in https://github.com/ethyca/fides/pull/2572.
We can fix things up to still support the lowercased `service_type` values and keep this fully backward compatible.
Also added in a fix to make sure we support lowercased `service_type` values in URL paths
* add back the upper-cased (transformed) `service_type` value assignment to the `values` dict in the pydantic validator
* ensure the validator is only run on request models, since we don't need to validate this value in responses. running this validator on responses would throw an error because the response `values` …
=> re-enable support for lower-cased messaging service_type values

clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/cypress/support/commands.ts, clients/privacy-center/cypress/tsconfig.json, clients/privacy-center/package-lock.json, clients/privacy-center/package.json
✅ Trying to resolve a build flake  ♻️
I was able to reproduce by enabling network throttling my Cypress browser. Then I was able to get `waitUntil` to resolve the issue.
=> pc/cy: Use waitUntil to check for cookie consent updates

clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/pages/consent.tsx, clients/privacy-center/types/api/models/Consent.ts, clients/privacy-center/types/api/models/Identity.ts
Closes #2232 
- pc/types: Update Consent API model
- pc/cy: Assert GPC fields passed to API
- pc/consent: Pass GPC status fields to consent update request
=> pc/consent: Pass GPC status fields to consent update request

src/fides/api/ops/api/v1/endpoints/messaging_endpoints.py, src/fides/api/ops/api/v1/endpoints/storage_endpoints.py, src/fides/api/ops/api/v1/urn_registry.py
Small fix to URL convention for active default `GET` routes. Didn't think this warranted a separate GH issue because it's a follow up tweak to new functionality that hasn't been used yet, but i can create a GH issue if that's preferred.
* switch routes to be `[messaging OR storage]/default/active` rather than `[messaging OR storage]/active/default` as it had been implemented initially
* this keeps things consistent with other `default` routes which use ``[messaging OR storage]/default/...`
Note that because "[order matters](https://fastapi.tiangolo.com/tutorial/path-params/#order-matters)" in FastAPI, these routes needed to be switched to now come _before_ the other `/default/...` routes
=> switch active default url path to default/active

CHANGELOG.md, clients/admin-ui/src/features/dataset/helpers.ts
Closes [fidesplus#619](https://github.com/ethyca/fidesplus/issues/619)
If the feature flag was enabled, the data would be visible on the data map. Adding the feature flag and not accounting for it in all areas is the root cause of the issue here
=> include feature flag check in helper

CHANGELOG.md, src/fides/api/ops/util/cache.py, tests/ops/util/test_cache.py
Closes #2691
* Prefix date objects when caching
* Look for date prefix before decoding back to a date object
=> Allow string dates to stay strings in cache decoding

clients/admin-ui/src/features/common/features/FlagControl.tsx, clients/admin-ui/src/features/common/utils.ts, clients/admin-ui/src/features/system/DataFlowsAccordionItem.tsx, clients/admin-ui/src/pages/management/about.tsx
Closes #2359 
* Fix doc + community links
* "Sentence case" utility applied to flag names
I considered adding a "name" field to the actual feature flags, but then I did the lazier thing. Worth it?
=> ui/about: About page doc links and flag names

src/fides/api/ops/api/v1/endpoints/privacy_request_endpoints.py, src/fides/api/ops/schemas/application_config.py, src/fides/core/config/config_proxy.py, src/fides/core/config/utils.py, tests/conftest.py, tests/ops/api/v1/endpoints/test_config_endpoints.py
In initial config API implementation, I forgot about the "manual request approval" setting and that we should support that through the API, in order to allow the UI-based system config to turn this on by default, when a messaging provider is configured.
This PR adds in support for setting this property via the config API.
* allow/support `execution.require_manual_request_approval` setting via config API
* update our code references to this property to use the `config_proxy` rather than the basic `CONFIG` object, so that API changes are picked up by the app during privacy request execution
* some small fixes/cleanup in related areas of config API
=> Add `execution.require_manual_request_approval` to supported config API

CHANGELOG.md, clients/admin-ui/cypress/fixtures/connectors/connection_types.json, clients/admin-ui/src/constants.ts, clients/admin-ui/src/features/privacy-requests/manual-processing/ManualProcessingList.tsx, src/fides/api/ops/models/connectionconfig.py, tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
Closes #2460
* Replaced "webhook" when it appears in user-visible strings
* Replaced the constant in Python where the human readable name is often referenced, even from the UI.
Note that the connector search compares by non-human-readable type, so "webhook" will still have results. See: https://github.com/ethyca/fides/issues/2460#issuecomment-1447232997
=> [2460]: Change "manual webhook" to "manual process"

CHANGELOG.md, src/fides/api/ops/api/v1/endpoints/drp_endpoints.py, src/fides/api/ops/api/v1/endpoints/privacy_request_endpoints.py, src/fides/api/ops/service/privacy_request/request_runner_service.py, src/fides/api/ops/service/privacy_request/request_service.py, tests/fixtures/saas/vend_fixtures.py, tests/ops/api/v1/endpoints/test_consent_request_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py, tests/ops/service/privacy_request/request_runner_service_test.py, tests/ops/service/privacy_request/test_request_service.py
Closes https://github.com/ethyca/fides/issues/2735
When updating consent preferences, and subject_identity_verification_required is True, Privacy Request should be put in a status of "pending" not "identity_unverified" as identity was verified before the consent preferences were saved.
=> Consent Privacy Request Status when Identity Verification Required

CHANGELOG.md, scripts/setup/user.py, src/fides/api/ctl/migrations/versions/9f38dad37628_redo_roles_scopes_mapping.py, src/fides/core/config/security_settings.py, src/fides/lib/oauth/roles.py, tests/conftest.py, tests/ctl/cli/test_cli.py, tests/fixtures/application_fixtures.py, tests/lib/test_client_model.py, tests/lib/test_oauth_util.py, tests/ops/api/v1/endpoints/test_connection_config_endpoints.py, tests/ops/api/v1/endpoints/test_oauth_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py, tests/ops/api/v1/endpoints/test_user_endpoints.py, tests/ops/api/v1/endpoints/test_user_permission_endpoints.py
Closes #2720 
POST {{host}}/user
```json
{
"username": "test_user",
"password": "Testpassword1!"
}
```
PUT {{host}}/user/{{user_id}}/permission
```json
{
"id": "{user_id}",
"roles": ["viewer"]
}
``` 
We recently added some backend roles associated with lists of scopes here: https://github.com/ethyca/fides/pull/2671, the roles were Admin, Viewer, Privacy Request Manager, and Viewer + Privacy Request Manager.
Requirements have changed, and roles need to be renamed/rearranged.
New Roles are:
- Owner: Full Admin
- Viewer: Can view everything
- Contributor: Can manage most things but can't adjust storage and messaging configs
- Approver: Limited view but can approve privacy requests
- Viewer + Approver: Full view and can approve privacy requests
=> Overhaul Roles and Roles Mapping [#2720]

clients/admin-ui/src/features/privacy-requests/configuration/MailgunEmailConfiguration.tsx, clients/admin-ui/src/features/privacy-requests/configuration/TwilioEmailConfiguration.tsx, clients/admin-ui/src/features/privacy-requests/configuration/TwilioSMS.tsx
Helps close #2455
specifically meant to resolve issue reported in [this comment](https://github.com/ethyca/fides/issues/2455#issuecomment-1456097873)
- i noticed that the `messagingDetails` param was undefined in the case where the messaging config form loads from "scratch", i.e. there is no messaging default already present for the given service type. this is because the `getMessagingConfigurationDetails()` query against the backend gets an (expected) `404` in these cases
- since the `TestMessagingProviderConnectionButton` constructor only really requires the `service_type` from the `messagingDetails`, and we know the `service_type` already given the context of the form, i just define a dummy `messagingDetails` object with the `service_type` inferred from the context of the form, in the …
=> fix messaging 'test connection' workflow on initial save

CHANGELOG.md, clients/admin-ui/cypress/e2e/privacy-requests.cy.ts, clients/admin-ui/cypress/fixtures/privacy-requests/messaging_configuration.json, clients/admin-ui/src/features/privacy-requests/constants.ts, clients/admin-ui/src/types/api/models/MessagingServiceType.ts, src/fides/api/ctl/migrations/versions/2f6aa5fe797a_update_messaging_service_type_enum.py, src/fides/api/ops/api/v1/endpoints/messaging_endpoints.py, src/fides/api/ops/models/messaging.py, src/fides/api/ops/schemas/application_config.py, src/fides/api/ops/schemas/messaging/messaging.py, src/fides/api/ops/schemas/messaging/messaging_secrets_docs_only.py, src/fides/api/ops/service/connectors/email_connector.py, src/fides/api/ops/service/messaging/message_dispatch_service.py, src/fides/api/ops/service/messaging/messaging_crud_service.py, src/fides/core/config/notification_settings.py, tests/conftest.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_config_endpoints.py, tests/ops/api/v1/endpoints/test_consent_request_endpoints.py, tests/ops/api/v1/endpoints/test_messaging_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py, tests/ops/integration_tests/test_integration_email.py, tests/ops/service/connectors/test_consent_email_connector.py, tests/ops/service/messaging/message_dispatch_service_test.py, tests/ops/service/privacy_request/request_runner_service_test.py
Closes #2680 
* update `MessagingServiceType` Enum in python codebase to have lowercased values, update any references in code and in tests
* switch any `.upper()` calls that coerced user-input values to instead be `.lower()`, to maintain backward compatibility and continue to support uppercased user input
* provide a DB migration to change the enum type in the DB schema, as well as a data migration to change any existing enum values in the DB to lowercased
* update FE code references to user lowercased enum values rather than uppercased
* ensure new system config UI still works as expected
* ensure migration works as expected:
* run server on `main` (e.g. `nox -s dev -- ui`) and create a messaging config (e.g. using the system config UI)
* teardown but do not delete volumes, i.e. `nox -s …
=> switch messaging service type db enum to use lowercase values

clients/admin-ui/src/features/common/Layout.tsx, clients/admin-ui/src/features/common/custom-fields/hooks.ts, scripts/quickstart.py
- To check for the new tables/columns that have been added in the release, look for new migration files in the `src/fides/api/ctl/migrations` directory and inspect their contents
- If found, look at the latest database diagram, and check whether it contains the tables/columns that were added in these migrations
- If the diagram is not up to date, follow the steps in the link above to generate a new database diagram with …
=> release 2.8.0

src/fides/api/ctl/migrations/versions/c9ee230fa6da_add_config_set_column_to_application_.py
Closes #2779 
* include a `server_default` of encrypted `{}` value when creating the `config_set` column in migration, so as to handle cases where an existing `appconfig` record exists while allow the new column to be nullable.
* see issue description for repro steps
~~the proposed solution is not ideal - i'm not sure of a truly clean way to handle this. the column in question here is a new column in `2.8.x` and it's an encrypted JSON column that ideally should be non-nullable. before this change, the problem with the migration was that it just added the non-nullable column to the table, but doesn't account for the fact that there may be an existing record in the db, even though that's _quite a narrow edge case_. but in that case, the new non-nullable column is added to …
=> update appconfig migration to handle existing record

CHANGELOG.md, src/fides/api/ctl/routes/datamap.py, src/fides/core/export.py
Closes #2768
Manual detail steps:
```
insert into public.plus_custom_field_definition (id, name, description, field_type, resource_type, field_definition, active)
select 'new_id', 'country', 'country name', 'string', 'system', 'string', true;
insert into public.plus_custom_field (id, resource_type, resource_id, custom_field_definition_id, value)
select 'updated_id', 'system', 'demo_analytics_system', 'new_id', '{portugal}';
```
Found as part of the release for `2.8.0`
An additional finding around the application of the custom fields was also found and included in here
=> Include custom columns in header row of datamap

clients/admin-ui/package-lock.json, clients/admin-ui/package.json, clients/cypress-e2e/package-lock.json, clients/cypress-e2e/package.json, clients/privacy-center/package-lock.json
After merging #2516, I'd prefer to have the same Typescript version on Privacy Center, Admin UI, and Cypress E2E clients.
=> Bump typescript version to 4.9.5 on all clients

CHANGELOG.md
Merging #2762 put the CHANGELOG entries into 2.8.1 incorrectly, they should have gone into Unreleased 👍
=> Fix incorrect merge to CHANGELOG

CHANGELOG.md, clients/admin-ui/src/features/common/Layout.tsx
| Before | After |
|---|---|
|![fides-nightly fides-staging ethyca com_add-systems](https://user-images.githubusercontent.com/1834295/224773511-61b988ca-c442-4a13-9307-b6c926836a0d.png)| ![localhost_3000_](https://user-images.githubusercontent.com/1834295/224773527-60561004-a074-420f-8e0d-67b90112bbde.png)|
This is a small CSS change to ensure the _overall_ app layout is consistent between the Fides and Fides Plus Admin UIs. In the Plus UI we have some pages that need to fill the viewport height, so the overall Layout needs to include `height=100vh` over there - by doing the same here, it just means we're less likely to get some minor discrepancies in app layouts over time without noticing.
Note: this should have *no* visual effect on the existing app pages! I looked at …
=> Update Admin UI Layout to fill viewport height

CHANGELOG.md, src/fides/core/export.py, tests/ctl/api/test_datamap.py
Closes https://github.com/ethyca/fidesplus/issues/679. 
* for systems with privacy declarations and with custom field data, our iteration to add the custom field data looked like this:
* for each custom field, iterate over each product (row of output data); and then within each product (row), add the custom field value to the row, and add the row to the list of output rows (the `cartesian_product_of_declaration` itself gets appended to the `output_list`):
```
if system_custom_field_data:
for _, v in system_custom_field_data.items():
for product in cartesian_product_of_declaration_builder:
product.append(v)
cartesian_product_of_declaration.append(tuple(product))
```
* this had the effect of adding a new _row_ of output data for each custom field - which is not what we want!
* instead, what …
=> support >1 custom fields per system in datamap export

CHANGELOG.md, clients/admin-ui/cypress/e2e/systems-plus.cy.ts, clients/admin-ui/cypress/e2e/systems.cy.ts, clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts, clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx, clients/admin-ui/src/features/common/custom-fields/hooks.ts, clients/admin-ui/src/features/common/custom-fields/types.ts, clients/admin-ui/src/features/system/SystemInformationForm.tsx, clients/admin-ui/src/features/system/form.ts, clients/admin-ui/src/features/taxonomy/hooks.tsx
Closes https://github.com/ethyca/fides/issues/2788
The issue presented itself like something was wrong with the `UnmountWarning` component, but it's actually because the form was always in a "dirty" state due to some circular logic going on in the `CustomFieldsList` component (hence the problem only showing up in plus)
Originally, `CustomFieldsList` had a `useEffect` which would read in the data from the custom fields endpoint, then populate the form on the fly via `setValue`. Using `setValue` made the form always dirty, hence the unmount warning always showing up.
I went for a pretty thorough (🤞) refactoring, where instead of populating the data on the fly, populate the data via the initial values to begin with. this cleans up a lot of the `useEffect`s and various `reload` functionality, …
=> Custom metadata refactoring so that form is not always dirty

CHANGELOG.md, clients/admin-ui/src/features/common/Layout.tsx, clients/admin-ui/src/features/common/NotificationBanner.tsx, clients/admin-ui/src/features/common/features/features.slice.ts, clients/admin-ui/src/features/user-management/user-management.slice.ts, clients/admin-ui/src/home/HomeLayout.tsx
Closes https://github.com/ethyca/fidesplus/issues/676
I wasn't sure if we wanted to add a check against the fides version here? Or how we determine when we will remove this banner. 
https://user-images.githubusercontent.com/24641006/225382627-95f2e99e-57dc-4e4c-862d-18ef985b7868.mov
=> Implement a notification banner to show up on login

CHANGELOG.md, src/fides/api/ctl/migrations/versions/064dd27a6d41_add_viewer_role.py, src/fides/api/ctl/migrations/versions/50180bbbb959_automigrate_viewer_role.py, src/fides/api/ops/tasks/storage.py, src/fides/data/test_env/fides.test_env.toml, src/fides/lib/oauth/roles.py, tests/ops/api/v1/endpoints/test_config_endpoints.py, tests/ops/service/storage_uploader_service_test.py
Closes #2776 
❗ Locked to the same release as https://github.com/ethyca/fides/pull/2739
"messagingconfig", "service_type", new_column_name="service_type_old"
)`
and so now the new migration is adding it back in to keep things in sync
This is an automated data migration to transition to the new "roles".
Sets all user scopes to an empty list and gives all users a `viewer` role.  Someone will need to login as a root user and assign  roles.  Intentionally nothing preventing users from adding scopes to their users via the API yet.
A followup in a future sprint will get rid of `fidesuserpermission.scopes` entirely https://github.com/ethyca/fides/issues/2696
=> Remove Scopes and Add Viewer Role

clients/admin-ui/src/features/common/form/inputs.tsx, clients/admin-ui/src/features/user-management/UserForm.tsx
Closes https://github.com/ethyca/fides/issues/2849
Note that adding the `isRequired` field is a bit of data duplication because [formik doesn't currently have a way to use the Yup validation schema](https://github.com/jaredpalmer/formik/issues/1241) to determine a field is required, so we pass it in.
=> Restore password validation in user management

CHANGELOG.md, src/fides/core/export.py, tests/ctl/api/test_datamap.py
Closes #2850 
* keep an ordered list of custom field headers, in the order that they appear in the header row
* leverage that ordered list when populating custom field row data
* add some test coverage for the error case and related cases
* we should be able to populate the DB similar to how we're doing it in the test cases and repro with the datamap export API solely on `fides`
* even better would be to cut an edge build off this release branch (not something we've normalized, yet, but maybe we can give it a try!) and test this with the fidesplus FE
* this will allow us to create and populate custom fields a lot more easily, and therefore stress test with more scenarios
i started considering a more significant refactor to the code where we don't rely on an implicit …
=> handle different orders of custom field additions in datamap export

clients/admin-ui/cypress/e2e/home.cy.ts, clients/admin-ui/src/features/common/custom-fields/hooks.ts, clients/admin-ui/src/features/common/nav/v2/NavSideBar.tsx, clients/admin-ui/src/features/common/nav/v2/nav-config.test.ts, clients/admin-ui/src/features/common/nav/v2/nav-config.ts, clients/admin-ui/src/home/HomeContent.tsx, clients/admin-ui/src/home/tile-config.test.ts, clients/admin-ui/src/home/tile-config.ts
Closes https://github.com/ethyca/fidesplus/issues/701
=> Various 2.9.0 fixes

CHANGELOG.md, src/fides/api/ops/schemas/privacy_request.py, src/fides/lib/models/fides_user_permissions.py, src/fides/lib/oauth/api/routes/user_endpoints.py, tests/ops/api/v1/endpoints/test_user_permission_endpoints.py
Calling FidesUserPermission.total_scopes could mutate whatever list was passed in for FidesUserPermission.scopes: taking every scope that was on the user's role and adding it to the list of scopes.  
This could have side effects such as a token for a root client being created that had many duplicate scopes.  Note that the root client is not a database object, but the CONFIG.security.root_user_scopes value could get mutated on subsequent calls to the get user permissions endpoint.
=> Fix FidesUserPermissions Scopes Mutation

CHANGELOG.md
```
fides status
exit
```
Next, run the following checks against the environment you've spun up using `fides deploy up --no-pull`:
Run these from within `nox -s dev -- shell`
=> Release 2.9.1

CHANGELOG.md, clients/admin-ui/src/features/common/Layout.tsx, clients/admin-ui/src/features/config-wizard/AddSystem.tsx, clients/admin-ui/src/features/config-wizard/ConfigWizardWalkthrough.tsx, clients/admin-ui/src/features/datastore-connections/ConnectionFilters.tsx, clients/admin-ui/src/home/HomeBanner.tsx, clients/admin-ui/src/home/HomeContent.tsx, clients/admin-ui/src/home/HomeLayout.tsx, clients/admin-ui/src/theme/index.ts
| Page | Before | After |
|---|---|---|
| Home (1024px) | <img width="1024" alt="image" src="https://user-images.githubusercontent.com/1834295/226481131-7b8750fd-74b0-4250-9a98-d4a51a8f496a.png"> | <img width="1024" alt="image" src="https://user-images.githubusercontent.com/1834295/226484284-16644cf0-da99-4396-9ca8-e1bd83116349.png">| 
| Privacy Requests (1024px) | <img width="1024" alt="image" src="https://user-images.githubusercontent.com/1834295/226481211-ce5d8209-5928-453b-9ef5-f4350eddbac9.png">| <img width="1024" alt="image" src="https://user-images.githubusercontent.com/1834295/226484507-2dc5dfcf-3f49-4f7b-9657-8b3e25bafacb.png">|
| View Systems (1024px) |<img width="1023" alt="image" src="https://user-images.githubusercontent.com/1834295/226481277-c4999710-3cd2-4152-b2ae-37345bd5d4 …
=> Improve standard layout for large width screens and polish misc. pages

CHANGELOG.md, clients/admin-ui/src/pages/management/about.tsx
This allows end users on FidesPlus to see the Fides Core it is using and not to be confused with Fides Plus.
Closes #TBD
=> fix: change Version to Fides Core Version

src/fides/api/ops/service/messaging/message_dispatch_service.py
This PR updates the Mailchimp Transactional adaptor to use the `html` attribute, and subsequently render html correctly in emails.
=> use HTML property, not text, when dispatching Mailchimp Transactional emails

CHANGELOG.md, clients/privacy-center/pages/404.tsx, clients/privacy-center/pages/consent.tsx
Closes #2893 
* Replace 404 logo width/height attributes to maxWidth/maxHeight
* Increase the maxWidth/maxHeight sizes to make the logo appear larger on 404 page
* Remove width constraint from consent page
* Launch privacy center from main (`npm run dev`)
* Replace the logo in the `config.json` with a few others:
* https://upload.wikimedia.org/wikipedia/commons/4/46/Wikipedia-logo-v2-en_6m_articles_204_white.png
* https://upload.wikimedia.org/wikipedia/commons/8/85/Logo-Test.png
* browse to http://localhost:3000/fake-page
* browse to consent page
* Launch privacy center from this branch (`rk-2893-privacy-center-404`)
* Repeat testing steps to confirm logos look correct
=> Fix Logo aspect ratio on Privacy Center `404` page and Consent Page

CHANGELOG.md, clients/admin-ui/cypress/e2e/systems.cy.ts, clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationAccordion.tsx, clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationForm.tsx, clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationManager.tsx, clients/admin-ui/src/features/system/privacy-declarations/types.ts
Closes https://github.com/ethyca/fides/issues/2894
* In retrospect, this was a _little_ overkill, as it doesn't actually solve [this problem](https://github.com/ethyca/fides/blob/main/clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationAccordion.tsx/#L99-L102). It gets us a lot closer though—we could probably use a javascript UUID package and replace the ID there and be fairly close. However, I think it'd be better if the backend gave an ID instead 😄 
* The 🔑 thing here was updating the `key` value to be a composite instead of just based off of `data_use`
=> Privacy declaration with composite ID

CHANGELOG.md, clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestModal.tsx, clients/privacy-center/components/modals/privacy-request-modal/RequestSubmitted.tsx
Closes #2911
* Removes the policy key in the modal post ID verification
* Launch privacy center, configured to connect to a Fides instance with ID verification enabled
* Submit access request
* View confirmation modal
=> [#2911] Remove policy key from submission modal

.github/workflows/backend_checks.yml, .github/workflows/cli_checks.yml
Note that I'm not sure of a better way to test this except by merging and trying it out. I guess I could push a couple fake commits to this branch to see what happens and then rebase...?
I often see us in a situation where [we forget to format some Typescript code](https://github.com/ethyca/fides/pull/2908/commits/9513480bdb20d70ffd6a430c519f2c3ecc483fab) and then re-run the entire pytest matrix. This just slows down code review IMO, even if those checks are usually pretty quick?
=> Don't run the backend/CLI code checks if only client code is edited

CHANGELOG.md, clients/admin-ui/cypress/e2e/user-management.cy.ts, clients/admin-ui/src/features/user-management/AssignSystemsModal.tsx, clients/admin-ui/src/features/user-management/AssignSystemsTable.tsx, clients/admin-ui/src/features/user-management/PermissionsForm.tsx, clients/admin-ui/src/features/user-management/RoleOption.tsx
Closes https://github.com/ethyca/fidesplus/issues/722
=> 722 tie user role and system save states together

clients/admin-ui/src/features/auth/ProtectedRoute.tsx, clients/admin-ui/src/features/auth/auth.slice.ts, clients/admin-ui/src/features/common/Header.tsx
Fixes this error that shows up on logging out in dev mode
It seems like this was introduced after we updated our npm packages https://github.com/ethyca/fides/pull/2921
It's possible we may need this update in plus too, I'm not sure yet.
* `rm -rf node_modules`
* `npm i`
* Log into the app
* Log out
* You shouldn't get any errors
=> Fix logout bug

CHANGELOG.md, clients/admin-ui/cypress/e2e/user-management.cy.ts, clients/admin-ui/src/features/user-management/UserManagementRow.tsx, clients/admin-ui/src/features/user-management/UserManagementTable.tsx
Closes https://github.com/ethyca/fides/issues/2861
=> add assigned systems to user management table

CHANGELOG.md, clients/admin-ui/src/features/user-management/PermissionsForm.tsx, clients/admin-ui/src/features/user-management/RoleOption.tsx
Closes https://github.com/ethyca/fides/issues/2898
=> 2898 alert system manager downgrade to approver

CHANGELOG.md, clients/admin-ui/src/features/user-management/UserForm.tsx
Closes #[735](https://github.com/ethyca/fidesplus/issues/735)
=> update new user toast message

CHANGELOG.md, clients/admin-ui/README.md, clients/admin-ui/src/features/common/features/FlagControl.tsx, clients/admin-ui/src/features/common/features/types.ts
Closes N/A, but seems like it will be useful for upcoming consent modeling work. It seems like there's a growing need of having feature flags but which the user cannot easily toggle. This is for the case of work that is still too in development to let users turn on, and came up already once here: https://github.com/ethyca/fides/pull/2937
```json
"organizationManagement": {
"description": "Management page to configure Organization details for RoPA reporting, messaging, etc.",
"development": true,
"test": true,
"production": false,
"userCannotModify": true
}
```
I decided to use `userCannotModify` since I thought it was useful as by default the user _can_ modify. But I'm not too attached to that if anyone thinks it should be the other way around.
=> Add `userCannotModify` field to flag control

CHANGELOG.md, clients/admin-ui/src/flags.json
Closes #[2890](https://github.com/ethyca/fides/issues/2890)
=> Hide message and storage configuration in ui 

.github/workflows/frontend_checks.yml, CHANGELOG.md, clients/admin-ui/src/features/common/FixedLayout.tsx, clients/admin-ui/src/features/common/SearchBar.tsx, clients/admin-ui/src/features/common/form/inputs.tsx, clients/admin-ui/src/pages/datamap/index.tsx, clients/admin-ui/src/theme/index.ts
Progress on https://github.com/ethyca/fides/issues/2976
This branch should now have everything needed to run the datamap UI from admin UI. if anything looks different from the original datamap UI, do flag it!
=> Fix layout of datamap page

CHANGELOG.md, clients/admin-ui/cypress/e2e/user-management.cy.ts, clients/admin-ui/src/features/user-management/UserManagementRow.tsx
Closes https://github.com/ethyca/fides/issues/2860
you should instead see the delete trash icon:
when it's clicked, you should be prompted to confirm username to delete user:
=> Replace hamburger menu with delete icon in user management table

clients/admin-ui/cypress/e2e/datamap.cy.ts, clients/admin-ui/cypress/e2e/privacy-notices.cy.ts, clients/admin-ui/cypress/e2e/routes.cy.ts, clients/admin-ui/src/features/auth/ProtectedRoute.tsx, clients/admin-ui/src/features/common/nav/v2/nav-config.test.ts, clients/admin-ui/src/features/common/nav/v2/nav-config.ts
Closes https://github.com/ethyca/fides/issues/3002
* This func was useful back when we had a progressive nav, but since we got rid of that we shouldn't need it anymore
* See steps in the issue
=> Fix navigating directly to a plus route

CHANGELOG.md, docs/fides/docs/development/postman/Fides.postman_collection.json, src/fides/api/ctl/sql_models.py, src/fides/api/ops/api/v1/endpoints/privacy_notice_endpoints.py, src/fides/api/ops/api/v1/urn_registry.py, src/fides/api/ops/models/privacy_notice.py, src/fides/api/ops/schemas/privacy_notice.py, tests/conftest.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_privacy_notice_endpoints.py
Partially closes #2834 (1 of 2 required endpoints)
* new `GET /api/v1/privacy-notice-by-data-use` endpoint that returns a map of `DataUse`s with their corresponding `PrivacyNotice`s
* Only `DataUse`s that are associated with a `System` are included in the map.
* `DataUse`s that do not have any `PrivacyNotice` associated with them are included
in the map, with empty lists.
* add some `System`s with privacy declarations (easiest to do thru the UI)
* add some `PrivacyNotice`s that have `DataUse`s that overlap with the privacy declarations of your `System`s (must be manual `POST /api/v1/privacy-notice` API calls for now)
* invoke the `GET /api/v1/privacy-notice-by-data-use` endpoint, and ensure the result looks as expected
=> endpoint to retrieve privacy notices by data use

tests/fixtures/saas/shippo_fixtures.py, tests/ops/integration_tests/saas/test_shippo_task.py, tests/ops/util/test_saas_util.py
n/a
~* [ ] Update `CHANGELOG.md`~
Quick fix to get the format checks on `main` passing.
=> Fix format errors from Shippo connector

.github/workflows/publish_package.yaml
Closes n/a
* update tag regex to route beta tags in "real" PyPI publishing in CI, rather than test PyPI
* I think we'll need to merge this to main in order to test it out!
We want to try out a new publishing pattern where we publish to "real" PyPI (not test PyPI) on "beta" tags (e.g. `2.10.1b1`),  which should only be generated on `main` commits. this will allow us to get a prerelease version of `fides` into `fidesplus` if desired, without having to go to testpypi, i.e. via `fidesplus`'s `requirements.txt`. this is particularly helpful in cases where there is feature development on `fidesplus` that _requries_ changes in `fides` that have not yet been released.
=> try publishing beta (main) tags to real PyPI

CHANGELOG.md, clients/admin-ui/cypress/e2e/privacy-notices.cy.ts, clients/admin-ui/cypress/fixtures/privacy-notices/list.json, clients/admin-ui/src/features/common/ConfirmationModal.tsx, clients/admin-ui/src/features/privacy-notices/PrivacyNoticesTable.tsx, clients/admin-ui/src/features/privacy-notices/cells.tsx, clients/admin-ui/src/features/privacy-notices/privacy-notices.slice.ts, clients/admin-ui/src/features/system/system.slice.ts
Closes https://github.com/ethyca/fidesplus/issues/740
* Set up your privacy notices as described in https://github.com/ethyca/fides/pull/3001
* Disable a privacy notice. You should get a confirmation modal
* Re-enable it
* Refresh the page and make sure your changes persist
https://user-images.githubusercontent.com/24641006/230660969-8a9a50bd-1033-4698-831d-4b87617a954e.mov
=> Enable toggle for privacy notices

.github/workflows/publish_docker.yaml, noxfiles/docker_nox.py, noxfiles/git_nox.py
Partially closes #2919 
* include a `push` session arg that can push images corresponding to a git tag, if one exists on the current commit (`nox -s "push(git-tag)"`)
* update GH actions to invoke this `push` session on any tags that are _not_ prod tags (prod tags already publish a nice, clean, versioned docker image via the `push(prod)` session, so it's not needed and we don't want to duplicate)
* this new nox session is a no-op if it finds no explicit git tag on the current commit, so we are OK to invoke it liberally, and it will weed out any commits where there's no tag, e.g. a "normal" commit to `main`. the `dev` tagged image will continue to be published on commits to `main`.
* as it stands now in the PR, feature and release branch tags will _also_ publish the `:dev` image. this may …
=> publish git-tag-specific docker images

docker-compose.yml
* ~[ ] Update `CHANGELOG.md`~
This is a regression for the development environment introduced by https://github.com/ethyca/fides/pull/3017. Obvious mistake is obvious!
=> Fix mount location for dev privacy center

clients/admin-ui/src/types/api/models/ConnectionSystemTypeMap.ts
Closes #3062
I was using `narrows` but the library checks that `encoded_icon` is defined and populated, but I just need to check that `encoded_icon` is not undefined.
=> Reverting the usage of narrows

clients/admin-ui/src/features/datamap/SpatialDatamap.tsx, clients/admin-ui/src/features/datamap/datamap.slice.ts, clients/admin-ui/src/features/datamap/types.ts
This video shows toggling the new data flow links on and off to highlight that the graph is rendering dep links.
https://user-images.githubusercontent.com/17103888/232067555-a7cb1148-b9c8-40a2-b765-3d25b7634068.mov
I went back and double checked how the dep links were generated and made sure that they're generated in the same exact way in this PR. Here is the code I checked for reference:
https://github.com/ethyca/fides/blob/aee09227838410674ed8d9efd31a56758122773b/clients/admin-ui/src/features/datamap/SpatialDatamap.tsx#L46-L51
=> Add dependency links

src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py, src/fides/api/ops/models/privacy_request.py, tests/ops/api/v1/endpoints/test_consent_request_endpoints.py, tests/ops/integration_tests/test_mongo_task.py, tests/ops/models/test_consent_request.py
Reverts change I should not have made in: https://github.com/ethyca/fides/pull/3016
For the older workflow, we should only be queuing Privacy Requests if we have executable Consent Preferences.  For users with front-end only workflows, they should not have Privacy Requests created.
=> Restore Behavior: Only Queue Privacy Requests if we have Executable Preferences

src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py, src/fides/api/ops/models/privacy_request.py, src/fides/api/ops/schemas/privacy_request.py, src/fides/api/ops/schemas/redis_cache.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_consent_request_endpoints.py, tests/ops/models/test_privacy_request.py
=> API endpoint for Consent reporting

CHANGELOG.md, clients/admin-ui/src/features/common/Layout.tsx, clients/admin-ui/src/features/common/NotificationBanner.tsx, clients/admin-ui/src/features/common/features/features.slice.ts
Closes https://github.com/ethyca/fides/issues/2844
* Log in as a viewer
* You should no longer see the warning banner about scopes being migrated
I left the general framework in place since I think it'll likely still be useful to us in the future if we need a banner displayed on all of our pages again.
=> Remove banner with scope migration warning

CHANGELOG.md, clients/admin-ui/src/features/common/custom-fields/hooks.ts, clients/admin-ui/src/flags.json
=> Remove `customField` feature flag

clients/admin-ui/src/home/HomeLayout.tsx
Closes https://github.com/ethyca/fides/issues/2844 (for real this time)
* Log in as a viewer
* You should no longer see the warning banner about scopes being migrated no matter which page you are on.
In https://github.com/ethyca/fides/pull/3055, I forgot the home page has a different Layout component than the rest of the app and also had a copy of the notification banner. This removes that banner as well.
The datamap UI also uses a different Layout component, but that one never had the banner so we are okay there 👍
=> Remove notification banner from home page

clients/admin-ui/src/features/common/nav/v2/nav-config.ts, clients/admin-ui/src/features/common/nav/v2/routes.ts, clients/admin-ui/src/features/plus/plus.slice.ts, clients/admin-ui/src/flags.json, clients/admin-ui/src/pages/management/custom-fields.tsx
Closes #3078 
This uses the same setup that privacy consent notices uses for feature flags so it will only show up in dev and test envs.
=> Add custom fields page

CHANGELOG.md, clients/admin-ui/cypress/e2e/privacy-notices.cy.ts, clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts, clients/admin-ui/cypress/fixtures/privacy-notices/notice.json, clients/admin-ui/cypress/support/commands.ts, clients/admin-ui/cypress/support/stubs.ts, clients/admin-ui/src/features/common/form/FormSection.tsx, clients/admin-ui/src/features/common/form/inputs.tsx, clients/admin-ui/src/features/data-use/data-use.slice.ts, clients/admin-ui/src/features/privacy-notices/ConsentMechanismForm.tsx, clients/admin-ui/src/features/privacy-notices/PrivacyNoticeForm.tsx, clients/admin-ui/src/features/privacy-notices/PrivacyNoticesTable.tsx, clients/admin-ui/src/features/privacy-notices/constants.ts, clients/admin-ui/src/features/privacy-notices/form.ts, clients/admin-ui/src/features/privacy-notices/privacy-notices.slice.ts, clients/admin-ui/src/pages/consent/privacy-notices/[id].tsx, clients/admin-ui/src/pages/consent/privacy-notices/new.tsx
Closes https://github.com/ethyca/fidesplus/issues/749
* Run with fidesplus edge (`nox -s fides_env -- prod_edge `) and dev server for admin-ui
* Follow the steps [here](https://github.com/ethyca/fides/pull/3001) for populating your db with privacy notices
* Once you have notices populating in your table, you should be able to click into one to edit the form
* You should be able to save changes, refresh the page, and see your changes persist
* If you change a consent mechanism to "notice only", the "GPC Enabled" toggle and the "Enforcement Level" should become disabled, with "GPC Enabled" toggling off, and "Enforcement Level" becoming "Not applicable"
* You should also be able to add an entirely new privacy notice
* Note that you'll see a success toast after creation, but you likely won't …
=> Individual privacy notice page

tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
Closes n/a
ops unit tests were broken because we now have > 50 connection types and our tests relied on all connection types being returned from the endpoints. our default page size is 50, so by increasing to explicitly set `100` as a page size, we can mitigate the problem.
longer term, once we have >100 connector types, we can look to incorporate paging into the tests. but i wanted a quick fix for now 😄 
* set `size=100` on our tests getting `connection_types` that need all connector types.
- automated tests should pass
=> fix unit tests for saas connector type endpoints

CHANGELOG.md, noxfiles/utils_nox.py, src/fides/api/ops/api/v1/endpoints/consent_request_endpoints.py, src/fides/cli/__init__.py, src/fides/cli/commands/scan.py, src/fides/cli/exceptions.py, src/fides/core/dataset.py, tests/ctl/cli/test_cli.py, tests/fixtures/application_fixtures.py, tests/fixtures/saas/klaviyo_fixtures.py, tests/ops/integration_tests/saas/test_klaviyo_task.py
Closes #3035 
Quick fix for a bug that @nicolas-ethyca found
=> Fix `scan dataset` commands not respecting `--local` flag

clients/admin-ui/src/features/common/table/FidesTable.tsx, clients/admin-ui/src/features/custom-fields/CustomFieldModal.tsx, clients/admin-ui/src/features/custom-fields/CustomFieldsTable.tsx, clients/admin-ui/src/features/privacy-notices/PrivacyNoticesTable.tsx
Part of https://github.com/ethyca/fides/issues/3127
* Run fidesplus backend with `npm run dev` admin ui
* Add some custom fields either through the edit system form or by editing a taxonomy entry
* Click on a row in the table
* The modal should come up with the name of the field
* Privacy notices table still works
https://user-images.githubusercontent.com/24641006/234064811-087c0b5b-48e5-4da9-8c63-7ef52eebfc24.mov
=> Custom fields table enhancements

clients/admin-ui/src/features/common/table/FidesTable.tsx, clients/admin-ui/src/features/custom-fields/CustomFieldsTable.tsx, clients/admin-ui/src/features/custom-fields/cells.tsx, clients/admin-ui/src/features/plus/plus.slice.ts
Closes https://github.com/ethyca/fides/issues/3127
* Run fidesplus backend with `npm run dev` in admin-ui for the front end
* Add some custom fields either through the edit system form or by editing a taxonomy entry
* You should now see a kebob menu on the right hand side of the table
* Clicking on the menu then "edit" should bring up the edit modal
* Clicking on the menu then "delete" should bring up a confirmation modal
* Confirming should delete the custom field
https://user-images.githubusercontent.com/24641006/234098530-d6093f0a-6aa6-459e-94e7-52951e4f7149.mov
=> Custom fields kebob menu for more actions

CHANGELOG.md, clients/admin-ui/src/features/datastore-connections/add-connection/forms/ConnectorParametersForm.tsx
Closes #3141
We key off of the type names to determine if we should convert a dataset reference string into a dataset reference object. The type in the front-end no longer matched the type in the backend.
=> Updating dataset reference type name

src/fides/api/ctl/migrations/versions/48d9caacebd4_create_privacy_declarations_table.py, src/fides/api/ctl/sql_models.py, src/fides/data/sample_project/sample_resources/sample_systems.yml
follow up to  https://github.com/ethyca/fides/pull/3098
per conversation with @NevilleS we're actually trying to move away from relying on the `name` property, so we shouldn't require it on the BE, even if we do want to use it as part of the uniqueness criteria.
i decided to update the migration in-place since the original PR was merged _minutes_ ago...are we OK with that??
=> make name not required on privacy declaration

CHANGELOG.md, src/fides/api/ctl/migrations/versions/5b03859e51b5_update_custom_field_resource_type_enum.py, src/fides/api/ctl/sql_models.py
❗ Contains migration; check downrev before merge
partially closes #3037 
there will need to be some follow up changes on the fidesplus API side to make this fully work, but these are the necessary updates in `fides`
* update sqlalchemy and DB `resource_type` enum for `CustomFieldDefinition` and `CustomField` tables/models to allow `privacy_declaration` as a value
* include a migration for this change. migration downgrade path has to remove any records (`CustomField`s and `CustomFieldDefinition`s) that have the `privacy_declaration` as their `resource_type`
* The only real testing we can do on this PR specifically would be around the migrations.
* I tested locally that migrating from a previous app state successfully added the `privacy_declaration` value to the `resourcetypes` enum
* …
=> 3037 support privacy declaration resource type for custom fields

CHANGELOG.md, src/fides/api/ctl/routes/crud.py, src/fides/api/ctl/routes/system.py, src/fides/api/ctl/schemas/system.py, tests/ctl/core/test_api.py
Closes https://github.com/ethyca/fideslang/issues/102
Adds an `id` field on the `privacy_declaration`s embedded objects returned in `system` APIs.
* extend our base pydantic models defined in `fideslang` with response-specific models that include `PrivacyDeclaration.id` fields in the response objects
* update tests to work and also confirm the `id` field is present in the response
* made some manual API calls against the `GET /api/v1/system` endpoint and confirmed the field was present. sample response from my local:
```
{
"fides_key": "test_system_1",
"organization_fides_key": "default_organization",
"tags": [],
"name": "test system 1",
"description": "",
"registry_id": null,
"meta": null,
"fidesctl_meta": null,
"system_type": "",
"data_responsibility_title": "Controller",
"egress": …
```
=> include 'id' on embedded privacy_declaration objects in system API responses

CHANGELOG.md, clients/admin-ui/src/features/datamap/GetStarted.tsx
Closes #3163
*  Fix typo found in #3163
*  Replace side remark delimiters with two em-dashes 
* View blank data map page
=> #3163 - Fix Typo in Admin UI

CHANGELOG.md, src/fides/api/ctl/sql_models.py, src/fides/api/ops/models/policy.py, src/fides/api/ops/models/privacy_notice.py, tests/fixtures/application_fixtures.py, tests/ops/conftest.py, tests/ops/models/test_privacy_notice.py
Closes #3154 
Context: https://github.com/ethyca/fides/pull/3120#discussion_r1175579109
Adding additional checks here to confirm sibling or nephew relationships are allowed in the hierarchy.  I thought this didn't work but the starts with check does handle these use cases so adding further tests here.
=> [Backend] More Privacy Notice Data Use Validation Checks

src/fides/connectors/aws.py
Found in manual testing by @allisonking 
Closes n/a
* provide empty list `privacy_declarations` arg in system scan code path, since it's required on the `fideslang.models.System` constructor
per @allisonking:
- run backend test env (either fides or fidesplus should work fine)
- go to localhost:8080
- click “add systems”
- click “Scan your infrastructure (aws)”
- fill out creds for aws using 1 passsword creds and region US East (ohio)
- you’ll see the error
this had been accidentally and unnecessarily removed in https://github.com/ethyca/fides/pull/3098/files#diff-c51150e13179fe1dfbba78397ad111ecd1a30909814fca4b4898715185dfb9faL253
=> patch privacy declarations system scan bug

CHANGELOG.md, src/fides/api/ctl/database/crud.py, src/fides/core/export.py, src/fides/core/export_helpers.py, tests/ctl/database/test_crud.py
partially closes https://github.com/ethyca/fidesplus/issues/821
‼️  should be cherry-picked into `2.12.0` release branch after merging into `main`
* include a filtered, bulk custom field retrieval method that allows us to get all of our custom fields in a single db query
* this should remove one of the n+1 query patterns we have in this code path (there is still at least one more to retrieve our  resources initially)
* in refactoring, i also made sure we retrieve the custom fields on privacy declarations 
* update our export code to add the new `privacy_declaration` custom field data to the export table
* fix a bug in the export code that added `data_use` and `data_subject` custom fields to the column header row, but did not populate their values in the data rows, which led to offset …
=> fides support for privacy declarations in datamap export

CHANGELOG.md, src/fides/api/ctl/routes/system.py, tests/conftest.py, tests/ctl/core/test_api.py
Closes #3187 
* change privacy declaration upsert logic used by `/system` APIs to update `PrivacyDeclaration` records in place when "matched" using `data_use` and `name` as matching criteria
* add in BE validation to prevent a request from specifying "duplicate" `PrivacyDeclaration`s based on the above matching criteria
* this validation is now important on the BE since our upsert logic now relies on this assumption being true
* add automated test coverage around this use cases
* there may still be some edge cases we need to cover here...
* i did some testing in the UI with these changes, while checking the DB records, and things generally looked good. but would appreciate others hitting this hard with the API and with the UI
* NOTE - as of now, if you change the "data use" or the …
=> refactor privacy declaration upsert to maintain constant IDs

src/fides/core/export.py
Closes n/a
‼️ should be cherry-picked into 2.12.0 release branch
Prevent datamap export from having duplicate privacy_declaration custom field columns when >1 privacy declaration on a given system has a custom field
- check if a "privacy declaration" column key exists in our running list of keys before inserting again
We believe this is responsible for the 500 coming back from the datamap export API as seen on our staging env in 2.12.0 rc testing
=> prevent duplicate privacy declaration custom field column headers

docs/fides/docs/development/releases.md
When smoke testing fides you need to make sure you're using a fresh virtual env. If not, you'll likely get an issue like:
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /opt/homebrew/lib/python3.10/site-packages/fides/data/sample_project/privacy_center/config
```
Context here: https://ethyca.slack.com/archives/CBKK8TS74/p1681757808038059?thread_ts=1681741284.094189&cid=CBKK8TS74
Note that I did have a virtual env activated but it was an old one.  I've also gotten this issue when I had a global version installed that interfered.
=> Release Checklist Update Post 2.12.0

CHANGELOG.md, src/fides/core/export.py
‼️ This should be hotfixed for `2.12.1`
Closes https://github.com/ethyca/fidesplus/issues/858
* treat defunct `data_use` or `data_subject` references from a privacy (data use) declaration as empty rows in the datamap export
* ensure at least one "placeholder" system row is returned if no rows are produced from declarations
- requires integration with fidesplus to properly test (will be a corresponding PR there with increased test coverage)
A broader improvement around taxonomy element deletion is covered in https://github.com/ethyca/fides/issues/3119.
=> handle deleted taxonomy elements in datamap export

clients/admin-ui/src/features/datamap/Datamap.tsx, clients/admin-ui/src/features/datamap/SettingsBar.tsx, clients/admin-ui/src/features/datamap/datamap.slice.ts
=> Hotfix - merge cached datamap settings with new data

CHANGELOG.md, src/fides/api/ctl/database/crud.py, tests/ctl/database/test_crud.py
Partially closes https://github.com/ethyca/fidesplus/issues/866
* include check on `CustomFieldDefinition.active` property in bulk query for custom fields
* improve test coverage for this requirement
* requires fidesplus for manual testing
Found when testing for `2.12.1` hotfix. Let's try to get this in the hotfix!
=> check CustomFieldDefinition.active with custom fields bulk query

src/fides/api/ctl/database/seed.py, src/fides/api/ops/api/deps.py, src/fides/api/ops/api/v1/endpoints/oauth_endpoints.py, src/fides/api/ops/api/v1/endpoints/privacy_request_endpoints.py, src/fides/api/ops/api/v1/urn_registry.py, src/fides/api/ops/models/connectionconfig.py, src/fides/api/ops/models/datasetconfig.py, src/fides/api/ops/models/messaging.py, src/fides/api/ops/service/connectors/fides_connector.py, src/fides/api/ops/service/messaging/message_dispatch_service.py, src/fides/api/ops/service/messaging/messaging_crud_service.py, tests/ops/api/v1/endpoints/test_user_permission_endpoints.py
[Changes around type hints. Previously several models were importing from their models from a mixture of fides.lib.db.base import Base or from fides.lib.db.base_class import Base. Now that we're importing models from src/fides/api/ops/db/base_class.py, there were some type issues that surfaced.
MessagingConfig and ConnectionConfig were some of the models that imported from a different location than the other models
=> Lib -> Ops Type Hinting Fixes

CHANGELOG.md, src/fides/api/ctl/database/session.py, src/fides/api/ctl/migrations/versions/15a3e7483249_make_customfielddefinition_uniqueness_.py, src/fides/api/ctl/sql_models.py, tests/ctl/core/test_custom_field_models.py
Partially closes https://github.com/ethyca/fidesplus/issues/826
* create the proper unique (functional) index for the uniqueness criteria
* include a migration that "handles" (i.e. reports with a cleaner error message) potentially invalid data on migration
* migration also has some small unrelated cleanup on `plus_custom_field_definition` table since we're touching it
* put in some more graceful handling of the unique constraint in the sqlalchemy model class
* add in some test coverage directly on the sqlalchemy model
* any manual testing here would require hitting the DB directly
* manual testing at the API level will come in corresponding `fidesplus` [PR](https://github.com/ethyca/fidesplus/pull/862) that has the API which exposes this model
We'll now ensure custom …
=> update custom field definition uniqueness criteria

clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts, clients/admin-ui/cypress/e2e/privacy-notices.cy.ts, clients/admin-ui/cypress/fixtures/privacy-notices/notice_only.json, clients/admin-ui/cypress/fixtures/privacy-notices/opt_in.json, clients/admin-ui/cypress/fixtures/privacy-notices/opt_out.json, clients/admin-ui/cypress/support/stubs.ts, clients/admin-ui/src/features/common/form/FormSection.tsx, clients/admin-ui/src/features/privacy-experience/form/BannerActionForm.tsx, clients/admin-ui/src/features/privacy-experience/form/BannerTextForm.tsx, clients/admin-ui/src/features/privacy-experience/form/DeliveryMechanismForm.tsx, clients/admin-ui/src/features/privacy-experience/form/PrivacyCenterMessagingForm.tsx, clients/admin-ui/src/features/privacy-experience/form/PrivacyExperienceForm.tsx, clients/admin-ui/src/features/privacy-experience/form/helpers.tsx, clients/admin-ui/src/features/privacy-experience/privacy-experience.slice.ts, clients/admin-ui/src/pages/consent/privacy-experience/[id].tsx, clients/admin-ui/src/pages/consent/privacy-experience/index.tsx, clients/admin-ui/src/types/api/index.ts, clients/admin-ui/src/types/api/models/PrivacyExperienceCreate.ts, clients/admin-ui/src/types/api/models/PrivacyExperienceResponse.ts, clients/admin-ui/src/types/api/models/PrivacyExperienceWithId.ts
Closes https://github.com/ethyca/fides/issues/3126
* Same setup as described in https://github.com/ethyca/fides/pull/3186
* Click into one of the experiences
* You should be able to fill out the form and persist the data 
https://www.loom.com/share/556bc39d3f6b4f7ca50a4c2cef14929a
https://user-images.githubusercontent.com/24641006/236256514-8be4a0c7-e771-4719-bb93-9ce28ef5571b.mov
=> Privacy experience form

CHANGELOG.md, src/fides/cli/commands/export.py
partially closes https://github.com/ethyca/fidesplus/issues/879
* add deprecation flag to `fides export` CLI command
Initially we were going to remove the command [wholesale](https://github.com/ethyca/fides/pull/3256). That PR can stay open for another release or two as we allow the command to be "phased out" more smoothly by being marked as deprecated. The `fides export` command in `fidesplus` will be able to override this deprecated command here and use all the code in `fidesplus`. This code should be effectively frozen until it is officially removed and phased out in the near future: https://github.com/ethyca/fides/issues/3265
=> mark 'export' CLI command as deprecated

src/fides/data/sample_project/privacy_center/config/config.css, src/fides/data/sample_project/privacy_center/config/config.json
=> Fix Cookie House Privacy Center styles for `fides deploy`

CHANGELOG.md, src/fides/api/ops/tasks/__init__.py
Closes #3204 
This logging is done on the "main path" of the code, at time of import, which means that it muddies the output of the CLI which isn't a great user-experience.
This is easily the lowest-friction method of solving this issue. Otherwise, a full rework of the module's imports would have to be done.
=> Remove logging from Celery app creation

src/fides/api/ops/service/connectors/dynamodb_connector.py, src/fides/api/ops/task/graph_task.py, src/fides/data/sample_project/fides.toml, tests/ops/service/privacy_request/test_request_runner_service.py
On further testing the DynamoDB connector this afternoon I was finding the following errors in the logs:
```
2023-05-12 22:08:37.130 [INFO] (graph_task:pre_process_input_data:327): Consolidating incoming data into dynamodb_example_test_dataset:login from __ROOT__:__ROOT__.
2023-05-12 22:08:37.130 [INFO] (graph_task:pre_process_input_data:327): Consolidating incoming data into dynamodb_example_test_dataset:login from dynamodb_example_test_dataset:customer_identifier.
Traceback (most recent call last):
File "/usr/local/lib/python3.10/site-packages/fides/api/ops/task/graph_task.py", line 92, in result
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/site-packages/fides/api/ops/task/graph_task.py", line 529, in access_request
output: List[Row] = self.connector.retrieve_data(
File …
```
=> Handle edge case where no attributes are defined

CHANGELOG.md, src/fides/api/ops/models/privacy_request.py
This PR gets `main` back up to date with `release-2.13.0` — the reasons we're not merging that release PR itself are:
- cherry-picked commits can get funky when merged back into the original branch
- if we delete the release branch after squash-merging, the release tag will go away
=> transfer  changes to `main` without merging the release PR

.fides/db_dataset.yml, docs/fides/docs/development/postman/Fides.postman_collection.json, src/fides/api/ctl/migrations/versions/2661f31daffb_track_experience_on_preferences.py, src/fides/api/ctl/migrations/versions/498dbe8af963_store_experience_on_historical_.py, src/fides/api/ops/api/v1/endpoints/privacy_experience_endpoints.py, src/fides/api/ops/api/v1/endpoints/privacy_notice_endpoints.py, src/fides/api/ops/api/v1/endpoints/privacy_preference_endpoints.py, src/fides/api/ops/models/privacy_experience.py, src/fides/api/ops/models/privacy_preference.py, src/fides/api/ops/schemas/privacy_preference.py, tests/conftest.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_privacy_preference_endpoints.py, tests/ops/models/test_privacy_preference.py
❗ Contains migration
❗ Dependent on #3292 
Closes #3133 
Closes #3196 
Start tracking additional fields when saving consent preferences to demonstrate compliance and move some of the existing fields from the request body to extract from request headers.
Start tracking new fields:
- `PrivacyPreferenceHistory.anonymized_ip_address` which is really a truncated version of the ip address and stored encrypted
- `PrivacyPreferenceHistory.method` - The method of consent preference in a modal (buttons, individual notices)
- `PrivacyPreferenceHistory.privacy_experience_config_history_id` - the particular version of the Config that surfaced the notice (contains the copy)
- `PrivacyPreferenceHistory.privacy_experience_history_id` - the particular Experience - contains the region, type, and delivery …
=> [Backend] Track Privacy Experience that surfaced Notices/ Pull data from request headers

clients/privacy-center/app/server-environment.ts, clients/privacy-center/pages/api/fides-js.ts
Closes https://github.com/ethyca/fides/issues/3332
```
process.env.FIDES_PRIVACY_CENTER__DEBUG,
process.env.FIDES_PRIVACY_CENTER__IS_OVERLAY_DISABLED,
process.env.FIDES_PRIVACY_CENTER__IS_GEOLOCATION_ENABLED,
process.env.FIDES_PRIVACY_CENTER__GEOLOCATION_API_URL,
process.env.FIDES_PRIVACY_CENTER__PRIVACY_CENTER_URL
```
=> put global settings for fides.js on privacy center settings

CHANGELOG.md, clients/privacy-center/cypress/e2e/consent-banner.cy.ts
Closes https://github.com/ethyca/fides/issues/3049
No core code changes, only tests added. If you wish to test, you'll have to look at console logs for now (until we get full stack working with real experience API calls):
=> 3260 Adds ability for fides.js to fetch its own geolocation

.github/workflows/publish_package.yaml, CHANGELOG.md, noxfiles/git_nox.py
partially closes #2919 
related to https://github.com/ethyca/fidesplus/pull/892
* event will be used to trigger a build of an integrated image using the version of `fides` that was just tagged
This is the `fides` side change that allows to automatically trigger, on feature tags, a build of an integrated image using the version of `fides` that was just tagged
=> feature branch builds, ci automation

.github/workflows/publish_package.yaml
Closes n/a
I noticed that our "feature-tag" dispatch event, created to trigger integrated pre-release builds in `fidesplus` based on feature tags in `fides`, was a bit too trigger-happy. every commit to `main` was sending a [dispatch event](https://github.com/ethyca/fides/actions/runs/5079806741/jobs/9125995673#step:13:3) to `fidesplus` and triggering an [unexpected and unintended build action](https://github.com/ethyca/fidesplus/actions/runs/5080008359/jobs/9126441662#step:5:1) on `fidesplus` that would inevitably fail.
A minor DX cleanup to avoid unnecessary build actions that inevitably fail.
=> filter out untagged main commits from feature-tag dispatch event

CHANGELOG.md
Closes n/a
* cosmetic change to changelog since audit log update is going in `2.14.0`
=> changelog: move audit log item to 2.14.0 section

CHANGELOG.md
Closes n/a
Final pass thru the changelog comparing directly to diff between `2.14.0rc3` and `2.13.0`: https://github.com/ethyca/fides/compare/2.13.0...2.14.0rc3
A few things accidentally had slid into `2.13.0` and some others just had been omitted - i made a judgement call what's worth including!
=> final pass on 2.14.0 changelog

CHANGELOG.md, clients/sample-app/Dockerfile, clients/sample-app/docker-compose.yml
This is a tiny fix for a slip-up in https://github.com/ethyca/fides/pull/2949 where I added support for two different styles of ENV vars to configure the sample app:
* `FIDES_SAMPLE_APP__DATABASE_*` (prefixed, for clarity & consistency)
* `DATABASE_*` (unprefixed, for backwards-compatibility)
Turns out I accidentally didn't support the backwards-compat version since the Dockerfile was surprisingly setting those prefixed ENV vars all the time... whoops!
=> Fix sample app `DATABASE_*` ENV vars for backwards compatibility

CHANGELOG.md, clients/fides-js/src/fides.ts, clients/fides-js/src/lib/consent-types.ts, clients/fides-js/src/lib/consent.tsx, clients/privacy-center/app/server-environment.ts, clients/privacy-center/pages/api/fides-js.ts, clients/privacy-center/public/fides-js-components-demo.html
Closes #3293 
Notice how `document.body` contains a `div` with `id="__next"` and a few other things...
Notice how `document.body` no longer has the Next root and instead we've replaced it with our own `div` with `id="fides-js-root"`
This fixes a rendering issue I ran into when doing some E2E testing locally. I can't pinpoint exactly why this is fundamentally required because in our testing of "simpler" pages like the static HTML demo page we use, this doesn't seem to happen - I think it must be an interaction between the NextJS VDOM and our own.
This just defensively adds a parent element to the `document.body` where we insert our root node to keep it away from thrashing with other running React apps, etc.
=> Fix overlay rendering issue by finding/creating a dedicated parent element for Preact

CHANGELOG.md, clients/sample-app/src/components/Home/index.tsx, clients/sample-app/src/components/Home/style.module.scss, clients/sample-app/src/pages/index.tsx
Tiny polish fix for the Cookie House link!
=> Fix the sample app privacy center link to be configurable

.github/workflows/backend_checks.yml, CHANGELOG.md, requirements.txt, src/fides/cli/__init__.py
Closes #3433 
Quick fix here, suppressing the warning as specifically as possible so that we can still see other warnings come through.
We've been out-of-range for this requirement for a long time but it doesn't seem to matter, it just started showing up in the CLI though which means we probably moved some imports around
=> Fix Snowflake Sqlalchemy warning on CLI usage

clients/fides-js/src/components/ConsentBanner.tsx, clients/fides-js/src/lib/overlay.module.css, clients/privacy-center/cypress/e2e/consent-banner.cy.ts, clients/privacy-center/public/fides-js-components-demo.html
Closes https://github.com/ethyca/fides/issues/3424
Mocks:
This PR:
=> 3424 styling for banner

docs/fides/docs/development/releases.md, noxfiles/git_nox.py
some minor cleanup of release related items i noticed during the 2.14.0 release process.
note @NevilleS  and @daveqnet  - this includes the updates to the release description that we discussed post-2.14.0 release. please let me know how those look to you.
=> release-related cleanup based on 2.14.0 release

CHANGELOG.md, clients/sample-app/src/components/GeolocationSelect/index.tsx, clients/sample-app/src/pages/_document.tsx, clients/sample-app/src/pages/index.tsx, clients/sample-app/src/pages/landing.tsx
Closes #3437 
This fixes a few lingering NextJS warnings that we've been ignoring for how we include external scripts, stylesheets, etc. In doing so, we also fix #3437 which was messing up the rendering of our banner 👍
=> Fix NextJS errors & warnings for Cookie House sample app

CHANGELOG.md, clients/fides-js/src/fides.ts, clients/fides-js/src/integrations/gtm.ts, clients/fides-js/src/integrations/meta.ts, clients/fides-js/src/integrations/shopify.ts, clients/fides-js/src/lib/events.ts, clients/fides-js/src/lib/preferences.ts, clients/privacy-center/cypress/e2e/consent-banner.cy.ts, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/cypress/support/commands.ts, clients/privacy-center/public/fides-js-components-demo.html, clients/privacy-center/public/fides-js-demo.html, clients/sample-app/src/components/Home/index.tsx, clients/sample-app/src/pages/index.tsx
Closes #3350 
Closes #3348
This exposes two new custom events on the `window` object to allow a user to listen for Fides.js lifecycle events and integrate consent state changes into their own custom Javascript handling. This is needed now that we allow preferences to change at runtime via the banner/modal components!
For example, you might integrate Fides.js into your website like:
```
<script src="privacy.example.com.fides.js" />
<script>
window.addEventListener("FidesUpdated", (event) => {
if (event.detail.consent.data_sales_and_sharing) {
// enable data sales code
}
});
</script>
```
This PR also updates the `Fides.gtm()` integration to listen to the same lifecycle events and cross-publish them to GTM. This ensures GTM stays up to date if consent preferences are …
=> Dispatch Fides.js lifecycle events on window (FidesInitialized, FidesUpdated) and cross-publish to Fides.gtm() integration

clients/fides-js/src/components/ConsentBanner.tsx, clients/fides-js/src/components/fides.css, clients/privacy-center/cypress/e2e/consent-banner.cy.ts, clients/privacy-center/public/fides-js-components-demo.html, clients/privacy-center/public/fides-js-demo.html
Closes https://github.com/ethyca/fides/issues/3444
* Spin up the privacy center and visit `localhost:3000/fides-js-demo.html` and resize your browser
https://github.com/ethyca/fides/assets/24641006/f25e157a-f819-478f-b192-af28fc818c55
=> Responsive banner

.fides/db_dataset.yml, CHANGELOG.md, docs/fides/docs/development/postman/Fides.postman_collection.json, src/fides/api/api/v1/endpoints/privacy_experience_endpoints.py, src/fides/api/api/v1/endpoints/privacy_preference_endpoints.py, src/fides/api/ctl/migrations/versions/317e6197c76a_reduce_experience_and_config_duplication.py, src/fides/api/db/base.py, src/fides/api/models/privacy_experience.py, src/fides/api/models/privacy_preference.py, src/fides/api/schemas/privacy_experience.py, src/fides/api/schemas/privacy_preference.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_privacy_experience_config_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_experience_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_notice_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_preference_endpoints.py, tests/ops/models/test_privacy_experience.py
Closes #3465 
❗ Contains data migration; check downrev before merge
Continue to deduplicate info between PrivacyExperience and PrivacyExperienceConfig.
- Remove common fields between the models like PrivacyExperience.disabled and PrivacyExperience.experience_config_history_id - these are at risk of getting out of sync
- Now that we've removed most of the fields from PrivacyExperience and it is largely just a linking table, I don't think we need to version this. Remove PrivacyExperience.version, and the entire PrivacyExperienceHistory table.
- PrivacyPreferenceHistory was referencing the PrivacyExperienceHistory id, but now that this doesn't exist, have it reference the PrivacyExperience id instead.
- When filtering PrivacyExperiences on disabled, actually filter the corresponding field on …
=> [Backend] Further Deduplicate PrivacyExperience and PrivacyExperienceConfig 

.github/workflows/backend_checks.yml, CHANGELOG.md, Dockerfile
This allows for the resulting container to be run by non-root users.
My only reasoning for this is that it was an attempt to keep from polluting/conflicting-with the system Python.
A `venv` is just as good at this, but can also be used by non-root users!
=> Dockerfile: Do not pip install --user, venv instead

clients/fides-js/src/components/fides.css
Fixes bug reported by @eastandwestwind https://www.loom.com/share/566b70db1ca345d0a133bad689ff05a8
* Pull up the demo site
* Banner should come up. Click the reject all button. Banner should completely hide
=> Fix banner transform

clients/admin-ui/src/types/api/models/ConsentReport.ts, clients/admin-ui/src/types/api/models/ConsentReportingSchema.ts, clients/admin-ui/src/types/api/models/ExperienceConfigCreate.ts, clients/admin-ui/src/types/api/models/ExperienceConfigResponse.ts, clients/admin-ui/src/types/api/models/ExperienceConfigUpdate.ts, clients/admin-ui/src/types/api/models/PrivacyExperienceResponse.ts, clients/admin-ui/src/types/api/models/PrivacyNoticeRegion.ts, clients/admin-ui/src/types/api/models/PrivacyPreferencesRequest.ts, clients/fides-js/src/components/Overlay.tsx, clients/fides-js/src/fides.ts, clients/fides-js/src/lib/consent-types.ts, clients/fides-js/src/lib/preferences.ts, clients/privacy-center/components/consent/NoticeDrivenConsent.tsx, clients/privacy-center/cypress/e2e/consent-banner.cy.ts, clients/privacy-center/cypress/e2e/consent-notices.cy.ts, clients/privacy-center/cypress/fixtures/consent/experience.json, clients/privacy-center/cypress/fixtures/consent/overlay_experience.json, clients/privacy-center/cypress/fixtures/consent/test_banner_options.json, clients/privacy-center/public/fides-js-components-demo.html, clients/privacy-center/types/api/models/ExperienceConfigResponse.ts, clients/privacy-center/types/api/models/PrivacyExperienceResponse.ts, clients/privacy-center/types/api/models/PrivacyNoticeRegion.ts, clients/privacy-center/types/api/models/PrivacyPreferencesRequest.ts
Closes https://github.com/ethyca/fides/issues/3472
* Saving your consent still works!
=> Frontend experience id swap

noxfiles/docker_nox.py, noxfiles/git_nox.py, noxfiles/test_git_nox.py
Closes n/a (reported by @NevilleS in slack)
* unrelated to the above problems, but i happened to notice was causing red-herring failures in our GH actions on `main`: https://github.com/ethyca/fides/actions/runs/5192945794/jobs/9362813520
A couple of tagging improvements to handle edge cases, and a (basically unrelated) QOL improvement for our CI actions that i happened to notice.
=> fix up tagging utility

clients/fides-js/src/lib/consent-utils.ts, clients/privacy-center/cypress/e2e/consent-banner.cy.ts
Closes https://github.com/ethyca/fides/issues/3485
=> Fix consent-banner cypress tests

CHANGELOG.md, clients/fides-js/src/components/fides.css, clients/fides-js/src/lib/consent.tsx
Closes https://github.com/ethyca/fides/issues/3309
The bulk of the a11y work was done while developing, but this should cover the straggling items.
* Bring up either cookie house or `fides-js-components-demo.html`
* As a keyboard user, tab into the page. You should immediately be tabbing through the banner (before, you'd have to tab through the whole page before getting to the banner. this is far more noticeable on cookie house than the demo page)
* Close the banner. Tab through the page. You should be able to tab through without issue (before, there would be a few tabs where it looked like nothing was happening, since it was tabbing through the hidden banner)
I went through a few sites, and I don't think there's actual regulation on where a banner should appear in a tab …
=> Fides-js accessibility wrap up

CHANGELOG.md, clients/fides-js/src/components/ConsentBanner.tsx, clients/fides-js/src/components/ConsentModal.tsx, clients/fides-js/src/components/Overlay.tsx, clients/privacy-center/cypress/e2e/consent-banner.cy.ts
Closes https://github.com/ethyca/fides/issues/3514
* See repro steps in the original ticket
Incidentally, I believe this is a regression after we incorporated the a11y-dialog library. Before, we were unmounting the Modal when we hid it. The library hides the modal instead, so the component doesn't unmount. However, we had some logic [which checked the window object in the modal](https://github.com/ethyca/fides/blob/main/clients/fides-js/src/components/ConsentModal.tsx#L32-L38) and set the toggle states that way. That bit of logic doesn't retrigger since the component doesn't mount again, so it becomes stale.
Now that we are only hiding the component, we have to be a little more careful with how we control the state. I think this way makes a bit more intuitive sense, or at …
=> Fix bug where modal does not reflect draft state

noxfiles/docker_nox.py, noxfiles/test_docker_nox.py
Closes #3422 
I thought about adding an additional parameter to build each one separately, i.e. `nox -s "push(git-tag, fides)" "push(git-tag, sample)"` etc. but felt this would also add additional complication to the CI workflows. I also couldn't think of a case where we _wouldn't_ want to build everything at once, so this seemed like the lowest-friction solution.
=> Parallelize Docker Publishing

src/fides/api/ctl/migrations/versions/5307999c0dac_remove_deprecated_data_uses_for_.py
Closes #3515 
Quick PR to remove the "old" default data uses in favor of the new ones
=> Remove Deprecated Data Uses

CHANGELOG.md, clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx
In #3432 we _reintroduced_ the ability to collect multiple identity inputs on consent requests, which reversed most of the changes in #2539
However, even though #3432 restored the ability to collect both email & phone, it didn't remove the form validation, so if you tried to type in both the email & phone fields they would still disable each other!
For example, this screenshot shows where I've typed in the email field, but the phone number field then gets disabled:
This change just removes that `isDisabled` logic to allow both fields to be populated simultaneously.
=> Remove form validation to allow both email & phone inputs for consent requests

CHANGELOG.md, clients/fides-js/src/components/Overlay.tsx, clients/fides-js/src/lib/consent.tsx
Closes https://github.com/ethyca/fides/issues/3483, closes https://github.com/ethyca/fides/issues/3488
=> Fix race condition with link rendering

clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParameters.tsx
Closes #3534 
Each of the schemas for the email connector secrets define a default value for the advanced settings, we don't need to use this front-end placeholder anymore.
=> Removing the stubbed advanced settings

src/fides/api/models/privacy_request.py, src/fides/api/schemas/privacy_request.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_consent_request_endpoints.py
This PR adds extra tests for the consent reporting API, including anonymous requests, use more detailed identity schemas in responses.
=> Reporting for anonymous consent requests

CHANGELOG.md, clients/admin-ui/src/features/datastore-connections/system_portal_config/ConnectionForm.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/ConnectionListDropdown.tsx
Closes #3535 
Updated the ConnectionListDropdown to be disabled when a connectionConfig is saved. 
=> disable connector dropdown in integration tab on save

CHANGELOG.md, data/saas/config/kustomer_config.yml, tests/fixtures/saas/kustomer_fixtures.py, tests/ops/integration_tests/saas/test_kustomer_task.py
Closes #tbd
Originally I was looking at writing an override that would only pass when the specific 404 was encountered, but opted for `ignore_errors` - open to further discussion here!
=> Ignore Errors For Non-existent identities - Kustomer

CHANGELOG.md, clients/fides-js/src/components/ConsentBanner.tsx, clients/fides-js/src/components/ConsentButtons.tsx, clients/fides-js/src/components/ConsentModal.tsx, clients/fides-js/src/components/NoticeToggles.tsx, clients/fides-js/src/components/Overlay.tsx, clients/fides-js/src/components/Toggle.tsx, clients/fides-js/src/components/fides.css, clients/fides-js/src/lib/consent-value.ts, clients/fides-js/src/lib/cookie.ts, clients/privacy-center/components/consent/ConsentItem.tsx, clients/privacy-center/components/consent/NoticeDrivenConsent.tsx, clients/privacy-center/cypress/e2e/consent-banner.cy.ts, clients/privacy-center/cypress/e2e/consent-notices.cy.ts, clients/privacy-center/cypress/fixtures/consent/experience.json, clients/privacy-center/cypress/fixtures/consent/test_banner_options.json, clients/privacy-center/public/fides-js-components-demo.html
Closes https://github.com/ethyca/fides/issues/3443
* Edit your `fides-js-demo-components.html` such that both notices are `notice_only` and have a default preference of `opt_in` (which all `notice_only` notices should have)
* `turbo dev` in the `fides-js` folder and visit http://localhost:3000/fides-js-components-demo.html
* You should see the banner render "OK" instead of accept/reject
* Click the modal link to view the notice-only notices which can't be toggled off. You should also see "OK" here instead of the 3 buttons
* Clicking "OK" should send an acknowledge preference
* Visit localhost:3000. You'll need to populate your notices with notice only ones. You should see the radio button becomes disabled
When only one notice is notice-only
Privacy center if we make a …
=> Notice only rendering

CHANGELOG.md, clients/admin-ui/src/features/common/custom-fields/CustomFieldsList.tsx
Closes #3545 
Updated custom fields list to check a field is created before showing
=> hide custom fields section when there are no custom fields created

.github/workflows/publish_docker.yaml, .github/workflows/publish_package.yaml
This PR updates the GH Actions `set-output` function to the new method of using the env var `$GITHUB_OUTPUT`
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Old style: `echo "::set-output name={name}::{value}"`
New style: `echo "{name}={value}" >> $GITHUB_OUTPUT` 
Closes #3531 
=> Update to new GitHub Actions Output Function - #3531 

CHANGELOG.md, clients/admin-ui/cypress/e2e/home.cy.ts, clients/admin-ui/src/home/constants.ts, clients/admin-ui/src/home/tile-config.test.ts, clients/cypress-e2e/cypress/e2e/smoke_test.cy.ts
Closes #3536 
delete the configure privacy request tile 
=> remove the configure privacy request tile from the home screen

CHANGELOG.md
Closes N/A
I cherry-picked https://github.com/ethyca/fides/pull/3512/commits/53d285ca2263f69764ea01ac77c8a4ec53c3eaec into https://github.com/ethyca/fides/pull/3512 but its changelog item was wrong since it unexpectedly made it into the release. I updated the changelog on the release branch, but also updating it here so that it makes it into main
=> Update changelog item which went into release

CHANGELOG.md, clients/fides-js/src/components/Overlay.tsx
Closes https://github.com/ethyca/fides/issues/3596
* See repro steps in the ticket
I tried adding a test case but had a hard time reproducing it in Cypress. I'll give it a shot in the E2E regression test
=> Initialize based on cookie instead of window

CHANGELOG.md, src/fides/api/api/v1/endpoints/connection_endpoints.py, src/fides/api/api/v1/endpoints/dataset_endpoints.py, src/fides/api/api/v1/endpoints/privacy_experience_config_endpoints.py, src/fides/api/api/v1/endpoints/privacy_experience_endpoints.py, src/fides/api/api/v1/endpoints/privacy_notice_endpoints.py, src/fides/api/api/v1/endpoints/utils.py, src/fides/api/models/datasetconfig.py, src/fides/api/schemas/privacy_experience.py, src/fides/api/util/consent_util.py, src/fides/api/util/data_category.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_connection_config_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_experience_config_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_experience_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_notice_endpoints.py, tests/ops/service/privacy_request/test_email_batch_send.py, tests/ops/util/test_consent_util.py
Closes #3301 
Strings that are escaped on ExperienceConfigs are currently surfaced in their escaped form.
=> [Backend] Remove Automatic SafeStr serialization from PrivacyExperienceConfig.

CHANGELOG.md, requirements.txt
Closes #3613 
See issue description for a synopsis of why this is just now biting us, it's been lurking for a while!
=> update to latest `asyncpg` dependency

CHANGELOG.md, src/fides/api/util/consent_util.py, tests/ops/util/test_consent_util.py
Closes #3604 
Only create default experience configs on startup - don't update existing ones.
=> Don't update default experience configs on startup - only create them.

CHANGELOG.md, clients/admin-ui/cypress/e2e/systems.cy.ts, clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationManager.tsx
Closes https://github.com/ethyca/fides/issues/3619
* See steps in issue
=> Fix bug with saving an edited declaration

CHANGELOG.md, src/fides/api/api/v1/endpoints/privacy_preference_endpoints.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_privacy_preference_endpoints.py
Closes #3618 
PATCH {{host}}/privacy-preferences
```
{
"browser_identity": {
"ga_client_id": "UA-XXXXXXXXX",
"ljt_readerID": "test_sovrn_id",
"fides_user_device_id": "<uuid4 here>"
},
"preferences": [{
"privacy_notice_history_id": "{{privacy_notice_history_id}}",
"preference": "opt_out"
}],
"user_geography": "us_ca",
"privacy_experience_id": "{{privacy_experience_id}}",
"method": "button"
}
```
PATCH {{host}}/privacy-notice
```
[
{
"id": "{{privacy_notice_id}}",
"enforcement_level": "system_wide"
}
]
```
Only create PrivacyRequests when there is at least one notice where enforcement == "System wide".
=> Create Consent Privacy Requests when Enforcement is System Wide Only

CHANGELOG.md, clients/privacy-center/app/server-environment.ts
Closes #3637 
I personally added some troubleshooting logs to the Privacy Center backend for loading config files, but didn't really _think_ them through - these fire on every request, so we really can't log anything for "normal" troubleshooting!
NextJS doesn't have thorough support for log levels like DEBUG/INFO/WARN/etc., so that kind of "normal" solution doesn't apply here, so I'm just disabling the logs based on the NODE_ENV instead.
=> Restrict Privacy Center debug logging to development-only

src/fides/api/app_setup.py, src/fides/api/util/cache.py
This is a small PR to alleviate the number of Redis connection test logs we see. It's currently logging on every healthcheck, which is excessive, and also pollutes downstream logging services for our customers.
@RobertKeyser is perma-using filters like `... -("Testing Redis connection..." OR "Redis connection succeeded.")` so it'd be nice to avoid wastage.
=> Remove most Redis connection test logs

CHANGELOG.md, src/fides/api/custom_types.py
Closes #3646
Increased the character limit to account for large known inputs such as CSS or PEM encoded certificates.
=> Increasing SafeStr character limit from 500 to 32000

CHANGELOG.md, clients/admin-ui/cypress/e2e/systems.cy.ts, clients/admin-ui/src/features/system/SystemFormTabs.tsx, clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationStep.tsx
Closes https://github.com/ethyca/fides/issues/3661
* See ticket
just realized the buttons don't look great in a smaller viewport, but that's unrelated to this work
https://github.com/ethyca/fides/assets/24641006/8110e4fb-69d0-4747-98d8-cf454c843adb
=> Subscribe to individual system query in manual create

CHANGELOG.md, clients/fides-js/src/components/fides.css
Often, we're going to want to use line breaks to break up paragraphs of legalese in the overlays - adding `whitespace: pre-line` allows the browser to do this without any fancy rich text components 👍 
For example, if I use a string like this:
```
We use cookies and similar methods to recognize visitors and remember their preferences.
We also use them to measure ad campaign effectiveness, target ads and analyze site traffic. Learn more about these methods, including how to manage them, by clicking ‘Manage Preferences.’ By clicking ‘accept’ you consent to the of these methods by us and our third parties. By clicking ‘reject’ you decline the use of these methods.",
```
Compare:
| Before (`whitespace: normal`) | After (`whitespace: pre-line`) |
|---|---|
| <img width="652" alt="image" …
=> Render linebreaks in the Fides.js overlay descriptions, etc.

CHANGELOG.md, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/fields/DatasetConfigField/DatasetConfigField.tsx
Closes https://github.com/ethyca/fides/issues/3667
The function that tries to match a dataset to its yaml was failing because the query to get all datasets was passing in a prop that filtered when it shouldn't. It turns out the prop was just missing!
* See steps in original bug ticket
=> Fix dataset yaml not properly reflecting dataset in dropdown

CHANGELOG.md, clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationManager.tsx
FE fix to get around https://github.com/ethyca/fides/issues/3682
https://github.com/ethyca/fides/pull/3571 refactored the privacy declaration form a bit so that we could include `cookies` fields. As part of that, there was a change where we only transformed the declaration was being edited, whereas previously we had transformed _all_ declarations prior to submission.
This PR restores doing an additional transform to all declarations right before sending to the API.
* Run `nox -s fides_env -- prod`
* On one of the existing systems that already has a data use, try to add another data use
* You should be able to add one without getting any errors
~* [ ] Issue Requirements are Met~ --> no they are not! but this is a smaller FE workaround
=> Transform null names to an empty string before submission

.fides/redis_dataset.yml, CHANGELOG.md, src/fides/api/graph/graph.py, src/fides/api/models/privacy_request.py, src/fides/api/service/privacy_request/request_runner_service.py, src/fides/api/service/storage/storage_uploader_service.py, src/fides/api/task/graph_task.py, src/fides/api/tasks/storage.py, tests/fixtures/postgres_fixtures.py, tests/ops/service/privacy_request/test_request_runner_service.py, tests/ops/service/test_storage_uploader_service.py, tests/ops/task/test_graph_task.py
Closes #3266 
We want to include `data_use` and `data_category` metadata as part of the output package for access requests. In order to do this, we need to make that metadata available to the `upload()` functions that produce and serialize the output packages. This PR updates the request execution internals to pass those pieces of metadata to the appropriate `upload()` function. 
The `data_category` metadata was already available as the `data_category_field_mapping` attribute on the `DatasetGraph` that's used during privacy request execution -- the update here is simply to pass that along as another argument to the `upload()` function.
The `data_use` metadata is not something we'd been keeping track of at all in privacy request execution. A new data structure has been created to maintain …
=> Include `data_use` and `data_category` metadata in `upload` of access results

clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/fields/DatasetConfigField/DatasetConfigField.tsx
Closes #3657
Removing the "required" asterisk from the database field in the integration configuration form.
=> Removing required flag for the dataset field

src/fides/api/service/privacy_request/dsr_package/dsr_report_builder.py, tests/ops/service/test_storage_uploader_service.py
Closes #3686 
The DSR report builder pre-processes the raw DSR data to separate the collection address into its separate parts, the dataset name and the collection name. The collection address for manual integrations is just the collection name without a dataset. The missing separator `:` from manual collection addresses causes an error when generating the DSR report. The fix uses a default dataset name of `manual` for manual collection addresses. I understand that using this approach might cause a collision with a non-manual datasets named `manual` but the product team (@rsilvery) agreed this was acceptable for now.
=> Updating DSR data pre-processor to support manual data

src/fides/api/models/privacy_notice.py, src/fides/api/util/consent_util.py, tests/ops/api/v1/endpoints/test_privacy_notice_endpoints.py, tests/ops/models/test_privacy_notice.py, tests/ops/util/test_consent_util.py
Closes #3353 
When creating or updating a notice, check all existing notices, as well as any incoming notices to see if there are going to be any notice key overlaps within a specific region.
POST /privacy-notice
```json
[
{
"name":"Profiling",
"notice_key": "profiling",
"regions":[
"us_oh"
],
"description":"Making a decision solely by automated means.",
"consent_mechanism":"opt_in",
"data_uses":[
"personalize"
],
"enforcement_level":"system_wide",
"has_gpc_flag":false,
"displayed_in_overlay":true
},
{
"name":"Essential",
"notice_key": "profiling",
"regions":[
"us_oh"
],
"description":"Notify the user about data processing activities that are essential to your services' functionality. Typically consent is not required for this.",
"consent_mechanism":"notice_only",
"data_uses":[ …
```
=> [Backend] Validation on Notice Keys within Region

CHANGELOG.md
Closes n/a
This is the changelog only update for `2.15.1`
The checklist and branch for this patch release are referenced on #3720 
=> Update CHANGELOG for `2.15.1`

pyproject.toml, src/fides/api/util/unsafe_file_util.py, tests/fixtures/saas_example_fixtures.py
Misc bug fixes for issues that made it to the `main` branch.
=> Fixing misc test failures

CHANGELOG.md, tests/ops/util/test_api_router.py
Closes #3736 
Mock the admin UI response for our test case to get a more predictable value.
It's not ideal, since there's a slight chance this could lead to false positives in the test case if we adjust our code around this area, so we'll just need to be a bit careful there. But I think it's a good enough test for now - and certainly better than getting false negatives all the time!
=> make malicious url test more robust to env differences

CHANGELOG.md, src/fides/cli/__init__.py, src/fides/cli/commands/annotate.py, src/fides/cli/commands/deploy.py, src/fides/cli/commands/generate.py, src/fides/cli/commands/ungrouped.py, src/fides/cli/commands/view.py, src/fides/cli/options.py
Closes #3745 
Ignore type checker on problematic function calls with decorator wrappers. This is due to a change in `click` version `8.1.4` that many others are also hitting: https://github.com/pallets/click/issues/2558
See issue descriptions (ours and theirs) for more detail/context.
Follow up tech debt ticket to revert this eventually, when possible: https://github.com/ethyca/fides/issues/3749
=> ignore type checker on `click` decorators to bypass known library issue

CHANGELOG.md, src/fides/api/db/base_class.py, src/fides/api/models/authentication_request.py, src/fides/api/models/datasetconfig.py, src/fides/api/util/connection_util.py, tests/ops/api/v1/endpoints/test_connection_config_endpoints.py
Closes #3757 
We needed to disable the name checking for the `ConnectionConfig` model since it is possible for multiple connections to have a `name` of `None` now that we don't require it in the front end. The concept of `check_name` is something we already had in various parts of the code so I just extended the use of it for our purposes.
=> Allow connection configs with duplicate names

CHANGELOG.md, src/fides/api/api/v1/__init__.py, src/fides/api/app_setup.py
Closes #3652 
our admin (`admin.py`) and health (`health.py`) routers have direct dependencies on the `fides.api.db.database` module, since they require direct interaction with the DB. if these routers are initialized within the `api.api.v1` module, this can easily lead to circular dependency problems on module initialization, because the `api.api.v1` module is itself imported by some classes and submodules of `api.db`. 
see #3652  and this [PR comment](https://github.com/ethyca/fides/pull/3692#issuecomment-1614508211) for context. additionally, this was motivated by @RobertKeyser attempting to import `fides.api.db.database.get_db_health` into a python shell and hitting a circular dependency.
Side note: I considered moving the router definitions themselves (i.e. their code) out of …
=> move db-dependent routers up a few levels to reduce circular dependencies

CHANGELOG.md, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParameters.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/DSRCustomizationForm/DSRCustomizationModal.tsx
Closes #3752 
Adds the integration identifier form to the manual connector creation process. The DSR customize form can only be filled out if there is a connection config. The `Customize DSR` button is disabled with a helpful on hover tooltip that explains that the integration needs to be created first. Once it's created the button will become enabled.
https://github.com/ethyca/fides/assets/17103888/aaca8e16-a5bf-4f74-973d-d9ca31fa31d0
=> Fix creating and editing manual integrations

CHANGELOG.md, src/fides/api/models/connectionconfig.py, src/fides/api/models/sql_models.py, tests/ctl/core/test_api.py
Closes #3769 
Updates the ORM backlink relationships between `System` --> `ConnectionConfig` and `ConnectionConfig` --> `DatasetConfig` to cascade deletes. This effectively ensures, via the ORM layer, that our `DELETE /system` API will also delete these related _integration_ (i.e. _connection_) artifacts in the DB, as is expected. 
=> cascade deletes from system -> connectionconfig -> datasetconfig

CHANGELOG.md, clients/admin-ui/src/flags.json
Closes N/A
Enables the privacy experience and notices flags by default
* Run `nox -s "fides_env(test)"`
* Go to localhost:8080 and confirm privacy notices and experiences are enabled by default in the management tab
=> Enable privacy notices and experiences by default in production

CHANGELOG.md, clients/admin-ui/src/features/common/custom-fields/hooks.ts
Closes [Fidesplus issue 960](https://github.com/ethyca/fidesplus/issues/960).
Removed the "Custom field successfully saved" toast on saving a resource with custom fields, following conversation with @rsilvery today.
=> Remove 'successfully added custom fields' toast

requirements.txt, tests/ctl/core/test_dataset.py
works on #3800 
the `pyyaml` update here is relatively straightforward and understood - `pyyaml>=6.0` seems to fix the compatibility issues that `pyyaml<6.0` had with `cython>=3.0`, namely use of a `setup.cfg` file. upgrading to `pyyaml>=6.0` seems like it _should_ be fine for us - at first glance, i can't find any concrete reason we're constrained lower, besides probably a general caution when first unpinning the dependency (see https://github.com/ethyca/fides/issues/217#issuecomment-985018791 for what i think is the context there). and upgrading to `pyyaml>=6.0` seems like a viable workaround from at least some others (e.g. https://github.com/yaml/pyyaml/issues/601#issuecomment-1638573950).
i also have here a temporary removal of the `pymssql` dependency, since that _also_ was causing …
=> fix broken build (`pyyaml` and `pymssql` issues related to `cython` version `3.0`)

clients/admin-ui/src/features/datastore-connections/DisableConnectionModal.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/ConnectionForm.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/DeleteConnectionModal.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/OrphanedConnectionModal.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParameters.tsx, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx
Closes #3801 and #3776 
- move disable toggle and delete button to top
- update look of buttons
- add grey square around directions
Note: the remaining work to update the UI will be done in the next sprint 
=> clean up ui on integration tab

.fides/db_dataset.yml, CHANGELOG.md, src/fides/api/alembic/migrations/versions/5abb65a8cb91_add_active_column_taxonomy_elements.py, src/fides/api/api/v1/endpoints/generic.py, src/fides/api/models/sql_models.py, src/fides/api/schemas/taxonomy_extensions.py, tests/ctl/core/test_api.py
Closes #3709 
Extends taxonomy pydantic models defined in `fideslang` to add an `active` boolean property, and updates the corresponding db model for these taxonomy elements. This enables us to update and persist this property on taxonomy elements via the CRUD API.
=> support active property on taxonomy elements

CHANGELOG.md, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx
Closes #3830
Removed unused `connectionKey` property from DeleteConnectionModal
=> Removing unused property from DeleteConnectionModal

CHANGELOG.md, clients/fides-js/src/components/ConsentModal.tsx, clients/fides-js/src/components/NoticeToggles.tsx, clients/fides-js/src/components/Tcf/CookiesTable.tsx, clients/fides-js/src/components/Tcf/FilterButtons.tsx, clients/fides-js/src/components/Tcf/TcfPurposes.tsx, clients/fides-js/src/components/Tcf/TcfTabs.tsx, clients/fides-js/src/components/fides.css, clients/privacy-center/cypress/e2e/consent-banner.cy.ts
Closes https://github.com/ethyca/fides/issues/3723
Adds generic UI components for more TCF components.
Here's a bunch of them combined into one view:
* Edit the `fides-js-components-demo.html` component so that `tcfEnabled` is `true`
* Run `turbo dev` in privacy center
* Visit `/fides-js-components-demo.html` and open the modal
* See the hodge podge of UI components
=> Remaining TCF UI components

CHANGELOG.md, clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx
Closes #3842
Using a field's `sensitive` property to determine if an `Input` should behave as a password or text input.
=> Flagging sensitive inputs as passwords to mask values during entry

CHANGELOG.md, clients/privacy-center/__tests__/common/geolocation.test.ts, clients/privacy-center/common/geolocation.ts, clients/privacy-center/pages/api/fides-js.ts
Closes https://github.com/ethyca/fides/issues/3849
Disable server-side geo lookup for now, to unblock release.
=> Disable server-side geo lookup for now

CHANGELOG.md, clients/privacy-center/pages/api/fides-js.ts
Unticketed
Removes API calls from privacy center server so that release is unblocked.
1. Run nox -s "fides_env(test)"
2. Open http://localhost:3001/fides.js
3. Observe no Internal Server Error
=> Remove experience prefetching

CHANGELOG.md, clients/admin-ui/src/features/system/SystemInformationForm.tsx, clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationStep.tsx
Closes #3778 
Add a max width of 70% at breakpoints `lg` and above to all components of the "system information" form, to bring them in line with the other system form tabs; also, adjust font weight on "system information" and "data use" forms to match designs.  (Below screenshot is on 1440p monitor)
=> Adjust max width of system information form

dangerous-requirements.txt, noxfiles/ci_nox.py, noxfiles/utils_nox.py, requirements.txt, setup.py
Closes #3824 
We previously thought we'd successfully worked around our `pymssql`/`Cython` compatibility issues on mac ARMs in https://github.com/ethyca/fides/pull/3829 by using different versions of `pymssql` for our Docker builds as compared with our package dependencies (`requirements.txt`).
From what I can see, I think we were mistaken on the second piece of that - i.e., I don't think we'd actually solved the package dependency problem. We mistakenly assumed we'd solved the issue because I was able to successfully `pip install -e .` from the root of `fides` locally, but I think that we were actually getting cached `pymssql-2.2.7.whl` files when doing that, and so we weren't truly evaluating whether the problem -- which manifested when _building_ `pymssql` wheels on a mac `ARM` -- was …
=> remove pymssql as a package requirement

clients/admin-ui/cypress/e2e/systems.cy.ts, clients/cypress-e2e/cypress/e2e/smoke_test.cy.ts
Closes #3881
Updating the Cypress tests to handle two new scenarios
- Integrations are now linked to systems, so they won't be available in the connection management page
- `fides_keys` are no longer required for systems or integrations
=> Updating Cypress tests

CHANGELOG.md, noxfiles/ci_nox.py, noxfiles/utils_nox.py, src/fides/api/api/v1/endpoints/health.py, src/fides/api/db/database.py, src/fides/api/tasks/__init__.py, src/fides/api/util/connection_util.py, tests/ctl/core/test_api.py
Closes #2517 
The `database` health check step was found to be extremely heavy, sometimes spiking response times to ~1 sec when running locally with nothing else hitting the server
After doing some investigation of the `worker` checks as well, I couldn't find evidence that this was an issue. It only increased processing time by ~6ms. After checking everything I believe that the database was the primary culprit here, but we'll continue to monitor this fix as it is rolled out and verify that conclusion.
=> Update Healthcheck logic

src/fides/api/api/v1/endpoints/health.py, src/fides/api/api/v1/endpoints/oauth_endpoints.py, tests/ctl/api/test_seed.py, tests/fixtures/saas_example_fixtures.py, tests/ops/api/v1/endpoints/test_oauth_endpoints.py
When a user configures an integration that uses the OAuth2 authorization code flow, they must follow an authorization URL to enter their credentials and authenticate the connection. When the authorization URL is generated, we also store the referrer to be able to redirect the user back to the system configuration page after authorization. There is a scenario where the referrer URL is the generic system URL (http://localhost:3000/add-systems/manual) and not the unique system path (http://localhost:3000/systems/configure/salesforce). This causes the user to be redirected to a generic system creation page after authorization instead of the system's configuration page.
=> Fixing OAuth2 redirect URL

src/fides/api/util/saas_util.py, tests/ops/util/test_saas_util.py
Adding support for the following scenario
`unflatten_dict({"A.0": "B", "A.1": "C"}) == {"A": ["B", "C"]}`
This would previously throw an exception since the 0 and 1 indices would be treated as strings instead of ints.
=> Additional scenario for unflatten_dict

CHANGELOG.md, src/fides/api/task/refine_target_path.py, tests/ops/task/test_refine_target_path.py
Closes #3905
Updating `refine_target_path` to return an empty path if the path is invalid, meaning the data doesn't exist at the level indicated.
=> Adding new scenario to refine_target_path

CHANGELOG.md, docker-compose.yml
Closes #3913
Fixing typo in `docker-compose.yml` that was preventing the code reload
=> Fixing typo

CHANGELOG.md, clients/privacy-center/pages/api/fides-js.ts
Small change to suppress the "Bundling generic fides.js & Privacy Center configuration together..." log message in production, as this'll current log every time the fides.js bundle is requested!
* n/a
=> Reduce verbosity of privacy center logging further

CHANGELOG.md, clients/admin-ui/src/features/datastore-connections/system_portal_config/ConnectionListDropdown.tsx
Closes #3681 
Keeping a reference to the integration search input so that the focus can be restored after a re-render.
=> Forcing focus on integration search input

src/fides/api/api/v1/endpoints/health.py
Closes https://github.com/ethyca/fides/issues/2517 by eliminates the high-latency part of the healthcheck. However, the real root cause is not identified yet and will have to be investigated as a follow-up issue.
* Removes the code that checks worker health when a `/health` API request is received.
=> Disable worker part of `/health` check

CHANGELOG.md, clients/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/admin-ui/src/features/taxonomy/hooks.tsx
Closes #3907 
> [!NOTE]
> Depends on #3901 being merged
This removes some deprecated data use fields from the taxonomy editor.
=> Remove deprecated fields from form

CHANGELOG.md, data/saas/dataset/vend_dataset.yml
Closes #3921
The dataset validator changed recently to detect extra collection fields. The dataset for Vend had duplicate `version` fields for the `sales` collection
=> Removing erroneous dataset fields

clients/admin-ui/cypress/e2e/datasets.cy.ts, clients/admin-ui/src/features/dataset/EditDatasetForm.tsx, clients/admin-ui/src/types/api/models/Dataset.ts
Closes #[3910](https://github.com/ethyca/fides/issues/3910)
remove retention period, identifiability, and geographic location from dataset form
=> remove fields from dataset form

CHANGELOG.md, src/fides/api/alembic/migrations/versions/fd52d5f08c17_system_dictionary_data_migration.py
Closes #3950
Adding a version check to call `array_cat` with the appropriate types
=> Adding a temporary version check to migration

.github/workflows/backend_checks.yml
This is a temporary removal of our `mypy` checks while we're working on #3839 
=> remove mypy type check from CI

clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationFormTab.tsx
change the no data use warning to use the existing component to match app
=> update the no data use warning styling

CHANGELOG.md, clients/admin-ui/src/features/system/form.ts
Fixes a bug where `exempt_from_privacy_declarations`, `processes_personal_data` and `dataset_reference` fields in system form weren't saving.
Changes some logic in `transformFormValuesToSystem` in `src/features/system/form.ts`
=> Fix some variables not submitting correctly in system form

.github/workflows/publish_docker.yaml, CHANGELOG.md, noxfiles/docker_nox.py, noxfiles/test_docker_nox.py
Closes #
I previously had tried to get parallel Docker builds working using Python's own multiprocessing framework, however this appeared to not function as expected in GitHub Actions.
This PR iterates on that and shifts the parallel execution responsibility to GitHub Actions with a strategy matrix
Used this for reference when redesigning how the `outputs` work: [GitHub Output Docs](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idoutputs)
=> Fix Parallel Docker Platform Builds

clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationForm.tsx, clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationFormTab.tsx
Fixes Fidesplus issue [1080](https://github.com/ethyca/fidesplus/issues/1080)
Adds custom fields section to new data use form
=> re-enable custom fields for new data use form

CHANGELOG.md, clients/admin-ui/src/features/system/SystemInformationFormSelectOptions.ts, requirements.txt, tests/ctl/core/test_api.py
Closes https://github.com/ethyca/fides/issues/4057
❗ Needs 1.4.6 bump
Allow System Legal Basis for Transfers to be any string.  
=> Fides: Relax Legal Basis for Transfers

requirements.txt
Closes #4020
Version [4.0.0](https://anyio.readthedocs.io/en/stable/versionhistory.html) of `anyio` made a breaking change by moving to [PEP 654 exception groups](https://peps.python.org/pep-0654/) which are only natively supported in Python 3.11. I ran a check to see the earliest version of anyio we could use for our dependencies
```
nox -s shell
pip install pipdeptree
pipdeptree --reverse --packages anyio
```
```
anyio==4.0.0
├── httpcore==0.16.3 [requires: anyio>=3.0,<5.0]
│   └── httpx==0.23.1 [requires: httpcore>=0.15.0,<0.17.0]
│       └── ethyca-fides==2.19.1b0.post0.dev2 [requires: httpx==0.23.1]
├── starlette==0.22.0 [requires: anyio>=3.4.0,<5]
│   └── fastapi==0.89.1 [requires: starlette==0.22.0]
│       ├── ethyca-fides==2.19.1b0.post0.dev2 [requires: fastapi==0.89.1]
│ …
```
=> Pinning anyio version to 3.7.1 to avoid using PEP 654 ExceptionGroups

clients/admin-ui/src/features/system/history/modal/SystemHistoryModal.tsx, clients/admin-ui/src/features/system/history/modal/fields/SystemDataSwitch.tsx, clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationFormTab.tsx
Increased the width of the modal to account for long data category tags that can't wrap. This is a temporary solution, the modal should be able to adapt to the contents, maintain a minimum width but expand if necessary.
Also fixed an issue where fields with missing boolean values were being evaluated as false
=> Fixing diff modal

CHANGELOG.md, clients/privacy-center/pages/api/fides-js.ts
Closes https://github.com/ethyca/fides/issues/4072
Check for fetch first and then load polyfill if its not defined. This reduces possibility for client errors and reduces an extra network call that could impact customers.
=> Do not load fetch polyfill if fetch is detected

CHANGELOG.md, clients/fides-js/src/components/fides.css
This `!important` CSS override on fides.js toggles ensures that if customers are using a CSS lib, for example https://getuikit.com/, that the toggles aren't getting hidden.
=> Adds important CSS override to display fides toggles

clients/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/admin-ui/cypress/fixtures/taxonomy/data_uses.json, clients/cypress-e2e/cypress/e2e/smoke_test.cy.ts, clients/privacy-center/config/config.json, clients/privacy-center/config/examples/full.json, clients/privacy-center/config/examples/v2Consent.json, clients/privacy-center/cypress/e2e/consent.cy.ts, clients/privacy-center/cypress/fixtures/config/config_all.json, clients/privacy-center/cypress/fixtures/config/config_consent.json, clients/privacy-center/cypress/fixtures/consent/verify.json, src/fides/data/sample_project/privacy_center/config/config.json
As part of the fideslang 2.0 upgrade, we should upgrade the default config.json file we ship with to not reference an obsolete fideslang data use.
=> Update config.json Improve -> Functional 

clients/admin-ui/src/features/common/table/cells.tsx, clients/admin-ui/src/features/custom-fields/cells.tsx, clients/admin-ui/src/features/privacy-notices/PrivacyNoticesTable.tsx, clients/admin-ui/src/features/privacy-notices/cells.tsx, clients/admin-ui/src/types/api/models/PrivacyNoticeResponse.ts
Closes #4077 
Privacy notice table updates - remove created and description columns, update location and consent mechanism tabs, and rearrange column order
=> Privacy notice table updates

src/fides/api/alembic/migrations/versions/671358247251_migrate_meta_vendor.py
Closes #4084 
Migrate system > meta > vendor > id _if it exists_  and **vendor_id doesn't already exist** to system > vendor id.  Remove the "vendor" key from meta dict if applicable and the migration took place on that row.
```sql
fides=# select id, meta, vendor_id from ctl_systems order by id
;
id                    |                 meta                  | vendor_id 
------------------------------------------+---------------------------------------+-----------
ctl_0118fbbd-282e-4d31-bc8b-5777d713cf3a | {"health": 2, "vendor": {"id": "87"}} | 
ctl_25efee31-7fb7-41cb-a660-5141cc79c23e | {"health": 1}                         | 
ctl_40f88ca0-810d-4af0-a26e-64aff9181e59 | {"health": 3, "vendor": {"id": "29"}} | 21
ctl_483e730c-3dba-4fe9-b59f-dc2ac562bc95 | {} …
```
=> Migrate system > meta > vendor > id if it exists to system > vendor_id.

clients/admin-ui/src/features/plus/plus.slice.ts, clients/admin-ui/src/features/system/SystemFormTabs.tsx, clients/admin-ui/src/features/system/history/SystemHistoryTable.tsx, clients/admin-ui/src/features/system/history/modal/SystemDataForm.tsx, clients/admin-ui/src/features/system/history/modal/SystemHistoryModal.tsx, clients/admin-ui/src/pages/systems/configure/[id].tsx
Fixing vendor ID field in system change modal and updating the diff modal to say "Change detail" instead of "Diff review"
=> Diff modal patch

scripts/verify_fideslang_2_data_migration.py, src/fides/api/alembic/migrations/versions/1ea164cee8bc_fideslang_2_data_migrations.py
Closes #
Fixing a bug in the Fideslang migration script
=> feat: add further checks to the migration script

scripts/verify_fideslang_2_data_migration.py, src/fides/api/alembic/migrations/versions/1ea164cee8bc_fideslang_2_data_migrations.py
Closes n/a
Our fideslang 2.0 migration was failing to run on a deployed env seemingly because there are custom data uses that do not have a parent, i.e. top-level custom taxonomy elements. This is a valid server/data state. See stack trace from the failed migration below.
This fix makes the string replacement that was choking more defensive.
=> fix: more defensive string replacement to handle Nones

CHANGELOG.md, src/fides/api/alembic/migrations/versions/f17f92237383_disable_inactive_notices.py
Closes https://github.com/ethyca/fides/issues/4094
❗ Needed for release 2.20 
This migration gets notices in a better state for new UI.  We originally shipped with out of the box notices that were enabled by default, but new UI prevents you from enabling a notice unless it is applicable for a system.  So we have some "enabled" notices that are "inactive" which our new UI is supposed to prevent.
- `nox -s dev -- shell`
- In admin `features.slice.ts` set plus=True, and run turbo run dev 
- Create one system with two declarations. One with a more specific use than our notice: `personalize.content` and one that matches: `analytics`
- In a postgres shell, run `update privacynotice set disabled=false` and `update privacynoticehistory set disabled=false` to mimic the state of a customer that is …
=> Fix: Disable Privacy Notices that are not Systems Applicable

CHANGELOG.md, clients/admin-ui/cypress/e2e/privacy-notices.cy.ts, clients/admin-ui/src/features/common/table/cells.tsx, clients/admin-ui/src/features/custom-fields/cells.tsx, clients/admin-ui/src/features/privacy-experience/cells.tsx, clients/admin-ui/src/features/privacy-notices/cells.tsx, clients/admin-ui/src/features/privacy-notices/form.ts
Closes https://github.com/ethyca/fides/issues/4092
New error toast for if an error comes up while enabling/disabling a privacy notice. Since this is a shared component, privacy experiences and custom fields also get the same upgrade!
* See steps in the issue
=> Notice toggle error toast

CHANGELOG.md, clients/fides-js/src/fides.ts, clients/fides-js/src/lib/consent-types.ts, clients/fides-js/src/lib/consent-utils.ts, clients/fides-js/src/services/fides/api.ts, clients/privacy-center/cypress/e2e/consent-banner.cy.ts
Closes https://github.com/ethyca/fides/issues/4108
Updates experience API to return empty obj instead of undefined when no experience was found for a specific location. This allows cache to work properly under this scenario, meaning that requests to the server will decrease overall.
=> Allows CDN to cache empty experiences responses from fides.js API

src/fides/api/alembic/migrations/versions/52b2cfd1af47_fix_messaging_template_indexes.py, src/fides/api/models/system_history.py
Closes #4105
The `alembic revision --autogenerate` command was generating for some tables added in previous tickets. This was due to naming mismatches in the classes or in the migrations themselves.
```
nox -s shell
cd src/fides/api/alembic/
alembic revision --autogenerate -m "check check"
```
Open the generated file and verify there are no mentions of `plus_system_history` or `plus_system_history`
```
def upgrade():
pass
def downgrade():
pass
```
=> Fixing migration and index name

src/fides/api/main.py, src/fides/api/tasks/scheduled/scheduler.py, tests/ops/conftest.py
Closes n/a
As part of https://github.com/ethyca/fidesplus/pull/1087, we'd like to put an async function on a scheduler. i had been working around this by wrapping the function with a `@sync` decorator but i think a cleaner solution is to just instantiate, start, and expose a global `AsyncIOScheduler` here in `fides`, alongside the `BackgroundScheduler` we already expose.
I could have put this directly in `fidesplus`, but it feels like something we may want to make more use of generally if/when we need to schedule other async functions, and generally feels like a better design to define and manage this directly alongside the `BackgroundScheduler` here in `fides` 👍 
=> add a global async scheduler

CHANGELOG.md, src/fides/api/api/v1/endpoints/system.py, src/fides/api/schemas/system.py
Closes #4028 
Narrow down what we return on the bulk `GET /system` endpoint to not have relationship fields that can lead to n+1 query problems - in this case, it was specifically the `connection_configs` property/relationship. See issue for more context.
=> avoid n+1 queries on bulk `GET /system` endpoint

noxfiles/git_nox.py, noxfiles/test_git_nox.py
Closes n/a
A slight change to our tagging utility so that it takes into account existing `rc` tags when generating a `beta` tag on `main`.  So if we are in _the process_ of releasing e.g. `2.20.0` and therefore have `2.20.0rc0` but _not_ an official `2.20.0` tag, when we run `nox -s tag` on `main` it will generate `2.20.1b0` as the tag.
This makes it easy for us to ensure our packages built from the latest of `main` will always be _ahead_ of our published `rc` packages, which is important in keeping the `double-edge-slim` images (and therefore our `plus-nightly` environment!) based off of `main` of both repos.
As part of this, we'll also want to tweak our release process to generate a tag on `main` as soon as we cut release branches (i.e. beginning of the release process), rather than …
=> consider rc tags as latest release when generating beta tags

src/fides/api/api/v1/endpoints/config_endpoints.py, src/fides/api/models/application_config.py, src/fides/api/schemas/application_config.py
Closes n/a
WIP for a `PUT /config` endpoint to help us with cors domain resetting
@TheAndrewJackson i still need to write in some tests and think about this a bit further, but on some initial testing i think this is good to get you an API to start working against?
=> `PUT /config` endpoint for cors domain resetting

CHANGELOG.md, clients/admin-ui/cypress/e2e/taxonomy.cy.ts, clients/admin-ui/src/features/taxonomy/hooks.tsx, clients/admin-ui/src/features/taxonomy/types.ts, clients/admin-ui/src/types/api/models/DataCategory.ts, clients/admin-ui/src/types/api/models/DataSubject.ts, clients/admin-ui/src/types/api/models/DataUse.ts
Closes #4134 
add version_added to TaxonomyEntity
=> add version_added to TaxonomyEntity

CHANGELOG.md, clients/fides-js/src/components/ConsentBanner.tsx, clients/fides-js/src/components/fides.css, clients/fides-js/src/components/notices/NoticeOverlay.tsx, clients/fides-js/src/components/tcf/TcfModalContent.tsx, clients/fides-js/src/components/tcf/TcfOverlay.tsx, clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
Closes https://github.com/ethyca/fides/issues/3934
https://github.com/ethyca/fides/assets/24641006/0c17014d-295f-4ba1-8c91-58bd871add22
* Go through [the usual steps](https://github.com/ethyca/fides/pull/4139) to set TCF up
* Visit the `/fides-js-demo` page. The banner should pop up but you should see stacks/purposes inside!
* Clicking "manage preferences" should open up the modal, which is the second layer.
=> Make the banner the initial layer

clients/admin-ui/src/features/system/privacy-declarations/PrivacyDeclarationStep.tsx
=> Add min width to data use tab

clients/privacy-center/config/config.css, src/fides/data/sample_project/privacy_center/config/config.css
=> Add privacy center new line css

CHANGELOG.md, clients/fides-js/src/components/DataUseToggle.tsx, clients/fides-js/src/components/tcf/TcfFeatures.tsx, clients/fides-js/src/components/tcf/TcfOverlay.tsx, clients/fides-js/src/components/tcf/TcfPurposes.tsx, clients/fides-js/src/fides-tcf.ts, clients/fides-js/src/lib/consent-utils.ts, clients/fides-js/src/lib/tcf/types.ts, clients/privacy-center/cypress.config.ts, clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts, clients/privacy-center/cypress/fixtures/consent/experience_tcf.json
Closes https://github.com/ethyca/fides/issues/4137
Removes toggles from Features and Special Purposes since users aren't supposed to be able to change those preferences. 
Can still expand them
* `nox -s dev`
* Add a system with a purpose data use and a special purpose data use. I used `analytics.reporting.campain_insights` for purpose, and `essential.fraud_detection` for special purpose. Make sure they have legal bases (campaign insights should probably be `Consent` and fraud detection `legitimate interest`)
* Add a feature and a special feature. I used `Link different devices` for feature, and `Use precise geolocation data` for special feature. Note that this is a select input, and you have to hit enter after adding the feature 
* Start up the privacy center via …
=> Remove features and special purposes toggles

CHANGELOG.md, clients/admin-ui/src/features/system/history/SystemHistoryTable.tsx, clients/admin-ui/src/features/system/history/helpers.tsx, clients/admin-ui/src/features/system/history/modal/SystemDataForm.tsx, clients/admin-ui/src/features/system/history/modal/SystemHistoryModal.tsx
Fixing misc bugs
- `ingress` and `egress` now show up in the UI as `source` and `destination`
- The system name is displayed for source and destination changes instead of the fides_key
- Fixed issue with `System Information` badge showing for data use changes
- `privacy_decralations` now show up in the UI as `data use`
=> Fixing system history bugs

CHANGELOG.md, src/fides/api/alembic/migrations/versions/4cb3b5af4160_update_special_feature_unique_constraint.py, src/fides/api/alembic/migrations/versions/4cb3b5af4160_update_special_purpose_unique_constraint.py, src/fides/api/models/privacy_preference.py
Closes https://github.com/ethyca/fides/issues/4173
We need unique constraints on CurrentPrivacyPreference and LastServedNotice to force those tables to store a single preference for a given dimension and a.given identity across time and versions of a notice.   A "provided identity" and "special purpose" were not being indexed in the CurrentPrivacyPreference table. 
```sql
\d currentprivacypreference
...
Indexes:
"identity_special_purpose" UNIQUE CONSTRAINT, btree (provided_identity_id, special_purpose)
```
=> CurrentPrivacyPreference > Special Purpose Unique Constraint Fix

clients/admin-ui/src/features/plus/plus.slice.ts
The `PUT /custom-asset` endpoint in fidesplus was updated to return the accepted CSS instead of just a success status. This meant that the Admin UI would try to parse the response as JSON and report a false error toast. This changes makes it so the response is treated as plain text instead of JSON.
=> Fixing response handling

CHANGELOG.md, data/saas/config/braze_config.yml, data/saas/dataset/braze_dataset.yml, src/fides/api/service/saas_request/override_implementations/braze_request_overrides.py, tests/fixtures/saas/braze_fixtures.py, tests/ops/integration_tests/saas/test_braze_task.py
Partially Closes #4179
Found in a recent test, unclear if this is a recent change by Braze
This creates an override that allows Braze to mask email with a proper format to meet the needs of Braze.
=> Braze Override for Email

noxfiles/drill.yml, requirements.txt, src/fides/api/api/v1/endpoints/privacy_experience_endpoints.py
Closes #4040 
See below ⬇️ 
This PR will be followed up with another that focuses on adding proper Caching to that endpoint
=> Performance Refactor for `privacy-experience`

CHANGELOG.md, clients/fides-js/src/components/tcf/TcfVendors.tsx
Closes N/A
Uses the `stdRetention` number if there is no specific number of retention days for a given purpose.
* Set up your TCF environment and add a vendor from the dictionary
* Instead of `N/A`s, you should now see the default `stdRetention` value as expected
=> Fix retention

CODE_OF_CONDUCT.md
No associated issue (this is a tiny docs change).
This change fixes a 404'ing link to the Fides Code of Conduct.
n/a
* Verify new link works and is correct
=> docs: fix 404'ing link to code of conduct

CHANGELOG.md, src/fides/api/service/saas_request/override_implementations/braze_request_overrides.py, src/fides/api/service/saas_request/override_implementations/domo_request_overrides.py
Closes #4179
The if was blocking the formatting of the email. This change simplifies it to block it if the key is present instead of relying on `user.contact.email` (`user.contact` is included in the policy instead)
We may also want to replicate this change to Domo overrides
=> Update for Braze and Domo overrides

clients/fides-js/src/components/tcf/DoubleToggleTable.tsx, clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
Closes bug reported by @galvana !
When a vendor has two toggles available, it was always setting consent instead of the proper one.
=> Fix double toggle bug

CHANGELOG.md, clients/admin-ui/src/flags.json
Allow users to view the new page to configure vendors and cookies for consent by toggling the Configure consent flag.
=> Turn on configureConsent flag

src/fides/api/schemas/tcf.py, tests/ops/api/v1/endpoints/test_privacy_preference_endpoints.py, tests/ops/util/test_tc_string.py
Closes n/a
Placeholder to get our response schema in the correct shape, field still needs to be populated
=> add placeholder field for AddtlConsent field in TCMobile data

.fides/db_dataset.yml, CHANGELOG.md, src/fides/api/alembic/migrations/versions/81886da90395_add_legal_basis_dimension.py, src/fides/api/alembic/migrations/versions/c5a218831820_additional_tcf_fields_system.py, src/fides/api/models/sql_models.py, src/fides/api/schemas/tcf.py, src/fides/api/util/tcf/tcf_experience_contents.py, tests/ctl/core/test_api.py, tests/ops/util/test_tcf_experience_contents.py
Closes #4227 
Adds support in fides for the new fields on the `System` and `PrivacyDeclaration` model added to fideslang.
- `System.cookie_max_age_seconds`
- `System.cookie_refresh`
- `System.uses_cookies`
- `System.uses_non_cookie_access`
- `System.legitimate_interest_disclosure_url`
- `PrivacyDeclaration.flexible_legal_basis_for_processing`
```
{"fides_key":"ts1","organization_fides_key":"default_organization","tags":[],"name":"ts1","description":"","registry_id":null,"meta":null,"fidesctl_meta":null,"system_type":"","data_responsibility_title":null,"egress":null,"ingress":null,"privacy_declarations":[{"name":"pd1", "flexible_legal_basis_for_profiling": true, "data_categories":["system.operations"],"data_use":"analytics.reporting.ad_performance","data_subjects":[],"features":[],"impact_a …
```
=> fides: add `System` model support for new tcf fields

CHANGELOG.md, src/fides/api/util/tcf/tc_model.py, src/fides/api/util/tcf/tc_string.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_privacy_experience_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_preference_endpoints.py, tests/ops/api/v1/endpoints/test_served_notice_endpoints.py, tests/ops/models/test_privacy_experience.py, tests/ops/models/test_privacy_preference.py, tests/ops/util/test_tc_string.py, tests/ops/util/test_tcf_experience_contents.py
Closes https://github.com/ethyca/fidesplus/issues/1129
Update all-things TCF on the BE (namely, overlay generation and preferences saving) to account for new "universal vendor ID" scheme.
In other words, we assume that TCF vendor preferences are saved against universal vendor ids, and also that universal vendor ids are returned in the experience.
Therefore, the main thing that needs to change on the backend is the translation to and from the TC string itself.
- Vendor ID -> GVL Universal Vendor ID: Save privacy preferences under universal vendor id when unpacking vendor preferences from a TC string by adding the gvl prefix
- Universal Vendor ID -> Vendor ID: When building a TCModel from the TCF Experience (a prerequisite to building TC strings), convert universal vendor ids to vendor ids …
=> Backend: Assume Universal Vendor Ids

CHANGELOG.md, clients/fides-js/src/components/fides.css, clients/fides-js/src/components/tcf/TcfVendors.tsx
Adding a `margin-top` to `.fides-info-box` and an inline `margin-bottom` to the external links in the fides disclosure
info box
disclosure
=> Fixing spacing issues caused by a CSS reset

CHANGELOG.md, clients/fides-js/src/components/tcf/TcfVendors.tsx, clients/fides-js/src/lib/tcf.ts, clients/fides-js/src/lib/tcf/vendors.ts, clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts, clients/privacy-center/cypress/fixtures/consent/experience_tcf.json
Closes https://github.com/ethyca/fides/issues/4242
Support vendor ids that are prefixed by `gvl.` 
* Everything should still work! This is another one where, without the backend change, it's hard to see what changed, but the cypress tests provide a case of a vendor with id `gvl.1` and things still work properly
=> GVL vendor id update

CHANGELOG.md, clients/fides-js/src/components/tcf/TcfOverlay.tsx, clients/fides-js/src/components/tcf/TcfVendors.tsx, clients/fides-js/src/fides-tcf.ts, clients/fides-js/src/lib/cookie.ts, clients/fides-js/src/lib/initialize.ts, clients/fides-js/src/lib/preferences.ts, clients/fides-js/src/lib/tcf.ts, clients/fides-js/src/lib/tcf/constants.ts, clients/fides-js/src/lib/tcf/vendors.ts, clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts, clients/privacy-center/cypress/fixtures/consent/experience_tcf.json
Closes https://github.com/ethyca/fides/issues/4212
Support AC string in fides-js!
* This is difficult to confirm outside of Cypress tests right now since we don't have universal vendor IDs on the backend yet. But if you play around with TCF as usual, you should notice a few things:
* When saving the cookie, we now save the tc string to `fides_tc_string`, and it'll end with `,1~"`. in theory, once we have AC vendor ids working, that string will fill in those AC ids so it'll be more like `1~[id].[id2]` etc.
* Whenever we print out Fides events, the event will include this composite string
* When looking at tcData events, there should not be the composite string (but it'll be included in `tcData` under `addtlConsents`. To look at tcdata events, you can paste this into your console:
```js …
```
=> Frontend AC string support

CHANGELOG.md, clients/fides-js/src/components/tcf/VendorInfoBanner.tsx
Closes bug @pattisdr found with vendor count over-counting
From Dawn:
> This sum seems misleading.  I only have four vendors, all four are using consent, and one is using both consent and legitimate interests.
This fixes that count. Now that vendor relationships and vendor systems have the full list of vendors/systems, we can query off of their lengths directly instead of reconciling their uniqueness.
* Add a vendor with both legint and consent purposes
* It should only show up as 1 vendor in the vendor count
=> Use relationship counts to compute total number of vendors

CHANGELOG.md, src/fides/api/api/v1/endpoints/privacy_preference_endpoints.py, src/fides/api/schemas/privacy_experience.py, src/fides/api/schemas/privacy_preference.py, src/fides/api/util/tcf/experience_meta.py, tests/ops/api/v1/endpoints/test_privacy_experience_endpoints.py, tests/ops/api/v1/endpoints/test_privacy_preference_endpoints.py
Closes https://github.com/ethyca/fidesplus/issues/1163
Use more generic "fides_string" instead of "tc_string" language in GET Experience and PATCH Privacy Preferences endpoints to pave the way for both a TC and AC string being combined in one string.
- GET TCF Privacy experiences or PATCH preferences and verify request and response keys.
[See internal dev docs for expected behavior](https://ethyca.atlassian.net/wiki/spaces/EN/pages/2805006351/2023-10-04+Developer-Friendly+Consent+API+Documentation)
=> Use Fides String instead of TC String language

CHANGELOG.md, clients/fides-js/src/lib/tcf.ts, clients/fides-js/src/lib/tcf/vendors.ts, clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
Closes https://github.com/ethyca/fides/issues/4165
The library we use wants to put every vendor in the GVL as part of the `vendors_disclosed` string. According to the docs, we should only put the vendors we've disclosed, i.e. the ones we've shown in the UI (makes sense!). There's a `vendors_disclosed` field we can set, but that appears to always be overwritten by the library to set the whole GVL. I believe the way around this is to use the [library's `narrowVendorsTo` function](https://github.com/InteractiveAdvertisingBureau/iabtcf-es/tree/master/modules/core#narrow-the-list-of-vendors)
Part of this ticket is also to not surface the vendor disclosed part of the string to the CMP API—that's covered in https://github.com/ethyca/fides/pull/4244
* Set up your TCF environment
* Opt in to some …
=> Narrow vendors disclosed to only the vendors we show in the UI

clients/fides-js/src/lib/tcf.ts, clients/fides-js/src/lib/tcf/vendors.ts, clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
Closes N/A
The AC prefix is actually `gacp`, not `ac`! This accounts for that.
* Everything works as before
=> Rename `ac` prefix to `gacp`

src/fides/api/util/tcf/tc_model.py, tests/fixtures/application_fixtures.py
Incorrectly assumed "ac." was the prefix for AC vendors. It's "gacp."
=> AC Prefix -> gacp Prefix

clients/admin-ui/package.json, clients/admin-ui/src/types/api/models/ExperienceMeta.ts, clients/admin-ui/src/types/api/models/PrivacyPreferencesRequest.ts, clients/admin-ui/src/types/api/models/SavePrivacyPreferencesResponse.ts, clients/admin-ui/src/types/api/models/TCDecode.ts, clients/admin-ui/src/types/api/models/TCFVendorConsentRecord.ts, clients/admin-ui/src/types/api/models/TCFVendorLegitimateInterestsRecord.ts, clients/admin-ui/src/types/api/models/TCFVendorRelationships.ts, clients/admin-ui/src/types/dictionary-api/models/Cookie.ts, clients/admin-ui/src/types/dictionary-api/models/DataUseDeclaration.ts, clients/admin-ui/src/types/dictionary-api/models/Vendor.ts
Regularly scheduled TS type generation 🧹 
Autogenerating TS types after the latest compass integration changes + renaming of `tc_string` to `fides_string`
* There should be no noticeable differences
=> Autogenerate ts types

CHANGELOG.md, clients/fides-js/src/components/fides.css
Sections with a hidden attribute need to stay hidden regardless of externally defined CSS rules
```
<section hidden...>
```
=> Forcing hidden sections to use display none

CHANGELOG.md, clients/fides-js/src/components/fides.css, clients/privacy-center/public/fides-js-components-demo.html
Closes https://github.com/ethyca/fides/issues/4307
Cleans up CSS for fides embed modal. Specifically does 2 things:
1. Removes outline from modal in embed mode
2. Fixes mobile responsiveness (flex) in embed mode
=> css fixes for fides embed modal

CHANGELOG.md
No associated issue, this is a docs chore.
Adds the CVE numbers to the `2.22.1` changelog.
* No code changes.
* Review `CHANGELOG.md` markdown.
=> Update 2.22.1 changelog with CVE numbers

tests/ops/models/test_privacy_preference.py
Closes n/a
we had a [small typo in our test in this PR](https://github.com/ethyca/fides/commit/9904b4f7f87da2b3a3a2cefefc1ad20cff1ee32b#diff-414f2caccaa58158d216b278fb0ae93cc810941e12bbc6507f83718602cd08deR139), fix this up to avoid test failures
n/a
=> fix up url typo in test

clients/fides-js/src/lib/tcf/utils.ts, clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
Today, providing a `fides_string` with an AC suffix throws a runtime error when decoding, which is just because #4308 is  in review. In the short-term, I'd like to get the current version "forwards-compatible" with that solution by just discarding the AC suffix. Ideally I should have included this in #4314 👍 
=> Add additional error handling for `fides_string` override options

CHANGELOG.md, src/fides/api/models/privacy_experience.py, src/fides/api/models/privacy_preference.py, tests/fixtures/application_fixtures.py, tests/ops/api/v1/endpoints/test_privacy_preference_endpoints.py, tests/ops/models/test_privacy_experience.py, tests/ops/models/test_privacy_preference.py
Closes https://github.com/ethyca/fidesplus/issues/1167
Update hardcoded TCF Version saved for consent reporting to 2.2.
```
curl -X 'GET' \
'http://localhost:8080/api/v1/privacy-experience?show_disabled=true&fides_user_device_id=6f8692dc-43f7-4dc5-97bb-4560c73f5503&systems_applicable=false&include_gvl=false&include_meta=false&page=1&size=50' \
-H 'accept: application/json'
```
PATCH http://localhost:8080/api/v1/privacy-preferences
```
{
"purpose_consent_preferences": [{"id": 10, "preference": "opt_in"}],
"browser_identity": {
"fides_user_device_id": "6f8692dc-43f7-4dc5-97bb-4560c73f5503"
}
}```
```
curl -X 'GET' \
'http://localhost:8080/api/v1/privacy-experience?show_disabled=true&fides_user_device_id=6f8692dc-43f7-4dc5-97bb-4560c73f5503&systems_applicable=false&include_gvl=false&include_m …
```
=> Backend: Update TCF Version
