ethyca/fides

CHANGELOG.md
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/lib/a11y-dialog.tsx

Closes https://ethyca.atlassian.net/browse/PROD-1266
Removes overflow styling for embedded modal in Fides.js

PROD-1266 Removes overflow styling for embedded modal in Fides.js

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/constants.ts
src/fides/api/api/v1/endpoints/privacy_experience_config_endpoints.py
tests/ops/api/v1/endpoints/test_privacy_experience_config_endpoints.py

Closes https://ethyca.atlassian.net/browse/PROD-1273
We have an endpoint that retrieves the Privacy Experience Config resources, which contain the language or the copy used for each experience type.  This is the endpoint that is queried on the "Privacy Experience" page.  TCF copy returns, regardless of whether TCF is enabled.
Also adds this casing change:

Restrict TCF Privacy Experience Config if TCF Disabled

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/systems-plus.cy.ts
clients/admin-ui/cypress/e2e/taxonomy-plus.cy.ts
clients/admin-ui/cypress/support/stubs.ts
clients/admin-ui/src/features/system/SystemInformationForm.tsx
clients/admin-ui/src/features/system/dictionary-form/dict-suggestion.slice.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts

Closes https://ethyca.atlassian.net/browse/PROD-1255
This was a very strange bug, and I think it was introduced by https://github.com/ethyca/fides/pull/4294#discussion_r1362890811 but even that seems to be a bit of a red herring... 
First I found that if I reverted that particular change described in that comment, things worked. I did a diff between `systemBody` and `result.data`, then added all the fields until I found the one that was causing things to break which was mysteriously `third_country_transfers`. There's no rhyme or reason to this as far as I can tell, so I dug further...
Then I realized the only fields that were being reset were the dictionary fields, so I looked specifically at `useDictSuggestion`.
It seems like this line …

Add initial state to suggestions

---

src/fides/data/gvl.json
tests/ops/util/test_tc_string.py

Closes n/a
We still hardcode the GVL.json (hopefully not for long!), but we need to keep things up to date while we do.

update hardcoded gvl json to latest version

---

CHANGELOG.md
clients/fides-js/src/components/ConsentContent.tsx
clients/fides-js/src/components/ConsentModal.tsx
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/components/fides.css
clients/fides-js/src/lib/a11y-dialog.tsx
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes https://ethyca.atlassian.net/browse/PROD-1277
Refactor embedded mode to not use A11y dialog.
https://www.loom.com/share/b68e6001f2bb49ffa3904d4324446643

PROD-1277 Refactor embedded mode to not use A11y dialog

---

CHANGELOG.md
clients/fides-js/src/lib/tcf/utils.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/fixtures/consent/experience_tcf.json
clients/privacy-center/cypress/fixtures/consent/notices_served_tcf.json

Closes https://ethyca.atlassian.net/browse/PROD-1295
There was a bug where vendor IDs weren't being parsed from the `fides_string` to the cookie properly. The cookie expects these IDs to be prefixed by `gvl` (since all TCF vendors in the experience will be prefixed by `gvl`, and that allows `updateExperienceFromCookieConsent` to work properly) but the TC string has no concept of our prefixed IDs.
https://www.loom.com/share/81339746560b4f7cbae7200fd1e6470e?sid=9fc5ad92-130b-4886-8ce5-e1f3718793d3

String override initialization bug

---

CHANGELOG.md
clients/admin-ui/src/features/plus/plus.slice.ts
clients/admin-ui/src/types/api/index.ts
clients/admin-ui/src/types/api/models/BulkCustomFieldRequest.ts
clients/admin-ui/src/types/api/models/ExperienceConfigCreate.ts
clients/admin-ui/src/types/api/models/ExperienceConfigResponse.ts
clients/admin-ui/src/types/api/models/ExperienceConfigUpdate.ts
clients/admin-ui/src/types/api/models/MySQLDocsSchema.ts
clients/admin-ui/src/types/api/models/Page_PrivacyExperienceMetaResponse_.ts
clients/admin-ui/src/types/api/models/PrivacyExperienceMetaResponse.ts
clients/admin-ui/src/types/api/models/ServingComponent.ts
clients/admin-ui/src/types/api/models/TCDecode.ts
clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/consent-utils.ts
clients/fides-js/src/lib/cookie.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/support/mocks.ts

Closes https://ethyca.atlassian.net/browse/PROD-1281
Rely on the backend calculated `version_hash` to determine whether or not to resurface the banner.
https://www.loom.com/share/0a3d388b388543428c1b75ede2184e21?sid=44f41194-e921-4217-b42c-70185d4c44c0
See loom video for an example

Resurface TCF consent (frontend)

---

CHANGELOG.md
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/initialize.ts
clients/fides-js/src/lib/tcf/utils.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes https://ethyca.atlassian.net/browse/PROD-1281
Passing in an invalid `fides_string` will now ignore it instead of breaking the app!
In the video, both with and without a fides string give the same result.
https://github.com/ethyca/fides/assets/24641006/ad1103e5-ccb6-4451-aebe-8de27e59b648

Handle decoding problems with passed in `fides_string`

---

CHANGELOG.md
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/events.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts

Closes [PROD-1280](https://ethyca.atlassian.net/browse/PROD-1280)
`FidesUpdated` is now only called when a user makes a change, not after initialization. 
https://github.com/ethyca/fides/assets/24641006/cc23f278-9f79-450e-a6cd-c45b87b6499c
[PROD-1280]: https://ethyca.atlassian.net/browse/PROD-1280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove duplicate `FidesUpdated` event and trigger `FidesInitialized` twice instead

---

CHANGELOG.md
src/fides/api/util/tcf/tc_model.py
tests/ops/util/test_tc_string.py

Closes https://ethyca.atlassian.net/browse/PROD-1311
Google Ads considers this an error and will only accept service-specific scopes
```
curl -X 'GET' \
'http://localhost:8080/api/v1/privacy-experience?show_disabled=true&region=fr&systems_applicable=false&include_gvl=false&include_meta=true&page=1&size=50' \
-H 'accept: application/json'
```

Backend TC String Is Service Specific should be True 

---

CHANGELOG.md
clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/ConsentContent.tsx
clients/fides-js/src/components/fides.css
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Update fides.css; tcf banner will be full width and non-tcf will be no greater than 75% width
https://github.com/ethyca/fides/assets/101993653/436f9c06-6047-4aec-adb3-cb1bdc80efb2

Update fides.css to vary width based on tcf

---

CHANGELOG.md
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/a11y-dialog.tsx
clients/fides-js/src/lib/consent-constants.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/initialize.ts
clients/privacy-center/app/server-environment.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/pages/api/fides-js.ts

Closes https://ethyca.atlassian.net/browse/PROD-1305
Adds fides_disable_banner config option, and as part of this, fixes bug where fidesUIShown event was not triggered for fidesEmbed mode.

PROD-1305 adds fides_disable_banner config option, fix bug with triggering fidesUIShown event for fidesEmbed mode

---

CHANGELOG.md
src/fides/api/schemas/tcf.py

Partially closes https://ethyca.atlassian.net/browse/PROD-1318
We need legal basis for processing on top-level Special Purposes again for frontend filtering.  We're not saving against Special purpose x legal basis combination but we do need it for display.  Even though data uses can only have one legal basis for processing, surfacing this as a list in case a special purpose is claimed on multiple vendors with differing legal bases.

Restore Legal Bases List to TCF Special Purpose Records

---

src/fides/api/schemas/connection_configuration/saas_config_template_values.py
src/fides/api/service/connectors/saas/connector_registry_service.py

Closes n/a
A tweak that attempts to address my concerns in https://github.com/ethyca/fides/pull/4374#pullrequestreview-1713655357

implement enabled actions support in a more extensible manner

---

CHANGELOG.md
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/initialize.ts
clients/fides-js/src/lib/preferences.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes https://ethyca.atlassian.net/browse/PROD-1241
Adds support for custom get preferences fn

PROD-1241 Adds support for custom get preferences fn

---

clients/admin-ui/cypress/e2e/systems.cy.ts
clients/admin-ui/cypress/fixtures/systems/system.json
clients/admin-ui/cypress/fixtures/systems/systems.json
clients/admin-ui/cypress/fixtures/systems/systems_with_data_uses.json
clients/admin-ui/src/features/system/form.ts
clients/admin-ui/src/types/api/models/BasicSystemResponse.ts
clients/admin-ui/src/types/api/models/System.ts
clients/admin-ui/src/types/api/models/SystemResponse.ts

Closes https://ethyca.atlassian.net/browse/PROD-1319
Frontend change needed to make sure https://github.com/ethyca/fides/pull/4383 doesn't break things for the UI!
```
{
"fides_key": "system_a",
"system_type": "system",
"name": "System A",
"description": "test description",
"privacy_declarations": [],
"cookies": [
{
"name": "test_cookie",
"path": "/",
"domain": "https://www.example.com"
}
]
}
```

System level cookie handling

---

CHANGELOG.md
clients/fides-js/src/components/ConsentContent.tsx

Closes FIDES-247
Requested by a user that noticed the `h1` element used in the consent overlay modal could detract from SEO.
Found that there is an existing style variable for this (`--fides-overlay-font-size-title`) that was in some cases being overridden by the `h1` element if styled.
Switching to a `p` allowed the expected style to be used
With styled `h1`:
Without styled `h1`:
After change to a `p`:
This could potentially result in some change in default appearance for the overlay, which should be reviewed (not a one person choice I think)

Replace h1 with p in consent overlay modal

---

CHANGELOG.md
clients/fides-js/src/components/ConsentContent.tsx

Closes FIDES-247
Requested by a user that noticed the `h1` element used in the consent overlay modal could detract from SEO.
Found that there is an existing style variable for this (`--fides-overlay-font-size-title`) that was in some cases being overridden by the `h1` element if styled.
Switching to a `div` allowed the expected style to be used
With styled `h1`:
Without styled `h1`:
After change to a `div`:
This could potentially result in some change in default appearance for the overlay, which should be reviewed (not a one person choice I think)

Replace h1 with div in consent overlay modal

---

CHANGELOG.md
clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/fides.css

Relates to PROD-1320
As part of the release testing, an issue with alignment for the privacy policy link was identified. The issue impacted the non-TCF modal and overlay

Privacy Policy alignment in non-TCF consent overlay banner and modal

---

CHANGELOG.md
clients/fides-js/src/components/ConsentBanner.tsx

Fixes an accidentally-backwards ternary I added to #4403! Whoops.

Fix dynamic class name for TCF-variant of consent banner

---

CHANGELOG.md
clients/fides-js/src/lib/tcf.ts

Closes https://ethyca.atlassian.net/browse/PROD-1312
Updates TC string generation code to specify `isServiceSpecific=true`. Also forces encoded segments, see ticket for reasoning behind that!

Set isServiceSpecific to true during TC string generation

---

clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx
src/fides/api/api/v1/endpoints/privacy_request_endpoints.py
src/fides/api/common_exceptions.py
src/fides/api/models/manual_webhook.py
src/fides/api/service/privacy_request/request_runner_service.py
src/fides/api/task/graph_task.py
tests/ops/integration_tests/saas/connector_runner.py
tests/ops/integration_tests/test_enabled_actions.py
tests/ops/models/test_manual_webhook.py
tests/ops/task/test_graph_task.py

Adds `enabled_actions` checks to various parts of the `graph_task` and `request_runner_service`. Since connectors often times require access data to be able to perform an erasure, access requests are still executed but are filtered out from being included in the final DSR package. Collections for erasure and consent requests are marked as skipped if their associated connection config does not contain the correct `enabled_actions` values. A `None` value for `enabled_actions` (as will be the case for OSS instances) will allow all actions to execute.

Adding enabled actions to DSR workflow

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/systems-plus.cy.ts
clients/admin-ui/src/features/system/SystemInformationForm.tsx
clients/admin-ui/src/features/system/add-multiple-systems/AddMultipleSystems.tsx
clients/admin-ui/src/features/system/add-multiple-systems/MultipleSystemsFilterModal.tsx

Closes [PROD-1354
](https://ethyca.atlassian.net/browse/PROD-1354)
Persist filter modal state after it's closed.
https://github.com/ethyca/fides/assets/17103888/75377db2-0279-4706-b65a-89958ecf77ca

Persist filter modal state after it's closed

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/system-integrations-plus.cy.ts
clients/admin-ui/src/features/common/form/inputs.tsx
clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx

Request type field enhancements

Fixing request type field

---

CHANGELOG.md
clients/admin-ui/src/types/api/models/ConsentMethod.ts
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/tcf/TcfConsentButtons.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/events.ts
clients/fides-js/src/lib/preferences.ts
clients/fides-js/src/services/api.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts
src/fides/api/models/privacy_preference.py

Closes https://ethyca.atlassian.net/browse/PROD-1328
Adds new enum members to `ConsentMethod`, ensure we're passing these new granular consent methods in our overlay components, and update our custom save preferences fn to intake consent method.

Prod 1328 Track more granular consent method

---

clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationDisplayGroup.tsx
clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationFormTab.tsx

Closes #4427 
Removes button from dictionary data use table.
With Compass enabled:
* Create a system
* View data uses populated from Compass (or add one manually)
* Sparkle button should *not* be present on table header:

Remove button to populate data uses from dictionary from data use table

---

CHANGELOG.md
clients/fides-js/src/lib/cookie.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes https://ethyca.atlassian.net/browse/PROD-1389
For TCF, if we have a previously saved `fides_consent` cookie or a `fides_string` override,  any consent pref that is not defined on cookie.tcf_consent should be assumed opt-out, instead of using the defaults on the experience.

PROD-1389 for TCF, any consent pref that is not defined on cookie should be assumed opt-out

---

CHANGELOG.md
requirements.txt
src/fides/api/alembic/migrations/versions/1af6950f4625_update_flexible_legal_basis_default.py
src/fides/api/models/sql_models.py
tests/ctl/core/test_api.py

❗ ~Contains migration; check downrev~
❗ ~Dependent on fideslang release of https://github.com/ethyca/fideslang/pull/184~
Closes #PROD-1264
Make "flexible legal basis for processing" non nullable and True by default in the backend.
- Update PrivacyDeclaration.flexible_legal_basis_for_processing to get rid of the third state. Make it required, and set the server default to True, to match what should happen when systems are created outside of Compass.
- Add a migration that first updates existing flexible_legal_basis_for_processing to False if it is currently null, then adds the new server default and makes it required.

Flexible Legal Basis = True Default

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/oauth_endpoints.py
src/fides/api/api/v1/endpoints/user_endpoints.py
src/fides/api/main.py
src/fides/api/models/client.py

Closes https://ethyca.atlassian.net/browse/PROD-1330
To help mitigate and be aware of a potential security weakness in production deployments, we've decided to provide some logging when the root user is in use. Specifically, we're providing:
- a warning message on server startup (both fides and fidesplus)
- a warning message whenever the root user credentials are successfully used for a user "login"
- a warning message whenever the root oauth client credentials are used to successfully acquire a client access token
Below is some logging i captured on my local fides server with representative actions as root user, to get an idea of what logs look like. To me, the only real questions are:
- ~should we change "info message when token is merely requested, warning if the token is actually …

PROD-1330: logging for root user access

---

Dockerfile

Fixes problem where fides was unable to determine its own version on our built `prod` image
Corresponds to https://github.com/ethyca/fidesplus/pull/1230

ensure setup.py is run as fidesuser in docker build

---

Dockerfile

cherry pick of https://github.com/ethyca/fides/pull/4446 into `main`, since it'd been merged directly into `release-2.24.1`

ensure setup.py is run as fidesuser in docker build: cherry pick #4446 into `main`

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/systems.cy.ts
clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationDisplayGroup.tsx

Closes #PROD-1317
Adds a confirmation modal on deleting a data use which warns the user that the data use and cookies will be deleted.
[Loom video](https://www.loom.com/share/ff3a3e16812e457180b744409bfa8bcb)

Add confirmation modal on deleting a privacy declaration

---

clients/admin-ui/cypress/e2e/systems-plus.cy.ts

Closes N/A
Adds more waits to help with test flakiness. The waits help on slow networks—on fast networks we don't need the "wait"s since they kind of just happen right away, but on slow networks (like in CI) we should explicitly wait.

Add more waits to reduce flakiness on slow networks for cypress tests

---

CHANGELOG.md
clients/fides-js/src/components/tcf/TcfVendors.tsx
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/fixtures/consent/experience_tcf.json

Closes https://ethyca.atlassian.net/browse/PROD-1396
Fix type errors when tcf vendors have no dataDeclaration. This PR fixes 2 possible errors that could arise in this case. I've also added e2e tests to confirm this is fixed.

PROD-1396 Fix typeerror when tcf vendors have no dataDeclaration

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/systems-plus.cy.ts
clients/admin-ui/src/pages/systems/configure/[id].tsx

Closes #PROD-1451
Fixes a bug where "system is locked for GVL" notice would appear on AC systems when accessing them to edit, and add a Cypress test to verify.
With TCF enabled:

Fix GVL vendor lock occurring on AC systems

---

CHANGELOG.md
clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/support/constants.ts

Closes https://ethyca.atlassian.net/browse/PROD-1420
Adds Cypress tests for the GPP extension!

Add tests for GPP extension

---

CHANGELOG.md
clients/fides-js/__tests__/lib/consent-utils.test.ts
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/consent-utils.ts
clients/fides-js/src/lib/initialize.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/support/commands.ts
clients/privacy-center/cypress/support/constants.ts
clients/privacy-center/pages/api/fides-js.ts

Closes https://ethyca.atlassian.net/browse/PROD-1243
Adds ability to provide custom fides overrides path, e.g. "window.config.override_options". The default is now "window.fides_overrides" if this config var isn't provided.

PROD-1243- adds ability to provide custom fides overrides path

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/user_permission_endpoints.py

Closes PROD-1480
Changes the log level of `Retrieved FidesUserPermission record for current user` message to `DEBUG` instead of `INFO`. When a user is browsing around the Admin UI, these logs show up almost every other line and make it harder to follow logs. They still have value, but I believe that `DEBUG` is a better level for them.

PROD-1480: Update logging level for 'Retrieved FidesUserPermission record for current user' message to Debug

---

tests/ops/api/v1/endpoints/test_config_endpoints.py

A test regression slipped through and this remedies that.

Fix get config test regression

---

clients/fides-js/__tests__/lib/consent-utils.test.ts
clients/fides-js/src/lib/consent-utils.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Fixes #PROD-1243
When testing PROD-1243 (from #4462) I found that I could cause `Fides.init(...)` to crash by supplying a nested `options.customOptionsPath` that didn't exist, e.g.
```
Fides.init({
options: {
customOptionsPath: "window.nonexistent_object.nested.path",
},
...
})
```
This throws an error like:
```
(uncaught exception)TypeError: Cannot read properties of undefined (reading 'nested')
```

Fix support for nested `options.customOptionsPath`

---

clients/admin-ui/src/features/datamap/GVLDatamapNotice.tsx

https://github.com/ethyca/fides/assets/101993653/182751a3-54fa-45d1-90b4-8b97bf1b93ea

Fix gvl datamap notice spacing

---

src/fides/api/util/tcf/tcf_experience_contents.py
src/fides/config/config_proxy.py
tests/conftest.py
tests/ops/models/test_privacy_preference.py
tests/ops/util/test_tcf_privacy_declarations.py

Closes [PROD-1513](https://ethyca.atlassian.net/browse/PROD-1513)
Use the config proxy for resolving the `consent.override_vendor_purposes` config property in the context of generating the TCF experience, such that we respect any value set for the config via the API.
Note that for https://ethyca.atlassian.net/browse/PROD-1416 we will likely need further changes, because we need to use the config proxy in a different codepath that's not quite as straightforward.
[PROD-1513]: https://ethyca.atlassian.net/browse/PROD-1513?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

use config proxy for purpose override flag check

---

CHANGELOG.md
clients/admin-ui/src/features/common/table/v2/FidesTable.tsx
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/system/add-multiple-systems/AddMultipleSystems.tsx

Closes https://ethyca.atlassian.net/browse/PROD-1329
https://github.com/ethyca/fides/assets/24641006/a16b43a1-ced7-4241-97f1-0dfc5827d072

Bulk add vendors disable state

---

clients/admin-ui/src/features/common/nav/v2/nav-config.ts
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/configure-consent/ConsentMangagementTable.tsx
clients/admin-ui/src/pages/consent/configure/index.tsx

Closes PROD-1515, PROD-1516
This PR addresses feedback based on UAT and release testing.
(Michael signed off on the styling and copy in Jira)

Add back "add vendor" buttons and styling fixes

---

src/fides/api/models/sql_models.py
src/fides/api/util/tcf/tcf_experience_contents.py
tests/ctl/core/test_api.py
tests/ops/util/test_tcf_privacy_declarations.py

Closes PROD-1513 (again)
Ensures that purposes are excluded no matter if they are declared with an inflexible legal basis.

general purpose override blocks purpose in all cases

---

CHANGELOG.md
clients/admin-ui/src/features/configure-consent/AddVendor.tsx

Remove Add Vendor btn from Consent > Vendors page

---

clients/admin-ui/cypress/e2e/consent-configuration.cy.ts

Fix cypress tests after removing the Add Vendor button https://github.com/ethyca/fides/pull/4509

Update cy tests for Manage your vendors page after removing Add Vendors btn

---

CHANGELOG.md
clients/admin-ui/src/features/system/VendorSelector.tsx

Closes #PROD-1449
Fixes a few bugged/incorrect states of the Compass button in the system information form:
* The button is now highlighted in purple while suggestions are being made in the typeahead, instead of only when a vendor is selected
* The button no longer has a hover state when it's disabled (i.e. if suggestions are already being shown, or if no vendor is selected)
* The button is now a menu button
With Compass enabled:
[Loom demo](https://www.loom.com/share/f1c8904833074652b3604384b54e374e)

Fix Compass button states

---

CHANGELOG.md
clients/admin-ui/src/features/system/form.test.ts
clients/admin-ui/src/features/system/form.ts

Closes PROD-1403
This PR aligns the FE with how the bulk vendor add route handles these fields.

PROD-1403: Omit specific fields from system payload if empty

---

CHANGELOG.md
clients/admin-ui/src/types/api/models/ConsentMethod.ts
clients/fides-js/__tests__/lib/cookie.test.ts
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/tcf/TcfConsentButtons.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/events.ts
clients/fides-js/src/lib/initialize.ts
clients/fides-js/src/lib/preferences.ts
clients/privacy-center/components/consent/NoticeDrivenConsent.tsx
clients/privacy-center/cypress/e2e/banner-overlay-dismissal.cy.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts
clients/privacy-center/cypress/e2e/consent-notices.cy.ts
clients/privacy-center/types/api/models/ConsentMethod.ts

This updates both `fides.js` and `fides-privacy-center` to record the "consent method" to the local cookie when preferences are saved, in the same way that we record this information on the server-side preference that is recorded. This'll allow us to inspect this on the frontend, both for troubleshooting (helpful!) but more importantly because I'd like to treat `consentMethod: "dismiss"` differently in a future release so I want to be recording that metadata now 👍 

Save consent method ("accept", "reject", "save", etc.) to `fides_consent` cookie as extra metadata

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/consent-configuration.cy.ts
clients/admin-ui/src/features/configure-consent/AddVendor.tsx

Temporarily (re-)removes the "Add a vendor" button from the consent configuration screen (will be added back with work for [PROD-1549](https://ethyca.atlassian.net/browse/PROD-1549?atlOrigin=eyJpIjoiMGUwOWI0NjQ3MTk2NGEzNWIxMzQzN2U0MTc4YTc0MGYiLCJwIjoiaiJ9)).
[PROD-1549]: https://ethyca.atlassian.net/browse/PROD-1549?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove 'Add a vendor' from consent configuration page

---

clients/admin-ui/cypress/e2e/locations.cy.ts
clients/admin-ui/cypress/fixtures/locations/list.json
clients/admin-ui/src/features/locations/LocationPickerCard.tsx

Closes https://ethyca.atlassian.net/browse/PROD-1561
Fixes bug where toggling "regulated" on a continent that has no regulated subregions would make the whole card disappear

Regulated toggle bug

---

clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts
clients/admin-ui/src/features/privacy-experience/form/helpers.tsx

Closes https://ethyca.atlassian.net/browse/PROD-1566
The new banner title and banner description fields can be null, so the yup schema had to be `nullable` not `optional`

Make banner title and description nullable, not optional

---

src/fides/api/service/privacy_request/dsr_package/dsr_report_builder.py
tests/ops/service/test_storage_uploader_service.py

Closes https://ethyca.atlassian.net/browse/PROD-1470
leading slashes in the constituent filenames were causing problems when unzipping the DSR report/package .zip on windows (when using the native windows zip utility to unzip). as far as i can tell, the leading slashes are unnecessary (and unintentional) - it gets stripped anyway automatically when unzipping on macOS (see below)
unzipping the old .zip package on macOS - note that absolute path (leading slash) is stripped anyway, which makes me think that we never intentionally included this, nor will it have any impact. 
```
→ unzip  ../fides_uploads/pri_65ab2ecd-b325-4d14-a392-76c337473d34.zip
Archive:  ../fides_uploads/pri_65ab2ecd-b325-4d14-a392-76c337473d34.zip
warning:  stripped absolute path spec from /data/main.css
extracting: …
```

remove leading slash in dsr zip report filenames

---

CHANGELOG.md
clients/fides-js/src/lib/tcf.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes N/A. See slack discussion here: https://ethyca.slack.com/archives/CBKK8TS74/p1704904930579039?thread_ts=1704898783.839119&cid=CBKK8TS74
Removes the vendors disclosed portion of the TC string entirely

Remove vendors disclosed entirely from fides.js

---

CHANGELOG.md
requirements.txt
src/fides/api/util/text.py

This is a tiny change to swap out a library used in the `to_snake_case` utility function to `anyascii` which has a safer license.
n/a

Switch to anyascii for unicode transliteration

---

CHANGELOG.md
clients/fides-js/src/lib/cookie.ts
clients/fides-js/src/lib/shared-consent-utils.ts
clients/fides-js/src/lib/tcf/utils.ts

Closes https://ethyca.atlassian.net/browse/PROD-1593
Addresses older Safari browser compatibility issues with using Object.hasOwn()

PROD-1593- replace object.hasown with object.keys().includes

---

CHANGELOG.md
clients/admin-ui/src/features/common/nav/v2/MainSideNav.tsx

Closes https://ethyca.atlassian.net/browse/PROD-1592
The ticket req was to make the management tab in the nav open by default. The reason why it was starting off closed was because, in general, we have the following accordion groups:
1. Overview
2. Data map
3. Privacy requests
4. Consent
5. Management
However, 4. Consent only shows up in plus environments. To figure out if we are in a plus environment, we have to query for it first. During the query time, the nav only sees 4 options, so it says "open 4 accordion tabs" and by the time the plus query says "yes we have plus, render Consent", only the first 4 tabs open up. 
Relatedly, [Michael also commented a while back](https://ethyca.slack.com/archives/C04S7K0T2V7/p1705085365822779):
> Is there any way to delay showing everything until the …

Do not render nav until we are finished loading

---

CHANGELOG.md
src/fides/api/app_setup.py
src/fides/api/custom_types.py
src/fides/api/schemas/application_config.py
src/fides/api/util/cors_middleware_utils.py
src/fides/config/config_proxy.py
src/fides/config/security_settings.py
tests/ctl/core/config/test_security_settings.py
tests/ops/api/v1/endpoints/test_config_endpoints.py

Closes [PROD-1419](https://ethyca.atlassian.net/browse/PROD-1419)
https://www.loom.com/share/c38df34b38194d76aa9b91ae9c32ba33
Fixes the broken CORS `allow_origins` update functionality. Basically, before we were trying to mutate the `allow_origins` attribute on the existing `CORSMiddleware` instance "in-place", which wasn't effective in actually updating middleware's functionality, as it requires some reinitialization.
To fix this, we can instead _remove_ the existing `CORSMiddleware` instance and _add_ a new `CORSMiddleware` instance (with the updated `allows_origins` values) using the proper fastAPI app method.
Some additional notes:
- as before, the complete set of `cors_origins` specified via API (i.e. via admin UI) will be the complete set of `allow_origins` in the server's CORS …

Fix CORS middleware hot-swapping

---

.github/workflows/backend_checks.yml
.github/workflows/cli_checks.yml
.github/workflows/cypress_e2e.yml
.github/workflows/frontend_checks.yml

Closes n/a
We have some edge cases in our release process where CI jobs won't run on the PRs opened from release branches because of merge conflicts between the release branch and `main` (due to cherry picking, or just `main` naturally diverging from the release branch).
the PR of the release branch --> main is just used as a placeholder anyway, it's not meant to actually represent a merge action. so rather than relying on CI being run on the PR action, which will execute a CI run on the _merge_ branch, i.e. what would result from merging the source (release) branch into `main`, we can trigger CI jobs directly against pushes to the release branch.
these CI results may not show up directly on the PR summary, but they should show up as a red/yellow/green status circle next to each commit, …

trigger CI jobs on release-** branch pushes

---

CHANGELOG.md
src/fides/api/service/privacy_request/request_runner_service.py
tests/ops/service/privacy_request/test_request_runner_service.py

Closes [PROD-1634](https://ethyca.atlassian.net/browse/PROD-1634)
Prevention privacy request completion emails from being sent for consent requests.
```
FIDES__NOTIFICATIONS__NOTIFICATION_SERVICE_TYPE=mailgun
FIDES__NOTIFICATIONS__SEND_REQUEST_COMPLETION_NOTIFICATION=true
```
[PROD-1634]: https://ethyca.atlassian.net/browse/PROD-1634?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Preventing completion email from being sent for consent requests

---

setup.py

Closes PROD-1558
I missed an important piece of the move of `pymssql` to optioanl-requirements that was leading to CI failures on fidesplus!
Basically, we weren't actually including the extra/optional dependencies in our package at all 😮. i'm almost positive this was the cause of the fidesplus CI [failures](https://github.com/ethyca/fidesplus/actions/runs/7733467792/job/21085607087), even while pulling in `[all]` of the latest RC tagged packages...`[all]` wasn't even doing anything!
the tarballs from the rc0 package (https://pypi.org/project/ethyca-fides/2.29.0rc0/#files) and the new alpha tag built off this branch (https://test.pypi.org/project/ethyca-fides/2.28.1a4/#files) tell the difference. within `src/ethyca_fides.egg-info/requires.txt`, the alpha tagged package (i.e. with the fix …

add extras require

---

clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx

Closes [PROD-1644](https://ethyca.atlassian.net/jira/software/projects/PROD/issues/PROD-1644)
Fixing error when rendering an empty datamap report.
[PROD-1644]: https://ethyca.atlassian.net/browse/PROD-1644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing error when rendering empty datamap report table

---

clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx
clients/admin-ui/src/types/api/models/AWSConfig.ts
src/fides/cli/commands/generate.py
src/fides/cli/commands/scan.py
src/fides/cli/options.py
src/fides/cli/utils.py
src/fides/connectors/models.py

Closes #4596
This change adds an option to pass `session_token` to the CLI, UI, or API when using the system discovery feature for AWS. Long-term credentials only require an `access_key_id` and `secret_access_key`. As it stands today, this means that long-term credentials have to be created to use any system discovery. By adding an option to use `session_token`s, we now allow for temporary credentials that can reflect the principle of least access.
After setting up the dev environment

Add support for STS-issued AWS Credentials

---

CHANGELOG.md
clients/fides-js/__tests__/lib/cookie.test.ts
clients/fides-js/package.json
clients/fides-js/rollup.config.mjs
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/cookie.ts
clients/fides-js/src/lib/preferences.ts
clients/package-lock.json
clients/privacy-center/app/server-environment.ts
clients/privacy-center/components/consent/ConfigDrivenConsent.tsx
clients/privacy-center/components/consent/ConsentToggles.tsx
clients/privacy-center/components/consent/NoticeDrivenConsent.tsx
clients/privacy-center/components/modals/consent-request-modal/ConsentRequestForm.tsx
clients/privacy-center/pages/api/fides-js.ts
clients/privacy-center/pages/consent.tsx

Closes https://ethyca.atlassian.net/browse/PROD-1538
Adds ability to use base64 cookie so that we send less data across all client <---> server packets. This is better for both performance and also decreases chance we'll get flagged by OWASP SQL injection rules.
We give our users the option to configure using base64 in a new env var: `FIDES_PRIVACY_CENTER__BASE_64_COOKIE` which defaults to `false`.

PROD-1538: Adds ability to use base 64 cookie format

---

CHANGELOG.md
clients/admin-ui/src/features/config-wizard/AuthenticateAwsForm.tsx
tests/ctl/cli/test_utils.py
tests/ctl/connectors/test_aws.py

Closes https://github.com/ethyca/fides/issues/4607
- Provides test coverage for functionality added in https://github.com/ethyca/fides/pull/4603
- Fixes tests accidentally broken y https://github.com/ethyca/fides/pull/4603
- Small UI addition to finish up what was started in https://github.com/ethyca/fides/pull/4603

AWS temporary cred test coverage, UI + test cleanup

---

clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/lib/a11y-dialog.tsx
clients/privacy-center/cypress/e2e/banner-overlay-dismissal.cy.ts

Closes # https://ethyca.atlassian.net/browse/PROD-1650
The "x" button will now be all that allows a user to dismiss consent banner and modal.

Remove click outside and esc dismissal

---

CHANGELOG.md
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/initialize.ts
clients/privacy-center/cypress/e2e/show-modal.cy.ts

Closes [PROD-1689](https://ethyca.atlassian.net/browse/PROD-1689)
Adds `Fides.showModal` to be able to manually trigger the modal if supported by the current experience configuration.
[PROD-1689]: https://ethyca.atlassian.net/browse/PROD-1689?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding Fides.showModal

---

src/fides/api/models/privacy_experience.py

Part of PROD-1606, needed for plus PR https://github.com/ethyca/fidesplus/pull/1317
Update the `PrivacyExperience` model to include a `gvl_translations` field that will be passed in the response payload.

add gvl_translations field to privacy experience model

---

CHANGELOG.md
src/fides/api/tasks/__init__.py

Without this change, we don't configure the loguru logger on the worker app/process. This means that even though we may have set e.g. `logging.serialization = json` on the worker container, it wouldn't actually impact the log behavior on the worker in any way.
With this change, before booting up the celery worker app, we now invoke the same `setup()` logging function that's invoked when creating our fides fast API app (i.e. within `create_fides_app`). This ensures consistent logging configuration across both our server and worker apps 👍 
* example: 
```
{"text": "2024-02-20 20:58:04.084 | ERROR    |  - Connector request failed. | {'action_type': 'access', 'system_key': 'asdf', 'connection_key': 'asdf_braze_api', 'collection': 'subscription_groups', 'privacy_request_id': …
```

configure logger on worker initialization

---

clients/admin-ui/src/features/system/history/SystemHistoryTable.tsx

Closes # https://ethyca.atlassian.net/browse/PROD-1580
This is a frontend half measure to hide empty rows in the system history tab. The backend still needs to be fixed https://ethyca.atlassian.net/browse/PROD-1567. 
``` 
{
"fides_key": "123456",
"name": "test 123",
"dpo": null,
"legal_address": null,
"privacy_declarations": [],
"system_type": "SaaS"
}
```

Hide empty history rows

---

src/fides/api/alembic/migrations/versions/fd52d5f08c17_system_dictionary_data_migration.py

Closes n/a
a little while back, we [adjusted](https://github.com/ethyca/fides/commit/7bef8b4ea8761049b1148654370e96e0dbe7a7ea) our db migration that creates the `array_accum` aggregate function to differ its syntax depending on db version, due to a change in postgres typing in version 14.
what we forgot to do was update a corresponding `DROP AGGREGATE IF EXISTS` statement to have the appropriate syntax for the version in question! the practical effect here is _very, very_ narrow - the only real scenario this would come up in is when the function actually already exists when we run this migration. that basically only happens if we've downgraded and are re-upgrading, OR if we are invoking the `db/reset` API endpoint/command!
we did hit this on a cloud (internal) env when trying to invoke …

update drop statement depending on db version

---

clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts
clients/admin-ui/src/features/privacy-experience/cells.tsx
clients/admin-ui/src/features/privacy-experience/privacy-experience.slice.ts

Updates the toggle switch in privacy experience table to use the `experience-config/{id}/limited_update` endpoint, rather than the generic PATCH endpoint which requires more fields.
* Add new Redux query for `/limited_update` endpoint
* Change EnablePrivacyExperienceCell to use new query

Fix "enable/disable" toggle in privacy experience table

---

CHANGELOG.md
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/lib/consent-utils.ts
clients/fides-js/src/lib/consent-value.ts
clients/fides-js/src/lib/initialize.ts
clients/fides-js/src/lib/shared-consent-utils.ts
clients/privacy-center/components/consent/NoticeDrivenConsent.tsx

Closes https://ethyca.atlassian.net/browse/PROD-1755
This addresses a bug where closing consent overlay via "x" sometimes overrides saved preferences. The issue was two-fold, in the code that determined what preferences to save when the "x" was clicked:
1. We wrapped code in a useMemo, which means it only ran once, and could not update once the user saved prefs on the banner/modal 
2. We were relying on the `cookie` variable, which doesn't actually get updated when the user saved prefs on the banner/modal 
So the fix was to remove the useMemo wrapper, and instead use a plain old fn, in addition to retrieving the fides consent cookie when this fn is called on modal / banner dismissal. 

PROD-1755: Fix bug where closing consent overlay via "x" sometimes overrides saved preferences

---

clients/admin-ui/src/features/common/nav/v2/MainSideNav.tsx

The blue outline caused by clicking the side nav was not pretty. This PR removes that focus outline. 

Remove focus outline from nav

---

CHANGELOG.md
src/fides/core/user.py
src/fides/core/utils.py
tests/ctl/core/test_user.py

Fixes issue introduced in #2153
`fides user login` stores the plaintext password to the `~/.fides-credentials` file. This removes the password since it's not actively used anywhere.

Remove password from credentials object

---

clients/fides-js/__tests__/lib/i18n/i18n-utils.test.ts
clients/fides-js/src/lib/i18n/i18n-utils.ts

Quick update to our `i18n` module to fix an issue that @jpople found while testing it out! Basically we weren't allowing you to update a particular message translation more than once, which would normally be fine, but breaks when we repeatedly initialize FidesJS in preview mode 👍

Update i18n.load() to replace existing messages with newer ones

---

src/fides/data/language/languages.yml
tests/ops/integration_tests/saas/connector_runner.py
tests/ops/schemas/language/test_language.py

Closes #PROD-1735 
Partially closes, just continued updates to backend translations 
We currently support language code "es" and are adding additional support for "es-MX" language code.

Add Spanish (Mexico) es-MX language code

---

clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx

Closes #[PROD-1778](https://ethyca.atlassian.net/browse/PROD-1778)
Remove "Customize appearance" button from experience config 
[PROD-1778]: https://ethyca.atlassian.net/browse/PROD-1778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove "Customize appearance" button from experience config 

---

clients/fides-js/src/components/DataUseToggle.tsx
clients/fides-js/src/components/Toggle.tsx
clients/fides-js/src/components/notices/NoticeToggles.tsx
clients/fides-js/src/components/tcf/RecordsList.tsx
clients/fides-js/src/components/tcf/TcfFeatures.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/components/tcf/TcfPurposes.tsx
clients/fides-js/src/components/tcf/TcfTabs.tsx
clients/fides-js/src/components/tcf/TcfVendors.tsx
clients/privacy-center/cypress/e2e/consent-i18n.cy.ts

Closes PROD-1754
This is a quick change to hide the "On" / "Off" toggle labels in any language other than English - basically, I don't think we can safely design these toggles without assuming they are fixed width, so I don't want us to try supporting anything remotely dynamic 👍
Here's a couple quick screenshots for UAT:
| Component | English | Spanish |
|---|---|---|
| Banner + Modal | ![image](https://github.com/ethyca/fides/assets/1834295/89a92848-9657-4313-8001-8bb122d37b89) | ![image](https://github.com/ethyca/fides/assets/1834295/3863233e-cc4b-4b0f-8897-5869f2111bca) |
| TCF Overlay | ![image](https://github.com/ethyca/fides/assets/1834295/71b46c0e-567e-4203-ba72-79836ca09bd1) | ![image](https://github.com/ethyca/fides/assets/1834295/71bca90f-ce51-456a-af6f-f72a45527c52) |
⚠️ NOTE: …

Hide On/Off toggle labels in non-default locales

---

src/fides/api/alembic/migrations/versions/14acee6f5459_translation_data.py
src/fides/api/alembic/migrations/versions/32497f08e227_translation_cleanup.py
src/fides/api/alembic/migrations/versions/a1e23b70f2b2_add_notice_and_exp_translations.py
src/fides/api/service/saas_request/override_implementations/oracle_responsys_request_overrides.py
tests/fixtures/saas/oracle_responsys_fixtures.py

Closes #PROD-1785
We are making adjustments to our out of the box Canadian Experience Configs and the data migration needs to take that into account:
```yaml
- id: pri-694e-02bd-4afe-81b3-2a2ban-modal
name: "Canada Banner + Modal"
regions:
- ca_ab
- ca_bc
- ca_mb
- ca_nb
- ca_nl
- ca_ns
- ca_nt
- ca_nu
- ca_on
- ca_pe
- ca_sk
- ca_yt
component: banner_and_modal
allow_language_selection: false
auto_detect_language: true
dismissable: true
disabled: true
privacy_notice_keys:
- marketing
- id: pri-d9ed6-25e7-4953-8977-772ban-modal
name: "Quebec Banner + Modal"
regions:
- ca_qc
component: banner_and_modal
allow_language_selection: false
auto_detect_language: true
dismissable: true
disabled: true
privacy_notice_keys:
- essential
- marketing
- analytics
```

Canadian Mulitranslation Data Migration Adjustments

---

CHANGELOG.md
clients/admin-ui/src/features/common/nav/v2/nav-config.ts
clients/admin-ui/src/flags.json

Closes https://ethyca.atlassian.net/browse/PROD-1747
Remove location and regulation beta flag so that the location page and the regulation 

Remove location and regulation beta flag

---

src/fides/api/alembic/migrations/versions/14acee6f5459_translation_data.py

Closes #PROD-1797
In the multitranslation data migration, we originally were disabling the new Experience Configs in the data migration as the safer default and added a manual step to enable them afterwards. However, we've learned it's preferable to ship with a preference towards enabling them if they can be enabled.

Conditionally Enabling Migrated Experience Configs

---

clients/admin-ui/src/features/privacy-experience/Preview.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx
clients/admin-ui/src/features/privacy-experience/preview/helpers.ts

Closes PROD-1686
* hide "Experience type" field and privacy notice selector when editing TCF experience
* hide preview, instead show placeholder with notice that preview is now shown for TCF

UX for experience config form for TCF

---

clients/admin-ui/src/features/privacy-experience/Preview.tsx

Closes PROD-1810
Fix an issue where:
* when creating/editing a "modal" experience, the preview modal would show in the top-right corner and have a modal overlay that prevented interaction elsewhere on the page
* when creating/editing a "banner and modal" experience, only the banner and not the modal would be shown in the preview
Issue was somewhere in Next's build process for production builds, was not occurring in a regular local dev build.

Fix modal preview not being shown/shown in the wrong position

---

clients/fides-js/__tests__/lib/i18n/i18n-utils.test.ts
clients/fides-js/src/lib/i18n/i18n-utils.ts

Handle a mismatch in translations between experience & GVL translations

---

clients/fides-js/__tests__/lib/i18n/i18n-utils.test.ts
clients/fides-js/src/lib/i18n/i18n-utils.ts

Closes PROD-1811
This is a small follow-up to #4689 

Select from GVL translations using a case-insensitive locale match

---

clients/fides-js/__tests__/__fixtures__/mock_experience.json
clients/fides-js/__tests__/lib/i18n/i18n-utils.test.ts
clients/fides-js/src/lib/i18n/i18n-utils.ts
clients/privacy-center/cypress/fixtures/consent/experience_banner_modal.json
clients/privacy-center/cypress/fixtures/consent/experience_banner_modal_notice_only.json
clients/privacy-center/cypress/fixtures/consent/experience_privacy_center.json
clients/privacy-center/cypress/fixtures/consent/fidesjs_options_banner_modal.json

Closes PROD-1824
Fixes a silly bug where I was attempting to load GVL translations for a non-TCF banner, which led to _all_ translations being discarded and the modal rendering like this:

Fix FidesJS to not attempt to load GVL translations for regular banner/modal components

---

clients/admin-ui/cypress/e2e/privacy-notices.cy.ts
clients/admin-ui/cypress/fixtures/privacy-notices/notice.json
clients/admin-ui/src/features/privacy-notices/PrivacyNoticeForm.tsx
clients/admin-ui/src/features/privacy-notices/PrivacyNoticesTable.tsx
clients/admin-ui/src/features/privacy-notices/privacy-notices.slice.ts

Closes #1457
Populates disabled/uninteractable "locations" field on privacy notice form.
Run backend on fidesplus branch `consent_multitranslation_plus`.  In `.fides/fides.toml`, make sure translations are enabled:
```
[consent]
enable_translations = true
```

Fix location display on privacy notice form

---

clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/ConsentModal.tsx
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/privacy-center/cypress/e2e/banner-overlay-dismissal.cy.ts
clients/privacy-center/public/fides-js-components-demo.html

Closes https://ethyca.atlassian.net/browse/PROD-1600
Allows consent banner / modal to be dismissable based on both the `PREVENT_DISMISSAL` env var and the `experience_config.dismissable` option.
This change prefers the `PREVENT_DISMISSAL` env var, so if that's set to "true", we respect that over any other setting, and do not show the "x". With any other case, we look at the `experience_config.dismissable` option to determine whether or not to show the "x".

PROD-1600 Implement experience-config-driven dismissable consent components

---

CHANGELOG.md
clients/admin-ui/src/features/common/ScrollableList.tsx
clients/admin-ui/src/features/privacy-experience/ConfigurePrivacyExperience.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceTranslationForm.tsx
clients/admin-ui/src/features/privacy-experience/form/helpers.tsx

Fixes the following from https://ethyca.atlassian.net/wiki/spaces/PM/pages/2957672451/Product+UAT:
* TCF Overlay missing some translation fields: Banner title, Banner description
* Additional translation fields should be required: Save button label, Acknowledge button label
* All optional translation fields should say “(optional)” for consistency: Banner title, Banner description, Privacy policy link label, Privacy policy link URL
* Privacy Experience Config - Long property names overflow from the list container

FE fixes related to experience config form

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/Preview.tsx

Add no preview notice for Privacy Center types to the Experience preview window

Add no preview notice for Privacy Center types

---

CHANGELOG.md
clients/admin-ui/src/features/common/nav/v2/nav-config.ts
clients/admin-ui/src/flags.json

Remove properties flag

---

src/fides/api/alembic/migrations/versions/14acee6f5459_translation_data.py

Closes #PROD-1834
On RC environment, data migration hit the following error:
```sql
[SQL:
INSERT INTO privacynoticehistory (id, name, description, origin, consent_mechanism, data_uses, version, disabled, enforcement_level, has_gpc_flag, internal_description, notice_key, gpp_field_mapping, framework, language, title, translation_id, privacy_notice_id)
SELECT %(record_id)s, name, description, origin, consent_mechanism, data_uses, %(new_version)s, disabled, enforcement_level, has_gpc_flag, internal_description, notice_key, gpp_field_mapping, framework, %(language)s, title, translation_id, privacy_notice_id
FROM privacynoticehistory
WHERE version = %(current_version)s AND
privacy_notice_id = %(privacy_notice_id)s
]
[parameters: {'record_id': 'pri_46f39301-f80c-4684-92fb-0a7dcfcd508b', …
```

Translation Data Migration - Duplicate Privacy Notice History records

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/form/helpers.tsx

Add acknowledge button label to default language form

---

clients/fides-js/src/components/fides.css

in the admin ui
https://github.com/ethyca/fides/assets/101993653/2eb1471b-7073-4716-9bf5-68b41610b507
https://github.com/ethyca/fides/assets/101993653/9bd64acf-da39-4d4d-842c-272fa6f3b57a

Make banner width 100% when mobile

---

clients/admin-ui/src/features/common/ScrollableList.tsx
clients/admin-ui/src/features/common/form/inputs.tsx

Fix styling on select dropdowns so they are not blocked by the "save/cancel" button panel
In privacy experience config form:
In front of button panel:
Or going upwards from select:

Fix issue with select dropdown hiding behind button panel

---

clients/admin-ui/src/features/privacy-experience/PrivacyExperienceTranslationForm.tsx

Fix issues with functionality for setting the default translation on a privacy experience.

Fix issue where default language for privacy experience was not being set

---

CHANGELOG.md
clients/fides-js/__tests__/__fixtures__/mock_experience.json
clients/fides-js/__tests__/lib/i18n/i18n-utils.test.ts
clients/fides-js/src/lib/i18n/i18n-utils.ts
clients/fides-js/src/lib/i18n/index.ts
clients/privacy-center/cypress/e2e/consent-i18n.cy.ts
clients/privacy-center/cypress/fixtures/consent/experience_banner_modal.json
clients/privacy-center/cypress/fixtures/consent/experience_banner_modal_notice_only.json
clients/privacy-center/cypress/fixtures/consent/experience_gpp.json
clients/privacy-center/cypress/fixtures/consent/experience_privacy_center.json
clients/privacy-center/cypress/fixtures/consent/experience_tcf.json
clients/privacy-center/cypress/fixtures/consent/fidesjs_options_banner_modal.json

Closes PROD-1831
This fixes a missing gap in the initial implementation of FidesJS localization to support a dynamic, configurable "default locale" set in the Experience configuration. How this works is:
1. During initialization, scan the list of `experience.experience_config.translations` to find which is marked as `is_default`
2. Set the "default locale" in the `i18n` module to use, or fallback to `en` if no API default is provided
3. Use the new "default locale" as the fallback in a few places:
1. When selecting the active locale for the overall session, the default locale is used when no "better" match exists
2. When auto-detection is disabled, the default locale will always be used
3. When the active locale (from the experience) is not available for a notice, the default locale is …

Update FidesJS to support localizing CMP UI with configurable, non-English default locales

---

README.md
docs/fides/docs/development/overview.md

Removing incorrectly pasted character from the code samples

Remove accidental back-tick causing errors in cli

---

CHANGELOG.md
clients/admin-ui/src/features/datastore-connections/system_portal_config/ConnectionForm.tsx

The buttons on the integration screen would sometimes overlap or leave big gaps that shouldn't happen. 
The buttons should display horizontally and in smaller screen they should stack vertically.

PROD-1356 Fix overlapping/floating buttons in integrations screen

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts
clients/admin-ui/cypress/e2e/privacy-notices.cy.ts
clients/admin-ui/cypress/support/stubs.ts
clients/admin-ui/src/features/privacy-experience/ConfigurePrivacyExperience.tsx
clients/admin-ui/src/features/privacy-experience/NewJavaScriptTag.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceTranslationForm.tsx
clients/admin-ui/src/features/privacy-notices/PrivacyNoticeTranslationForm.tsx
clients/admin-ui/src/types/api/models/ExperienceConfigCreate.ts
clients/admin-ui/src/types/api/models/ExperienceConfigListViewResponse.ts
clients/admin-ui/src/types/api/models/ExperienceConfigResponse.ts
clients/admin-ui/src/types/api/models/ExperienceConfigResponseNoNotices.ts
clients/admin-ui/src/types/api/models/ExperienceConfigUpdate.ts
clients/admin-ui/src/types/api/models/MinimalPrivacyExperience.ts
clients/admin-ui/src/types/api/models/MinimalProperty.ts
clients/admin-ui/src/types/api/models/PrivacyExperienceResponse.ts
clients/admin-ui/src/types/api/models/PrivacyNoticeResponse.ts
clients/admin-ui/src/types/api/models/Property.ts
clients/admin-ui/src/types/api/models/SupportedLanguage.ts

Closes PROD-1820
Removes references to translations in the privacy notice and privacy experience forms when user does not have translations enabled on the backend, replacing them with generic "text editing" forms.
Use fidesplus backend on branch `PROD-1819_surface_translation_config_settings`.
As a control to confirm translation interfaces still work as expected when translations are enabled, have the following in `.fides/fides.toml` in fidesplus:
```toml
[consent]
enable_translations = true
enable_oob_translations = true
```
Replace `true` with `false` in the config snippet above, then rerun backend.

Hide translation interface in notice/experience form when translations aren't enabled

---

CHANGELOG.md
src/fides/api/db/base.py
src/fides/api/models/experience_notices.py
src/fides/api/models/privacy_experience.py
src/fides/api/models/privacy_notice.py
tests/ops/models/test_privacy_notice.py

Closes #PROD-1839
Running `nox -s dev -- shell postgres`  fails when the postgres setup script runs due to the way we've defined some of our new multitranslation models:
```shell
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class PrivacyNotice->privacynotice, expression 'experiencenotices' failed to locate a name ("name 'experiencenotices' is not defined"). If this is a class name, consider adding this relationship() to the <class 'fides.api.models.privacy_notice.PrivacyNotice'> class after both dependent classes have been defined.
no custom setup logic found for postgres, skipping
```
You can get around this by importing in the ExperienceNotices model early into that script, but instead let's try to define these models more properly. I don't know if anyone else has …

Issues Seeding Data due to Import Issues with Multilang models

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/domains.cy.ts
clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
clients/admin-ui/src/pages/management/domains.tsx

Closes #PROD-1829
The display for CORS origin regex on domains page was [incorrectly removed](https://github.com/ethyca/fides/pull/4576/files#diff-f1e807941f25cb9ef3e43bcae355506ec80fe430bfd4dbb26aaa12418fe00f4e) as part of the Consent 3.0 release, this restores it.
In .fides/fides.toml under `[security]`, add a value for `cors_origin_regex`, e.g.:
`cors_origin_regex = "http://localhost:[0-9][0-9][0-9][0-9]"`

Restore CORS domain regex to domains page

---

clients/admin-ui/src/features/common/table/v2/FidesCell.tsx

Accidentally moved styles into the `article` styles instead of the root element.

Fix: move cell styles outside of `article`

---

clients/fides-js/src/components/notices/NoticeOverlay.tsx

Fix type err in cypress test and on tsx compile.

Fix- adds back missing option param

---

CHANGELOG.md
clients/sample-app/src/components/GeolocationSelect/index.tsx
clients/sample-app/src/components/Home/index.tsx
clients/sample-app/src/pages/index.tsx

Related to PROD-1862
This is a small update to the Cookie House sample app for demo purposes. It allows selecting a few extra locations (Canada, Quebec, EEA) and also lets you add a `property_id=` query param to the URL, which'll get passed along to the `fides.js` script include. Combined, you can use this to demo a lot more advanced consent experiences 👍 

Update Cookie House to support for additional locations (Canada, Quebec, EEA) and a "property_id" override

---

clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/lib/i18n/i18n-context.tsx
clients/privacy-center/cypress/e2e/consent-i18n.cy.ts

Closes [PROD-1888](https://ethyca.atlassian.net/browse/PROD-1888)
i18n context was being initialized prior to the overrides taking effect. Changed to initialize as `null` and then use the override value once it was ready.
[PROD-1888]: https://ethyca.atlassian.net/browse/PROD-1888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix language switcher with queryParams + e2e tests

---

clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/privacy-center/cypress/e2e/consent-i18n.cy.ts

Closes [PROD-1892](https://ethyca.atlassian.net/browse/PROD-1892)
matches Notices Overlay in TCF Overlay for how we watch the locale state from the i18n react context.
[PROD-1892]: https://ethyca.atlassian.net/browse/PROD-1892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: language switcher not working in tcf overlay

---

clients/admin-ui/src/features/privacy-experience/PrivacyExperienceTranslationForm.tsx
clients/admin-ui/src/features/privacy-experience/form/helpers.tsx
clients/admin-ui/src/features/privacy-experience/preview/helpers.ts
clients/admin-ui/src/features/privacy-experience/privacy-experience.slice.ts
clients/admin-ui/src/types/api/models/ExperienceTranslation.ts
clients/admin-ui/src/types/api/models/ExperienceTranslationCreate.ts
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/lib/i18n/locales/index.ts
clients/fides-js/src/lib/tcf/i18n/locales/index.ts

Closes [PROD-1709](https://ethyca.atlassian.net/browse/PROD-1709)
Adds new field to the translation form for Trigger Link Label. This allows users to set the language of the link that opens the Fides modal on their site.
[PROD-1709]: https://ethyca.atlassian.net/browse/PROD-1709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FE Admin UI update - New field to accept this value

---

CHANGELOG.md
clients/privacy-center/app/server-environment.ts
clients/privacy-center/pages/api/fides-js.ts

Add `CUSTOM_OPTIONS_PATH` to privacy center env vars
```
window.mv = {
fides_overrides: {
fides_primary_color: "blue"
}
}
```

add CUSTOM_OPTIONS_PATH to env vars

---

CHANGELOG.md
clients/fides-js/package.json
clients/fides-js/rollup.config.mjs
clients/fides-js/src/docs/fides-event.ts
clients/fides-js/src/docs/fides-options.ts
clients/fides-js/src/docs/fides.ts
clients/fides-js/src/docs/index.ts
clients/fides-js/tsconfig.json

This adds a new `dist/fides-types.d.ts` file to our build outputs in `fides-js` that includes _just_ the documented types that we use to build the developer docs here: https://ethyca.com/docs/dev-docs/js/reference
As a next step, we could host the most recent `fides-types.d.ts` on the docs site so that customer developers could download these and use them! Technically the _right_ thing to do is to publish these on `npm`, but let's not overengineer it too much... yet 😉.
Basically: I can tinker with how to _distribute_ these types next, but first want to get the build reviewed and working.

Build a `fides-types.d.ts` type declaration file to include alongside our FidesJS developer docs

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/privacy-requests.cy.ts
clients/admin-ui/cypress/fixtures/privacy-requests/list.json
clients/admin-ui/src/features/common/PII.tsx
clients/admin-ui/src/features/common/PIIToggle.tsx

Closes [PROD-1925](https://ethyca.atlassian.net/browse/PROD-1925)
Fixing an issue with the `PII` component where it would not render if it received a `number` type as the `data` prop.
```
curl -X 'POST' \
'http://localhost:8080/api/v1/privacy-request/authenticated' \
-H 'accept: application/json' \
-H 'Authorization: Bearer REDACTED\
-H 'Content-Type: application/json' \
-d '[
{
"external_id": "abc1234561",
"identity": {
"email": "testuser@example.com"
},
"custom_privacy_request_fields": {
"userIDs": {
"label": "User IDs",
"value": 1234
},
"analyticsIDs": {
"label": "Analytics IDs",
"value": "abcd"
}
},
"policy_key": "default_erasure_policy"
}
]'
```
[PROD-1925]: https://ethyca.atlassian.net/browse/PROD-1925?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNv …

Fixing privacy request detail page

---

CHANGELOG.md
clients/fides-js/src/components/fides.css
clients/fides-js/src/lib/consent.ts

Closes https://ethyca.atlassian.net/browse/PROD-1889
Hard-code inactive toggle color to light grey

PROD-1889: hard-code inactive toggle color to grey

---

CHANGELOG.md
clients/fides-js/docs/interfaces/FidesOptions.md
clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/ConsentModal.tsx
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/components/fides.css
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/docs/fides-options.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

This turned out to be a bit of an adventure. Initially I wanted to allow embedding the banner and the modal in separate containers and after spending some time going in this direction, it turned out to be not possible without a lot of effort refactoring the code which I didn't feel comfortable doing (also time). The issue is that putting the banner and the modal in two different containers would require separating the components "all the way to the top", so to speak, which would mean they'd have entirely separate state and everything.
The approach here is to embed both the banner and the modal in the same `fides-embed-container`. The `bannerIsOpen` state in `Overlay` is used to control if the banner or the modal is shown.
The changes can be tested by using the `fides_embed=true` override. …

Update FidesJS `fides_embed` option to support embedding both banner & modal components

---

CHANGELOG.md
clients/fides-js/src/components/ConsentButtons.tsx

A small and backwards compatible change to add a few classes to the different button-groups to be able to differentiate between them in custom CSS.

Add a few CSS classes to help with styling FidesJS button groups

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/ConfigurePrivacyExperience.tsx

Fix bug that prevented adding new translation for privacy center
Investigated the problem a bit, and notices that there was a form validator error about some field being null.
The problem is that the privacy center experience don't have a need for this field, but the validator stills checks for it. Added nullable option to the validator to account for this use case.

PROD-1941 Fix bug that prevented adding new privacy center translations

---

CHANGELOG.md
src/fides/api/service/connectors/sql_connector.py

Closes FIDES-611
Some discovered Redshift connection issues were found to be related to password character issues along with ssl failures. This PR should make an allowance for both of those

Password Encoding and SSL Preference

---

Dockerfile

Addresses a new change to `setuptools` described [here](https://github.com/pypa/setuptools/issues/4300), introduced in setuptools `69.3.0`.
As described in https://github.com/pypa/setuptools/issues/4300, setuptools changed to produce built tarballs with `_` instead of `-` in the distribution's naming convention. Our Dockerfile `prod` build (incorrectly) relied on the `-` naming convention for our built distribution of `ethyca-fides`.
We can adjust the expected naming convention to `ethyca_fides`. Per the comments on https://github.com/pypa/setuptools/issues/4300, we _can_ now rely on this naming convention, as it is up to spec.
As mentioned in the issue, [the change in setuptools](https://github.com/pypa/setuptools/pull/4286/files#diff-b9c5224191f52b3ea80acfdc52fce5ea9e840a6a9237d479918bb7 …

Setuptools Handling of Dashes

---

clients/admin-ui/src/pages/consent/privacy-experience/index.tsx
clients/admin-ui/src/pages/consent/privacy-notices/index.tsx
clients/admin-ui/src/pages/reporting/datamap/index.tsx

Closes #[1911](https://ethyca.atlassian.net/browse/PROD-1911)
Update the Privacy Experience and Privacy Notice tables to not overflow the page. Update the Data map report table padding to match other pages.  

use FixedLayout to contain the new tables when expanding the columns

---

CHANGELOG.md
src/fides/api/worker/__init__.py

The Celery startup banner that gets displayed on the workers is bulky and doesn't serialize well into logging systems, as it spans multiple lines. This PR removes the banner by setting the `--quiet` flag on the worker command. It then listens for the 
setup complete signal and prints a log message that contains most of the same info as the banner.
Derived from https://blog.sneawo.com/blog/2021/06/17/how-to-replace-celery-banner-with-one-log-line/
* Pass `--quiet` to the Celery worker command
* Create a function that listens for the setup complete signal to log information
* In the `fides.toml`, set `task_always_eager = false`
* Spin up Fides with a worker: `nox -s dev -- shell ui pc worker`
* Review Worker logs and notice that Celery banner doesn't show up
* Submit a DSR …

Remove Celery Startup Banner

---

src/fides/api/task/deprecated_graph_task.py
src/fides/api/task/execute_request_tasks.py
src/fides/api/task/task_resources.py
tests/ops/task/test_execute_request_tasks.py
tests/ops/task/test_task_resources.py

Closes #PROD-1881
❗ Dependent on https://github.com/ethyca/fides/pull/4760
Improve external db connection management
- In your toml file, toggle DSR 3.0 to on and task_always_eager to True (to test celery)
```
[execution]
use_dsr_3_0 = true
```
```
[celery]
task_always_eager = true
```
-  nox -s dev -- shell postgres mongodb worker
- In another terminal, cd /fides/clients
- turbo run dev
-  Setup postgres connector
- http://localhost:3001/add-systems
- Click Add a System
- Add system name: `postgres_example_test_dataset`
- Click Integrations
- Integration type: PostgreSQL
- Add credentials for local postgres example container running in docker (these aren't private secrets, these are for the example postgres database, docker/docker-compose.integration-postgres.yml). Test connection
- …

DSR 3.0 Improve External DB Connection Management

---

CHANGELOG.md
clients/fides-js/docs/interfaces/FidesEvent.md
clients/fides-js/docs/interfaces/FidesOptions.md
clients/fides-js/src/docs/fides-event.ts
clients/fides-js/src/docs/fides-options.ts
clients/fides-js/src/integrations/gtm.ts
clients/fides-js/src/lib/events.ts
clients/fides-js/src/lib/preferences.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts
clients/privacy-center/cypress/support/commands.ts

Closes https://ethyca.atlassian.net/browse/PROD-1965
Adds a new `FidesUpdating` even that fires (almost) immediately after the user has updated their consent. This allows page code to react to the change sooner than `FidesUpdated` as that will potentially make a network request to save the preferences before firing.

Added FidesUpdating event

---

clients/privacy-center/cypress/e2e/consent-i18n.cy.ts
clients/privacy-center/cypress/support/commands.ts
clients/privacy-center/cypress/support/stubs.ts
clients/privacy-center/pages/api/fides-js.ts
clients/privacy-center/public/fides-js-components-demo.html

Closes [PROD-1953](https://ethyca.atlassian.net/browse/PROD-1953)
Up until now, all of the end-to-end tests in Cypress have been loading either `fides.js` or `fides-tcf.js` directly. Since this doesn't exactly match the end-user experience it's better to load `fides.js` from the NextJS route where the correct file gets loaded along with a lot of other bundling logic that we're missing out on testing.
The changes in this PR implements similar logic to the demo page set up for testing, attempting to be true to the original implementation, with the difference being that we're now utilizing the NextJS route.
* Pass some new params to the fides.js route to signal ignoring the default config and auto-init behavior, in favor of the Cypress e2e configs (fixtures).
* Privacy Center Cypress tests …

update tests to use the router version of fides.js

---

src/fides/api/models/sql_models.py
tests/conftest.py
tests/ctl/core/test_dataset.py

Closes [PROD-1998](https://ethyca.atlassian.net/browse/PROD-1998)
Fixes a bug caused by accessing `None` valued `field.data_categories` on the `Dataset` model. 
[PROD-1998]: https://ethyca.atlassian.net/browse/PROD-1998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing field_data_categories property

---

clients/admin-ui/src/features/consent-settings/GppConfiguration.tsx

Update "Enable TC string" tooltip

---

src/fides/api/service/privacy_request/request_service.py

Closes  N/A
DSR 3.0 adds a scheduler that runs by default every 30 seconds (good for staging, should be higher on production environments).It is logging that it is running, which adds a ton of logs to Datadog.  Switching to a lower-severity log, so these won't show up unless the log level is set to "debug" or lower level.

Change Privacy Request Polling Logging from Info -> Debug

---

CHANGELOG.md
clients/admin-ui/__tests__/features/common-utils.test.ts
clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/src/features/common/modals/StandardDialog.tsx
clients/admin-ui/src/features/common/utils.ts
clients/admin-ui/src/features/datamap/constants.ts
clients/admin-ui/src/features/datamap/datamap.slice.ts
clients/admin-ui/src/features/datamap/modals/ReportExportModal.tsx
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx

Closes [PROD-1914](https://ethyca.atlassian.net/browse/PROD-1914)
Export a file that mirrors the criteria of data showing in the UI
* New button and confirmation modal for downloading the report
* visit Datamap report page `/reporting/datamap`
* play around with various settings to view the data on the page
* click new export button in top right corner
* export either csv or xlsx
* verify that the data mimics what is on the screen
[PROD-1914]: https://ethyca.atlassian.net/browse/PROD-1914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add download UI to data map report

---

CHANGELOG.md
clients/fides-js/src/components/fides.css
clients/privacy-center/cypress/e2e/consent-banner.cy.ts

This removes a tiny little CSS override when using HTML descriptions in FidesJS components. The net result is that, by default, FidesJS is going to treat whitespace as significant when provided by the Admin UI forms, which is just more intuitive for end-users: we implicitly want to write paragraphs of text with newlines, etc.
This'll make it easier to support a real rich text editor in the future, too, by not rendering our plaintext/richtext descriptions with slightly different CSS rules. 
FYI: I was the one that put this CSS rule there in the first place, because I thought (incorrectly!) that this would be a safer default for HTML descriptions, but that's just hogwash and I see the error of my ways now.
I checked to ensure that all existing usage of HTML descriptions is unaffected by …

Remove the extra 'white-space: normal' CSS for FidesJS HTML descriptions

---

docker-compose.integration-tests.yml

Follow up to https://github.com/ethyca/fides/pull/4852, missed another reference we had.

fix mysql service in integration-tests compose

---

CHANGELOG.md
clients/admin-ui/src/features/common/hooks/useTaxonomies.test.ts
clients/admin-ui/src/features/common/hooks/useTaxonomies.tsx

Closes [PROD-1991](https://ethyca.atlassian.net/browse/PROD-1991)
Update `getDataDisplayName` utility to accept a level to return the primary label. This way we can pass a level 2 to when retrieving categories.
* Visit Data Map Report table page `/reporting/datamap`
* Expand the Categories column so that all the badges are broken out individually rather than combined
* Note that before this fix, nearly all of them used a generic "User Data" label and now with this fix those primary, bold labels display the secondary level instead.
[PROD-1991]: https://ethyca.atlassian.net/browse/PROD-1991?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update `getDataDisplayName` to accept levels

---

CHANGELOG.md
data/saas/config/segment_config.yml

Closes INTS-294
Includes the option to also collect the segment ID via `email` instead of the `user_id`
I'm unclear if there is any issue with running dual read requests, assuming the returned values are consolidated if (as in our test case) the segment_id is returned for both

Search for both email and user_id to get a segment_id

---

CHANGELOG.md
clients/admin-ui/src/features/common/helpers.ts
clients/admin-ui/src/features/system/add-multiple-systems/MultipleSystemsFilterModal.tsx

Closes [PROD-2019](https://ethyca.atlassian.net/browse/PROD-2019)
Updates our determination of vendor source in the FE to more strictly check for a `gvl.` prefix in the `vendor_id`, rather than assuming any non-AC vendors are GVL vendors.
[PROD-2019]: https://ethyca.atlassian.net/browse/PROD-2019?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

attempt to only label GVL vendors from compass as such

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/src/features/common/hooks/useLocalStorage.ts
clients/admin-ui/src/features/common/table/v2/FidesTable.tsx
clients/admin-ui/src/features/common/table/v2/column-settings/ColumnSettingsModal.tsx
clients/admin-ui/src/features/datamap/constants.ts
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx

Closes [PROD-1907](https://ethyca.atlassian.net/browse/PROD-1907)
This modifies the existing Data Map Reporting page to keep track of the various states in Local Storage in addition to the react state. This will allow the user to reload the page, or close the page and come back to it, and not need to adjust these settings again.
This includes storing
- The overall "Group by" status
- Each column’s “Group/Display” status
- Each column’s width
- Column visibility
- Column order
* created a new hook `useLocalStorage` in AdminUI client that is a modified version of the one in FidesJS.
* converted or created state management over to local storage for the following:
```
export enum DATAMAP_LOCAL_STORAGE_KEYS {
GROUP_BY = "datamap-group-by",
COLUMN_ORDER = "datamap-column-order",
TABLE_GROUPING …
```

Persist the state of the reporting table so that viewers can return to their previous view easily

---

CHANGELOG.md
clients/fides-js/src/lib/consent-constants.ts
clients/privacy-center/__tests__/common/geolocation.test.ts
clients/privacy-center/common/geolocation.ts
clients/privacy-center/public/fides-js-components-demo.html
clients/privacy-center/public/fides-js-demo.html

Closes PROD-2015
This fixes a subtle error where the Privacy Center would consider some valid ISO-3166 codes as invalid if they had single-character regions; for example, `SE-O` would be rejected. The fix here is trivial (accept 1-3 characters!) but this PR also adds additional test coverage for confidence, and also adds an extra defensive check to fallback to just the country header if an invalid CloudFront region header is detected.

Fix handling of some ISO-3166 geolocation edge cases in Privacy Center /fides.js endpoint

---

CHANGELOG.md
src/fides/core/utils.py

Closes FIDES-665
* Follow on from #4790, sets Redshift SSL to prefer

Set Redshift to prefer SSL in generate as well

---

CHANGELOG.md
src/fides/api/models/privacy_request.py
tests/ops/models/test_privacy_request.py

Closes [PROD-2009](https://ethyca.atlassian.net/browse/PROD-2009)
This is a fix for a defect that was introduced with the custom identities feature, specifically [this line](https://github.com/ethyca/fides/pull/4764/files#diff-ef7d3e10be42d5a81721075db1647f7a59ad17ab20b273bfcda1edbcbc8ba391R356). Moving forward, we want to make sure that any non-JSON-encoded values in the cache can still be read. There is no data lost between the two caching methods since we're just formatting the values differently. This means the change can be targeted and everything can continue to work as expected as long as `get_cached_identity_data` returns the expected response.
[PROD-2009]: https://ethyca.atlassian.net/browse/PROD-2009?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …

Update the get_cached_identity_data function to support non-JSON-encoded value

---

CHANGELOG.md
clients/fides-js/src/lib/hooks.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts

Closes PROD-2017
This is a small change to make the `fides_disable_save_api` option more consistent; in usage, we expected this to disable all save APIs (both notices-served & privacy-preferences), but as of today only the privacy-preferences API is disabled, which was surprising.
As with a lot of PRs, the majority of the changes here are updating the tests 😄 

Update fides_disable_save_api option in FidesJS SDK to disable both privacy-preferences & notice-served APIs

---

CHANGELOG.md

* [Marigold/Sailthru integration](https://github.com/ethyca/fides/pull/4826)
* [Stuck DSRs](https://github.com/ethyca/fides/pull/4855)
* [Update FidesJS' GTM integration](https://github.com/ethyca/fides/pull/4847)
* [Allow 204 error for integrations](https://github.com/ethyca/fides/pull/4834)
* [Redshift SSL part 2](https://github.com/ethyca/fides/pull/4849)
* [Segment integration to use email](https://github.com/ethyca/fides/pull/4851)
* [edit compass/nonGVL vendors](https://github.com/ethyca/fides/pull/4857)
* [geolocation edge cases in Privacy Center](https://github.com/ethyca/fides/pull/4858)
* [fides.js disable save option](https://github.com/ethyca/fides/pull/4860)

Update changelog for release 2.35.1

---

CHANGELOG.md
clients/fides-js/docs/README.md
clients/fides-js/docs/interfaces/Fides.md
clients/fides-js/docs/interfaces/FidesEvent.md
clients/fides-js/docs/interfaces/FidesOptions.md
clients/fides-js/package.json
clients/package-lock.json

This updates `typedoc-plugin-markdown` to the latest release and follows the [v4 migration guide](https://typedoc-plugin-markdown.org/docs/migration-guide) to tweak a couple of the formatting features 👍
This improves the format of the generated `.md` files in a couple ways which I like, including removing the inline table of contents that was _OK_ but more confusing than helpful in our docs.
NOTE: I originally did this hoping to find a way to add some additional pages to document features that aren't strictly part of the types (e.g. guides) but looks like we'll need to wait until this plugin supports the `typedoc` beta: https://github.com/TypeStrong/typedoc/issues/2567

Update typedoc-plugin-markdown to 4.0.0

---

CHANGELOG.md
clients/admin-ui/__tests__/features/common-utils.test.ts
clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/src/features/common/CheckboxTree.tsx
clients/admin-ui/src/features/common/modals/FilterModal.tsx
clients/admin-ui/src/features/common/table/v2/filters/GlobalFilterV2.tsx
clients/admin-ui/src/features/common/utils.ts
clients/admin-ui/src/features/datamap/reporting/DatamapReportFilterModal.tsx
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx

Closes [PROD-1916](https://ethyca.atlassian.net/browse/PROD-1916)
Update the filters on the table to apply a modified version of the hierarchy component that we are using on the dataset page. 
* New `DatamapReportFilterModal` which reduces a lot of over-engineered complexity and implements the `CheckboxTree` component
* Update old `getQueryParamsFromList` as new `getQueryParamsFromArray` utility
* Update checkbox tree to have animated caret similar to accordion.
* Unit test and e2e test
* visit Data Map Report `/reporting/datamap`
* click the "Filter" button in the top bar
* expand one of the 3 categories
* Note the new style for checking boxes uses our existing tree component rather than just a flat list of check boxes within each of the 3 main sections
* Expand/collapse and click …

Use CheckboxTree for data map filtering

---

clients/privacy-center/pages/api/fides-js.ts

Closes [PROD-2026](https://ethyca.atlassian.net/browse/PROD-2026)
Document support for `gpp` query param in fides.js api docs
See the update on http://localhost:3000/docs
[PROD-2026]: https://ethyca.atlassian.net/browse/PROD-2026?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Include `gpp` in fides-js docs

---

README.md

Closes n/a
Taking some lessons learned and being more explicit about using a virtual environment when installing fides locally
View the formatted output here -> https://github.com/ethyca/fides/blob/d99cb8b236aa5a793273fb18a862b83840b6a1ef/README.md#download-and-install-fides

add virtual env step to readme quickstart

---

CHANGELOG.md
clients/fides-js/src/components/fides.css
clients/fides-js/src/lib/consent-constants.ts
clients/fides-js/src/lib/consent-utils.ts
clients/privacy-center/__tests__/common/geolocation.test.ts
clients/privacy-center/common/geolocation.ts
clients/privacy-center/pages/api/fides-js.ts

Closes PROD-2063
This makes FidesJS and the Privacy Center slightly more defensive against invalid ISO 3166-2 codes that must use two-character country codes (e.g. `US` vs `USA`). Technically there are [ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) codes that are three letter codes, but these are meant for other purposes (like passports) and aren't used along with the ISO 3166-2 subdivisions, etc.
More importantly, the Fides API expects only two-letter country codes compliant with [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2), so this ensures that FidesJS & Privacy Center code will match the validation used in the API 👍 
However, we do support a special-case `EEA` location code, so this ensures that is still considered valid!
* …

Ignore invalid three-character country codes for FidesJS geolocation (e.g. "USA")

---

CHANGELOG.md
clients/fides-js/rollup.config.mjs
clients/fides-js/src/fides-ext-gpp.ts

Closes [PROD-2080](https://ethyca.atlassian.net/browse/PROD-2080)
Only include sourcemaps when in dev mode
* restore previous change where `IS_DEV` was commented out and `true` was left in
* build and run Privacy Center
* View source of `fides.js` in browser devTools
* Note the browser warning that the sourcemap can’t be found is now gone
[PROD-2080]: https://ethyca.atlassian.net/browse/PROD-2080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Remove sourcemaps from fides-js dist

---

src/fides/api/models/detection_discovery.py
tests/ops/models/test_detection_discovery.py

closes n/a
Pesky bug i found in recently merged model-level updates that did not handle falsey `0` values well. This is a simple fix.

tweak logic in execution frequency property function to be more robust

---

src/fides/api/db/crud.py

Closes n/a
Our `create_resource` crud function, used as a general function to create DB resources/records with an async DB session, had been executing a `get_resource` and expecting (and catching) a `NotFoundError`. I found that in practice, the underlying exception that was thrown -- even though it was caught and handled within this function -- would cause unexpected async/session problems when used in endpoints/contexts that open other async sessions. Namely, it seemed to be closing the async session that i used to populate another resource.
We already have a version of `get_resource` that _doesn't_ throw a `NotFoundError`, and so I can't see any good reason why our `create_resource` function shouldn't use that version, and avoid the unnecessary exception handling. I've confirmed that …

improve safety of async `create_resource` crud operation

---

CHANGELOG.md
data/saas/config/segment_config.yml

Closes FIDES-701
When adding the option for either an ID or an email, we also should have handled the error response of an ID or email not found

Allow 404 errors for Segment ID/Email not found

---

src/fides/api/schemas/privacy_center_config.py
src/fides/api/schemas/property.py

To help with https://github.com/ethyca/fidesplus/pull/1432 - this base class will give us a space to add sensitive fields to a `Property` schema while keeping the public API's response model more locked down.

public property response schema as a base class

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/form/helpers.tsx

Closes [PROD-2061](https://ethyca.atlassian.net/browse/PROD-2061)
the helper method that transforms the response into form values was missing the newer value added recently for Modal Link Label. This was causing the form field to always be empty, even when the value entered was actually saved. Updating that form helper to include the value.
* update `transformTranslationResponseToCreate` to include `modal_link_label`
* edit an experience (eg. TCF)
* select a language for the experience to edit (eg. English)
* add a “Trigger link label (optional)” 
* click save and click save again
* select the same experience and language again.
* Note the field is still populated with the saved value
[PROD-2061]: https://ethyca.atlassian.net/browse/PROD-2061?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y …

include Modal Link Label in form values

---

CHANGELOG.md

I mistakenly added two changelog entries in https://github.com/ethyca/fides/pull/4905, just cleaning this up

remove duplicate changelog entry

---

CHANGELOG.md
docker-compose.yml

Closes PROD-2120
Following up on #4912, we need to also add the new port to the Docker Compose file, so it works in Nox. Currently `nox -s pc` expects it to be exposed on port `3000`, which leads to a network error when trying to access it via `http://localhost:3001`.
* Run `nox -s pc` and confirm that `http://localhost:3001` properly serves the privacy center.

Docker Compose - Change privacy center port to 3001

---

clients/privacy-center/public/fides-js-demo.html

Fix fides-js-demo page so fides_embed=true works

---

clients/privacy-center/app/server-environment.ts

Fixprivacy center custom paths not working in production because it's using the wrong url to connect within docker.

FIx privacy center paths

---

CHANGELOG.md
clients/privacy-center/common/toast-options.ts

This PR fixes some wonky capitalization that's been on my mind for a while. 
Original:
Updated: 
* Change toast text from `An error occurred while retrieving the Privacy Center Config` to `An error occurred while retrieving the Privacy Center config`

Fix Capitalization in Privacy Center Error Toast

---

CHANGELOG.md
clients/fides-js/__tests__/lib/cookie.test.ts
clients/fides-js/src/lib/cookie.ts

Closes [PROD-2027](https://ethyca.atlassian.net/browse/PROD-2027)
IP addresses and top level hostnames that included multiple TLDs (like `co.uk`) were not working for setting a Fides Cookie.
This fix update cookie setter to guarantee highest level domain allowed to set cookie. It relies on browser's own methods to determine viable domain.
* Loop through parts of hostname backwards until cookie gets set.
* Validate the cookie gets set and stop looping
* Update `/etc/hosts` on your local machine to include new line:
```127.0.0.1 privacy.example.co.uk```
* Fire up privacy center on localhost
* Instead of visiting localhost, visit `http://privacy.example.co.uk:3001/fides-js-demo.html`
* In the banner/modal make a selection that will set the cookie
* Verify that the cookie was set with domain …

Fix: get the top-level hostname

---

.github/workflows/frontend_checks.yml
clients/fides-js/package.json
clients/fides-js/rollup.config.mjs
clients/privacy-center/app/server-utils/PrivacyCenterSettings.ts
clients/privacy-center/cypress.config.ts
clients/privacy-center/cypress/fixtures/consent/fidesjs_options_banner_modal.json
clients/privacy-center/package.json
clients/privacy-center/public/fides-js-components-demo.html
clients/privacy-center/public/fides-js-demo.html

We recently updated Privacy Center development mode to run on port 3001. This could sometimes conflict with Cypress settings so these updates push it even further to start Cypress runs on that same port.
* Cypress config changed to port `3001`
* `cy:start` script to start server on `3001`
* get dev mode working as intended for local rollup to make local testing easier
* run `npm run cy:start`
* then run `npm cy:run`
* Everything should be visiting `localhost:3001`
* Viewing the Source of `fides.js` should result in expanded (not-minified) view

Privacy Center port updates for Cypress tests

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/src/features/common/table/v2/FidesCell.tsx
clients/admin-ui/src/features/common/table/v2/FidesTable.tsx
clients/admin-ui/src/features/datamap/datamap-drawer/DatamapDrawer.tsx
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx

Closes [PROD-2133](https://ethyca.atlassian.net/browse/PROD-2133)
Added ability to open system preview side panel from new datamap table, similar to how it works in the old datamap table and re-using that existing slide-out component. Only "System" column cells highlight with a hover state and are clickable.
* Add new support for clickable cells (in addition to clickable rows) to FidesTable V2 via `react-table`'s `meta` property
* Add clickable cell configuration to the new datamap table and have it open the existing drawer component.
* Add system(s) to Fides using Admin UI at `/add-systems`
* Visit the newer datamap report page `/reporting/datamap`
* Table will be grouped by system by default
* Click the system name in the System column
* Change the table to Group By "Data use"
* Click …

Datamap report side panel

---

clients/admin-ui/src/pages/systems/configure/[id].tsx

A Plus Cypress test was failing due to finding two elements with data-testid `system-tabs`, this fixes by removing it from the TabContent element (that testid was newly introduced by #4922 and is not being used).

Fix duplicate data-testid on system tabs

---

src/fides/api/models/detection_discovery.py
tests/ops/models/test_detection_discovery.py

Closes n/a
Found by @jpople in testing.
If the `hour` in the `monitor_execution_trigger` is `0`, then we were accidentally treating it as unset.
- Fix the falsey value check to check explicitly for `None`

avoid 0 as falsey bug in monitor config db property method

---

CHANGELOG.md
clients/fides-js/src/fides-ext-gpp.ts
clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts

Closes [PROD-2020](https://ethyca.atlassian.net/browse/PROD-2020)
Adding a check for TCF when setting the signal status to ensure it doesn't get set incorrectly. We've been setting it to "ready" too early in TCF enabled environments.
* first added signal status tests to TCF disabled scenario to make sure those do not change or get broken with the rest of these changes
* check for TCF when setting the signal status to "ready"
* added comments and clean up to test scenarios for accuracy
1. Enable TCF and GPP
2. Add some GVL vendors so that TCF will appear in the EU
3. Visit demo site with EU geolocation (eg. `/fides-js-demo.html?geolocation=fr-id`)
4. When initial banner is visible, check the signalStatus of GPP - you can do this by opening the console and running `__gpp('ping', …

When the TC String is included in GPP and Layer 1 is visible, the signalStatus should be "not ready"

---

clients/privacy-center/cypress/e2e/consent-banner-cookies.cy.ts
clients/privacy-center/cypress/fixtures/domains.json

Set up tests and instructions to run against various real world TLDs and validate that our cookie logic is sound. Can only be run locally and manually, but handy to keep around for validating any future changes.

set up tests for validating various domains

---

clients/admin-ui/cypress/e2e/integration-management.cy.ts
clients/admin-ui/src/features/datastore-connections/useTestConnection.tsx
clients/admin-ui/src/features/integrations/ConnectionStatusNotice.tsx
clients/admin-ui/src/features/integrations/IntegrationBox.tsx
clients/admin-ui/src/pages/integrations/[id].tsx

Closes PROD-2129
Add a "test connection" button to the new integrations UI on the list view and also detail view.
* Navigate to `/integrations`
* Create a new BigQuery integration and provide it with credentials
* On integration detail view, click "test connection"; should see success toast and status message should update with current timestamp
* Return to list view and click "test connection"; same thing should happen
* Return to detail view and click "manage"
* Input any incorrect credentials JSON
* Click "test connection" again
* Should show failure toast and change to failure message

Add 'test connection' button to integrations view

---

CHANGELOG.md
clients/admin-ui/cypress/support/stubs.ts
clients/admin-ui/src/features/data-subjects/data-subject.slice.ts
clients/admin-ui/src/features/data-use/data-use.slice.ts
clients/admin-ui/src/features/dataset/dataset.slice.ts
clients/admin-ui/src/features/messaging-templates/messaging-templates.slice.ts
clients/admin-ui/src/features/organization/organization.slice.ts
clients/admin-ui/src/features/plus/plus.slice.ts
clients/admin-ui/src/features/privacy-experience/language.slice.ts
clients/admin-ui/src/features/privacy-experience/privacy-experience.slice.ts
clients/admin-ui/src/features/privacy-notices/privacy-notices.slice.ts
clients/admin-ui/src/features/system/system.slice.ts
clients/admin-ui/src/features/taxonomy/taxonomy.slice.ts

Closes [PROD-2178](https://ethyca.atlassian.net/browse/PROD-2178)
Many of our endpoints in Fides Admin UI are pointing at a URL unnecessarily ending with `/` which ends up being redirected in the browser behind the scenes to the same URL without it.
Fixing these URLs in the code is a quick way to optimize our response time!
* Open DevTools to the Network tab
* Visit Fides Admin UI and click around to various pages
* Endpoints should be getting called directly without redirecting
[PROD-2178]: https://ethyca.atlassian.net/browse/PROD-2178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

remove unnecessary ending slash (/) in endpoint URLs

---

CHANGELOG.md
clients/fides-js/__tests__/lib/cookie.test.ts
clients/fides-js/src/lib/cookie.ts
clients/privacy-center/cypress/e2e/consent-banner-cookies.cy.ts

Closes [PROD-2196](https://ethyca.atlassian.net/browse/PROD-2196)
Our cookie saving logic wasn't saving updates to the `fides_consent` cookie after it was first created.
* use the `updatedAt` property to validate the cookie to ensure the domain checking logic doesn't get false positives when updating the cookie in addition to setting a new cookie.
* Additional E2E tests to validate cookie can also be _updated_ on any domain.
1. Visit https://cookiehouse-plus-rc.fides-staging.ethyca.com/?geolocation=US-CA
2. Delete any existing fides_consent cookie 
3. Open the FidesJS modal and opt-out of “Targeted Advertising” and save changes
4. Inspect the `fides_consent` cookie is created with `false` set for the notice
5. Refresh the page
6. Open the FidesJS modal and change your consent to opt-in of …

Fix cookie update logic

---

CHANGELOG.md
src/fides/api/alembic/migrations/versions/a3c173391603_add_property_id_to_privacy_request_model.py
src/fides/api/api/v1/endpoints/consent_request_endpoints.py
src/fides/api/db/system.py
src/fides/api/schemas/connection_configuration/__init__.py
tests/ctl/core/test_api.py

Closes PROD-2134
When creating or updating a `System`, we now validate that it references `DataUses`, `DataCategories`, and `DataSubjects` that both exist and have their `active` attribute set to `True`.
* Updated the `validate_privacy_declarations` method to add validation for `DataCategories` and `DataSubjects` and to update the validation for `DataUses`
* Added relevant unit tests
1. Go to the `POST api/v1/system` endpoint in the Swagger UI, or alternatively make the request from Postman
2. Use an invalid category for a privacy declaration in the request body, see example JSON below (invalid category is ` "user.contact.company_website"`):
```
{
"system_type": "Third Party",
"fides_key": "salesforce_system",
"name": "Salesforce",
"description": "Salesforce operates as a business …
```

PROD-2134: Adds validation for taxonomy labels

---

docs/fides/docs/development/developing_fides.md

Adds a warning in the `nox` section of the docs so that people who run into issues with the python versions know that the culprit may be `pipx` and that using `pip` may be preferred. 

Add Warning for nox installation

---

tests/ctl/core/test_api.py

unticketed
seems to be at least a flaky test in `main`, i think this should make it more consistent

sort comparison in test to ensure consistent comparison

---

requirements.txt

Fixed CI failing because numpy 2.0.0 just got released. Added `numpy==1.26.4` to requirements.txt

Fix CI pipeline because numpy == 2.0.0 is being installed

---

CHANGELOG.md
clients/fides-js/docs/interfaces/FidesEvent.md
clients/fides-js/src/docs/fides-event.ts
clients/fides-js/src/fides-ext-gpp.ts
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/events.ts
clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts
clients/privacy-center/cypress/e2e/fides-js.cy.ts
clients/privacy-center/cypress/support/commands.ts
clients/privacy-center/pages/api/fides-js.ts
clients/privacy-center/public/fides-js-components-demo.html

Closes [PROD-2214](https://ethyca.atlassian.net/browse/PROD-2214)
Initializing GPP without initializing Fides has been known to cause issues, especially in cases where Fides never gets initialized.
* When FidesJS is downloaded with `initialize=false`, ensure that GPP is not initialized at all
* When `Fides.init()` is called, ensure that the GPP stub is initialized promptly and is not delayed by any other blocking logic (e.g. API calls, etc.)
* eliminated waste on resulting `fides.js` response by not printing config object twice.
* include `gppEnabled` as part of the config options object (similar to existing `tcfEnabled`)
* add new `FidesInitializing` event for benefit of GPP initialization and other similar use cases
* wait for `FidesInitializing` to be dispatched before initializing …

Disable GPP stub when `initialize=false` is set until `Fides.init()` is called

---

clients/admin-ui/src/features/privacy-requests/RequestTableColumns.tsx

Closes [PROD-2227](https://ethyca.atlassian.net/browse/PROD-2227)
The title of the columns should have consistent capitalization. To keep consistency with other table headers and with other titles, buttons, etc. we are only capitalizing the first word.
* string changes only
* go to request manager /privacy-requests
* the title of the columns should have consistent capitalization. 
[PROD-2227]: https://ethyca.atlassian.net/browse/PROD-2227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

consistent casing

---

CHANGELOG.md
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/common/table/v2/index.ts
clients/admin-ui/src/features/configure-consent/ConsentManagementTable.tsx
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx

Closes https://ethyca.atlassian.net/browse/PROD-2230
Adds new re-usable component to display badges in table cells where we only have count (number) to work with, instead of the value names.

PROD-2230: Fix table cell formatting for vendors

---

CHANGELOG.md
clients/privacy-center/pages/api/fides-js.ts

No need to continue supporting browsers without `fetch` capabilities.
See https://caniuse.com/?search=fetch
* Remove polyfill that was used to supplement `fetch` when browsers didn't support it.
* For the scope of this change, we only need to ensure that no regressions occur using your default / standard browser and all pre-existing functionality with the cookie banner is not broken.

Remove fetch polyfill from FidesJS

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/privacy-notices.cy.ts
clients/admin-ui/src/features/common/util.test.ts
clients/admin-ui/src/features/common/utils.ts
clients/admin-ui/src/features/privacy-notices/PrivacyNoticeForm.tsx
clients/admin-ui/src/features/privacy-notices/constants.ts
clients/admin-ui/src/features/privacy-notices/form.ts

Closes [PROD-2206](https://ethyca.atlassian.net/browse/PROD-2206)
The “enforcement level” is what controls the “backend consent propagation” integrations, so we need the ability to enable/edit this in the Admin UI.
Additionally, we were defaulting the enforcement level to “system-wide” but that default has been changed to "frontend"
* Add ability to configure "Enforcement Level" for Privacy Notices in Admin UI
* Update Cypress tests to look for new field
* Add new Options utility and related unit test
* Update options maps to use same key as our data models to avoid regressions
* change default to "frontend"
* Log in to Admin UI
* Visit Manage privacy notices
* Click on a notice listed to open the edit form
* Enforcement level should now be a required option
* Change it and save the form …

Add ability to configure "Enforcement Level"

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/system.py
tests/ctl/core/test_api.py
tests/ops/service/connectors/test_queryconfig.py

Closes https://ethyca.atlassian.net/browse/PROD-2254
Remove "OR" condition in the security of Delete Systems endpoint such that we only check for users with the "SYSTEM_DELETE" scope explicitly.

PROD-2254: User must have delete scope to delete systems

---

CHANGELOG.md

Unticketed changelog chore.
Include [GHSA-cvw4-c69g-7v7m](https://github.com/ethyca/fides/security/advisories/GHSA-cvw4-c69g-7v7m) a.k.a. [CVE-2024-38537](https://nvd.nist.gov/vuln/detail/CVE-2024-38537) in 2.39.1 changelog.
n/a
n/a

Update 2.39.1 changelog to include CVE-2024-38537

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/integration-management.cy.ts
clients/privacy-center/cypress/e2e/consent-i18n.cy.ts
clients/privacy-center/cypress/e2e/consent.cy.ts
clients/privacy-center/cypress/e2e/home.cy.ts

Running Cypress locally has caused some level of developer frustration. Some tests require messing with environment variables to get them to behave like the CI tests, others fail randomly due to race conditions. These fixes help make everything more consistent, and thereby help give more confidence in the tests as we work.
* Move the definition of the `patchNoticesServed` intercept for `consent-i18n.cy.ts` in to the `beforeEach` section to make sure it's ready prior to the test running at all. This was one that was randomly failing.
* Force `isOverlayEnabled` to be false on a particular consent test that was previously requiring developers to set to `false` manually before running. No longer need to update `.env` to run tests!
* Force `isOverlayEnabled` to be true on a test that would …

fix various Cypress race conditions in Privacy Center

---

tests/ops/integration_tests/saas/test_gorgias_task.py

We don't have a test account for Gorgias so we are getting false test failures. Disabling the tests.

Disable Gorgias tests

---

CHANGELOG.md
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx

In the datamap report, rename columns Ingress and Egress to Sources and Destinations.
Intentionally didn't update enum key value or row.ingress/row.egress because the api endpoint still return the property as ingress/egress.
Updated column names in table
Updated column names in Edit columns modal

PROD-2219-FE-add-system-names-to-new-data-map-reporting

---

clients/privacy-center/cypress/e2e/home.cy.ts
clients/privacy-center/package.json

This environment variable still isn't working correctly in tests because it's read by the Next server, not the client. Setting it in Cypress is never going to work because Cypress relies on the server to already be running.
Force this env variable for all tests, so that developer's machine settings don't cause unexpected failures.
* move `FIDES_PRIVACY_CENTER__IS_OVERLAY_ENABLED=true` from Cypress config to `package.json` script that runs the cypress start.
* set `FIDES_PRIVACY_CENTER__IS_OVERLAY_ENABLED=false` in local `privacy-center/.env`
* run `npm run cy:start` and then run `cy:run`
* All tests should pass

Move .env var to before server runs

---

CHANGELOG.md

update changelog for release 2.39.2

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/integration-management.cy.ts
clients/admin-ui/src/features/integrations/configure-monitor/ConfigureMonitorDatabasesForm.tsx
clients/admin-ui/src/features/integrations/configure-monitor/ConfigureMonitorForm.tsx
clients/admin-ui/src/features/integrations/configure-monitor/ConfigureMonitorModal.tsx

In discovery monitor configuration UI, changes form to submit immediately instead of advancing to blank project selection UI when there are no projects associated with the integration.

Skip database selection step when monitors would have no databases

---

src/fides/api/service/connectors/scylla_connector.py

Fix intermittently failing scylla integration test.

Fix Scylla Integration Test

---

clients/admin-ui/src/features/datamap/modals/FilterModal.tsx

Closes: [PROD-2311](https://ethyca.atlassian.net/browse/PROD-2311)
Memo was not being updated with new table data because it was only monitoring the table instance and not the data. Removing memo since it's really not helping much at all anyway, it's just extracting the data to a variable.
* Remove memo from the `headerGroups` variable
* Log out of Admin UI (important step for reproducing!)
* Log in and visit Spatial Datamap `/datamap`
* Click "Filter" button.
* Modal should not be empty.
[PROD-2311]: https://ethyca.atlassian.net/browse/PROD-2311?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix empty Filters modal

---

docker-compose.integration-tests.yml
docker/docker-compose.integration-mysql.yml

prereq for PROD-2083
removes command calling naive plugin, changes image to mysql:9 instead of 8

fix mysql integration: pin 9, remove command

---

CHANGELOG.md
clients/admin-ui/src/features/messaging-templates/useMessagingTemplateToggle.tsx
clients/admin-ui/src/pages/messaging/index.tsx

Fix unresponsive messaging ui due to react render loop. Also fix other warnings on the page.

PROD-2349 Fix messaging ui unresponsive. Fix warnings.

---

clients/admin-ui/next.config.js

The `next export` command is being deprecated in favor of `output: "export"` which is not compatible with rewrites.
Since Admin UI gets run from a static export (see the script for `npm run prod-export` in the `package.json` file for reference), these rewrites are likely no longer being used or respected anyway.
Removing these entirely for now to make sure that the assumption that they are already ignored is true before attempting to upgrade NextJS.
* remove `rewrites()` section of `next.config.js`
* existing Cypress smoke tests should sniff this out pretty quickly

remove rewrites from NextJS config

---

clients/admin-ui/next.config.js

This reverts commit ba3013ebc547d0f4ab17f4c0234b7e4858b3a607.
health and login are failing locally. need to pause and re-evaluate a more comprehensive solution here.

Revert "remove rewrites from NextJS config (#5087)"

---

CHANGELOG.md
clients/admin-ui/src/pages/messaging/index.tsx

Add notice in messaging page when property specific messaging isn't enabled.

PROD-2336 Add notice when messaging is in global or basic mode

---

clients/fides-js/src/services/api.ts

Experience object can get pretty huge and is mostly not helpful to log here.
* clean up log line

Remove entire `experience` from logs

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/discovery-detection.cy.ts
clients/admin-ui/src/features/common/dropdown/TaxonomySelectDropdown.tsx

In the taxonomy picker by default, don't show data categories that are disabled.
Need to have D&D setup and some classification results.

PROD-2409 By default, don't show data categories that are disabled

---

.syncignore
CHANGELOG.md

Closes n/a
This is a minor dev qol change to reduce build times when dropping volumes. It was noticed that we were moving the entire .nox directory over causing >7GB of data transfer
This will reduce it to <1GB (more could likely be added but this is a good start anyway)
Before:
After:

Add .syncignore to ignore unnecessary file syncs to volume

---

clients/fides-js/src/lib/initOverlay.ts

Closes [PROD-2413](https://ethyca.atlassian.net/browse/PROD-2413)
When GVL languages are not available, the UI should fall back to the default language (English) even when the locale is set to something else.
* Replace hard-coded instances of default locale with `DEFAULT_LOCALE`
* call `i18n.activate(DEFAULT_LOCALE)` during fallback to fix fallback bug.
1. visit https://privacy-plus-rc.fides-staging.ethyca.com/fides-js-demo.html?geolocation=eea&fides_locale=fr (or localhost equivalent http://localhost:3001/fides-js-demo.html?geolocation=eea&fides_locale=fr) 
2. Simulate a failed api call by opening dev tools Networks tab, right clicking the gvl/translations and choosing to block that URL. Make sure to update the resulting blocked URL to just use a * wildcard (eg. …

"activate" default locale during fallback of GVL language error

---

clients/fides-js/src/services/api.ts
clients/privacy-center/cypress/e2e/consent-i18n.cy.ts

Include query param when calling the privacy experience endpoint so that it's not excluded by default, thereby making it backwards compatible.
* add new `exclude_gvl_languages` query param to `/api/v1/privacy-experience` api call
* This change won't have any real effect until the `fidesplus` backend is updated to accommodate.

backwards compatibility for TCF optimization work

---

CHANGELOG.md
src/fides/core/annotate_dataset.py
src/fides/core/dataset.py
tests/ctl/cli/test_cli.py
tests/ctl/data/dataset_missing_categories.yml

Closes #2423
`fides generate` and `fides annotate` dataset commands are running into issues due to pyyaml not being able to find a constructor for the FidesKey tag.  FidesKeys are `ConstrainedStr` underneath and have been successfully dumped as strings in the past.  The commands appear to pass, but then data like this is written to the yaml file:
```yaml
dataset:
- fides_key: !!python/object/new:fideslang.validation.FidesKey
- public_a5735113d5
organization_fides_key: default_organization
name: public
```
```yaml
dataset:
- fides_key: public_a5735113d5
organization_fides_key: default_organization
name: public
```
- Open your .fides/db_dataset.yml
- Remove a data category from an existing field
- Run `fides annotate dataset .fides/db_dataset.yml` to annotate your dataset interactively
- …

CLI Issues: YAML Cannot Find Constructors for FidesKeys

---

CHANGELOG.md
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/LanguageSelector.tsx
clients/fides-js/src/components/fides.css
clients/fides-js/src/components/tcf/TcfConsentButtons.tsx
clients/fides-js/src/lib/consent-constants.ts
clients/fides-js/src/lib/initOverlay.ts
clients/fides-js/src/services/api.ts
clients/privacy-center/cypress/e2e/consent-i18n.cy.ts

Closes [PROD-2412](https://ethyca.atlassian.net/browse/PROD-2412)
Because GVL languages are so bandwidth intensive, it is preferred to only load the appropriate language at the appropriate time.
- At initialization time: load the user’s preferred language based on “best locale”
- At language switch
In the UI we communicate that we are fetching the language by spinning the globe icon. The api result is so fast that most users won't experience this anyway. Example with network throttling at **2G** Speeds:
* Add spin animation to globe during api load
* update initial call to `gvl/translations` to only load current "best" locale
* update language switcher to call `gvl/translation` for updating
* For non-TCF experiences, nothing should change; language switcher should behave as normal
* For …

Serve GVL languages as they are requested

---

clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/data-discovery-and-detection/ActionButton.tsx

* Changes "last scanned" timestamp to use sentence case
* Removes asymmetrical padding on "Scan" action button that was left from when that component always expected an icon
Before:  
After:

Visual fixes for monitor table

---

CHANGELOG.md
clients/admin-ui/src/features/system/hooks/useSystemFormTabs.tsx

Closes PROD-2374
Changes text on old system integrations tab to direct to new integrations menu for D&D:

Add notice to old system integrations page

---

CHANGELOG.md
clients/admin-ui/src/features/integrations/integration-type-info/bigqueryInfo.tsx

Closes [PROD-2381](https://ethyca.atlassian.net/browse/PROD-2381)
Updates the `bigquery.projects.get` permission to be `resourcemanager.projects.get`, which is the correct google cloud permission.
* Visit BigQuery integration details page and click both instances of "show more" to reveal the text. Verify that the property name is now correct.
[PROD-2381]: https://ethyca.atlassian.net/browse/PROD-2381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix typo in bigquery monitor copy

---

src/fides/api/models/privacy_request.py

Removing `index=True` for the `property_id` field of `ConsentRequest` to prevent the index from being added during Alembic autogenerate

Remove unused index

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts
clients/admin-ui/src/features/privacy-experience/form/helpers.tsx

Closes [PROD-2008](https://ethyca.atlassian.net/browse/PROD-2008)
Backend defaults weren't reflected in the Frontend. These fields weren't being passed at all if not set, which caused the backend to apply its defaults. Since backend defaults are set to "true" on both of these fields, it was a mismatched experience.
Setting these to default to "true" on the Frontend now to match BE defaults. User can turn them off without issue during initial save.
* Set defaults to true for the 2 fields causing problems
1. log in to fides plus 
1. click on the experiences 
1. click on create new experience 
1. complete the following fields 
- name
- experience type (banner and modal)
- add a privacy notice (data sales and sharing)
- note that "allow users to dismiss" and "auto detect language" are now on …

Fides Experience form fixes

---

CHANGELOG.md
clients/fides-js/rollup.config.mjs
clients/turbo.json

Since sourcemaps don't get copied over to privacy center, the easiest solution is to include them in the scripts inline. This is also beneficial when we add GPP where there's potential for more than one sourcemap to be included.
* Remove `[^build]` dependency from rollup, since that runs as `production` and conflicts with sourcemap building.
* Change sourcemap option from `true` to `"inline"` in dev mode.
* Point to correct schema version for our version of Turbo (see https://turbo.build/repo/docs/getting-started/editor-integration#older-versions)
* From `/clients` directory in fides, run `turbo dev`
* In the browser, load the Privacy Center demo page `/fides-js-demo.html`
* Open dev tools to the Source (chrome) or Debugger (firefox) tab
* Notice that the full source is included for …

Include fides.js sourcemaps during development

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/privacy_request_endpoints.py
src/fides/api/models/privacy_request.py
tests/fixtures/application_fixtures.py
tests/ops/api/v1/endpoints/test_consent_request_endpoints.py
tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py

Closes #PROD-2359
Sending in a large list value for a single custom privacy request field results in an extremely lengthy response time that can time out due to 1) hashing the list and 2) trying to then index that list for search.
We're going to skip hashing/index custom privacy request values for search if the supplied value is an **array**. This avoids us potentially hashing/indexing too large of a value. Further, indexing arrays don't really serve a purpose given that we're indexing the entire array, there's no full text search or anything of that nature enabled.
This request should be extremely quick locally. Previously, this would hang for several minutes and then fail with a (psycopg2.errors.ProgramLimitExceeded) index row requires 51720 bytes, maximum size is 8191
```bash
curl -X …
```

Skip Indexing Custom Privacy Request Field Arrays

---

clients/admin-ui/src/features/system/hooks/useSystemFormTabs.tsx

Prevents link to the new integration management view from being shown in system form tabs if user doesn't have Plus enabled.
With "Detection & Discovery" beta flag enabled, visit a system information form's "Integrations" tab.  With Plus enabled, should see notice about detection & discovery integrations being at Integration Management; without Plus, should see description of integrations without link.

Require Plus for D&D integrations notice to be shown on system form

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts
clients/admin-ui/src/constants.ts
clients/admin-ui/src/features/privacy-experience/Preview.tsx
clients/admin-ui/src/features/privacy-experience/preview/helpers.ts

Closes [PROD-2474](https://ethyca.atlassian.net/browse/PROD-2474)
If the user's browser is set to ask sites not to track (GPC), we automatically set a cookie and do not display the banner anymore. This is causing an issue in the Admin UI preview mode where the banner preview was disappearing if a user had GPC enabled.
By always clearing cookies in preview mode, we ensure GPC doesn't cause the banner to be removed from the preview.
* Update preview container ID to be a constant
* Update preview config to include `fidesClearCookie: true`
* Enable GPC in the browser.
* Visit a non-TCF, Banner and Modal experience in Admin UI
* If the banner appears, notice that a cookie is set (you can see it set in browser dev tools)
* Reload the page or navigate away and come back
[PROD-2474]: …

Always cookies in preview mode

---

dev-requirements.txt
noxfiles/setup_tests_nox.py

Adding the `pytest-rerunfailures` plugin to `dev-requirements.txt`. This plugin introduces a `--reruns` flag that allows us to rerun failed tests up to `n` times before considering them a failure. We've implemented this to mitigate false positives that frequently occur due to data in the third-party APIs we're integrating with not settling in time for our tests.

Rerun SaaS tests on failure

---

CHANGELOG.md
clients/admin-ui/src/features/integrations/configure-monitor/ConfigureMonitorDatabasesForm.tsx
clients/admin-ui/src/features/integrations/configure-monitor/MonitorConfigTab.tsx
clients/admin-ui/src/features/integrations/configure-monitor/MonitorDatabasePicker.tsx

Text fixes:
* Change heading of "Location" column in monitor table to "Scope"
* Change title of "Projects" table in project selection table to "Scope"
* Rephrase project selection tooltip slightly

Text fixes on monitor configuration UI

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/dataset_endpoints.py
src/fides/api/api/v1/endpoints/generic_overrides.py
tests/ops/api/v1/endpoints/test_dataset_endpoints.py

Closes [PROD-2473](https://ethyca.atlassian.net/browse/PROD-2473)
Added two query params `exclude_saas_datasets` and `only_unlinked_datasets` to the `GET /datasets` endpoint to match those in `GET /filters/datasets`. 
* Updated `list_dataset_paginated` to add the two new filter options,  `exclude_saas_datasets` and `only_unlinked_datasets`
* Added relevant unit tests
* Added comment to docstring for `GET /filter/datasets` endpoint
[PROD-2473]: https://ethyca.atlassian.net/browse/PROD-2473?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-2473 Update `GET /dataset` endpoint to support `exclude_saas_datasets` and `only_unlinked_datasets` params

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/router_factory.py
src/fides/api/util/endpoint_utils.py
src/fides/api/util/errors.py
tests/ctl/core/test_api.py

Today we throw a generic 403 error for a variety of edits which make it _look_ like the user is lacking sufficient permissions, but in reality it is that they are forbidden from editing the `is_default` field on a resource (e.g. `DataUse`, `DataCategory`).
For example, we had a user report this unexpected error: they called the `/api/v1/data_category/upsert` API with this body:
```
[
{
"version_added": "2.0.0",
"is_default": true,
"fides_key": "user.unique_id.my_custom_category",
"organization_fides_key": "default_organization",
"name": "custom data category",
"description": "description for custom data category",
"parent_key": "user.unique_id",
"active": true
}
]
```
Which returns this error:
```
{ 'detail': { 'error': 'user does not have permission to modify',
'fides_key': …
```

Improve API error messages when using `is_default` field on taxonomy resources

---

CHANGELOG.md
clients/admin-ui/src/features/datamap/SettingsBar.tsx

Fix wrong system count on Datamap page

PROD-2529 Fix wrong system count on datamap

---

src/fides/api/models/consent_automation.py
src/fides/api/schemas/consentable_item.py
tests/ops/models/test_consent_automation.py
tests/ops/schemas/test_consentable_item_schema.py

Updating the `ConsentableItem` schema to use `external_id` instead of `id` to remove the need for a custom `from_orm` function. Using `external_id` allows us to just map the SQLAlchemy model's `external_id` to the Pydantic model's `external_id` without needing to map `external_id` to `id`.

Refactoring ConsentableItem to simplify Pydantic v2 migration

---

CHANGELOG.md
clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/fides.css

Fixes a newly introduced issue with overlay banner layout, specifically with the positioning of the buttons.
Includes some added polish for noticed issues while testing the mobile version.
* Reverts and HTML ordering change made [in a recent commit](https://github.com/ethyca/fides/pull/5125/files#diff-ae153e26075500c4b8af65798b4e815786cb27a5f50304e1877e7265c3ad6939L124-L126)
* Fixes some styling issues relating to the banner buttons and layout.
* Visit TCF enabled experience in the demo site (eg. http://localhost:3001/fides-js-demo.html?geolocation=eea)
* Verify user can scroll the content but the buttons remain sticky at the bottom
* Verify the "Manage Preferences" button has similar size as other buttons
* Verify order of buttons to ensure Privacy Policy link appears below Manage …

Fix TCF overlay issues on mobile sized screens

---

CHANGELOG.md
data/saas/config/snap_config.yml

Closes [#PROD-2542](https://ethyca.atlassian.net/browse/PROD-2542)
Fixes some issues with the OAuth2 config

Fixing OAuth2 config for Snap integration

---

clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/fides.css

Language picker menu is being cut off in the mobile view of overlays. Update the positioning of the button and menu to correct this issue and mimic the layout in the modal where language picker and privacy policy link occupy the same space.
* CSS tweaks to fix button/menu layouts
* Visit TCF enabled experience in the demo site in mobile (eg. http://localhost:3001/fides-js-demo.html?geolocation=eea)
* Click to open the Language picker
* Verify the menu opens _up_ and is not cut off

Fix language picker cut-off in mobile

---

clients/fides-js/src/components/fides.css

Previous button fix, caused a regression on the modal buttons specifically. This update restores the previous style that was removed, but only for those specific buttons.
* Added `flex: 1` to modal buttons only
* Visit TCF enabled experience in the demo site in mobile (eg. http://localhost:3001/fides-js-demo.html?geolocation=eea)
* Open the modal
* The buttons at the bottom should span the entire row

fix button sizes on modal

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/system-integrations-plus.cy.ts
clients/admin-ui/cypress/fixtures/connectors/connection_types.json
clients/admin-ui/cypress/fixtures/connectors/consentable_items.json
clients/admin-ui/cypress/fixtures/systems/system_active_integration.json
clients/admin-ui/src/features/common/api.slice.ts
clients/admin-ui/src/features/common/form/inputs.tsx
clients/admin-ui/src/features/datastore-connections/system_portal_config/ConsentAutomationForm.tsx
clients/admin-ui/src/features/plus/plus.slice.ts
clients/admin-ui/src/features/system/hooks/useSystemFormTabs.tsx
clients/admin-ui/src/mocks/data.ts
clients/admin-ui/src/types/api/index.ts
clients/admin-ui/src/types/api/models/ConsentableItem.ts
clients/fidesui/src/icons/ArrowDownRight.tsx
clients/fidesui/src/icons/index.ts

Closes [PROD-2344](https://ethyca.atlassian.net/browse/PROD-2344)
Adds an accordion panel to the System's Integration tab to allow customers to map each consentable item to a privacy notice for consent automation.
* Consumes both the Consentable Items API and the Privacy Notices API
* UI for displaying the options to the user for mapping
* Saves changes to the Consentable Items API and displays saved data when returning
1. In Admin UI of Fides Plus, visit the System Inventory page `/systems`
2. Add a new system and configure the Iterable integration (check with Adrian for credentials)
3. Once added, a new "Consent Automation" accordion button will appear. Click to expand it
4. Verify that the appropriate parent/child relationships exist for Iterable (see screenshot)
5. Make some …

Map notices to consent able items in Admin UI

---

clients/admin-ui/src/features/common/form/inputs.tsx
clients/admin-ui/src/pages/login.tsx

I added the `autocomplete` attribute to the password input field on the login for so that password managers got the correct hint for whether to show a "new password" form fill or an "existing password" form fill.
https://developer.1password.com/docs/web/compatible-website-design/#password-change-and-reset-forms
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
**Before:**
**After:**

Fix password manager auto complete

---

CHANGELOG.md
clients/fides-js/src/lib/cmp-stubs.ts

Closes [FIDES-1135](https://ethyca.atlassian.net/browse/FIDES-1135)
Include passed in `name` when retrying after timeout is set. Otherwise the iframe name gets added as `undefined`.
* load demo page with tcf experience (eg. http://localhost:3001/fides-js-demo.html?geolocation=eea)
* find the iframe using the following in the browser console ```document.getElementsByName("__tcfapiLocator")```
* validate that the console responds with a single iframe
[FIDES-1135]: https://ethyca.atlassian.net/browse/FIDES-1135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

include `name` in timeout retry

---

CHANGELOG.md
src/fides/api/oauth/roles.py

Closes https://ethyca.atlassian.net/browse/PROD-1782
Adds a scope to the approver role so that they can view the user management section of the Admin-UI. We already have appropriate checks in place so that the approver cannot delete other users or change other users' info.

PROD-1782: Allows approver to view user management table so they can reset their own password

---

CHANGELOG.md
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/data-discovery-and-detection/hooks/useDetectionResultColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/hooks/useDiscoveryResultColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/ActivityTable.tsx

Update when column to display when the result appeared and display a tooltip with the full date string.

PROD-2504 FE When-column-should-never-be-blank-or-have-N-A-in-Activity-table

---

clients/admin-ui/src/features/data-discovery-and-detection/tables/DiscoveryFieldBulkActions.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/DiscoveryResultTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/DiscoveryTableBulkActions.tsx

Closes PROD-2591
Right-align bulk table actions menu on table- and field-level discovery results tables.
Old:
New:

Right-align bulk action buttons on discovery tables

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/connection_endpoints.py
tests/ops/api/v1/endpoints/test_connection_config_endpoints.py

Closes [PROD-2588](https://ethyca.atlassian.net/browse/PROD-2588)
Adds a new `PATCH` endpoint for connection secrets so that each field can be updated individually. This supports a UX improvement for the Integrations page. 
* Added the new endpoint `PATCH /connection/{connection_key}/secret`
* Added relevant unit tests
* Create an integration, either from the admin UI or from the API 
* Call the PATCH endpoint, e.g from Swagger UI, and update just one field of the connection secret using this new endpoint: For example in a big query integration, you can send the `dataset` field
* Endpoint should return 200 and integration secrets should be updated, only changing the field(s) you sent in the request
[PROD-2588]: …

[PROD-2588] Support PATCH requests for connection secrets

---

clients/admin-ui/src/features/data-discovery-and-detection/hooks/useDiscoveryResultColumns.tsx

Closes [PROD-2505](https://ethyca.atlassian.net/browse/PROD-2505)
Requires BE changes from https://github.com/ethyca/fidesplus/pull/1556 to be effective
This tweak on the FE allows "empty" schemas to be shown in discovery results and acted upon.
[PROD-2505]: https://ethyca.atlassian.net/browse/PROD-2505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ensure that action buttons are displayed for empty results

---

CHANGELOG.md
clients/fides-js/docs/interfaces/Fides.md
clients/fides-js/src/components/LanguageSelector.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/docs/fides.ts
clients/fides-js/src/lib/i18n/i18n-context.tsx
clients/fides-js/src/lib/i18n/i18n-utils.ts
clients/fides-js/src/lib/initOverlay.ts
clients/privacy-center/cypress/e2e/consent-i18n.cy.ts

The current implementation ensures that the call to the language API does not block `FidesInitialized`. With these changes, it also doesn't block `FidesUIShown`.
Loads the UI immediately using English for the GVL string and asynchronously loads the resulting translation (if not English) as it becomes available.
On most connections, this is completely transparent to the user. For slower connections the user may see English strings in the banner GVL strings for a brief moment. For non-TCF overlays, these changes have zero effect or need.
* Fix malformed `<button>` in the example documentation
* Use the GVL strings from Experience to pre-populate GVL in the banner.
* load GVL translations after UI is already initialized (moved to the `TFCOverlay` component)
* update globe …

Dynamically load GVL translations

---

CHANGELOG.md
src/fides/api/models/connectionconfig.py
src/fides/api/schemas/consentable_item.py
src/fides/api/service/saas_request/saas_request_override_factory.py
tests/ops/models/test_consent_automation.py
tests/ops/service/saas_request/test_saas_request_override_factory.py

Closes [#PROD-2346](https://ethyca.atlassian.net/browse/PROD-2346)
Minor changes needed to support the main feature in Fidesplus

Changes to support consent signals

---

clients/admin-ui/src/features/user-management/NewPasswordModal.tsx

User password reset screen did not hint to password managers that a new password should be input.
https://developer.1password.com/docs/web/compatible-website-design/
https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/autocomplete
User Password Reset modal did not hint to password managers that a new password should be generated.

Use autocomplete to hint new password on User Reset Password screen

---

clients/privacy-center/components/Card.tsx

When a user hovers or focuses any of the buttons in the Privacy Center, the inner content size of the buttons changes due to the addition of borders since we use `box-size: border-box`. Adding a transparent border that is always present prevents this text reflow.
https://github.com/user-attachments/assets/7f762bad-0b09-4193-b0a7-f7264d4cddd5
https://github.com/user-attachments/assets/05176603-0c9e-48bd-b49a-013e769ce1dc

Fix text reflow on Privacy Center when user hovers

---

.vscode/settings.json
clients/admin-ui/.eslintignore
clients/admin-ui/cypress.config.ts
clients/admin-ui/cypress/.eslintignore
clients/admin-ui/cypress/.eslintrc.cjs
clients/admin-ui/cypress/tsconfig.json
clients/admin-ui/tsconfig.json
clients/cypress-e2e/.eslintignore
clients/cypress-e2e/.eslintrc.cjs
clients/cypress-e2e/cypress/support/commands.ts
clients/cypress-e2e/package-lock.json
clients/cypress-e2e/package.json
clients/fides-js/.eslintignore
clients/fides-js/rollup.config.mjs
clients/fidesui/.eslintignore
clients/privacy-center/.eslintignore
clients/privacy-center/cypress.config.ts
clients/privacy-center/cypress/.eslintignore
clients/privacy-center/cypress/.eslintrc.cjs
clients/privacy-center/cypress/e2e/consent-banner-cookies.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts
clients/privacy-center/cypress/e2e/consent-notices.cy.ts
clients/privacy-center/cypress/e2e/consent.cy.ts
clients/privacy-center/cypress/e2e/home.cy.ts
clients/privacy-center/cypress/tsconfig.json
clients/privacy-center/tsconfig.json
clients/sample-app/.eslintrc.cjs

Updates to ESLint configs to support Cypress directories

fix linting issues, especially with Cypress directories

---

CHANGELOG.md
data/saas/config/oracle_responsys_config.yml
src/fides/api/service/saas_request/override_implementations/oracle_responsys_request_overrides.py

Closes FIDES-1070
This prevents race conditions when duplicate requests are submitted or the responsys user is deleted outside of Fides

Oracle Responsys: ignore `404`s on delete endpoint

---

CHANGELOG.md
clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/fides.css
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/components/tcf/fides-tcf.css

Closes [PROD-2609](https://ethyca.atlassian.net/browse/PROD-2609)
* change to a full-width footer
* modify the order and sizing of buttons
* Split all TCF related styles into its own, new `fides-tcf.css` file
* tweak poistioning of button code for TCF banner
* Update styles of TCF banner to match new designs ([Figma](https://www.figma.com/design/nyFaHNzWkrWiC8IUc0gHg8/TCF-banner-updates?node-id=3173-192645&m=dev))
* Visit demo site with a TCF experience (eg. http://localhost:3001/fides-js-demo.html?geolocation=eea)
* validate position of banner buttons (span the full width of the banner)
* Right-click and inspect buttons and hover a button (should register 40px high and 180px wide)
* Switch to responsive design mode and pick a mobile size (or just shrink your window to around 375px.
* …

update TCF banner button layout/split tcf styles

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-requests/cells.tsx

Fix privacy request screen crashes when a PrivacyRequestResponse daysLeft property is null.

PROD-2626 Privacy-Request-screen-crashes-when-daysLeft-null

---

clients/admin-ui/package.json
clients/privacy-center/package.json

Update type generation script to also run formatter

---

CHANGELOG.md
clients/fides-js/rollup.config.mjs
clients/privacy-center/cypress/e2e/fides-js.cy.ts
clients/privacy-center/pages/api/fides-js.ts

Sourcemaps for `fides.js` and `fides-tcf.js` are now functional with this change. GPP doesn't work, but since nothing worked before, this is a huge improvement.
Clicking from console logs etc. will take you to the correct source in the browser. Setting breakpoints is now possible.
* Removes sourcemaps for GPP extension (conflicted with fides.js sourcemap)
* Moves fides.js output to first line to maintain line numbering with source maps

FidesJS sourcemaps working correctly

---

clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx
clients/admin-ui/src/types/api/models/ConnectionConfigurationResponse.ts

After the Pydantic update, integrations that contain a FidesDatasetReference field as part of their secrets are causing the frontend to crash

Fix crashing integrations after pydantic update

---

CHANGELOG.md
src/fides/api/app_setup.py

Partially Closes #2604
Add Gzip middleware https://fastapi.tiangolo.com/advanced/middleware/#gzipmiddleware specially for compressing responses in Fidesplus Experience Translations. 

Add Gzip Middleware

---

CHANGELOG.md
data/saas/config/snap_config.yml
tests/fixtures/saas/snap_fixtures.py

Closes PROD-2648
Removes an unused parameter in the Snap connector. `ad_account_id` is collected as configuration, but it's never used in the integration or its overrides.

PROD-2648: Remove unused parameter in Snap integration

---

src/fides/api/alembic/migrations/versions/9cad5a5c438c_update_stagedresource_chid_diff_statuses_booleans_data.py

Partially closes [PROD-2390](https://ethyca.atlassian.net/browse/PROD-2390)
Data migration that is needed for https://github.com/ethyca/fidesplus/pull/1581
Changes any `child_diff_statuses` keys that have a value > 0 to now have a boolean `true` value, to match the new expected schema of `{ DiffStatus.value : boolean }`
[PROD-2390]: https://ethyca.atlassian.net/browse/PROD-2390?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-2390: data migration for child diff statuses

---

CHANGELOG.md
data/saas/config/hubspot_config.yml

Partially Closes [# 2415](https://ethyca.atlassian.net/browse/PROD-2415).
We are adding the 400 Ignore errors for the unsubscribe call.
A PR For expanding the Ignore errors functionality to a postprocessor that checks the error message is on the way, See [PR-5211](https://github.com/ethyca/fides/pull/5211)
Attempt to Replicate bug reported on [the Issue](https://ethyca.atlassian.net/browse/PROD-2415)

PROD-2415 : Adding ignore 400 to unsubscribe call

---

.vscode/settings.json

Uses filetype specific settings to avoid potential conflicts with the Python side of things.

include autofix for VS code users

---

clients/admin-ui/src/features/system/system-form-declaration-tab/PrivacyDeclarationDisplayGroup.tsx

- Row hover color
- Expand clickable row area, used to only be able to click on the label's content area.
**Before**
**After**

Improve Data uses row interactions

---

CHANGELOG.md
clients/fides-js/src/lib/events.ts
clients/privacy-center/public/fides-js-demo.html

Adds timings to our debug logs for fides.js
* Run the demo site with console log open, preferable with an experience (like TCF) where the banner appears (eg. `http://localhost:3001/fides-js-demo.html?geolocation=eea`)

add timing to debug logs for fides.js

---

CHANGELOG.md
clients/admin-ui/src/features/data-discovery-and-detection/utils/findResourceType.ts

Fix no monitor button appearing on empty tables.
The problem was caused because the FE was trying to figure out the resource type based off the nested resource content. This caused a problem with empty tables causing it to think that it was a Field and therefore not showing a Monitor icon. The BE now returns a resource_type so we should use that instead. I still left the other code as a fallback since resource_type is listed as an optional property.

PROD-2701 Fix no monitor button on empty tables

---

CHANGELOG.md
clients/admin-ui/__tests__/features/dataset-helpers.test.tsx
clients/admin-ui/__tests__/test-utils.tsx
clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/package.json
clients/admin-ui/src/features/common/hooks/useLocalStorage.ts
clients/admin-ui/src/features/common/table/v2/FidesCell.tsx
clients/admin-ui/src/features/common/table/v2/FidesRow.tsx
clients/admin-ui/src/features/common/table/v2/FidesTable.tsx
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/common/table/v2/util.ts
clients/admin-ui/src/features/datamap/constants.ts
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx
clients/admin-ui/src/features/integrations/configure-monitor/MonitorConfigTab.tsx
clients/admin-ui/src/features/privacy-requests/cells.tsx

Closes PROD-2677
On the Datamap Reporting table
* New overflow indicator that represents how many categories are hidden after displaying the first 2
* Update badge styles for Data uses and Data categories columns
* User can expand each cell individually by clicking the overflow indicator
* User can collapse each cell individually by clicking anywhere in the cell
* Update the header menu:
* Rename options to "Expand all" and "Collapse all"
* Reorder so that "Expand all" is first
* add a "Wrap results" checkbox option
* Update all badges in this table to be hidden if there are 0 results
* Adjust table column resize handle to be more user friendly
* Visit Datamap report page in Admin UI `/reporting/datamap`
* Ensure that Data categories are collapsed by default (may need to visit in …

Expand/Collapse Data Categories

---

CHANGELOG.md
data/saas/config/yotpo_reviews_config.yml

Closes PROD-2738
Yotpo Reviews `domain` tooltip erroneously refers to Yotpo Loyalty.
* Edit wording on Yotpo Reviews integration tooltip

Replace Yotpo Loyalty with Yotpo Reviews in description

---

requirements.txt

Bumps `fideslang` dep - I don't _think_ anything else is needed to make the adjustment for the new special purpose?

PROD-2645: bump fideslang to 3.0.4

---

src/fides/api/schemas/connection_configuration/connection_secrets_base_aws.py
src/fides/api/schemas/connection_configuration/connection_secrets_dynamodb.py
src/fides/api/schemas/connection_configuration/connection_secrets_s3.py
src/fides/api/util/aws_util.py
src/fides/api/util/connection_type.py
tests/ops/util/test_connection_type.py

Closes [PROD-2722](https://ethyca.atlassian.net/browse/PROD-2722), [PROD-2761](https://ethyca.atlassian.net/browse/PROD-2761)
- fix PROD-2722: remove default value for the `auth_method` field on the base AWS connection secret type, so it's now correctly populated as a `required` field
- implement a fallback so that UI doesn't crash if there aren't any `required` fields inferred by the pydantic secrets schema
- fix PROD-2761: set the `region_name` arg in all of our AWS sessions that we instantiate within  our base `get_aws_session` utility function
[PROD-2722]: https://ethyca.atlassian.net/browse/PROD-2722?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[PROD-2761]: …

PROD-2722, PROD-2761

---

CHANGELOG.md
src/fides/api/common_exceptions.py
src/fides/api/graph/traversal.py
src/fides/api/models/privacy_request.py
src/fides/api/task/create_request_tasks.py
src/fides/api/task/deprecated_graph_task.py
src/fides/cli/commands/ungrouped.py
tests/fixtures/application_fixtures.py
tests/ops/task/test_create_request_tasks.py
tests/ops/task/test_deprecated_graph_task.py

Closes [PROD-2644](https://ethyca.atlassian.net/browse/PROD-2644)
When a `TraversalError` is raised as part of running an access or erasure request the logged error does not include the privacy request id, making it hard to find, and the UI shows the request in an error state but provides no information on what the error actually was. This PR adds a log that includes the privacy request id, and also creates an `ExecutionLog` instance so the error can be surfaced in the UI.
* Created two specific error classes `UnreachableNodeError` and `UnreachableEdgeError` that inherit from `TraversalError`, and throw those instead when we have an unreachable node or edge, respectively. 
* Catch all `TraversalErrors` in both `run_access_request` and `run_access_request_deprecated` , log the error …

PROD-2644 Improve logging and error visibility for TraversalErrors

---

README.md

Most of the readme hyperlinks were broken since they pointed to old urls. 
This pr intends to fix that.

Update Readme URLs to match website

---

clients/fides-js/src/components/fides.css

update fides-no-scroll so it works in all browsers (especially safari)

update fides-no-scroll so it works in all browsers 

---

clients/admin-ui/src/features/data-discovery-and-detection/hooks/useDiscoveryResultsFilterTabs.tsx

Fix discovery pagination. Change was lost due to bad merge.

Fix discovery pagination

---

CHANGELOG.md
clients/fides-js/rollup.config.mjs
clients/fides-js/src/components/Button.tsx
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/components/Spinner.tsx
clients/fides-js/src/components/fides.css
clients/fides-js/src/components/tcf/TcfConsentButtons.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/preferences.ts
clients/fides-js/src/lib/tcf.ts
clients/fides-js/src/lib/tcf/utils.ts
clients/fides-js/src/lib/tcf/vendors.ts
clients/fides-js/src/services/api.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes [PROD-2777](https://ethyca.atlassian.net/browse/PROD-2777)
Today, the “minimal” TCF banner can display the banner but the “Accept All” and “Reject All” actions are not enabled until the “full” experience is loaded. This can take several seconds to do on a low-speed connection, which creates a window where users can see a banner but are unable to opt-in.
These changes are set up for handling a new scenario in which a minimal version of `experience.gvl` is provided as part of the minimal TCF experience response.
If no GVL is included, we'll at least show some spinners during the loading of the full experience to not appear "broken" during that time.
1. visit the Fides.JS demo site with TCF enabled (eg. http://localhost:3001/fides-js-demo.html?geolocation=eea)
2. In browser's dev …

Support Accept/Reject All with minimal TCF

---

CHANGELOG.md
clients/fides-js/__tests__/lib/i18n/i18n-utils.test.ts
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/i18n/i18n-utils.ts
clients/fides-js/src/lib/initOverlay.ts
clients/privacy-center/pages/api/fides-js.ts

Closes [PROD-2764](https://ethyca.atlassian.net/browse/PROD-2764)
When the fides.js script gets cached, but a user changes their browser's language, we get into a weird state with multiple languages (especially after the GVL languages load correctly).
* Update fides.js response headers to include `Accept_Language` in the `Vary` to instruct caches to reset when language changes
* Address a few inconsistencies left over from when we switched to Minimal TCF
* Determine if Minimal TCF Experience translation matches the user's locale (in the case of caching or `window.fides_overrides.fides_locale`) and load the available translation until full TCF Experience is ready with the correct language.
1. Throttle network in browser dev tools to help see when things are loading slower
2. Load demo page …

Fix cached translation issues with Minimal TCF experience

---

CHANGELOG.md
clients/privacy-center/pages/api/fides-js.ts

In version 2.44 of the Privacy Center, the value of the default experience was set to `{}` (see https://github.com/ethyca/fides/pull/5230/files#diff-ba7bb0c80dbf370b49c211bf0e888dc34cf0f7a713e2b4b685d98b0b46b25014R155-R158).
This causes problems specifically for clients not using prefetch and CDNs as now Fides.js believe that the user received a valid, albeit empty experience and then does not call the Fides API to check for experiences.
Reverting back to `undefined` for that reason.
* initialize `experience` as `undefined`

revert to undefined instead of empty object

---

CHANGELOG.md
src/fides/api/alembic/migrations/versions/784f145ec892_add_is_hash_migrated_column.py

Closes [PROD-2793](https://ethyca.atlassian.net/browse/PROD-2793)
Updating an existing migration to use a table size check before creating the indices. Refer to the corresponding fiesplus PR for the post-migration script.
[PROD-2793]: https://ethyca.atlassian.net/browse/PROD-2793?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding table size checks to hash migration

---

CHANGELOG.md
data/saas/config/talkable_config.yml

Closes PROD-2796
Ignores `400` errors thrown by Talkable when a person is not found. 
```
{
'action_type': 'access',
'system_key': 'talkable',
'connection_key': 'talkable_api', 
'collection': 'person', 
'privacy_request_id': 'pri_[REDACTED]', 
'method': 'GET', 
'url': 'https://www.talkable.com/api/v2/people/[REDACTED]/personal_data?site_slug=[REDACTED]', 
'response': '{"ok":false,"error_message":"No person found by `person_slug`."}', 
'status_code': 400, 'error_group': 'ClientSideError'
}
```
Ideally we'd only ignore the `400`s when the error message matches that case, but for now, we'll ignore all `400` errors. We can implement that when https://github.com/ethyca/fides/pull/5211 is merged.

PROD-2796: ignore 400 errors on Talkable's person endpoint

---

CHANGELOG.md
clients/fides-js/docs/interfaces/Fides.md
clients/fides-js/src/docs/fides.ts
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/events.ts

This PR adds an `onFidesEvent` method to the global `Fides` object that subscribes the callback to Fides events. This is equivalent to calling `window.addEventListener(...)` yourself, except that the callback receives the `FidesEventDetail` object instead of a `CustomEvent`. This is needed for the Google Tag Manager template integration as it doesn't allow usage of APIs like `addEventListener` and also doesn't support `CustomEvent` or, really, any other non-primitive type.
See this [Slack thread](https://ethyca.slack.com/archives/C076JELF2HL/p1726258977000399) for the rationale.
* Load the new `fides.js` version on a page
* Make sure `Fides.onFidesEvent` is available
* Call it with a handler (e.g. `console.log`), trigger the event and verify that the handler was called

Add onFidesEvent method for an alternative way to subscribe to Fides events

---

CHANGELOG.md
src/fides/api/models/connectionconfig.py
src/fides/api/service/connectors/base_erasure_email_connector.py
src/fides/api/service/connectors/consent_email_connector.py
src/fides/api/service/connectors/dynamic_erasure_email_connector.py
src/fides/api/service/connectors/erasure_email_connector.py

Closes [PROD-2709](https://ethyca.atlassian.net/browse/PROD-2709)
Adds the `name_or_key` property to `ConnectionConfig`, and updates all email connectors to do two things:
- All logs will log the connection config key, not the name
- All `ExecutionLog` instances created will use the `name_or_key` property instead of just the name 
This is because the `name` is an optional property for the connection config. 
[PROD-2709]: https://ethyca.atlassian.net/browse/PROD-2709?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PROD-2709 Fix Email Connector logs so they use configuration key instead of name

---

CHANGELOG.md
src/fides/api/service/saas_request/override_implementations/firebase_auth_request_overrides.py
src/fides/api/service/saas_request/override_implementations/oracle_responsys_request_overrides.py
src/fides/api/util/saas_util.py
tests/ops/integration_tests/saas/connector_runner.py
tests/ops/integration_tests/saas/request_override/test_firebase_auth_task.py
tests/ops/integration_tests/saas/test_oracle_responsys_task.py

Closes [PROD-2794](https://ethyca.atlassian.net/browse/PROD-2794)
Updating the Responsys and Firebase Auth integrations to support multiple identities. These two integrations are custom and were relying on some code that is no longer in use.
[PROD-2794]: https://ethyca.atlassian.net/browse/PROD-2794?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating custom integrations to support multiple identities

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/Preview.tsx
clients/fides-js/src/components/ConsentContent.tsx

Closes [PROD-2715](https://ethyca.atlassian.net/browse/PROD-2715)
When we're adding languages in the Admin UI to an Experience Config, we should see them on the preview until they're saved, the preview just had the exp.title, exp.description, etc. because the new language wasn't included in the `available_locales` list.
This update ensures that the `available_locales` list always includes the currently edited language locale.
* As we're updating/determining the language to display, also update the `available_locales` list with that language's locale.
* Cleaned up changelog where some items were added in the wrong release
* In Admin UI, edit an experience with an available preview (non-TCF).
* Add a new language to the experience
* When the language defaults load into the form, those …

Fix Preview when Adding Languages to Experience Config

---

CHANGELOG.md
clients/admin-ui/src/features/datastore-connections/system_portal_config/ConsentAutomationForm.tsx

Fix bug where Consent Automation Accordion shows up on integrations without support for consent automation.
Iterable Integration
HubSpot Integration

PROD-2821-Consent-automation-accordion

---

CHANGELOG.md
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/components/types.ts
clients/fides-js/src/lib/initOverlay.ts
clients/fides-js/src/lib/initialize.ts

Closes [PROD-2812](https://ethyca.atlassian.net/browse/PROD-2812)
Custom overrides were being applied to the minimal TCF experience, but once the full experience was loaded custom overrides were being ignored. This fix passes the overrides along to i18n as part of the full experience's re-initialization, similar to what happens during first `init()` phase.
* Pass along the `translationOverrides` into the TCFOverlay to be used while loading the messages from experience.
* edit `fides-js-demo.html`:
Replace
```
// window.fides_overrides = {
//   fides_embed: true,
// };
```
With
```
window.fides_overrides = {
fides_title: "This is my new title",
fides_description: "This is my new description",
fides_privacy_policy_url: "https://example.com/privacy-policy",
fides_override_language: "en",
}; …
```

Include overrides when loading full experience

---

clients/admin-ui/src/features/privacy-experience/Preview.tsx

The fix in https://github.com/ethyca/fides/pull/5316 created a new regression where, even though the correct translations are appearing, the language picker stopped appearing.
* include exising `available_languages` instead of overriding them with a single language.
* In Admin UI, edit an experience with an available preview (non-TCF).
* Ensure that while changing languages to edit, or adding a new language, does indeed show the language picker.

Fix preview's language picker

---

CHANGELOG.md
src/fides/api/migrations/hash_migration_job.py

Closes [PROD-2828](https://ethyca.atlassian.net/browse/PROD-2828)
Updates the hash migration status check query to use the `is_hash_migrated IS FALSE` clause instead of `is_hash_migrated = FALSE`. The indexes for this query are created with `IS FALSE` so the status check queries were running an inefficient sequential scan on the entire table instead of an optimized index scan.
[PROD-2828]: https://ethyca.atlassian.net/browse/PROD-2828?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Updating hash migration status check

---

clients/privacy-center/public/fides-js-components-demo.html
clients/privacy-center/public/fides-js-demo.html

On the demo page, Firefox wasn't removing the cookie when clicking the "Delete cookie and reload" button. This fix specifies the `Path` to ensure that we are deleting the correct cookie.

fix deleteCookie script on demo page to include `Path`

---

CHANGELOG.md
clients/admin-ui/src/features/common/table/v2/FidesTable.tsx
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/custom-fields/CustomFieldsTable.tsx
clients/admin-ui/src/features/custom-fields/cells.tsx
clients/admin-ui/src/features/data-discovery-and-detection/hooks/useDetectionResultColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/hooks/useDiscoveryResultColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/ActivityTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/DetectionResultTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/DiscoveryResultTable.tsx
clients/admin-ui/src/features/datamap/datamap-table/hooks/useDatamapTable.ts
clients/admin-ui/src/features/integrations/configure-monitor/MonitorConfigTab.tsx
clients/admin-ui/src/features/integrations/configure-monitor/MonitorDatabasePicker.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperiencesTable.tsx
clients/admin-ui/src/features/privacy-notices/PrivacyNoticesTable.tsx
clients/admin-ui/src/features/privacy-requests/RequestTable.tsx
clients/admin-ui/src/features/properties/PropertiesTable.tsx
clients/admin-ui/src/pages/dataset/[datasetId]/[collectionName]/[subfieldUrn].tsx
clients/admin-ui/src/pages/dataset/[datasetId]/[collectionName]/index.tsx
clients/admin-ui/src/pages/dataset/[datasetId]/index.tsx
clients/admin-ui/src/pages/dataset/index.tsx
clients/admin-ui/src/pages/messaging/index.tsx
clients/admin-ui/src/pages/settings/domain-records.tsx
clients/admin-ui/src/pages/systems/index.tsx

Closes PROD-2721
Users want to be able to see the full descriptions when they get truncated in table cells. To accommodate this, we are making 3 updates to make this easier:
* Make it so that resizing columns is much easier and smoother in each table so that it's less painful to expand a "Description" column to see the full text
* Add an Expand/Collapse menu on each “Description” column to control whether or not all cells in the column will truncate the text.
* Add a `title` tooltip to each description so that users can hover their cursor over the text to see it in full.
* Update all tables to include the setting `columnResizeMode: "onChange"` for smoother resizing
* Update `<DefaultCell>` to accept `cellProps` and to hide/unhide `overflow` with ellipsis based on column settings as well …

Make all description table columns expandable

---

clients/admin-ui/src/features/datastore-connections/system_portal_config/ConnectionListDropdown.tsx
clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParametersForm.tsx
clients/admin-ui/src/features/taxonomy/TaxonomyFormBase.tsx

Closes 
Fixes a couple of small visual issues that arose as part of #5357.
Before:
After:
Before:
After:

Visual fixes for button migration issues

---

CHANGELOG.md
clients/admin-ui/src/features/common/table/v2/FidesCell.tsx
clients/admin-ui/src/features/datamap/reporting/DatamapReportTableColumns.tsx

Closes HJ-37
* change `overflowX` to `overflow` for Firefox support
* pass along the "hidden" value to the overflow attribute

Address Firefox overflow issue on Data Categories column

---

clients/admin-ui/src/features/common/custom-reports/CustomReportCreationModal.tsx

Search and replace for a code name change ended up affecting the body text. This fix reverts that mistake.

Revert search/replace issue

---

.github/workflows/backend_checks.yml
.github/workflows/cypress_e2e.yml
.github/workflows/publish_docker.yaml

Closes OPS-772
* Add Docker Hub auth to Cypress E2E Tests workflow
* Add Docker Hub auth to Backend Code Checks workflow
* Removes hardcoded Docker username in Publish Docker Images workflow and upgrades action to latest (v3)
* Adding Docker Hub auth for a premium user will increase the rate limit to 5000/day instead of the 100/6 hours for unauth'd Docker users. 
* Run currently failing CI jobs for modified workflows and ensure they pass.

Add Docker Hub auth to rate-limited CI workflows

---

CHANGELOG.md
clients/admin-ui/src/features/common/Breadcrumbs.tsx
clients/admin-ui/src/features/dataset/EditCollectionDrawer.tsx
clients/admin-ui/src/features/dataset/EditFieldDrawer.tsx
clients/admin-ui/src/features/dataset/constants.ts
clients/admin-ui/src/features/dataset/helpers.ts
clients/admin-ui/src/pages/dataset/[datasetId]/[collectionName]/[subfieldUrn].tsx
clients/admin-ui/src/pages/dataset/[datasetId]/[collectionName]/index.tsx
clients/admin-ui/src/pages/dataset/[datasetId]/index.tsx

Closes HJ-36
This is a bit of a bandaid fix to handle nested fields on the frontend. We are specifying something other than `.` used in nested field names for the URN so that we can distinguish those. More robust fixes are happening on both the BE and FE in separate tickets.
* Specify a non-period separator for FE logic
* Apply some best practices to the Edit drawer and Breadcrumbs to avoid race conditions during E2E testing and for optimization in general.
* In Fides Plus Admin UI, visit the Manage datasets page (eg. http://localhost:3000/dataset)
* **If the dataset `example_dataset_issue_hj36` exists**
1. Click it
2. Click `example_table`
3. Ensure that you can still add/remove Categories from the "Can save data category changes" fields.
4. Click through to the nested field …

FIX: separate urn with non-nested-pattern for now

---

CHANGELOG.md
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/lib/preferences.ts
clients/privacy-center/components/consent/notice-driven/NoticeDrivenConsent.tsx
clients/privacy-center/public/fides-js-demo.html

If GPP (browser's "Do Not Track") is being applied after Fides initialization, we need to update the initial overlay to reflect the new state.
This is especially important for Firefox browsers (Gecko) because—not only does FF make it easy to enable GPP—GPP gets applied rather late due to how Gecko handles queuing the `setTimeout` on the [last step](https://github.com/ethyca/fides/blob/main/clients/fides-js/src/lib/initialize.ts#L461) of our `initialize` function.
* Add an event watch for `FidesUpdating` and use that to update the Overlay's notices as applicable
* Enable [GPP in Firefox](https://support.mozilla.org/en-US/kb/how-do-i-turn-do-not-track-feature).
* Using Firefox now, visit demo page of (or create) an Experience with config:
* Modal only
* GPP enabled for U.S. …

Apply any updated state to the overlay

---

clients/admin-ui/src/features/data-discovery-and-detection/SearchInput.tsx
clients/admin-ui/src/features/privacy-requests/PrivacyRequestsContainer.tsx
clients/admin-ui/src/pages/dataset/new/index.tsx
clients/admin-ui/src/pages/integrations/[id].tsx
clients/admin-ui/src/theme/ant.ts

Closes HJ-60
Fixes several visual issues introduced by Ant button migration. 
Changes "default" button color from light gray to white:
Changes spacing between action buttons on privacy request manager page:
Adds space between buttons on integration detail view:
Fixes a bug where "upload a dataset YAML" button in add dataset view was in "ghost" state:
Tweaks colors on search input and clear button to differentiate more clearly:

Fix button visual issues

---

CHANGELOG.md

- Improve GoogleCloudSQLPostgresMonitor so it explores available databases 
https://github.com/ethyca/fides/pull/5358
- Incorrect GPC signal on manual consent load 
https://github.com/ethyca/fides/pull/5384
- Dataset with nested fields unable to edit Categories 
https://github.com/ethyca/fides/pull/5383
- Gladly Integration 
https://github.com/ethyca/fides/pull/5346
https://github.com/ethyca/fides/pull/5374 - icons
- button styling updates 
https://github.com/ethyca/fides/pull/5386
- Allow Responsys and Firebase connectors to ignore extra identities
https://github.com/ethyca/fides/pull/5388
- Fixed cookies not deleting on opt-out 
https://github.com/ethyca/fides/pull/5338

update changelog for 2.47.1

---

CHANGELOG.md
clients/admin-ui/src/features/auth/ProtectedRoute.tsx

Closes [HJ-77](https://ethyca.atlassian.net/browse/HJ-77)
Cypress tests have been failing occasionally in the Auth tests, specifically relating to the login redirects.
After some investigation, it has been determined this is caused by a race condition where we are sometimes telling the NextJS router to redirect to `/login` multiple times resulting in the error: `"Abort fetching component for route: ..."`
It turns out NextJS sends that error when given too many `router.push` commands at once.
* Take advantage of `useState` to track redirects to prevent duplicating a redirect already in progress. ([credit](https://github.com/vercel/next.js/discussions/39040#discussioncomment-3289472))
* Also checks to see if a redirect is looping on itself, making sure the "from" and the "to" are not the …

Prevent multiple login redirects at once

---

clients/fides-js/src/lib/initialize.ts
clients/fides-js/src/services/api.ts

Closes [PROD-1410]
If you call `Fides.init()` it doesn't seem to pass property ids specified in the config. This PR should fix that.

PROD-1410: Pass property id when fides.js intializes

---

clients/admin-ui/src/features/data-discovery-and-detection/SearchInput.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/ActivityTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/DetectionResultTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/DiscoveryResultTable.tsx

Closes HJ-35
Restores width of search input to stop the icon legend tooltip from floating awkwardly off to the side.

Fix search input width on D&D tables

---

data/saas/config/attentive_config.yml
data/saas/config/checkr_config.yml
data/saas/config/marigold_engage_config.yml
data/saas/config/oracle_responsys_config.yml
data/saas/config/powerreviews_config.yml
data/saas/config/simon_data_config.yml
data/saas/config/snap_config.yml
data/saas/config/stripe_config.yml
data/saas/config/surveymonkey_config.yml
data/saas/config/talkable_config.yml
data/saas/config/twilio_conversations_config.yml
data/saas/config/twilio_sms_config.yml

Closes [FIDES-1412]
Updates integration user guides to correct URLs instead of older URLs that 404.
[FIDES-1412]: https://ethyca.atlassian.net/browse/FIDES-1412?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIDES-1412: Update integration guides to not 404

---

src/fides/api/alembic/migrations/versions/4ebe0766021b_add_connection_type_to_dataset_.py
src/fides/api/alembic/migrations/versions/4ebe0766021b_add_connection_type_to_dataset_namespace.py
src/fides/api/schemas/namespace_meta/bigquery_namespace_meta.py
src/fides/api/schemas/namespace_meta/namespace_meta.py
tests/ops/service/connectors/test_queryconfig.py

Part of [HJ-23](https://ethyca.atlassian.net/browse/HJ-23)
Migration to add the `connection_type` field to all existing `namespace` dicts in the `fides_meta` field of the `Dataset` model.
* Migration to populate `connection_type` for existing datasets with a namespace 
* Make sure you have at least 4 datasets created (but the more the merrier!): 
*  A: One without a `namespace` key in its `fides_meta` field 
*  B: One with a `namespace` key and value `{ "project_id": "some-id" }` (simulates a BigQuery dataset created through D&D)
*  C: One  with a `namespace` key and value `{ "database_instance_id": "some-id" }` (simulates an RDS MySQL dataset created through D&D)
* D: One with a `namespace` key and value `{ "other": "test" }` 
* Run the migration (if it was already run when you started …

HJ-23 Add connection_type to NamespaceMeta

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/datasets.cy.ts
clients/admin-ui/cypress/fixtures/dataset.json
clients/admin-ui/src/features/common/nav/v2/routes.ts
clients/admin-ui/src/features/dataset/DatasetBreadcrumbs.tsx
clients/admin-ui/src/features/dataset/EditFieldDrawer.tsx
clients/admin-ui/src/features/dataset/constants.ts
clients/admin-ui/src/features/dataset/helpers.ts
clients/admin-ui/src/pages/dataset/[datasetId]/[collectionName]/[...subfieldNames]/index.tsx
clients/admin-ui/src/pages/dataset/[datasetId]/[collectionName]/index.tsx
clients/admin-ui/src/pages/dataset/[datasetId]/index.tsx
clients/admin-ui/src/pages/dataset/index.tsx

Utilize NextJS catch-all segments to avoid the need for "." separated `subfieldURN` and encode/decode all field names when used as URL parts.
(see https://nextjs.org/docs/pages/building-your-application/routing/dynamic-routes#catch-all-segments)
* Implement catch-all segment route
* Replace URN usage with new catch-all segment support instead
* Include styles to allow breadcrumbs to get super long and scrollable
* Hides Taxonomy Picker on rows with subfields until [that bug](https://ethyca.atlassian.net/browse/HJ-20) gets fixed
* Add the following dataset
```
- fides_key: example_dataset_issue_hj36
organization_fides_key: default_organization
tags: null
name: example_dataset_issue_hj36
description: Minimal dataset reproducing issue (HJ-36)
meta: null
data_categories: null …
```

Use NextJS catch-all segments instead of URN

---

clients/admin-ui/src/features/common/table/v2/FidesCell.tsx

Closes [#HJ-75](https://ethyca.atlassian.net/browse/HJ-75)
On the bottom of the first column in the reporting view, there’s a double line. Let’s remove that. See ref image below. 
Before:
After:
* Visit a populated Data map report page (eg. `http://localhost:3000/reporting/datamap`)
* Scroll to the very bottom
* First column should not have a double border

Fix: remove double line from final row's first column

---

CHANGELOG.md
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx
clients/admin-ui/src/features/privacy-requests/RequestTable.tsx

Closes HJ-74
Fixes icon placement on "download" buttons on datamap report table and privacy request table so it's no longer off-center.
Before:
After:

Fix "download" button icon placement

---

clients/admin-ui/src/features/common/SearchBar.tsx
clients/admin-ui/src/features/data-discovery-and-detection/SearchInput.tsx
clients/admin-ui/tailwind.config.js
clients/fidesui/src/index.ts

Styling tweaks to D&D search input "clear" button (particularly hover state).  Before:
After:
* Refactor D&D's debounced search input to use existing SearchBar component
* Adds new "neutral" colors to Tailwind config

Refactor search inputs

---

clients/fides-js/src/lib/hooks/useMediaQuery.ts

Closes [FIDES-1429]
The method we're using for media queries only became available as of Safari 14. Applied the work around mentioned in the stackoverflow post below to use an API that is available in Safari 13 when necessary.
https://stackoverflow.com/questions/62693995/addeventlistener-is-not-a-function-for-matchmedia-in-safari-browser/75517985#75517985
[FIDES-1429]: https://ethyca.atlassian.net/browse/FIDES-1429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIDES-1429: Safari < 14 support

---

CHANGELOG.md
clients/admin-ui/src/features/common/ClipboardButton.tsx
clients/fidesui/package.json
clients/fidesui/src/index.ts
clients/package-lock.json

Supports [HJ-71](https://ethyca.atlassian.net/browse/HJ-71)
Exports [Carbon Icons](https://carbondesignsystem.com/elements/icons/library/) from `fidesui` prefixed as `Icons` to avoid conflicts with other components
Upgrade Ant Design to latest version to benefit from new `variant` property as well as bug fixes.
[HJ-71]: https://ethyca.atlassian.net/browse/HJ-71?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add Carbon Icons and upgrade Ant Design

---

clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/src/features/common/table/v2/cells.tsx

Closes [HJ-105](https://ethyca.atlassian.net/browse/HJ-105)
We should support enter/return while editing column names in the reporting view (to apply/save). This is a nice quality of life improvement for our customers and compliant for accessibility.
* Add form context to the header field
* Add ability to submit form when the Enter key is pressed
* Visit a populated Data map report page in Admin UI (`/reporting/datamap`)
* Click the kebab menu
* Click the "Rename columns" option
* Enter some text in one of the fields
* Instead of clicking the "apply" button, simply press the Enter key while still focused in the edited field
* Form should submit and go back to read only mode (same behavior as the "apply" button)
[HJ-105]: https://ethyca.atlassian.net/browse/HJ-105?atlOrigin=eyJpIjoiNWRkNTlj …

Submit form on Enter press

---

src/fides/api/service/connectors/sql_connector.py

Closes [LA-57](https://ethyca.atlassian.net/browse/LA-57)
Adding keep-alive settings for the Redshift connector. Here is an explanation of the settings:
- keepalives: enable tcp keepalive
- keepalives_idle: seconds before sending first keepalive probe after the connection is idle
- keepalives_interval: seconds between subsequent keepalive probes is no response is received
- keepalives_count: number of failed keepalive probes before declaring a connection dead
[LA-57]: https://ethyca.atlassian.net/browse/LA-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add keepalive settings for redshift integration

---

CHANGELOG.md
src/fides/api/service/connectors/sql_connector.py

Closes [LA-57](https://ethyca.atlassian.net/browse/LA-57)
Adding keep-alive settings for the Redshift connector. Here is an explanation of the settings:
- keepalives: enable tcp keepalive
- keepalives_idle: seconds before sending first keepalive probe after the connection is idle
- keepalives_interval: seconds between subsequent keepalive probes is no response is received
- keepalives_count: number of failed keepalive probes before declaring a connection dead
[LA-57]: https://ethyca.atlassian.net/browse/LA-57?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding keepalive settings for Redshift

---

CHANGELOG.md

- API router sanitizer being too aggressive with NextJS Catch-all Segments
https://github.com/ethyca/fides/pull/5438
- Fix BigQuery `partitioning` queries to properly support multiple identity clauses 
https://github.com/ethyca/fides/pull/5432

update changelog for 2.48.1

---

CHANGELOG.md
src/fides/api/models/connectionconfig.py
src/fides/api/schemas/namespace_meta/bigquery_namespace_meta.py
src/fides/api/schemas/namespace_meta/namespace_meta.py
tests/fixtures/bigquery_fixtures.py
tests/ops/service/connectors/test_bigquery_queryconfig.py

Trying to parse a correct `fides_meta.namespace` field from a BigQuery dataset (i.e with a `connection_type: 'bigquery'`) was raising a Pydantic validation error, because Pydantic was expecting an Enum instance for `connection_type` rather than a string.  We now use the string literal for the type rather than the enum value. 
I've also added a test for this case (this was an oversight on my part when I implemented the original PR) and updated two fixtures to include the `connection_type` as well.  
If you run the test added in `tests/ops/service/connectors/test_bigquery_queryconfig.py` without the other changes, it should fail with the validation error. Adding the changes to the `BigQueryNameSpaceMeta` should have the test passing. 
**Manual check: ** 
For easier testing …

HJ-143: Fix ValidationError for datasets with a connection_type

---

CHANGELOG.md
clients/admin-ui/src/features/datamap/reporting/DatamapReportTableColumns.tsx

Closes [HJ-39](https://ethyca.atlassian.net/browse/HJ-39)
Any column in Data map report that uses a badge should have the newer badge look/feel
* Add `badgeProps={{ variant: "outline" }}` to each column using the `GroupCountBadgeCell` component as the cell renderer
Create a system that populates each of the following columns in the Data map report
* Data use
* Data category
* Data subjects
* Data Stewards (can this even be done?
* Destinations
* Features
* Sources
* Legal Basis for profiling
* Legal Basis for transfers
* Responsibilities
* Shared Categories
* System Dependencies
* System Undeclared data categories
* Data use undeclared categories
* Cookies
Ensure all of those columns have the new, consistent looking badge.
Note: Data use and Data category columns already have this new …

Apply updated taxonomy labels and patterns to other columns in the data map report

---

CHANGELOG.md
clients/admin-ui/src/features/common/system-data-flow/DataFlowAccordionForm.tsx

Closes HJ-164
Restores the HTML `submit` type to the "Save" button in the system detail source/destination forms so the form works again (it was accidentally removed in the Ant button migration).

Fix source-destination save button

---

.github/workflows/backend_checks.yml

While working on FE CI stuff, the Backend checks keep firing off just because I'm updating the github actions for FE. This change is to stop that madness.
* Ignore FE github yml's

ignore checking BE with FE CI changes

---

.github/workflows/cli_checks.yml

While working on FE CI stuff, the CLI checks keep firing off just because I'm updating the github actions for FE. This change is to stop that madness.
* Ignore FE github yml's

 ignore checking CLI with FE CI changes

---

CHANGELOG.md
clients/admin-ui/src/features/consent-settings/GppConfiguration.tsx
clients/admin-ui/src/pages/settings/consent.tsx
clients/admin-ui/src/types/api/models/GPPUSApproach.ts
clients/fides-js/__tests__/lib/gpp/us-notices.ts
clients/fides-js/src/fides-ext-gpp.ts
clients/fides-js/src/lib/gpp/types.ts
clients/fides-js/src/lib/gpp/us-notices.ts
clients/privacy-center/types/api/models/GPPUSApproach.ts

Closes [HJ-167](https://ethyca.atlassian.net/browse/HJ-167), [HJ-84](https://ethyca.atlassian.net/browse/HJ-84)
- Under “Settings > Consent” IN the US GPP section, I can choose a third option: “Enable US National and State-by-State notices”
- Fides allows users to configure both the national and state notices simultaneously.
- The CMP includes the national section as a parsed and applicable section when a user visits from a location with an experience configured to display the national section.
- The CMP still includes the appropriate state section as a parsed and applicable section when a user visits from a state with an experience configured to display that state section. 
* Adds new configuration option to set the approach to `GPPUSApproach.ALL` on consent settings page
* Fixes button …

Support new "All" GPP approach

---

clients/fides-js/__tests__/integrations/blueconic.test.ts
clients/fides-js/src/docs/fides.ts
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/integrations/blueconic.ts
clients/fides-js/src/integrations/shopify.ts
clients/fides-js/src/lib/consent-constants.ts
clients/fides-js/src/lib/consent-types.ts

Closes [HJ-166]
Support BlueConic Objectives
[HJ-166]: https://ethyca.atlassian.net/browse/HJ-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HJ-166: Support BlueConic objectives

---

CHANGELOG.md
src/fides/api/db/base.py
src/fides/api/models/connectionconfig.py
src/fides/api/models/detection_discovery.py
tests/conftest.py
tests/fixtures/detection_discovery_fixtures.py
tests/ops/api/v1/endpoints/test_connection_config_endpoints.py
tests/ops/models/test_detection_discovery.py

Closes  [HJ-131](https://ethyca.atlassian.net/browse/HJ-131)
Before, trying to delete an integration (i.e `ConnectionConfig`) that had a related monitor (i.e `MonitorConfig`) would throw a 500 error. Intended behavior is to cascade the deletion so that all monitors associated to the given `ConnectionConfig` are deleted. 
- Updated `ConnectionConfig` model to explicitly define its `monitors` reference, and updated the class' `delete` method to iterate over its related `MonitorConfig`s and delete them as well
- Added a test for this case
- Created a `detection_discovery_fixtures.py` file to organize D&D fixtures in one single place
1. Pull down [this fidesplus branch](https://github.com/ethyca/fidesplus/pull/1717) so that you have all D&D features. 
2. Create an integration, or click on an …

HJ-131 Delete monitors before deleting integration

---

clients/fides-js/__tests__/integrations/blueconic.test.ts
clients/fides-js/src/integrations/blueconic.ts

Closes HJ-166
Uses the BlueConic API correctly.
* Get profile before using it.
NA

HJ-166: Use BlueConic Profile API correctly.

---

CHANGELOG.md
tests/fixtures/bigquery_fixtures.py

Closes [LA-147](https://ethyca.atlassian.net/browse/LA-147)
Fixing an issue with a fixture used by BigQuery tests. See inline comments for details.
* Updated fixture
1.  All CI tests should pass
[LA-147]: https://ethyca.atlassian.net/browse/LA-147?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing BigQuery fixture

---

CHANGELOG.md
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/fides.css

Closes HJ-201
Fixes a bug where the "powered by" brand link was misaligned when the consent modal didn't have a language picker or privacy policy link.
Before:
After:
With language picker and privacy policy link:
* Add a new classname to the modal secondary button group and enforce a min-height (as we do for the language picker) when showFidesBrandLink is true
1. View the consent modal for an experience with a 

Fix misalignment of "powered by" brand link

---

clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParameters.tsx
clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/helpers.test.ts
clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/helpers.ts

Closes [LA-149](https://ethyca.atlassian.net/browse/LA-149)
Updates the `generateIntegrationKey` helper function to remove unsupported characters.
* Remove unsupported characters from system key
* Adds unit tests
1.  Create a system with a period, for example "Zendesk Inc."
2. Add an integration
3. You should be able to save the integration with no issues
[LA-149]: https://ethyca.atlassian.net/browse/LA-149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removing invalid characters from auto-generated integration keys

---

clients/fides-js/docs/README.md
clients/fides-js/docs/enumerations/PrivacyNoticeRegion.md
clients/fides-js/docs/interfaces/FidesExperienceConfig.md
clients/fides-js/src/docs/fides-experience-config.ts
clients/fides-js/src/docs/index.ts
clients/fides-js/src/docs/privacy-notice-region.ts

LA-128 Fix docs for region codes

---

clients/admin-ui/cypress/e2e/discovery-detection.cy.ts

Removes a .only that was accidentally left in the D&D Cypress test suite.
1. CI passes

Remove .only from test suite

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/privacy_request_endpoints.py
tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py

Closes [LA-156](https://ethyca.atlassian.net/browse/LA-156)
Fixing issue where custom identities were not being passed in correctly to the `dispatch_message_task`.
1. Add a custom identity to the Privacy Center
```
"identity_inputs": {
"email": "required",
"stack_overflow_id": { "label": "Stack Overflow ID" }
},
```
2. Configure a messaging provider
3. Set `FIDES__NOTIFICATIONS__SEND_REQUEST_RECEIPT_NOTIFICATION=true`
4. Submit a privacy request
5. You should receive a `Your privacy request has been received` email
[LA-156]: https://ethyca.atlassian.net/browse/LA-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing privacy request received message

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/form/helpers.tsx

Closes [HJ-253](https://ethyca.atlassian.net/browse/HJ-253)
include manage label in TCF experience
1.  Visit Experience page in Admin UI
2. Click through to a TCF experience
3. Click "English" to open translations
4. Ensure "Manage privacy preferences" button label is an option
[HJ-253]: https://ethyca.atlassian.net/browse/HJ-253?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

include manage label in TCF experience

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/cells.tsx

Closes HJ-255
Note: This is almost exactly the same as #5489 but for the Experiences table.
Toggling the switches in the Experiences table can sometimes take a moment or two and we aren't giving any feedback to the user. Now that we have toggle switches with loading states (thanks, Ant!) let's take advantage of that.
https://www.loom.com/share/c4da372b70ab46d89c01324a24fa8e53
* Add a loading state to the `EnablePrivacyExperienceCell` component
1. Visit Privacy experience page `/consent/privacy-experience`
2. Toggle some notices and notice the spinner while it loads (even after the confirmation modal)

add loading state to Experience switches

---

CHANGELOG.md
clients/privacy-center/app/server-environment.ts
clients/privacy-center/app/server-utils/PrivacyCenterSettings.ts
clients/privacy-center/app/server-utils/loadEnvironmentVariables.ts
clients/privacy-center/features/common/property.slice.ts
clients/privacy-center/features/consent/consent.slice.ts
clients/privacy-center/features/consent/hooks.ts

Fetch correct experience when a privacy center property is being use. Add env variable to override use a specific property for the root domain (when no property paths are used).
* If property_id is available, send it as a paramater to the fetch experience function
* Add env variable to override use a specific property 

Send property id and also override path.

---

clients/fides-js/__tests__/integrations/blueconic.test.ts
clients/fides-js/src/integrations/blueconic.ts

Set Consented Objects to all if Fides detects that a user is in a region with no consent preferences.
Closes [FIDES-1606]
Update BlueConic integration to communicate that objectives are consented to when Fides detects that the user is in a state with no consent options.
[FIDES-1606]: https://ethyca.atlassian.net/browse/FIDES-1606?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FIDES-1606: Change BlueConic Consent Behavior

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/systems-plus.cy.ts
clients/admin-ui/src/features/system/hooks/useSystemFormTabs.tsx
clients/admin-ui/src/pages/systems/configure/[id].tsx
clients/admin-ui/src/pages/systems/index.tsx

Closes [LA-167](https://ethyca.atlassian.net/browse/LA-167)
Adds URL "fragments" for the different tabs in the system page. This allows us to deep-link into specific tabs. It also allows us to navigate back to a specific system tab if needed.
* Moved some logic away from the systems page and into `useSystemFormTabs.tsx`
1.  Navigate between the different tabs in the system page, verify the URL updates
2. Copy one of the URLs and verify you can navigate directly to that tab by following the URL
[LA-167]: https://ethyca.atlassian.net/browse/LA-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Adding hashes to system tab URLs

---

CHANGELOG.md
src/fides/config/helpers.py

Closes https://ethyca.atlassian.net/browse/LA-170
Remove unnecessary load_file debug logs
* Remove log line
1.  run `nox -s dev`
2. Confirm no log lines like the following: 
```
fides  | 2024-11-26 16:22:10.859 | DEBUG    | fides.config.helpers:load_file:45 - Loading file /fides/src/fides/api/models/../../data/location/locations.yml from /fides/.fides/fides.toml
fides  | 2024-11-26 16:22:11.300 | DEBUG    | fides.config.helpers:load_file:45 - Loading file /fides/src/fides/api/models/../../data/location/locations.yml from /fides/.fides/fides.toml
fides  | 2024-11-26 16:22:11.425 | DEBUG    | fides.config.helpers:load_file:45 - Loading file /fides/src/fides/api/schemas/../../data/language/languages.yml from /fides/.fides/fides.toml
```
* …

LA-170: Remove unnecessary load_file debug logs

---

CHANGELOG.md
src/fides/api/api/v1/endpoints/generic_overrides.py
src/fides/api/schemas/taxonomy_extensions.py
tests/ops/api/v1/endpoints/test_taxonomy_overrides.py

Closes https://github.com/ethyca/fides/pull/new/LA-168
Adds support for taxonomy creation specifying a parent key while not specifying a fides key.
If parent_key is provided, fides_key must contain that parent_key. e.g. parent_key = `user`, and fides_key must start with `user.`
If parent_key is not provided, fides_key is generated as usual, with no prefix.
* Updates data category and data use create endpoints to support fides_key generation when parent key is provided.
1. Use `http://localhost:8080/docs#/DataCategory/Create_api_v1_data_category_post` with the following req body:
```
{
"version_deprecated": null,
"replaced_by": null,
"organization_fides_key": "default_organization",
"tags": null,
"name": "new user key",
"description": "Records of the location of a user.",
"parent_key": …
```

LA-168: adds support for taxonomy creation specifying a parent key

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-requests/events-and-logs/EventLog.tsx

Closes https://ethyca.atlassian.net/browse/LA-171
Adds column for action type in event logs of privacy requests. Helps distinguish data retrieval vs data deletion as part of an erasure request
* Add column for action type
1. Create a deletion request in the privacy center
2. Nav to admin-UI and see that there is a new column for "Action Type"

LA-171: adds column for action type in event logs

---

CHANGELOG.md
clients/sample-app/README.md
clients/sample-app/src/pages/embedded-consent.tsx

Creating a new sample page that demonstrates how to embed the CMP onto a page. This is useful on its own, but will also be helpful for demonstrating how to load it into a Native mobile web view.
* Updated the Readme with a note about port conflicts
* Added the Embedded Consent page
1. Run Cookie House sample app
2. visit `/embedded-consent?geolocation=eea` to see the new embedded page
3. compare to the same modal on the existing cookie house page. They should be identical. `/?geolocation=EEA`

Embedded CMP Layer 2 example page

---

tests/ops/api/v1/endpoints/test_dataset_test_endpoints.py
tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py
tests/ops/service/dataset/test_dataset_service.py

Removes the unnecessary `integration-external` Pytest mark from recently added tests
1.  CI tests should pass

Removing unnecessary integration-external mark

---

CHANGELOG.md
clients/privacy-center/components/BrandLink.tsx
clients/privacy-center/components/Layout.tsx
clients/privacy-center/components/consent/ConfigDrivenConsent.tsx
clients/privacy-center/components/consent/notice-driven/NoticeDrivenConsent.tsx
clients/privacy-center/pages/index.tsx

Closes HJ-299
Fixes Fides brand link sometimes overlapping page content on small screens.  Issue was caused by absolute positioning offsetting from the bottom, but the location of the bottom of the container is positioned differently depending on whether a privacy policy link is present.
To fix, removes the BrandLink component from the universal Layout (calculating vertical position is tricky since it varies depending on page size and contents) and puts it in page content along with the privacy policy link when present.
* Moved BrandLink from Layout component to be part of page content on all pages
* Refactors to BrandLink to move commonly-used props inside the component
1.  View privacy center homepage and consent page at all screen sizes
2. Make sure "powered by Ethyca" link is …

Fix Fides brand link position on small screens

---

clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/components/fides.css
clients/sample-app/src/pages/embedded-consent.tsx

Some minor fixes for the Embedded Demo page.

Minor Demo fixes

---

CHANGELOG.md
tests/ops/integration_tests/setup_scripts/postgres_setup.py

Closes [LA-206](https://ethyca.atlassian.net/browse/LA-206)
Adding `MonitorConfig` import to `postgres_setup.py` to fix data seeding
1.  Run `nox -s quickstart` and go through the steps, you should see the access results JSON at the end
[LA-206]: https://ethyca.atlassian.net/browse/LA-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fixing quickstart

---

src/fides/api/tasks/__init__.py
tests/ops/tasks/test_database_task.py

Closes HJ-311
Reverts the disabling of connection pooling on celery worker tasks that was introduced by https://github.com/ethyca/fides/pull/5448/files.
We are suspecting (but are not entirely sure) that this is contributing to some DB performance degradation we are noticing on Fides Cloud
1. [x] we should smoke test for no obvious regressions
2. [x] once complete, we should build a prerelease image and deploy to fides cloud to see if this is effective in mitigating the performance issue we're noticing

revert disabling pooling on celery worker tasks

---

CHANGELOG.md

Add missing changelog entry from https://github.com/ethyca/fides/pull/5592
This change is going into `2.51.1` so i've put it under that section

update changelog for PR #5592

---

CHANGELOG.md
clients/admin-ui/src/theme/ant.ts
clients/fidesui/src/hoc/CustomSelect.tsx

Closes [HJ-312](https://ethyca.atlassian.net/browse/HJ-312)
- Ant Select component’s hover color is still “Sandstone” but should be “Neutral 50”
- For multiselect/tags mode, the checkmark should be the Carbon icon and not Ant Icon.
1. In AdminUI, Open any select and hover the options. Hover color should be "Neutral 50" aka "#fafafa" which is slightly lighter than a selected option.
2. Open a "tag" mode select (like the Responsibility field when creating a new System) and make a selection. Note that the check icon is slightly different from Ant's default
**OLD**
**NEW**
[HJ-312]: https://ethyca.atlassian.net/browse/HJ-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Ant Select minor fixes

---

CHANGELOG.md
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/sample-app/package-lock.json
clients/sample-app/package.json
clients/sample-app/src/pages/embedded-consent.tsx
clients/sample-app/src/pages/index.tsx

Adds a "FidesUpdated" listener which in turn triggers a "FidesUpdated" event in the Flutter apps which have these pages open in a webveiw.
* Some minor renaming and inconsistency updates
* Upgrade react-select for the Cookie House region selector
* Add "FidesUpdated" listener/trigger on both the Cookie House webpage and the Embedded Consent.
NOTE: These updates are completely reliant on the Flutter Native App to be running in order to work. Testing is not feasible for this PR alone, so a thorough code review will have to suffice.

Set up Flutter listeners and callHandlers in the Sample App for native app communication

---

.github/dependabot.yaml

Add fides-js to dependabot.

---

clients/admin-ui/cypress/e2e/datamap-report.cy.ts

Updating a Cypress test for the datamap report table now that the undeclared data category columns use the new `BadgeCellExpandable` component
* Updated test
1.  Cypress tests should pass

Fixing datamap Cypress test

---

CHANGELOG.md
clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParameters.tsx
clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/fields/DatasetConfigField/useDatasetConfigField.tsx

* Added option to patchConnectionDatasetConfig to show/hide success alert (default: true)
* Use option to hide alert when updating datasets from integration screen
1. Create a system, or open the system page for an existing system 
2. Go to the Integrations tab of the system page 
3. Add a database integration and save it
5. Only one toast should show up saying "Integration successfully added!"
6. Now hit save again 
7. Only one toast should show up saying "Integration successfully updated!"

LA-56 Only trigger dataset save if values have changed

---

clients/admin-ui/src/features/taxonomy/components/TaxonomyInteractiveTree.tsx
clients/admin-ui/src/features/taxonomy/components/TaxonomyTreeNode.tsx

Data Subjects don't support parent_keys, so we shouldn't allow creating child labels. Hide the buttons to add a new label, except for the root node.
* Hide the buttons to add a new Data Subject label, except for the root node.
1.  Go to Taxonomy page
2. Select Data Subject
3. Hover over the labels and confirm the Add button is not there
4. Hover over the root label "Data Subject" and confirm the add button is there and you're able to create a new label

Hide buttons to add child labels for Data Subjects

---

clients/admin-ui/src/features/data-discovery-and-detection/DiscoveryMonitorBreadcrumbs.tsx
clients/admin-ui/src/pages/consent/privacy-notices/[id].tsx
clients/admin-ui/src/pages/consent/reporting/index.tsx
clients/admin-ui/src/pages/messaging/[id].tsx
clients/admin-ui/src/pages/settings/domains.tsx
clients/admin-ui/src/pages/settings/locations.tsx
clients/admin-ui/src/pages/settings/organization.tsx
clients/admin-ui/src/pages/settings/regulations.tsx
clients/admin-ui/src/pages/systems/configure/[id]/test-datasets.tsx

General clean up fixes after Breadcrumb story migration
* Remove Layer icon from "All activity" breadcrumb item in D&D
* Bump paragraph descriptions from sticky PageHeader as needed
1. Visit Data Detection page and notice that "All activity" does not have an icon next to it
2. Visit the following pages to make sure page header still looks good:
* Privacy Notices -> click on a notice
* Consent reporting
* Messaging -> click on a message
* Domains
* Locations
* Organization
* Regulation
* System config -> click a system -> add `/test-datasets` to the end of the URL in place of `#tabname`

Page Header/Breadcrumb fixes

---

clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx

Fix datamap report breaking when no it has no results
* Check for datamap results length before accessing element
1.  Delete all systems
2. Go to Datamap Report page
3. Check that it doesn't break when it doesn't have any results

LA-225 Datamap-report-page-breaks-if-there-are-no-results

---

clients/admin-ui/src/pages/taxonomy/index.tsx

Fix creation of root level new labels. 
* Use null as parent_key instead of root when creating root-level labels
1.  Go to Taxonomy
2. Try create a label from the top level (Data Categories, Data Uses, Data Subjects)

Fix creation of new root level labels

---

CHANGELOG.md
src/fides/api/models/db_cache.py
tests/ops/models/test_dbcache.py

Relates to [HJ-319](https://ethyca.atlassian.net/browse/HJ-319)
Adds some methods to `DBCache` that allow deleting a cached entry, deleting all cached entries for a given namespace, and deleting all entries. 
[HJ-319]: https://ethyca.atlassian.net/browse/HJ-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HJ-319 Add cache-clearing methods to DBCache

---

src/fides/api/api/v1/endpoints/dataset_endpoints.py
src/fides/api/api/v1/endpoints/messaging_endpoints.py
src/fides/api/api/v1/endpoints/policy_endpoints.py
src/fides/api/api/v1/endpoints/policy_webhook_endpoints.py
src/fides/api/api/v1/endpoints/pre_approval_webhook_endpoints.py
src/fides/api/api/v1/endpoints/privacy_request_endpoints.py
src/fides/api/api/v1/endpoints/storage_endpoints.py
src/fides/api/api/v1/endpoints/user_endpoints.py

I don't find much value in logging messages like `Finding all datasets for connection '{}' with pagination params {}` in a production setting, when the HTTP logs cover almost the same information.
This PR converts all of those messages that are spawned from a read-type action (so not creates/updates/deletes) to a `debug` level. While they aren't hugely problematic, it will help our logs stay a bit cleaner.
IMO we're not really losing too much here, because when HTTP logs are logged with context, I don't need a second message telling me that it's doing what it should be doing. I did, however, keep those `finding xyz` logs on PUTs and DELETEs, etc to help show progress for those actions.
* info -> debug for read actions
1.  launch Fides w info logging enabled
2. go to the request manager …

Modify Logging Levels for Read-only actions

---

.github/workflows/backend_checks.yml
.github/workflows/static_checks.yml
noxfiles/ci_nox.py
src/fides/api/main.py

* Breaks out the static checks into their own step so we can run always run them, even if there aren't any backend changes. This is done so we can prevent a branch from being merged if the static checks don't pass.
* Fixing silent error with Xenon
1.  CI tests should pass

Updating static checks

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/src/features/datamap/reporting/DatamapReportFilterModal.tsx
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx
clients/admin-ui/src/features/datamap/reporting/datamap-report-context.tsx
clients/admin-ui/src/features/datamap/reporting/utils.ts

Closes HJ-357, HJ-155
* Updates functionality of Custom Report reset to reset the entire table to its default state once applied, not just reset the filter.
* Restores the Filter accordion label
* Fixes ordering to be based on the `tableinstance` columns, rather than the backend defined columns.
* Enhances Cypress tests to help catch these issues in the future
1. Clear Local Storage for AdminUI or open an ingocnito window. Log in again.
2. Assuming you have systems set up in your Admin UI, visit the Datamap Report page `/reporting/datamap`.
3. Add a filter to the report using the Filters dialog. While doing that, note that all 3 accordions have labels (the top one was missing).
4. Update the grouping of the report. Note that the only column order change when doing so are the first 2 …

Saved report bug fixes

---

CHANGELOG.md
src/fides/api/models/db_cache.py
tests/ops/models/test_dbcache.py

Relates to HJ-319
When `set_cache_value` is called, we want to update the `updated_at` value for that cache entry, even if the value provided is the same as the previous one. 

HJ-319 Updated updated_at field of DBCache even when value doesn't change

---

CHANGELOG.md
src/fides/api/task/execute_request_tasks.py

Closes [LA-108](https://ethyca.atlassian.net/browse/LA-180)
This PR is to commit the changes done as part of testing in https://github.com/ethyca/fides/pull/5547
* Opens a new session to finalize the task activities for the `run_access_node`, `run_erasure_node`, and `run_consent_node`
1.  No new functionality, this just makes it so that long running DSR tasks can complete their finalizing activities, even after running a long query or request.
[LA-108]: https://ethyca.atlassian.net/browse/LA-108?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Opening new session to complete task activities

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts
src/fides/api/api/v1/endpoints/privacy_request_endpoints.py
src/fides/config/admin_ui_settings.py
tests/fixtures/application_fixtures.py
tests/ops/api/v1/endpoints/test_privacy_request_endpoints.py

Closes https://ethyca.atlassian.net/browse/LA-174
This PR adds a new config var to limit n number of rows for DSR downloads, `FIDES__ADMIN_UI__MAX_PRIVACY_REQUEST_DOWNLOAD_ROWS`. This is similar to what we already have in place for consent reporting download. The default limit is set at 100,000 for now.
* Adds new config `FIDES__ADMIN_UI__MAX_PRIVACY_REQUEST_DOWNLOAD_ROWS`
* updates DSR download endpoint to throw 400 if request is > this max
* updates admin-ui code to surface this err in a user-friendly way
* adds new unit test for this behavior
1.  Set `FIDES__ADMIN_UI__MAX_PRIVACY_REQUEST_DOWNLOAD_ROWS=1`
2. In Privacy center, make 2 privacy requests (access and erasure)
3. In The privacy request manager, attempt to download those requests
4. Confirm you are unable to download and that …

LA-174: Adds max rows limit config to privacy req csv download

---

.github/workflows/backend_checks.yml
.github/workflows/cypress_e2e.yml
.github/workflows/publish_docker.yaml
.github/workflows/publish_docs.yaml

Fix failing CI jobs that are missing the specific python version install.
* Add missing python install steps in different workflows
* Add missing env variables for default python version
1.  CI fully passed

Add missing install python 3.10

---

.github/workflows/backend_checks.yml

Fix the order of steps so the checkout step is before the python install step.
* Fix the order of steps so the checkout step is before the python install step.
1.  CI Passes

Fix order of steps of CI backend checks

---

.github/workflows/backend_checks.yml

unticketed
`external-datastores` job is timing out on `main`, ~possibly due to the GH runner upgrades to python 3.12 (since we now have to install python manually?)~ -- this seems unlikely upon further investigation, more likely is we added tests to increase the runtime of the job but it hadn't been running for a few days due to the python upgrade issue, so that increase in timing was being obfuscated.
at least as a temporary measure, we can bump the timeout to hopefully avoid the timeout and get this job passing again
* bumped timeout on `external-datastores` job from 20 to 30 min
1.  ~let's see how the job does on CI on this PR~ nevermind, forgot to put the `run unsafe ci checks` label on so `external-datastores` was skipped. let's just get this merged and test it on `main`, it's a very …

bump `external-datastores` job timeout from 20 to 30 min

---

CHANGELOG.md
clients/fides-js/src/components/fides.css

Closes [HJ-382]
Provides a single css var for customers to use to override the font sizes.
This allows for customers to "opt in" to accessibility compliance by setting this as "1rem" while avoiding the footgun probability that most are hard coding an HTML font size anyway which has the potential to cause sizing issues with fides.js out of the box.
* Adds a new `--fides-base-font-size`
* Converts all instances of the use of `rem` to calculate from the base size instead.
1. Visit the fidej.js component demo page (http://localhost:3001/fides-js-components-demo.html)
2. Font sizes should remain exactly how they have always been.
[HJ-382]: https://ethyca.atlassian.net/browse/HJ-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5Y …

Convert `rem` to base font size

---

CHANGELOG.md
src/fides/api/service/connectors/mongodb_connector.py

Trying to add an integration to mongodb with an user or password with special URL reserved characters was throwing the following error on console 
Username and password must be escaped according to RFC 3986, use urllib.parse.quote_plus
_Solution proposed by pymongo docs:_ 
> For username and passwords reserved characters like ':', '/', '+' and '@' must be percent encoded following RFC 2396:
```
from urllib.parse import quote_plus
uri = "mongodb://%s:%s@%s" % (
quote_plus(user), quote_plus(password), host)
client = MongoClient(uri)
```
We are using quote plus to parse URL reserved characters on the username and password directly, so they can be used as characters in a connection URL
* updating mongodb connector
1.  Prepare a mongodb image on the same network as fides dev. This can be done …

LA 151 - Allow Special URL reserved characters in the username/ passwords of mongodb

---

CHANGELOG.md
src/fides/api/cryptography/cryptographic_util.py
tests/lib/test_cryptography_util.py

Closes [HJ-397]
Handles the `UnicodeDecodeError` that is raised by `decode_password` if it is given a plaintext password that's also valid base64. The exception is caught, and the input string is returned as it was provided, under the assumption that it is a plaintext (and _not_ base64-encoded) password.
See issue description for more details. This impacts some user-related endpoints (e.g. reset password, accept invite) if the user provides a password that also happens to be valid base64. Notably, the utilities also _ignore_ invalid base64 characters like `_`, so a value like  e.g. `Test_1234` is treated as valid base64, since the `_` is ignored and its length of `8` is a multiple of 4.
* catch and ignore `UnicodeDecodeError` in `decode_password` utility function, assuming input string is …

ensure `decode_password` function properly handles plaintext but valid base64 passwords 

---

CHANGELOG.md
clients/admin-ui/src/features/system/hooks/useSystemFormTabs.tsx

After creating a new system, update the url to the new system's edit url.
* Add router.push after system creation
1.  In admin-ui, go to Add Systems > Add a system
2. Enter a system name
3. Scroll to the bottom and click Save
4. Check that the url has change to this format systems/configure/{newSystemId}
5. Reload the page and check that it loads the edit page for that system

LA-248 Change current path after adding a new system

---

clients/admin-ui/src/features/data-discovery-and-detection/action-center/action-center.slice.ts

Closes [LJ-319]
Params were being passed as comma separated but server is expecting serialized list.
* generate serialized query string by looping through array first
[LJ-319]: https://ethyca.atlassian.net/browse/LJ-319?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix bulk add/ignore assets

---

CHANGELOG.md

Fixed a changelog link to point at the PR as intended.
* updated Changelog with correct link
1.  Click link in Changelog to verify it takes you to the PR.

fixed link for changelog

---

CHANGELOG.md
clients/fides-js/src/lib/consent-types.ts
src/fides/api/models/privacy_experience.py

Prep work needed to be able to update the Experience form with "headless" as an option

add "headless" to consent types

---

data/saas/config/stripe_config.yml
data/saas/dataset/stripe_dataset.yml
tests/fixtures/saas/stripe_fixtures.py
tests/ops/integration_tests/saas/test_stripe_task.py

Closes [LJ-66](https://ethyca.atlassian.net/browse/LJ-66)
Stripe and recharge integrations failed on erasure because some fields where not properly mask. The solution is to apply masking overrides.
Relates to: https://github.com/ethyca/fidesplus/pull/1830
[LJ-66]: https://ethyca.atlassian.net/browse/LJ-66?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Stripe Config Update to match fidesplus

---

CHANGELOG.md

Fixes changelog title for 2.54 release

Fix changelog for 2.54

---

CHANGELOG.md
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-notices.cy.ts
clients/privacy-center/cypress/support/commands.ts

Closes [LJ-322]
Currently, when we have successfully loaded the Full TCF Experience, we replace the experience object in the React environment for use by the CMP.
However, the `window.Fides.experience` object only ever gets the Minimal TCF Experience.
This change **merges** the minimal and full experiences so that all properties from either experience is available and apply that to the `window.Fides.experience` once the fetch is successful.
* sets `Fides.experience` to merged object of both minimal and full after the successful result.
* Adds Cypress test for the merge
* Updates/fixes some Cypress test configs to help support this as well as tighten up some unrelated testing issues.
1. Configure a TCF Experience in Admin UI
2. Visit demo page for TCF experience …

Merge Full TCF in to `window.Fides.experience` after successful fetch

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/action-center.cy.ts
clients/admin-ui/cypress/fixtures/detection-discovery/activity-center/system-aggregate-results.json
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredSystemAggregateColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredSystemDataUseCell.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/types.d.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/utils/isConsentCategory.ts

Closes HA-356
Adds a read-only consent category cell to the action center aggregate systems table.
1. Checkout and run the backend from Adam's branch in the fidesplus repo (asachs/HJ-295).
2. Run turbo dev from the clients directory
3. Visit AdminUI's "About" page and enable the new "Website Monitor" feature flag
4. Click the "Action center" left nav item
5. If you receive a message here saying it's disabled, contact Adam to update config.
6. You should see 2 monitors, which are just dummy data from Adam's BE at the moment.
7. Click into a monitor by clicking the row or the "Review" button
8. For aggregate system results that have with data uses, the eligible data uses should show in the "Categories of consent" cell

Action center: Categories of consent cell

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx

Closes https://ethyca.atlassian.net/browse/LJ-309
Exposes privacy notice picker to add privacy notices to TCF components
Please test alongside https://github.com/ethyca/fidesplus/pull/1836
1.  Run `nox -s "build(slim)" "dev(slim)" -- dev` on https://github.com/ethyca/fidesplus/pull/1836 branch
2. Run this PR within `/clients/admin-ui` with `turbo run dev`
3. Update a TCF experience with notices, confirm it's saved correctly

LJ-309: allow privacy notices to be assigned to TCF components

---

CHANGELOG.md
clients/admin-ui/src/features/common/ScrollableList.tsx
clients/admin-ui/src/features/common/dropdown/SystemSelect.tsx
clients/admin-ui/src/features/common/dropdown/TaxonomySelect.tsx
clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/SelectDataset.tsx
clients/admin-ui/src/features/system/VendorSelector.tsx
clients/fidesui/src/hoc/CustomSelect.tsx

Change default options for Select component to allow search by default.
* Set default props to showSearch = true
* Remove showSearch from components since it's no longer needed
1.  Login to admin ui
2. Go to any system and add a new Data Use
3. Check that all Selects within this modal allow typing to filter the dropdown options
Note: This change applies to all Selects in the product, but specifically this modal has a few Selects that didn't have a showModal prop, so it's a good test for the new default behavior.

LJ-343 Allow search by default in all Selects

---

CHANGELOG.md
clients/admin-ui/src/features/system/add-multiple-systems/AddMultipleSystems.tsx
clients/fides-js/src/components/Overlay.tsx
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes [LJ-341]
When fides_embed is enabled, the vendor count isn’t being set in place of the __VENDOR_COUNT_LINK__ template string. This happens regardless of whether disable_fides_banner is also true or not.
* Minor string fix for pluralizing multiple vendors/systems
* Include Vendor click behavior in embedded layer 2, similar to modal, which enables the vendor text check.
* add Cypress test to catch this issue in the future
1. Create a TCF experience with the default text for description which includes the `__VENDOR_COUNT_LINK__` template string.
2. Visit demo page as normal (http://localhost:3001/fides-js-demo.html?geolocation=eea)
3. Note that the `__VENDOR_COUNT_LINK__` string has been replaced by a vendor count as a button. Clicking that button will open the modal to the Vendors …

Fix vendor count in embedded 2nd layer

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/data-catalog.cy.ts
clients/admin-ui/cypress/fixtures/data-catalog/catalog-tables.json
clients/admin-ui/src/features/common/copy/components.tsx
clients/admin-ui/src/features/data-catalog/CatalogResourceActionsCell.tsx
clients/admin-ui/src/features/data-catalog/CatalogStatusBadgeCell.tsx
clients/admin-ui/src/features/data-catalog/datasets/CatalogDatasetDetailDrawer.tsx
clients/admin-ui/src/features/data-catalog/datasets/useCatalogDatasetColumns.tsx
clients/admin-ui/src/features/data-catalog/projects/CatalogProjectsTable.tsx
clients/admin-ui/src/features/data-catalog/staged-resources/CatalogResourceDetailDrawer.tsx
clients/admin-ui/src/features/data-catalog/staged-resources/CatalogResourceOverflowMenu.tsx
clients/admin-ui/src/features/data-catalog/staged-resources/CatalogResourcesTable.tsx
clients/admin-ui/src/features/data-catalog/systems/CatalogSystemDetailDrawer.tsx
clients/admin-ui/src/features/data-catalog/systems/CatalogSystemsTable.tsx
clients/admin-ui/src/features/data-catalog/useCatalogResourceColumns.tsx
clients/admin-ui/src/features/data-catalog/utils.ts
clients/admin-ui/src/features/data-discovery-and-detection/tables/cells/EditCategoryCell.tsx
clients/admin-ui/src/pages/data-catalog/[systemId]/projects/[projectUrn]/index.tsx
clients/admin-ui/src/pages/data-catalog/[systemId]/resources/index.tsx

Closes HA-410
Adds detail trays to items at all levels of the new data catalog view.
Test with both BQ and a non-database-layer system.
1. Create systems with integrations with and without a database layer (e.g. BigQuery and DynamoDB)
2. For each system, create and run a monitor
3. Go to data catalog view
4. Check all resources have a "View details" option in the table "actions" cell overflow menu
5. For systems, should be able to edit data uses and go to full edit system form
6. For tables and fields with "In Review" status, should be able to edit data categories

Data catalog item detail trays

---

CHANGELOG.md
clients/admin-ui/src/features/common/nav/NavMenu.tsx
clients/admin-ui/src/theme/global.scss

Fix menu caret to animate and flip when expanding/collapsing menu groups
* Go back to using ant's default caret icon
* Update ant global styling to remove rounding from ant icon
* Update ant global styling to make arrow lines slightly longer to cover up a missing pixel
1.  Login to admin ui
2. Check the caret icon on menu groups isn't rounded
3. Check that when expanding a menu item the caret flips with an animation

Fix menu caret

---

clients/admin-ui/src/features/common/nav/MainSideNav.tsx
clients/admin-ui/src/theme/global.scss

Closes [LJ-374]
Update nav menu to use `NextLink` instead of `onClick` for routing
1. Main menu can be focusable using keyboard tab key or arrows and pressing the Return key activates the link to navigate.
2. Main menu allows user to Command + Click to open links in new tab
3. Main menu allows user to right click + open in new tab
[LJ-374]: https://ethyca.atlassian.net/browse/LJ-374?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

update nav menu as links

---

CHANGELOG.md
README.md

Unticketed change (minor docs correction)
* Changes the LDFLAGS and CFLAGS exports used to run build Fides with MSSQL support on macOS
* The new exports use symlinks in their paths so that they don't have to be changed very time the openssl and freetds versions used by homebrew are updated. Homebrew manages these symlinks automatically.
* No code changes
1. Test the updated build instructions at https://github.com/ethyca/fides/blob/daveqnet/unticketed/update-README/README.md#%EF%B8%8F-advanced-setup-for-microsoft-sql-server-mssql-support

Update LDFLAGS & CFLAGS exports in MSSQL local build instructions

---

clients/fides-js/src/components/Overlay.tsx
clients/privacy-center/cypress/e2e/show-modal.cy.ts

Closes [LJ-383]
Changes during the Headless implementation made it so that the .fides-overlay-modal-link-shown classname we add to the <body> tag is reliant on the modalLinkId being found on the page, which potentially breaks the support for a custom link + Fides.showModal() implementation some customers may be using (as seen in this example: https://ethyca.com/docs/dev-docs/js/reference/interfaces/Fides#examples-2)
* move the setting of `.fides-overlay-modal-link-shown` outside of checks for the `modalLinkId` being present and found.
* Update existing Cypress test to validate this change and help prevent future missteps.
1.  Edit line 107 of the `fides-js-demo.html` file in the privacy center to be `button.classList.add("my-custom-class");` instead of the standard ID.
2. Run Privacy …

fix missing classname on body with updated test

---

docs/fides/docs/development/releases.md

Updates the release template/checklist to include a warning to avoid merging release branch into `main`, to help avoid confusion/mistakes moving forward.

add warning note to release checklist to avoid merging release branch

---

CHANGELOG.md
src/fides/api/graph/config.py
tests/ops/graph/test_config.py
tests/ops/models/test_datasetconfig.py

Closes https://ethyca.atlassian.net/browse/LJ-424
Our initial/existing partitioning support (https://github.com/ethyca/fides/pull/5325) incorrectly prohibits `-` as a character in the "operand"s or "value expressions". This can cause problems, specifically when trying to reference specific timestamps in the partitioning clause (e.g. `TIMESTAMP("2019-01-01")`), which is a somewhat common use case.
This PR updates the validation regex to allow `-` characters in the operands.
* update validation regex to allow `-` characters in the operand
* add test coverage for this use case
1.  didn't do any manual confirmation (yet), but the unit test should be solid 👍 

Allow `-` in BQ partition clause operands

---

tests/ops/integration_tests/saas/test_hubspot_task.py
tests/ops/service/privacy_request/test_saas_privacy_requests.py

Hubspot tests are failing on user creation.
We will skip this tests until the issue is investigated and resolved.
[follow up issue](https://ethyca.atlassian.net/browse/LJ-425)

Skip flaky hubspot tests

---

CHANGELOG.md
data/dataset/bigquery_example_test_dataset.yml
src/fides/api/service/connectors/query_configs/bigquery_query_config.py
tests/fixtures/bigquery_fixtures.py
tests/ops/service/connectors/test_bigquery_queryconfig.py
tests/ops/service/privacy_request/test_bigquery_privacy_requests.py

Closes [LJ-432](https://ethyca.atlassian.net/browse/LJ-432)
Adding nested identity query support for BigQuery
* Overriding the base `generate_raw_query_without_tuples` method for `BigQueryQueryConfig`. This allows us to correctly map dot-delimited/nested `input_data` such as
```
{"contact_info.primary_email": ["customer-1@example.com"]}
```
1.  Run the tests in `tests/ops/service/privacy_request/test_bigquery_privacy_requests.py`
[LJ-432]: https://ethyca.atlassian.net/browse/LJ-432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Nested identity query support for BigQuery

---

CHANGELOG.md
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredAssetsColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredSystemAggregateColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/hooks/useDetectionResultColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/hooks/useDiscoveryResultColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/cells/DetectionItemActionsCell.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/cells/DiscoveryItemActionsCell.tsx

Closes HA-179
Fixes a bug where D&D action buttons were sometimes cut off at certain screen sizes and after resizing other columns.
https://github.com/user-attachments/assets/1206a8f2-170f-4279-bb03-7a1302044c40
* Changes all "Actions" columns in D&D tables to have width `auto`
* Also removes stopPropagation calls to move to updated `disableRowClick`pattern
1. Populate the D&D tables with some items
2. On both detection tables and discovery tables, make sure action buttons are visible and don't get cut off when resizing

Fix action column width on D&D tables

---

tests/ctl/core/test_api.py
tests/ops/api/v1/endpoints/test_dataset_config_endpoints.py

Closes [LJ-442](https://ethyca.atlassian.net/browse/LJ-442)
A PR was merged yesterday when the test workflows hadn't run, and so now we have a broken test. This fixes it.
1.  CI passes
[LJ-442]: https://ethyca.atlassian.net/browse/LJ-442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LJ-442 Fix breaking test

---

CHANGELOG.md
src/fides/api/api/deps.py
src/fides/api/api/v1/endpoints/consent_request_endpoints.py
src/fides/api/api/v1/endpoints/dataset_config_endpoints.py
src/fides/api/api/v1/endpoints/generic_overrides.py
src/fides/api/api/v1/endpoints/privacy_request_endpoints.py
src/fides/api/service/deps.py
src/fides/api/service/privacy_request/request_service.py
src/fides/api/task/graph_task.py
tests/fixtures/mariadb_fixtures.py
tests/ops/integration_tests/setup_scripts/mariadb_setup.py
tests/ops/integration_tests/setup_scripts/postgres_setup.py
tests/ops/integration_tests/setup_scripts/timescale_setup.py
tests/ops/integration_tests/test_external_database_connections.py
tests/ops/integration_tests/test_sql_task.py
tests/ops/task/test_graph_task.py

Closes [LJ-447](https://ethyca.atlassian.net/browse/LJ-447)
**Issue**: We were seeing a lot of data being transferred from the DB to the fides webserver 
**Explanation**:
We have a recurring task `poll_for_exited_privacy_request_tasks` that checks all in-progress privacy requests to see if they have any errored tasks. This task was inadvertently querying for all fields in the request tasks table (including task results), instead of for just task status. 
At the same time, we have long-running privacy request that has a LOT of request tasks, and since it's stuck in "in progress", all its tasks keep getting polled by the recurring check . This long-running request fails to move to a completed status because of access tasks that take a long time to process: the task processes fine, but when …

LJ-477 Improvements to GraphTask and poll_for_exited_privacy_request_tasks

---

CHANGELOG.md
src/fides/api/service/privacy_request/request_service.py
tests/task/test_requeue_interrupted_tasks.py

Closes [LJ-450](https://ethyca.atlassian.net/browse/LJ-450)
Updating the way we check for in progress request tasks to reduce the amount of DB reads
* Adding tests
1.  Follow steps from https://github.com/ethyca/fides/pull/5800
[LJ-450]: https://ethyca.atlassian.net/browse/LJ-450?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Optimize DB access for terminated task check

---

clients/admin-ui/cypress/e2e/systems-plus.cy.ts
clients/admin-ui/src/features/system/hooks/useSystemFormTabs.tsx
clients/fidesui/src/hoc/CustomTag.tsx

Moves "Assets" to be before "History" in the system form tabs; also fixes a bug in the new Ant tags where icons weren't showing up correctly.
1.  View a system details page
2. "Assets" should be before "History"
3. Clicking any tab should append the appropriate hash to the URL
4. Should be able to navigate to tabs by adding the appropriate hash

Move system 'Assets' tab to be before 'History'

---

.github/workflows/backend_checks.yml
.github/workflows/cli_checks.yml
.github/workflows/cypress_e2e.yml
.github/workflows/publish_docker.yaml
.github/workflows/publish_docs.yaml
.github/workflows/static_checks.yml
CHANGELOG.md
Dockerfile
docs/fides/Dockerfile
tests/ctl/cli/test_cli.py

- Bumps all use of Python `3.10.x` in repo from `3.10.13` to `3.10.16`
- Bumps all use of Python `3.9.x` in repo from `3.9.18` to `3.9.21`
- Latest release versions listed at https://www.python.org/downloads/source/
* See code diff (very simple version bumps)
1.  CI passes

Bump Python 3.9.x and 3.10.x versions to latest

---

CHANGELOG.md
pyproject.toml
requirements.txt

plotly is the largest single site-package in the final fides image but appears to unused in the source code. I think it may not be needed after this PR: https://github.com/ethyca/fides/pull/1571
* Removes plotly package
1.  CI passes

Remove plotly (unused package) to reduce fides image size

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-requests/cells.tsx
clients/admin-ui/src/pages/ant-poc.tsx

Closes [LJ-461]
"warn" is not a valid Palette color or Ant color, so the color treatment was failing.
* Updated to use "warning" instead of "warn"
* Added "caution" color to POC for completeness.
[LJ-461]: https://ethyca.atlassian.net/browse/LJ-461?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix Days Left Badge Color

---

CHANGELOG.md
src/fides/data/sample_project/sample_connections/sample_connections.yml
tests/ctl/api/test_seed.py

Unfortunately the variable expansion logic in the `FIDES__DATABASE__LOAD_SAMPLES` handling can result in loading a character like `&`, which YAML parsing then tries to interpret as an anchor, and then it fails to load the sample data.
Fides' startup routine is resilient to that failure, it just continues starting up but aborts loading the rest of the sample data, which is a subtle footgun and caught us in a test environment recently!
This addresses this by wrapping all the variables we load from the template connections in quotes, and adds some tests to exercise that.
* Update sample connections YML to wrap variables in quotes
* Add test to ensure that sample connections YML loads safely with special characters in variables
* Add test to demonstrate what will/won't fail to load, for …

Fixed load_samples to wrap variables in quotes to prevent YAML parsing errors

---

CHANGELOG.md
src/fides/api/util/logger_context_utils.py
tests/ops/util/test_logger_context_utils.py

Closes [LJ-488](https://ethyca.atlassian.net/browse/LJ-488)
Fixing bug where positional arguments were not being captured correctly by the `@log_context` decorator.
* Fixed positional arguments use case and added more test coverage
1.  Submit a privacy request, you should see the `privacy_request_id` as extra context for the following log
```
fides  | 2025-03-11 01:03:19.697 | INFO     | fides.service.privacy_request.privacy_request_service:queue_privacy_request:512 - Queueing privacy request from step None | {'privacy_request_id': 'pri_003425fe-a37e-4560-967e-58b3c0182c84'}
```
[LJ-488]: https://ethyca.atlassian.net/browse/LJ-488?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Supporting more use cases for the log_context decorator

---

CHANGELOG.md
src/fides/service/privacy_request/privacy_request_service.py
tests/service/test_privacy_request_service.py

Closes [LJ-471](https://ethyca.atlassian.net/browse/LJ-471)
When `require_manual_request_approval` is set to True and there's at least one pre approval webhook, resubmitting a privacy request was causing it to get queued twice. This was because both the pre approval webhook and the resubmit code were queuing the request. 
This changes the resubmit code so that:
- if `require_manual_request_approval` is set to `True` and there are pre approval webhooks, we only trigger the webhooks and don't auto-approve the request
- if `require_manual_request_approval` is set to `True` and there are no pre approval webhooks, then the request was originally approved by a person, so re-submitting will auto-approve the request 
- If `require_manual_request_approval` is set to `False`, we auto approve the …

LJ-471 Fix privacy request /resubmit endpoint so it won't queue the request twice 

---

CHANGELOG.md
src/fides/api/models/location_regulation_selections.py
src/fides/data/location/locations.yml

Closes [HA-499](https://ethyca.atlassian.net/browse/HA-499) along with https://github.com/ethyca/fidesplus/pull/1957
OSS Fides changes to support country filtering on `GET /locations` endpoint.
As noted in the jira ticket, this will be used by the web monitor config UX (at least initially), since the only valid locations to configure on a web monitor are countries (specifically, 2 letter country codes)
Specifically, it adds:
- an `is_country` flag to the `Location ` model (default=False)
- populates the flag appropriately on all of our entries defined in `locations.yml`
* update pydantic model for Location
* update the base yml with the location definitions
1. see [fidesplus PR](https://github.com/ethyca/fidesplus/pull/1957) …

support `is_country` flag on locations

---

clients/admin-ui/src/theme/global.scss

Fix problem with hover/selected colors.
* Split css rule for focus/hover
* Make hover rule override ant variable
* Modify focus-within rule (for accessibility) to exclude selected elements
1. Login to admin-ui
2. Hover over the menu items and check the background is gray
3. Click on a submenu item and check the selector color background is sandstone
4. Reload the page
5. Use keyboard tab/arrows to navigate up and down the menu items
6. Check the focused menu item background color is gray

Fix hover/selecter colors in main menu

---

CHANGELOG.md
clients/fides-js/src/lib/gpp/types.ts
clients/privacy-center/pages/api/fides-js.ts

Closes [LJ-490](https://ethyca.atlassian.net/browse/LJ-490)
Uses `gpp_settings.cmp_api_required` from the Privacy Center to decide whether or not the GPP JS API needs to be included in the fides JS bundle, rather than just looking at `gpp_settings.enabled`. 
* Enable TCF and GPP (national) in your fides .toml file and start fidesplus. The enable_tcfeu_string setting should be set to True.
* Enable three experiences:
* TCF experience
* US Modal experience , add a state to it that's not on the default Privacy Center experience (e.g us_wi)
* Privacy Center experience , add a state to it that's not on the default US Modal experience and make sure no GPP notices are added in this experience
* Enable a GPP notice and add it to the US Modal experience 
* Run the privacy center 
* Go to the …

Use gpp_settings.cmp_api_required to determine if GPP should be included

---

clients/admin-ui/src/features/common/nav/nav-config.tsx
clients/admin-ui/src/features/common/nav/routes.ts
clients/admin-ui/src/features/policy/policy.slice.ts
clients/admin-ui/src/pages/policies.tsx
clients/admin-ui/src/pages/policies/[policyKey].tsx
clients/admin-ui/src/utils/policy.ts

Adding read-only UI view for policies. Includes a link to the docs for policy creation

Adding read-only UI view for policies

---

Dockerfile
dev-requirements.txt

Updated Dockerfile and pytest-env version.
This was probably caused by the underlying image we use getting an update in the last 24 hours. 
https://hub.docker.com/layers/library/python/3.10.16-slim-bookworm/images/sha256-83f353e03a40bbebc8d2fe1fcd2d7357d8613e92512c556b02483a670eeb7211
* updated pytest-env version.
* updated Dockerfile
1.  None - docker builds

Updated a couple dev requirements to resolve docker build issues

---

CHANGELOG.md
clients/fides-js/__tests__/lib/consent-utils.test.ts
clients/fides-js/docs/interfaces/FidesOptions.md
clients/fides-js/rollup.config.mjs
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/notices/NoticeToggles.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/components/tcf/TcfPurposes.tsx
clients/fides-js/src/docs/fides-options.ts
clients/fides-js/src/fides-headless.ts
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-constants.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/consent-utils.ts
clients/fides-js/src/lib/initialize.ts
clients/fides-js/src/lib/tcf/types.ts
clients/privacy-center/app/server-environment.ts
clients/privacy-center/app/server-utils/PrivacyCenterSettings.ts
clients/privacy-center/app/server-utils/loadEnvironmentVariables.ts
clients/privacy-center/components/consent/notice-driven/NoticeDrivenConsent.tsx
clients/privacy-center/cypress/e2e/consent-banner-tcf-custom-notices.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts
clients/privacy-center/cypress/e2e/consent-notices.cy.ts
clients/privacy-center/pages/api/fides-js.ts

Closes [LJ-487]
Adds support for disabling specific notice toggles in the CMP overlay via a new `fides_disabled_notices` configuration option. This allows clients to prevent users from toggling certain privacy notices while preserving their current consent state.
* Added new `fides_disabled_notices` option to `FidesOptions` interface that accepts a comma-separated string of notice keys
* Implemented `parseFidesDisabledNotices` utility to parse the disabled notices string into an array
* Modified `NoticeOverlay` and `TcfOverlay` components to respect disabled notices:
- Preserves consent state for disabled notices during accept/reject all actions
- Disables toggle UI elements for specified notices
- Updates consent handling logic to maintain disabled notice states
- preserves existing …

Support disabling Notice Toggles with override option

---

CHANGELOG.md
clients/privacy-center/pages/api/fides-js.ts
src/fides/api/main.py
src/fides/api/service/privacy_request/request_runner_service.py
src/fides/api/tasks/__init__.py
tests/api/test_logging.py

Closes [LJ-579](https://ethyca.atlassian.net/browse/LJ-579)
- Adds logging for sessions in DatabaseTasks, hoping to provide more info for debugging customer issues
- Adds debug log in privacy-center, hoping to provide more info for performance testing on customer environments
- Fixes the way we were calculating handler time in `log_request`; we were using `timedelta.microseconds` instead of `total_seconds` so we were getting an inaccurate handler time for any request that took longer than 1s
1. Tests pass
[LJ-579]: https://ethyca.atlassian.net/browse/LJ-579?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LJ-579 Add logging for DSR session management and fix backend handler time calculation

---

.gitignore
CHANGELOG.md
clients/fides-js/__tests__/lib/tcf/tcf.test.ts
clients/fides-js/package.json
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/tcf.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes [LJ-546](https://ethyca.atlassian.net/browse/LJ-546)
This PR gets the `tcf_publisher_country_code` from the experience and uses it when building TC strings. 
* Update the `PrivacyExperience` type to include the new optional field `tcf_publisher_country_code` 
* Updated `generateFidesString` to pass in the field to `TCModel` 
* Added tests
1. Enable TCF 
2. In the admin UI, go to Settings > Consent and select a Publisher Country code . Save
3. Enable a TCF experience
4. Go to http://localhost:3001/fides-js-demo.html?geolocation=eea and delete the cookie and refresh. 
5. Accept or reject notices 
6. Log `Fides.cookie` in the console and take the TC string (first part of the `fides_string`)
7. Decode it in https://iabgpp.com/
8. Check that the `publisherCountryCode` matches the one …

LJ-546 Add tcf_publisher_country_code to fides JS

---

CHANGELOG.md
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/lib/tcf.ts
clients/fides-js/src/lib/tcf/stub.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes [LJ-506]
The Fides TCF CMP is setting a tcloaded status incorrectly, when a user has no previously saved TC Data. According to the [CMP documentation](https://ethyca.atlassian.net/jira/software/projects/HA/boards/187/backlog?selectedIssue=HA-149), the tcloaded event should not fire when a string is either not present OR when it is determined to be outdated and the UI will be shown to users
ONLY fire TCF `update` method when applicable:
1. Never on modal close, no change is made at that point so no `update` is needed
2. Only `update` during fides.js initialization if:
- TC string was _already set_ on a prior visit.
- We are _not_ going to show the banner (i.e. the TCF hash has not changed).
- It is the _first_ init (This should only ever happen once per visit).
Use new …

fix incorrect calls to tcf api update method

---

clients/admin-ui/src/pages/fides-js-docs.tsx
clients/package-lock.json

Fix build issue after pc merge. The docs for fides-js were moved to admin-ui, but the export fails because the docs page uses getServerSideProps, so I changed it to getStaticProps. Docs are not included in production build anyways.
* Replace getServerSideProps with getStaticProps
* Commit automatic package-lock update by nextjs
1.  Log in to admin ui
2. Go to Developer > Fides JS Docs
3. Check Swagger UI appears correctly
4. Go to the `clients/admin-ui` folder and run `npm export`
5. Check the previous command finishes without errors

Fix build issue after pc merge

---

CHANGELOG.md
clients/fides-js/__tests__/lib/consent-utils.test.ts
clients/fides-js/__tests__/lib/fides-string.test.ts
clients/fides-js/docs/interfaces/Fides.md
clients/fides-js/docs/interfaces/FidesOptions.md
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/docs/fides-options.ts
clients/fides-js/src/docs/fides.ts
clients/fides-js/src/fides-ext-gpp.ts
clients/fides-js/src/fides-headless.ts
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/consent-utils.ts
clients/fides-js/src/lib/consent-value.ts
clients/fides-js/src/lib/fides-string.ts
clients/fides-js/src/lib/gpp/string-to-consent.ts
clients/fides-js/src/lib/initialize.ts
clients/fides-js/src/lib/tcf/utils.ts
clients/privacy-center/cypress/e2e/banner-overlay-dismissal.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts

Closes [LJ-305]
Introduces Notice Consent String functionality to the FidesJS client, allowing programmatic control of notice consent preferences through a base64-encoded string. The changes include:
- New encoding/decoding utilities for Notice Consent strings
- Integration with the existing Fides string format in a new fourth slot
- Automated application of Notice Consent preferences during initialization
* Added `encodeNoticeConsentString` and `decodeNoticeConsentString` utility functions and exposed `encodeNoticeConsentString` to the Fides window object.
* Updated `DecodedFidesString` interface to include `noticeConsent` field
* Modified `initialize` to handle Notice Consent string application
* Removed unused `context` parameter from `resolveConsentValue`
* Added comprehensive tests …

Add notice consent to Fides string

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/action-center.cy.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/action-center.slice.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredAssetsColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredAssetsTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetDataUseCell.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/SystemCell.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/useDiscoveredAssetsTabs.tsx

Closes HA-471
Updates discovered asset table so assets don't disappear from the table while being edited; also adds a tab view that filters on resource diff status and system.
* "Attention required" is the replacement for the previous default view that shows `addition` resources.
* "Recent activity" shows all resources from the current _monitor_ (not just system) that have been promoted to system assets; resources in this view can't be edited and there is no "Actions" column in the table
* "Ignored" shows all ignored resources; resources here can be edited
* Add tabs and tab hash and filter handling to the DiscoveredAssetsTable
* Add a read-only variant of the system and data use cells
1. Populate some web monitor results
2. Assign a system and consent categories to some assets and add …

Action center asset row persistence updates

---

CHANGELOG.md

Move changelog entry for #5946 from 2.58.0 to Unreleased
* No code changes
1.  Ensure the changelog entry for #5946 is in the unreleased section, not 2.58.0

Move Next.js bump to correct section of changelog

---

CHANGELOG.md
src/fides/api/models/privacy_experience.py

Implements [LJ-611](https://ethyca.atlassian.net/browse/LJ-611)
Adds a new `opt_in_only` to the `Layer1ButtonOptions` to allow configuring an experience that only shows the `opt in` button in the layer 1 banner
1. N/A ? 
[LJ-611]: https://ethyca.atlassian.net/browse/LJ-611?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LJ-611 Add opt_in_only to Layer1ButtonOption enum

---

clients/admin-ui/cypress/e2e/action-center.cy.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredAssetsColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredAssetsTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetActionsCell.tsx

Closes HA-566
Disables bulk resource actions on the "Recent activity" tab in the action center UI and removes checkbox column.
1. Populate some web monitor resources
2. Promote some resources
3. View "Recent activity" tab
4. Should see the resources you promoted in the table
5. Should not be able to edit inline
6. "Actions" menu should be disabled

Disable bulk actions on action center 'Recent activity' tab

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/Preview.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx
clients/fides-js/__tests__/__fixtures__/mock_experience.json
clients/fides-js/__tests__/lib/i18n/i18n-utils.test.ts
clients/fides-js/docs/interfaces/FidesExperienceConfig.md
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/tcf/TcfConsentButtons.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/docs/fides-experience-config.ts
clients/fides-js/src/lib/consent-types.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/types/api/models/ExperienceConfigResponseNoNotices.ts
clients/privacy-center/types/api/models/Layer1ButtonOption.ts
clients/privacy-center/types/api/models/RejectAllMechanism.ts

Closes [LJ-502], [LJ-592]
This PR implements two key TCF-related features:
1. Control over the "Reject All" mechanism behavior for TCF experiences
2. Control over the visibility of the "Reject All" button between Layer 1 (banner) and Layer 2 (modal)
* Modified `PrivacyExperienceForm` to add:
* New "Reject all behavior" dropdown for TCF experiences
* Separate button layout options for TCF vs regular banner experiences
* Tooltips explaining the reject mechanism behavior
* Updated `TcfConsentButtons` to conditionally hide reject button based on `layer1_button_options`
* Modified preview configuration to properly handle TCF button options (when TCF Preview gets implemented)
* Updated type definitions to support new configuration options
1. Create or edit a TCF experience in Admin UI
2. Verify …

Reject All Options in TCF Experience

---

CHANGELOG.md
src/fides/api/custom_types.py
tests/api/v1/endpoints/test_html_sanitization.py

Closes [LJ 607 ](https://ethyca.atlassian.net/browse/LJ-607)/ [LJ 609](https://ethyca.atlassian.net/browse/LJ-609) (Duplicated)
During HTML rendering of custom templates, we've found that we are removing the target link and href pages, due to nh3 sanitization. We have to allow these attributes in for links
Updating the custom_types.py  validation to include allowed atributes on the <a> level
* Set up the  FIDES_PRIVACY_CENTER__ALLOW_HTML_DESCRIPTION=true env variable 
* Create a custom html modal with an <a> tag and link and href attrbiutes 
* see that they are rendered appropiately

Lj 609 sanitization allow link

---

clients/fides-js/__tests__/lib/consent-utils.test.ts
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-utils.ts
clients/privacy-center/cypress/e2e/banner-overlay-dismissal.cy.ts

Closes [LJ-62]
Reverts update to banner behavior [made in recent PR](https://github.com/ethyca/fides/pull/5895/files#diff-f16513cf5775803ac3c57f5e37c86e581999176bea890715fad7b35451b60cbeL247)
* removes check for Dismiss consent type before resurfacing the banner
1. Load any banner + modal experience in demo page
2. Dismiss the banner
3. Reload the page
4. Confirm banner does not re-appear
[LJ-62]: https://ethyca.atlassian.net/browse/LJ-62?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: Do not resurface dismissed banner

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/discovery-detection.cy.ts
clients/admin-ui/src/features/data-discovery-and-detection/tables/cells/DiscoveryItemActionsCell.tsx

Closes HA-565
Removes option to reclassify fields from data discovery result tables.
1. Populate D&D results
2. Send some results to classification and wait for it to complete
3. View a table-level field; should see option to reclassify in "Actions" cell
4. View a field-level field; should not see option to reclassify

Disable 'reclassify' option on fields in D&D UI

---

src/fides/api/models/tcf_publisher_restrictions.py
tests/api/models/test_tcf_publisher_restrictions.py

Adds the `update_async` method in the `TCFPublisherRestriction` model, and also adds validation. The validation is as follows: a single TCF configuration may have multiple restrictions for the same purpose, as long as there are no overlapping vendor ranges for those restrictions (for the same purpose) 
Additionally, I replaced the implementation of `create` so it throws a `NotImplemented` error -- I think it's confusing to have two ways to create the instances and we want to move towards async sessions in the future anyways. The fidesplus logic for this feature uses exclusively async sessions so it won't be a problem, and this avoids having to duplicate all the validation logic for both sync and async sessions. 
No changelog entry since this model is brand new and will be new in this …

LJ-622 Refactor TCFPublisherRestrictions to use async methods

---

.github/workflows/publish_package.yaml

Actually fix the Publish Fides action by installing a newer setuptools version. 

Actually fix Publish Fides action

---

CHANGELOG.md
src/fides/api/api/deps.py
src/fides/config/database_settings.py

Updates `DatabaseSettings` to be able to specify a read-only database server. This is phase one, a more complete implementation will be added in https://ethyca.atlassian.net/browse/LJ-663
* Added `readonly_server` and `sqlalchemy_readonly_database_uri` to `DatabaseSettings`
* Added `get_readonly_api_session`, it falls back to a normal database session if `readonly_server` is not provided

Read-only database connection

---

clients/privacy-center/package.json

I had added the cypress-parallels library to bring down the execution time on these tests. However, we're seeing some flakiness and it looks like me like the runners are getting resource constrained. This should ease up the stress on the runner by only running two threads, while at the same time, still giving us a gain on a single thread.
* Changes the cy:parallel command to use 2 threads instead of 5.
1. The privacy center cypress tests should run successfully.

Reduce cypress threads to 2 for PC tests

---

CHANGELOG.md
clients/admin-ui/src/features/common/privacy-notice-regions.ts

There is no associated ticket.
There was a typo in "Vermont" that used to say "Vermon".
- Text updated
1. In the left menu, go to Consent -> Experiences
2. Scroll down to Locations & Languages
3. Click "Add location"
4. Search for Vermont

Fix a typo in Vermont

---

CHANGELOG.md
src/fides/api/models/privacy_experience.py
src/fides/api/models/tcf_publisher_restrictions.py

Closes LJ-678
The way the SQLAlchemy relationships were defined was causing the experience config to get duplicated. 
1.  Edit a TCF experience config, e.g its name , and Save
2. Go back to the list and refresh the page, you should see no duplicates

LJ-678 Fix TCFConfiguration relationship definitions

---

clients/admin-ui/cypress/e2e/systems-plus.cy.ts

Fixes a failing Cypress test on the system assets tab.
1.  CI passes

Fix failing asset table test

---

.github/workflows/cypress_privacy-center.yml

The Privacy Center Cypress Tests were being a little flakey with cypress-parallel, so this goes back to using the regular cypress command. I left in the library and the command in the package.json as some may find it useful to run locally. It does quite well for that use case.
Removed the custom command from the github workflow
Running the Privacy Center Cypress workflow should show the normal cypress run command being used, not cy:parallel.

Remove cypress-parallel from Cypress CI run

---

clients/admin-ui/cypress/e2e/consent-settings.cy.ts
clients/admin-ui/cypress/fixtures/tcf/configurations.json
clients/admin-ui/cypress/fixtures/tcf/publisher-restrictions.json
clients/admin-ui/cypress/fixtures/tcf/purposes.json
clients/admin-ui/cypress/support/stubs.ts
clients/admin-ui/src/features/consent-settings/PublisherSettings.tsx
clients/admin-ui/src/features/consent-settings/tcf/CreateTCFConfigModal.tsx
clients/admin-ui/src/features/consent-settings/tcf/PublisherRestrictionActionCell.tsx
clients/admin-ui/src/features/consent-settings/tcf/PublisherRestrictionsConfig.tsx
clients/admin-ui/src/features/consent-settings/tcf/PublisherRestrictionsTable.tsx
clients/admin-ui/src/features/consent-settings/tcf/PurposeRestrictionFormModal.tsx
clients/admin-ui/src/features/consent-settings/tcf/PurposeRestrictionsTable.tsx
clients/admin-ui/src/features/consent-settings/tcf/TCFConfigurationDropdown.tsx
clients/admin-ui/src/features/consent-settings/tcf/TCFOverrideToggle.tsx

Closes [LJ-668]
Changes primarily focus on expanding test coverage for Purpose overrides in Consent Settings
* Added new test cases for TCF configuration management including:
- Creating, selecting, and managing TCF configurations
- Handling publisher restrictions table display and interactions
- Validating vendor ID input formats
- Testing restriction type management (require consent, legitimate interest)
* Added new test fixtures for TCF configurations and publisher restrictions
* Improved test organization by consolidating TCF-related tests
* Refactored publisher settings tests to be more focused and reduce code duplication
* Fixed validation for vendor ID input format in the UI
* Removed redundant GPP configuration tests that were moved to TCF-specific sections
Passing Admin UI …

Cypress tests for Purpose overrides in Consent Settings

---

src/fides/api/models/fides_user.py

In a [previous PR](https://github.com/ethyca/fides/pull/5984), the `SystemManager` import was removed from the `src/fides/api/models/fides_user.py` file. This import is not used explicitly in the file, but it prevented the following error:
```
sqlalchemy.exc.InvalidRequestError: When initializing mapper mapped class FidesUser->fidesuser, expression 'systemmanager' failed to locate a name ("name 'systemmanager' is not defined"). If this is a class name, consider adding this relationship() to the <class 'fides.lib.models.fides_user.FidesUser'> class after both dependent classes have been defined.
```
[Here is the explanation of the PR that originally added the import](https://github.com/ethyca/fides/pull/2714#discussion_r1124441032).
This error was obtained when running `nox -s dev -- …

LJ-553 - Adds an import that prevents errors

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts
clients/admin-ui/cypress/support/stubs.ts
clients/admin-ui/src/features/privacy-experience/ConfigurePrivacyExperience.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx
clients/admin-ui/src/types/api/models/ExperienceConfigCreate.ts

Closes [LJ-623]
This PR adds support for selecting TCF (Transparency & Consent Framework) Publisher Override configurations when configuring Privacy Experiences. It includes UI changes to allow users to select and manage TCF configurations within the privacy experience settings.
* Added TCF configuration selection dropdown in Privacy Experience form
* Added handling for clearing TCF configuration (sets to null when cleared)
* Added new Cypress test for TCF configuration editing functionality
1. When running locally, make sure you have latest from `fidesplus` repo `main` branch and that TCF is enabled.
2. Navigate to the consent settings page in the Admin UI (`/settings/consent`)
3. Enable the Override vendor purposes option.
4. Create a new configuration
- Click the "Create configuration …

TCF Experience option for selecting a restriction configuration

---

CHANGELOG.md
clients/privacy-center/components/modals/privacy-request-modal/PrivacyRequestForm.tsx

Closes [LJ-686]
When a identity_inputs value is set to null, do not set a label/value for it on the response
for example:
```
{
...
identity_inputs: {
"name": null,
"email": "required",
"phone": null
}
...
}
```
should ignore "name" and "phone" when setting default values in the form response, since they have no form elements.
* filter if the field is not defined
1. In local privacy center, set config.json to have an `identity_inputs` property like the one in the example above
2. Run privacy center and attempt to "Access your data" by filling in your email address
3. You should be able to submit the form successfully and without errors.
[LJ-686]: https://ethyca.atlassian.net/browse/LJ-686?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhM …

Fix: Ignore `null` fields from `identity_inputs`

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/datamap-report.cy.ts
clients/admin-ui/src/features/common/custom-reports/CustomReportTemplates.tsx
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/datamap/reporting/DatamapReportTable.tsx
clients/admin-ui/src/features/datamap/reporting/RenameColumnsButtons.tsx

Closes: [LJ-687]
Cypress tests were becoming flaky on the data map report due to the fact that Formik was re-rendering the entire table with every form change, causing a react performance issue. Tests were timing out and failing eventually because of it.
This performance issue was also causing some visible slowness in the UI for the end user.
To address both the Cypress and user issues, I've gone ahead and refactored the Formik implementation to rely more heavily on `useFormikContext` rather than wrapping the entire Formik child in a function that passes those same values in.
The result is much faster and the tests are no longer flaky
* Updated form handling in `DatamapReportTable` to use Formik context more effectively by removing the child wrapper function
* Added `resetForm` parameter …

Improve Formik performance on datamap report

---

CHANGELOG.md
clients/privacy-center/public/embedded-consent.html

Closes https://ethyca.atlassian.net/browse/LJ-683
Adds new embedded-consent route in PC to be used by TCF mobile SDK. 
Features:
1. Forwards any query params to the fides.js script, including geolocation and property_id
2. Loads the 1st layer TCF banner, allows clicking to the 2nd layer modal
3. Displays a message and "x" in the edge case where there is no Fides UI. Clicking "X" does not do anything as this is a placeholder button for the mobile SDK to bind to.
* Adds new /embedded-consent route to privacy center
1. Set up TCF experience for eea location
2. Disable US experiences
3. Navigate to http://localhost:3001/embedded-consent.html?geolocation=eea, confirm embedded TCF banner displays
5. Navigate to http://localhost:3001/embedded-consent.html?geolocation=us-ca, confirm err message …

LJ-683: Adds new embedded-consent route to PC

---

CHANGELOG.md
clients/admin-ui/src/types/api/models/MessagingServiceDetailsAWS_SES.ts
src/fides/api/schemas/messaging/messaging.py
src/fides/service/messaging/aws_ses_service.py
tests/ops/api/v1/endpoints/test_messaging_endpoints.py
tests/service/messaging/test_aws_ses_service.py

Closes [LJ-685](https://ethyca.atlassian.net/browse/LJ-685)
We used to take the `email_from` and `domain` as required in the AWS SES `messagingconfig`, but this depends on the configurations in AWS.
> In Amazon SES, you can create an identity at the domain level or you can create an email address identity. These identity types aren’t mutually exclusive. In most cases, creating a domain identity eliminates the need for creating and verifying individual email address identities, unless you want to apply custom configurations to a specific email address. Whether you create a domain and utilize email addresses based on the domain, or create individual email addresses, there are benefits to both approaches. (https://docs.aws.amazon.com/ses/latest/dg/creating-identities.html)
Now when sending …

LJ-685 - AWS SES setup requires both email and domain identities

---

clients/admin-ui/src/features/common/DebouncedSearchInput.tsx
clients/admin-ui/src/features/common/SearchInput.tsx
clients/admin-ui/src/features/common/system-data-flow/DataFlowSystemsModal.tsx
clients/admin-ui/src/features/common/table/v2/filters/GlobalFilterV2.tsx
clients/admin-ui/src/features/data-catalog/staged-resources/CatalogResourcesTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredAssetsTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredSystemAggregateTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/ActivityTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/DetectionResultTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/tables/DiscoveryResultTable.tsx
clients/admin-ui/src/features/locations/LocationManagement.tsx
clients/admin-ui/src/features/locations/RegulationManagement.tsx
clients/admin-ui/src/features/system/tabs/system-assets/SystemAssetsTable.tsx
clients/admin-ui/src/features/user-management/AssignSystemsModal.tsx
clients/admin-ui/src/features/user-management/UserManagementTableActions.tsx
clients/admin-ui/src/pages/data-discovery/action-center/index.tsx

Closes HA-547
Updates placeholder in asset table search bars (both in action center results and system "assets" tab) to "Search by asset name..."; also some while-I'm-in-there refactors.
* Renames `SearchInput` to `DebouncedSearchInput` to make purpose clearer and moves out of D&D-specific directory
* Renames `SearchBar` to `SearchInput` for consistency
* Refactors `SearchInput` and `DebouncedSearchInput` to share a prop type that more naturally extends Ant's `InputProps`
1. Verify placeholders have been updated
2. General regression

Refactor search inputs and update asset search placeholders

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/privacy-experiences.cy.ts
clients/admin-ui/src/features/common/ScrollableList.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx
clients/admin-ui/src/features/privacy-experience/PrivacyExperiencesTable.tsx
clients/admin-ui/src/features/privacy-experience/form/TCFConfigSelect.tsx
clients/admin-ui/src/features/privacy-experience/preview/Preview.tsx
clients/admin-ui/src/features/privacy-experience/preview/helpers.ts
clients/admin-ui/src/pages/api/fides-preview.js.ts
clients/admin-ui/src/pages/consent/privacy-experience/[id].tsx
clients/admin-ui/src/theme/global.scss
clients/admin-ui/src/types/window.d.ts

Closes [LJ-681] & [LJ-637]
This PR introduces several UI/UX improvements to the Privacy Experience configuration interface, particularly around TCF (Transparency & Consent Framework) configuration and component editing. Key changes include improved component type handling, better UI interactions, and code organization improvements.
1. Performance
* Extracted TCF configuration selection into a new separate component (`TCFConfigSelect`) so that it doesn't call the configs endpoint unless it's needed
* Updated useEffect that renders the preview so it only watches for relevant form values (doesn't re-render when changing experience name, for example)
2. Usability/UX improvements
* Added edit functionality to `ScrollableList` component with new edit icon and handler and Changed translation row …

Experience Preview Enhancements

---

CHANGELOG.md
src/fides/api/schemas/connection_configuration/connection_secrets_postgres.py
src/fides/api/service/connectors/postgres_connector.py
tests/ops/api/v1/endpoints/test_connection_config_endpoints.py
tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
tests/ops/integration_tests/test_connection_configuration_integration.py

- **Add ssl mode as an option to postgres connector.**
Closes [HA-635]
Adds SSL Mode to PG Connector
1.  Configure a monitor or connector and use SSL Mode.
2.  Configure a monitor or connector and do not use SSL Mode.
[HA-635]: https://ethyca.atlassian.net/browse/HA-635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HA-635: Postgres Connector SSL Mode

---

clients/admin-ui/cypress/e2e/consent-settings.cy.ts
clients/admin-ui/src/features/consent-settings/tcf/PublisherRestrictionsTable.tsx
clients/admin-ui/src/features/consent-settings/tcf/PurposeRestrictionFormModal.tsx
clients/admin-ui/src/pages/settings/consent/[configuration_id]/[purpose_id].tsx

Closes [LJ-694]
Removes restrictions on editing purpose restrictions for non-flexible purposes in TCF consent settings. Instead of blocking editing entirely, the UI now allows users to create restrictions for these purposes but limits them to only use Purpose Restriction type.
* Removed code that hid the "Edit" button for non-flexible purposes in `PublisherRestrictionsTable`
* Added state and logic in `PurposeRestrictionFormModal` to disable the Restriction Type dropdown for non-flexible purposes
* Added a tooltip explanation for why the Restriction Type is disabled
* Removed the error toast and redirect in the purpose config page (`[purpose_id].tsx`) that prevented accessing non-flexible purposes
1. Navigate to a TCF consent configuration (`/settings/consent`)
2. Attempt to edit …

Allow non-flexible Purposes to add Purpose Restriction

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-requests/RequestTableActions.tsx

Update request table action icons to carbon and fix sizing
* Update action icons to Carbon icons
* Update size of trash icon to 14 (visually it looks heavier than the others with default size)
1.  Login to admin-ui
2. Go to Privacy Request > Request managers
3. Looks at the actions column icons
4. Check we're using carbon icons, that the sizing make sense for the size of the button and that they're centered

Update request table action icons to carbon and fix sizing

---

CHANGELOG.md
clients/admin-ui/src/features/consent-reporting/hooks/useConsentReportingTableColumns.tsx
clients/admin-ui/src/pages/consent/reporting/index.tsx

- **Add recorded URL to consent report.**
- **Add aria label to textless button.**
Closes [LJ-702]
This adds the recorded URL to the consent report.
1. Make a consent choice.
2. Look at consent report.
3. Confirm column present.
[LJ-702]: https://ethyca.atlassian.net/browse/LJ-702?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LJ-702: Add url_recorded to consent report

---

clients/fides-js/docs/interfaces/Fides.md
clients/fides-js/src/fides-preview.ts

Closes [LJ-711]
Part of the clean up function was setting `window.Fides` to null. This creates a race condition where sometimes the rest of the cleanup hasn't taken place yet, or the new iteration hasn't been created yet and the assumption of the code at that time is that window.Fides exists. At any rate, setting that to null was a bit overkill for the cleanup anyway, let's just remove it for now.
* remove setting window.Fides to null in the fides-preview script
1. Save a TCF experience a few times in Admin UI
[LJ-711]: https://ethyca.atlassian.net/browse/LJ-711?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix experience errors when window.Fides isn't present

---

CHANGELOG.md
clients/fides-js/__tests__/lib/tcf/tcf.test.ts
clients/fides-js/src/lib/tcf.ts

Closes https://ethyca.atlassian.net/browse/LJ-700
Fix Special-purpose only vendors not correctly encoded in TC string
* Update tcf encoding logic to consider special-purpose only vendors
* Adds specific test for this scenario
1.  Login to the Fides Admin UI 
2. Navigate to the Vendors configuration
3. Enable a special-purpose only vendor (e.g. SeenThis) in the vendor list
4. Save the configuration
5. Ensure you have a system with data use added in Admin-UI
6. Enable the TCF experience
7. Visit http://localhost:3001/fides-js-demo.html?geolocation=fr-idf&fides_locale=en 
8. Confirm that SeenThis vendor is listed under Purposes -> Legitimate Interest -> Special purposes section
9. Make a consent choice (or just x out of the banner), the action doesn't matter
10. Inspect the generated TC …

LJ-700: Fix Special-purpose only vendors not correctly encoded in TC string

---

CHANGELOG.md
clients/admin-ui/src/features/datastore-connections/system_portal_config/TestConnectionMessage.tsx
clients/admin-ui/src/features/datastore-connections/system_portal_config/forms/ConnectorParameters.tsx
clients/admin-ui/src/features/datastore-connections/useTestConnection.tsx
clients/admin-ui/src/types/api/index.ts
clients/admin-ui/src/types/api/models/GoogleCloudSQLIPType.ts
clients/admin-ui/src/types/api/models/GoogleCloudSQLMySQLDocsSchema.ts
clients/admin-ui/src/types/api/models/GoogleCloudSQLPostgresDocsSchema.ts
clients/privacy-center/types/api/index.ts
clients/privacy-center/types/api/models/GoogleCloudSQLIPType.ts
clients/privacy-center/types/api/models/GoogleCloudSQLMySQLDocsSchema.ts
clients/privacy-center/types/api/models/GoogleCloudSQLPostgresDocsSchema.ts
src/fides/api/schemas/connection_configuration/connection_secrets_google_cloud_sql_mysql.py
src/fides/api/schemas/connection_configuration/connection_secrets_google_cloud_sql_postgres.py
src/fides/api/schemas/connection_configuration/enums/google_cloud_sql_ip_type.py
src/fides/api/service/connectors/google_cloud_mysql_connector.py
src/fides/api/service/connectors/google_cloud_postgres_connector.py
src/fides/api/service/connectors/sql_connector.py
tests/ops/api/v1/endpoints/test_connection_template_endpoints.py
tests/ops/schemas/connection_configuration/test_connection_secrets_google_cloud_sql_mysql.py
tests/ops/schemas/connection_configuration/test_connection_secrets_google_cloud_sql_postgres.py
tests/ops/service/connectors/test_google_cloud_mysql_connector.py
tests/ops/service/connectors/test_google_cloud_postgres_connector.py

Closes [HA-631](https://ethyca.atlassian.net/browse/HA-631)
- Add the ability to specify the “IP Type” as an optional connection argument using Google Cloud SQL (mysql and postgres). This applies to connection tests in:
- Integrations -> Connection
- In case of connection error, display error information in admin-ui.
- Added GCP SQL IP Type Support
- New ip_type field with options: "public", "private", "psc"
- Applied to both MySQL and PostgreSQL connectors
- Default value is "public" if not specified
- UI Error Handling Improvements
- Enhanced error messages in connection test responses
- Added failure reason display in the UI
1. Have an integration with Google Cloud SQL MySQL (credentials in 1password)
2. Set the IP type to "public" and see that the connection test works.
3. Set the IP …

HA-631 - Add support for ip_type for GCP SQL connection

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx
clients/admin-ui/src/flags.json
clients/admin-ui/src/pages/settings/consent/index.tsx

Closes [LJ-716]
Added a feature flag for TCF publisher restrictions to allow controlled deployment of the feature. The flag controls visibility of the publisher restrictions configuration in the TCF settings UI and shows/hides related UI components.
* Added new feature flag `publisherRestrictions` in flags.json
* Modified consent settings page to conditionally show publisher restrictions based on the feature flag
* Updated Privacy Experience Form to hide TCF config select when publisher restrictions flag is disabled
1. Verify that when TCF Publisher Restrictions flag is enabled, the Publisher Restrictions Config is visible for TCF-enabled experiences
2. Verify that when TCF Publisher Restrictions flag flag is disabled, the legacy vendor overrides UI is shown instead
3. Check that the TCF …

Add feature flag for TCF Publisher Restriction configs

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/preview/Preview.tsx
clients/fides-js/src/integrations/gtm.ts

Closes [LJ-720]
Fixed a bug in the GTM integration where duplicate notice keys between `privacy_notices` and `non_applicable_privacy_notices` arrays caused incorrect consent values to be reported. The issue occurred when custom notices were created with the same `notice_key` as existing notices.
**GTM Integration Fix**: Completely reworked how consent values are initialized and applied in the GTM integration. Now it:
1. First initializes an empty consent values object
2. Sets defaults for non-applicable notices when needed
3. Then overrides with actual consent values from configured notices
4. This ensures proper prioritization even when duplicate keys exist
**Admin UI Preview Improvement**: Replaced the use of `systemsCount` with a proper `vendorCount` that is fetched from the vendor …

Treat non-applicable keys as defaults which then get overridden

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-experience/PrivacyExperienceForm.tsx

Closes [LJ-723]
Added conditional logic to display TCF overlay option in the Privacy Experience component type dropdown. The option now appears as the second item in the list only when TCF is enabled in the plusHealth configuration.
* Created separate constants for base component options and the TCF overlay option
* Added a dependency on the plusHealth selector to access TCF enabled state
* Implemented a useMemo to conditionally insert the TCF overlay option when applicable
* Fixed array ordering to ensure TCF overlay appears as the second item
1. Verify TCF overlay option appears in the component dropdown when fidesplus `FIDES__CONSENT__TCF_ENABLED=true` env variable is set
2. Verify TCF overlay option is not visible when fidesplus `FIDES__CONSENT__TCF_ENABLED=false` env variable is set …

conditionally add TCF to the Experience type options

---

CHANGELOG.md
src/fides/api/service/connectors/redshift_connector.py
src/fides/api/util/logger.py
src/fides/api/util/sqlalchemy_filter.py
tests/ops/util/test_logger.py

Closes LJ#462
We were having trouble with unwanted SQLAlchemy log message related to caching issues with third-party dialects like Redshift.
* Implemented a SQLAlchemyGeneratedFilter in sqlalchemy_filter.py to filter out specific unwanted log messages from the SQLAlchemy engine. (Thanks @galvana )
* Added a new test suite TestSQLAlchemyLogger in test_logger.py to ensure that the SQLAlchemyGeneratedFilter correctly filters out unwanted log messages.
1. Run the test suite in test_logger.py to ensure that the SQLAlchemyGeneratedFilter is correctly filtering out the specified log messages.

Lj 462 Reduce Logging for Disabled Cache on SQLAlchemy

---

clients/admin-ui/src/app/store.ts

Adds a middleware that turns redux query failures into toasts. Should we consider pushing to an error page?
- Redux error middleware.

handle errors in redux queries

---

CHANGELOG.md
clients/fides-js/src/components/fides.css

Closes [LJ-725]
When the `--fides-overlay-container-border-width` css variable is set, it doesn't apply to the banner as expected, only the modal.
It does however get applied to the mobile version of the banner, which is where the bug stems from. When the responsive version of the banner was updated, this width was hard coded instead of using the variable.
Fixing this should be low risk in the ecosystem of custom css because if anyone is trying to use that variable to adjust the width, they are likely not being successful and using something _hard coded_ and that will STILL APPLY when this variable gets added to the responsive styling, but it has been marked as https://github.com/ethyca/fides/labels/high-risk in the change log just in case.
* replaced hard coded value with variable
1. …

fix border width to respect variable

---

CHANGELOG.md
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/tcf.ts
clients/fides-js/src/lib/tcf/types.ts

Closes [LJ-624]
Adds support for TCF publisher restrictions when creating the TCF String
* Added `tcf_publisher_restrictions` to PrivacyExperience and PrivacyExperienceMinimal types
* Added TcfPublisherRestriction type definition
* Updated generateFidesString to handle publisher restrictions when generating TC string
* Added logic to process publisher restrictions in TC string generation
* Renamed `experience` state variable to `experienceFull` throughout TcfOverlay.tsx for clarity (I was getting confused reading through that file)
Testing currently requires using branch `LJ-625-add-tcf-publisher-restrictions-subquery` to run your fidesplus backend.
1. Test that publisher restrictions are properly encoded in the TC string by:
- Setting up a publisher restriction configuration in the admin …

TCF Publisher Restriction support

---

CHANGELOG.md
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/consent-settings/tcf/PurposeRestrictionFormModal.tsx
clients/admin-ui/src/features/consent-settings/tcf/usePurposeRestrictionTableColumns.tsx

Improves vendor restriction handling in TCF consent settings and fixes UI components. Updates the vendor restriction form to better handle input validation and adds a reusable text header component with info tooltips.
* Added new `TextWithInfoIconHeader` component for consistent header styling with tooltips
* Updated vendor restriction form to:
- Fix validation logic for "Restrict All Vendors" option
- Add token separators for vendor ID input (to handle commas and spaces correctly)
- Remove unnecessary key event handling
1. Make sure Publisher restrictions feature flag is enabled in `/settings/about`
2. Go to Consent settings `/settings/consent` and make sure "Override vendor purposes" is enabled
3. Create a new Configuration
4. Edit a purpose and add a restriction
5. Select a Restriction …

Admin UI Publisher Restriction UX Enhancements

---

CHANGELOG.md
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-migration/index.ts
clients/fides-js/src/lib/consent-migration/onetrust.ts
clients/fides-js/src/lib/consent-migration/types.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/cookie.ts
clients/fides-js/src/lib/initialize.ts
clients/privacy-center/cypress/e2e/onetrust-migration.cy.ts

Closes https://ethyca.atlassian.net/browse/LJ-722
Allow OT migration to auto write to fides preferences api
* Adds code to automatically write to consent prefs api when we have OT consent
* Adds test assertions
1. In fides-js-demo, uncomment out the `window.fides_overrides` declaration. Add a new field, `ot_fides_mapping` that will hold your OT -> fides mappings. 
Example core data: 
```
{
C0001: ["essential"],
C0002: ["analytics"],
C0004: ["advertising", "marketing"],
}
```
To prep this, you'll need to JSON.stringify, then URL-encode it.
Here's my resulting fides_overrides obj:
```
window.fides_overrides = {
fides_embed: true,
ot_fides_mapping: "%7B%22C0001%22%3A%5B%22essential%22%5D%2C%22C0002%22%3A%5B%22analytics%22%5D%2C%22C0004%22%3A%5B%22advertising%22%2C%22marketing%22%5D%7D"
}; …
```

Allow OT migration to auto write to fides preferences api

---

clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts

Closes [LJ-624]
When we implemented "Reject Consent Only" last month, we didn't have a vendor requirement, only Purposes. Now that we've implemented vendor level LI, we need to update that to include vendors
* Pass in vendorLegitimateInterest IDs when "Reject Consent Only" applies
[LJ-624]: https://ethyca.atlassian.net/browse/LJ-624?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Fix: include vendors in consent only rejection

---

CHANGELOG.md
clients/fides-js/src/lib/tcf.ts

Closes [LJ-744](https://ethyca.atlassian.net/browse/LJ-744)
In the Publisher Restrictions work, we noticed that vendor 838 was getting included as a special purpose only vendor when it has other purposes as well; this is because we weren't checking the `legIntPurposes` section of the GVL vendor entry 
[LJ-744]: https://ethyca.atlassian.net/browse/LJ-744?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LJ-744 Fix special purpose vendor check

---

CHANGELOG.md
clients/admin-ui/src/features/system/add-multiple-systems/AddMultipleSystems.tsx

Closes [LJ-742]
This updates a tooltip to refer to a nav menu item by name so it's more clear where the user should go to see the vendor information.
* Just a tweak to the the tooltip text in one spot
1.  Go to Vendors / Add Vendor
2. Add any vendor
3. Go back to Vendors / Add Vendor
4. Hover over the added vendor to see the new tooltip.
[LJ-742]: https://ethyca.atlassian.net/browse/LJ-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update Add Vendor tooltip to match navigation option

---

CHANGELOG.md
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/initialize.ts
clients/privacy-center/cypress/e2e/onetrust-migration.cy.ts

Closes https://ethyca.atlassian.net/browse/LJ-749
Refactor OT consent migration to use existing logic to auto apply preferences
Refactor OT consent migration to use existing logic to auto apply preferences
1. confirm tests pass
2. confirm no regressions in OT consent migration (https://ethyca.atlassian.net/browse/LJ-722)

Refactor OT conent migration to use existing logic to auto apply preferences

---

src/fides/api/service/storage/util.py
tests/ops/service/storage/test_util.py

Issue [745](https://ethyca.atlassian.net/browse/LJ-745)
Found an edge case - both `jpg` and `jpeg` have the same value which caused some unexpected behavior. Updated the checking code to use `members` rather than `name`
* Updated the function
* Added more tests!
1. All tests should pass - the endpoint work will be in fidesplus.

LJ-745 Better enum checking

---

requirements.txt
src/fides/api/service/connectors/saas/authenticated_client.py
tests/ops/service/connectors/saas/test_authenticated_client.py

Closes[ LJ-728](https://ethyca.atlassian.net/browse/LJ-728?atlOrigin=eyJpIjoiMDkyMGFkOWVmMjEzNDcyOThkNzhkZjhkNTdkZjg2YTgiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
We were having trouble hitting Shopify subdomains recently, with the integration returning an SSL Error of an invalid CA. 
We confirmed that from the server, we were able to access those endpoints, so it was a problem with Fides not getting the Certificates correctly. 
This should point which certificates to use directly. 
* Using [Certifi](https://pypi.org/project/certifi/) to get the proper CA 
1.  DSRs where we had problems with SSL should pass 

Adding certifi to fix SSL CA Error

---

CHANGELOG.md
clients/fides-js/__tests__/lib/consent-utils.test.ts
clients/fides-js/__tests__/lib/fides-string.test.ts
clients/fides-js/__tests__/lib/gpp/string-to-consent-tcf.test.ts
clients/fides-js/docs/interfaces/Fides.md
clients/fides-js/docs/interfaces/FidesOptions.md
clients/fides-js/rollup.config.mjs
clients/fides-js/src/docs/fides-options.ts
clients/fides-js/src/docs/fides.ts
clients/fides-js/src/lib/consent-utils.ts
clients/fides-js/src/lib/fides-string.ts
clients/fides-js/src/lib/tcf.ts
clients/fides-js/src/lib/tcf/utils.ts
clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes [ENG-443]
Updated the Additional Consent (AC) string format from version 1 to version 2, which now includes a disclosed vendors section with the "dv." prefix. This change ensures compatibility with [Google's updated AC string specification](https://support.google.com/admanager/answer/9681920?hl=en).
* Updated AC string format from version 1 (`1~id1.id2.id3`) to version 2 (`2~id1.id2.id3~dv.id4.id5.id6`)
* Renamed `idsFromAcString` function to `consentIdsFromAcString` for better clarity
* Enhanced string validation in `consentIdsFromAcString` to handle both version 1 and version 2 AC strings
* Updated all test cases with the new AC string format
* Improved documentation with clearer code examples showing the new format
1. In Admin UI, add some systems that are not part of GVL (AC) …

Support Additional Consent string v2

---

CHANGELOG.md
clients/fides-js/__tests__/lib/tcf/tcf.test.ts
clients/fides-js/package.json
clients/fides-js/src/lib/tcf.ts
clients/package-lock.json
clients/privacy-center/cypress/e2e/consent-banner-gpp.cy.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes [LJ-415]
1. Add the following Vendors in Admin UI. This table illustrates each vendor's legal basis in the GVL
| ID   | Name       | PC | LI | SP |
| ---- | ---------- | -- | -- | -- |
| 232  | Rockerbox  | x  | x  |    |
| 415  | SeenThis   |    |    | x  |
| 509  | One Tech   |    | x  |    |
| 553  | **Adhese** | x  |    | x  |
| 740  | 6Sense     | x  | x  | x  |
| 1261 | Encore DM  | x  | x  |    |
| 1407 | M6 Pub.    | x  |    |    |
<sub>PC = Purpose Consent | LI = Legitimate Interest | SP = Special Purpose | FP = Flexible Purpose</sub>
NOTE: **Adhese** is the only vendor that should be affected by this fix, since they only have PC and SP. The rest have been added to help …

Update IAB TCF with Special Purpose exception fix

---

CHANGELOG.md
clients/admin-ui/src/features/common/privacy-notice-regions.ts
clients/admin-ui/src/features/locations/LocationManagement.tsx
clients/admin-ui/src/types/api/models/PrivacyNoticeRegion.ts
src/fides/api/models/location_regulation_selections.py
src/fides/data/location/locations.yml

Closes https://ethyca.atlassian.net/browse/ENG-72
Please test alongside https://github.com/ethyca/fidesplus/pull/2176
- No longer need to set up all US states, can just use "United States" location. Same with "EEA". E.g. When visiting from "us-ca", an experience would show up that just has the "US" configured.
- Can designate a "global" fallback location on any experience, including TCF, etc. E.g. When visiting from a location outside of any existing location configured on your experiences, you will be shown the experience labeled with the "global" location.
- Can only configure one "global" fallback experience on a given property, same as other locations
* Adds "global" fallback location
* Excludes it from showing in the "Locations" tab of Admin-UI
* Allows the global location to show up …

ENG-72: Implements Fallback Locations in CMP (FE)

---

CHANGELOG.md
clients/fides-js/src/lib/initialize.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts

Closes [ENG-459]
Fixes issue where `Fides.consent` wasn't respecting `fidesConsentFlagType` and `fidesConsentNonApplicableFlagMode` overrides until after a consent choice. This update ensures that value applies those overrides during initialization as well.
* Pass the `Fides.cookie.consent` value through the `applyOverridesToConsent` method before using it to initialize the `Fides.consent` value.
1. Add `6sense` to system, which will give a handful of notices. Only enable 1 or 2 of the notices and add them to the US Modal Experience and enable it.
2. Visit the Privacy Center demo page with both overrides in their non-default state (eg. http://localhost:3001/fides-js-demo.html?geolocation=US-CA&fides_consent_non_applicable_flag_mode=include&fides_consent_flag_type=consent_mechanism)
3. DO …

Apply overrides during initialization

---

CHANGELOG.md
clients/fides-js/__tests__/lib/preferences.test.ts
clients/fides-js/docs/interfaces/Fides.md
clients/fides-js/src/docs/fides.ts
clients/fides-js/src/fides-headless.ts
clients/fides-js/src/fides-tcf.ts
clients/fides-js/src/fides.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/init-utils.ts
clients/fides-js/src/lib/preferences.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts

Closes [LJ-684]
Added a new `updateConsent` method to the Fides interface, allowing developers to programmatically update user consent preferences using either a consent object or fidesString.
* Added comprehensive tests for the `updateConsent` function in preferences module
* Updated Fides interface documentation to include the new `updateConsent` method
* Implemented error handling for various edge cases in the consent update process
1. Add `6Sense` vendor in Admin UI
2. Enable Analytics, Data sales and sharing, and Essential notices
3. Create a Headless experience and add those 3 notices to it
4. Add location Utah to the Headless experience
5. Visit the privacy center demo page for Utah (`/fides-js-demo.html?geolocation=us-ut`)
6. Verify updating consent works with a plain consent …

Add a new method to Fides object for updating user consent

---

clients/fides-js/__tests__/lib/preferences.test.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/init-utils.ts
clients/fides-js/src/lib/preferences.ts

Closes [ENG-533]
Simply converts the valid `validation` values to an enum and applies that everywhere.
* Refactor to add `UpdateConsentValidation` enum
* Apply new enum
* Update tests
1. Passing tests
[ENG-533]: https://ethyca.atlassian.net/browse/ENG-533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Refactor validation types as enum

---

clients/admin-ui/src/features/common/nav/nav-config.tsx
clients/admin-ui/src/features/common/nav/routes.ts
clients/admin-ui/src/pages/poc/table-migration.tsx
clients/fidesui/src/index.ts

Closes [ENG-437]
Cursor prompts:
1. `@ConsentManagementTable.tsx` uses custom table components built with TanStack and Chakra. We want to recreate this exact table functionality, but ONLY using AntTable from Fides UI. You can ignore the filter for now. Add this new Ant Table version to the `@table-migration.tsx` page. Try to avoid using non-Ant components
2. Instead of a filter button that will open a custom modal, can we implement the same filter functionality using Ant Table's built in Column Filtering?
3. the filter looks good, but the api query doesn't seem to be configured right. The end result of selecting and applying the filters should look something like `...plus/system/consent-management/report?page=1&size=25&purposes=2&purposes=3` but it currently looks something like …

Table migration mini POC using Cursor

---

CHANGELOG.md
clients/fides-js/src/integrations/shopify.ts

Closes https://ethyca.atlassian.net/browse/ENG-682
Currently we have an arbitrary 3000ms wait (3 secs) before loading Shopify. This change allows us to init Shopify early in init lifecycle, passing in defaults first, then updating as Fides completes initialization.
* Update the Shopify integration to allow earlier initialization of Shopify.
1. In `fides-js-components-demo.html`, add the following code after Fides init (L:220):
```
window.Shopify = {
customerPrivacy: {
setTrackingConsent: function () {
// This function is used to test the Shopify integration.
// It will be called by the Shopify platform script.
console.log("Shopify customer privacy function called");
}
}
}
Fides.shopify();
```
2. Nav to `http://localhost:3001/fides-js-components-demo.html`, and open up console
3. Reload …

ENG-682: Smarter and earlier initialization strategy for Shopify integration

---

src/fides/api/alembic/migrations/versions/bf713b5a021d_staged_resource_ancestor_link_data_.py
src/fides/api/migrations/post_upgrade_index_creation.py

Handles an edge case in the staged resource ancestor creation where we have `children` pointers in our staged resources that refer to URNs of nonexistent `stagedresource`s. This is an unexpected state, but it's one we've seen in practice, so we should guard against it.
Without this update, we'd create `stagedresourceancestor` links that point to the nonexistent `stagedresource` records, and then we get a constraint error when trying to create the FK constraint on `stagedresourceancestor.descendant_urn`.
1. confirmed this handled our edge case locally with a sample dataset that showed the problem initially

Handle edge case in staged resource ancestor data migration

---

CHANGELOG.md
clients/admin-ui/src/features/integrations/integration-type-info/manualInfo.tsx
clients/admin-ui/src/features/privacy-requests/constants.ts

Closes ENG-739
It looks like we were missing the `Awaiting email send` status in the filter. This PR adds it.
* Add "Awaiting Email Send" to the status filter dropdown on the request manager page.
* Improve consistency for casing in other status options
1. start server
2. browse to request manager
3. try to filter on all available statuses.

ENG-739: Add Request Filter for Awaiting Email Send + Improve Casing Consistency

---

CHANGELOG.md
clients/fides-js/rollup.config.mjs

Closes [ENG-724]
Fixed AMD module loading conflicts by preventing FidesJS from registering itself as an AMD module when RequireJS or other AMD loaders are present on the page.
* Added `amd: { define: undefined }` configuration to Rollup UMD output to prevent AMD module registration
1. Run `npm run build` in `clients/fides-js` to generate bundles
2. Test that FidesJS loads correctly in browser environments without RequireJS conflicts by adding `<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js"></script>` near the top of `clients/privacy-center/public/fides-js-demo.html`. Load the demo page with a valid experience and make sure FidesJS still runs correctly without errors (`jsonview.js` will throw an error, but that's not our problem).
* …

Disable AMD in FidesJS

---

CHANGELOG.md
clients/fides-js/docs/interfaces/FidesEvent.md
clients/fides-js/rollup.config.mjs
clients/fides-js/src/components/ConsentBanner.tsx
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/ConsentModal.tsx
clients/fides-js/src/components/DataUseToggle.tsx
clients/fides-js/src/components/ExperienceDescription.tsx
clients/fides-js/src/components/Overlay.tsx
clients/fides-js/src/components/Toggle.tsx
clients/fides-js/src/components/notices/NoticeOverlay.tsx
clients/fides-js/src/components/notices/NoticeToggles.tsx
clients/fides-js/src/components/tcf/RecordsList.tsx
clients/fides-js/src/components/tcf/TcfFeatures.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/components/tcf/TcfPurposes.tsx
clients/fides-js/src/components/tcf/TcfTabs.tsx
clients/fides-js/src/components/tcf/TcfVendors.tsx
clients/fides-js/src/docs/fides-event.ts
clients/fides-js/src/lib/consent-types.ts
clients/fides-js/src/lib/events.ts
clients/fides-js/src/lib/preferences.ts
clients/fides-js/src/lib/providers/event-context.tsx
clients/fides-js/src/lib/renderOverlay.tsx
clients/fides-js/src/lib/tcf/renderOverlay.tsx
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-events.cy.ts
clients/privacy-center/cypress/e2e/consent-third-party.cy.ts
clients/privacy-center/cypress/e2e/consent.cy.ts

Closes [ENG-442]
Implemented comprehensive event trigger tracking across all FidesJS UI components. Added a centralized event context system that captures detailed information about what UI element triggered each event, including the element type, label, and origin (internal vs external). This enables better analytics and debugging capabilities by providing granular details about user interactions with the consent interface.
* Added `EventProvider` Preact context and `useEvent` Preact hook for centralized event trigger management
* Updated all button and toggle components to set trigger details before dispatching events
* Enhanced `FidesEvent` interface to include `origin`, expanded `type` options (`button`, `link`, `toggle`), and newer consent methods that had been previously left out …

Consistent event trigger information in FidesJS

---

clients/fides-js/src/lib/size-of.ts
clients/fides-js/src/services/api.ts

Closes [ENG-783]
Older browsers do not support .size on URLSearchParams
This is a recent enough API that some close to 1% of users see this with global enough traffic. 
1. Try using Fides in an older browser ¯\\_(ツ)_/¯ 
[ENG-783]: https://ethyca.atlassian.net/browse/ENG-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-783: Handle older browsers that do not support .size on URLSearchParams

---

CHANGELOG.md
src/fides/api/service/connectors/postgres_connector.py

Closes ENG-780
Removing an erroneous $ for f-strings when providing sslmode for Postgres.
* Remove dollar sign from f-string
1.  Connect to Postgres when providing SSL Mode

String formatting issue in Postgres connector

---

clients/admin-ui/cypress/e2e/integration-management.cy.ts
clients/admin-ui/src/features/integrations/add-integration/allIntegrationTypes.tsx

Hide saas integration from the integrations page
* Remove saas from supported list of integrations in the integrations page
* Skip related tests
1.  Using the preview link (https://fides-plus-nightly-git-fix-saas-integration-appea-1ef946-ethyca.vercel.app/) and login
2. Go to systems, check that "Test saas system" is there and it has a Shopify integration
3. Navigate to the Settings > Integrations page
4. Check there are so integrations of saas type appearing in the table

Hide saas integration from the integrations page

---

CHANGELOG.md
clients/admin-ui/src/pages/poc/ant-components.tsx
clients/admin-ui/src/theme/ant.ts
clients/fidesui/src/hoc/CustomTag.module.scss
clients/fidesui/src/hoc/CustomTag.tsx
clients/fidesui/src/hoc/CustomTooltip.module.scss
clients/fidesui/src/hoc/CustomTooltip.tsx
clients/fidesui/src/hoc/index.tsx
clients/fidesui/src/index.ts

Closes [ENG-849]
Introduces a new Higher-Order Component (HOC) `CustomTooltip` that wraps the Ant Design `Tooltip` to provide enhanced keyboard accessibility. This HOC automatically adds a `tabIndex` to non-focusable elements, allowing them to receive focus and trigger the tooltip. It also applies a custom focus-visible style for better visibility.
*   **`fidesui`**
*   Added a new `CustomTooltip` HOC that automatically provides keyboard accessibility (focus trigger, `tabIndex`) to Ant Design's Tooltip.
*   Exported `CustomTooltip` as the default `AntTooltip` from the `fidesui` library.
*   **`admin-ui`**
*   Updated the POC page to demonstrate the new tooltip behaviors.
*   Added theme overrides for the `Tag` component.
1.  Navigate to the Ant components POC page at …

Add keyboard accessible CustomTooltip HOC

---

src/fides/api/service/connectors/saas_connector.py

Adds a check to avoid post-processing non-JSON responses
1.  Tests should pass, there were two tests failing before this change https://github.com/ethyca/fides/actions/runs/16033978123/job/45242137055

Prevent post-processing for non-JSON responses

---

src/fides/api/task/manual/manual_task_utils.py
src/fides/api/util/connection_util.py
tests/api/task/test_manual_task_integration.py

Closes [ENG-886](https://ethyca.atlassian.net/browse/ENG-886?atlOrigin=eyJpIjoiNzc4YWI0MjI3MDkwNGJiZTg0MTZjMWRiZWFhNDBjNzMiLCJwIjoiaiJ9)
Added connection config filtering to ManualTask creation in DAG - this should ensure that only connection configs which are enabled show up in the request runner. This matches the overall dataset functionality [here](https://github.com/ethyca/fides/blob/a60607f201c3144d6150c6ef61a6c203f05ca2f8/src/fides/api/service/privacy_request/request_runner_service.py#L453)
* Added filters for `ConnectionConfig.disabled.is_(False)` to various manual task dag functions. 
1.  Create a manual task connection config - enabled
2. Verify that the manual task appears in privacy requests.
3. Disable the connection config
4. Verify the manual task does not appear in new …

ENG-886 Filter for connection config disabled to manual task

---

clients/admin-ui/src/features/common/table/v2/filters/GlobalFilterV2.tsx
clients/privacy-center/features/external-manual-tasks/ExternalStoreProvider.tsx
clients/privacy-center/features/external-manual-tasks/components/ExternalAuthLayout.tsx

Fix unresponsive navigation after going to the Manual Tasks tab. Fix wrong privacy center logo appearing.
* Fix old bug in the GlobalFilterV2 component that caused a rendering loop
* Fix external task logo by fetching from the correct configs
1.  Go to Admin UI > Privacy Request page
2. Switch to the Manual Tasks tab
3. Click on any link on the nav menu and check that it navigates correctly

Fix manual tasks UI bugs

---

clients/admin-ui/src/features/manual-tasks/manual-tasks.slice.ts
clients/privacy-center/app/external-tasks/ExternalTasksClient.tsx
clients/privacy-center/features/external-manual-tasks/components/ExternalCompleteTaskModal.tsx
clients/privacy-center/features/external-manual-tasks/components/ExternalManualTasks.tsx
clients/privacy-center/features/external-manual-tasks/components/ExternalSkipTaskModal.tsx
clients/privacy-center/features/external-manual-tasks/external-manual-tasks.slice.ts

Make external task ui allow only a single value for every column filtering (api only supports that). Remove unnecessary param to complete action for consistency with admin-ui. Fix skip task.
* use filterMultiple false option in the column filtering
* update filtering code
* remove unnecessary field key param
* update pagination sizes to match admin-ui
* fix auth layout

Fix external UI bugs

---

clients/fides-js/package.json
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-events.cy.ts
clients/privacy-center/cypress/e2e/consent-third-party.cy.ts

Added modern `exports` field to package.json to improve package resolution and enable direct imports of different Fides variants. This allows customers to import specific builds (headless, TCF) directly using clean import paths while maintaining backward compatibility with existing usage patterns.
Solves the following issues:
- Only main `fides.mjs` was referenced in package.json "module" field
- Missing modern "exports" field for better package resolution
- Other variants (TCF, headless) weren't exposed through package exports
Example:
```
// Main Fides SDK
import { init } from 'fides-js';
// Headless version (no UI)
import { init } from 'fides-js/headless';
// TCF-enabled version
import { init } from 'fides-js/tcf';
```

Include exports field to improve 3rd party usage

---

CHANGELOG.md
clients/fides-js/__tests__/lib/gpp/string-to-consent.test.ts
clients/fides-js/__tests__/lib/gpp/us-notices.test.ts
clients/fides-js/src/fides-ext-gpp.ts
clients/fides-js/src/lib/gpp/constants.ts
clients/fides-js/src/lib/gpp/gpp-utils.ts
clients/fides-js/src/lib/gpp/string-to-consent.ts
clients/fides-js/src/lib/gpp/stub.ts
clients/fides-js/src/lib/gpp/types.d.ts
clients/fides-js/src/lib/gpp/us-notices.ts

Closes [ENG-891]
Refactored GPP (Global Privacy Platform) code to eliminate duplication and improve maintainability. Extracted common GPP utility functions into a `gpp-utils.ts` file that can be duplicated between this and the `fidesplus` repo seamlessly.
* Moved `GPPUSApproach` enum from `types.d.ts` to `constants.ts`
* Created new `gpp-utils.ts` file with shared utility functions: `setMspaSections`, `setOptOuts`, `setNoticesProvided`, and `getGppSectionAndRegion`
* Updated `string-to-consent.ts` to use centralized `getGppSectionAndRegion` function
* Updated all import statements across files and tests to use new locations
* Added JSDoc documentation indicating file synchronization between fides and fidesplus repositories
1. All tests pass
2. GPP strings get generated as expected.
* …

Refactor GPP to be more DRY

---

clients/cypress-e2e/cypress/e2e/smoke_test.cy.ts

Updates `smoke_test.cy.ts` for compatibility with new Ant tabs in the system form.

Fixes smoke test failure from Ant tab migration

---

clients/admin-ui/cypress/e2e/user-management.cy.ts

Addresses race condition in Cypress test by ensuring data is loaded into the React state (by checking that it's shown in the UI) before proceeding with the test.

Fix flaky user management tests

---

CHANGELOG.md
src/fides/api/app_setup.py
src/fides/api/util/cache.py

Closes [ENG-924](https://ethyca.atlassian.net/browse/ENG-924)
After a lot of troubleshooting, we found that the `logger` calls inside the `get_cache` method are causing Celery workers to hang indefinitely, particularly when running test privacy requests. The problem seems to be an interaction between the `loguru` module and our singleton pattern for Redis connections. There's more relevant context in the Jira ticket.
This PR removes all calls to `logger` inside our `get_cache` method as a quick fix while we work on a more long-term solution. Ticket for longer-term solution: https://ethyca.atlassian.net/browse/ENG-933
We tested in RC already
[ENG-924]: https://ethyca.atlassian.net/browse/ENG-924?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY …

ENG-924 Remove all logger calls in get_cache

---

clients/package-lock.json
src/fides/api/task/manual/manual_task_graph_task.py
src/fides/api/task/manual/manual_task_utils.py
tests/api/task/test_manual_task_integration.py
tests/task/manual/test_manual_task_instance_filter.py

Closes [ENG-899]
The bug where access instances were being created on erasure tasks showed back up after the last change. 
I have made another update to fix that issue and added tests.
* One of the last changes caused extra instances to start popping up again, especially when a config had been deleted. 
1.  Spin up FidesPlus banch `ENG-899-research-and-correct-task-instance-creation` pointed at this fides branch.
2. Create a couple manual task integrations with access and erasure tasks
3. Delete an erasure task
4. Create an erasure privacy request
5. Verify it does not create extra instances or stop the task from processing. 
[ENG-899]: https://ethyca.atlassian.net/browse/ENG-899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …

Eng 899 research and correct task instance creation 3

---

clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx

Closes [ENG-934]
Added ID attributes to consent buttons so that external scripts (eg. web monitor) don't need to rely on `class` names or `data-testid` which are less reliable.
1. Check that button IDs are properly set on all of the footer buttons in the banner and modal for both TCF and non-TCF.
[ENG-934]: https://ethyca.atlassian.net/browse/ENG-934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Add IDs to FidesJS buttons

---

CHANGELOG.md
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredAssetsTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredSystemAggregateTable.tsx

Closes [ENG-867]
Updates the Action Center tables to persist row selections across pagination. This allows users to select items on multiple pages and perform bulk actions on the entire selection. The total count of selected items is now accurately displayed and updated as the user navigates through pages. Selections are reset when filters or tabs are changed to avoid unintended actions.
*   **`DiscoveredAssetsTable.tsx` & `DiscoveredSystemAggregateTable.tsx`**
*   Replaced `selectedRows` state array with a `selectedRowsMap` to store selections across all pages.
*   Updated the `rowSelection.onChange` logic to manage the `selectedRowsMap`, preserving selections when paginating.
*   Added a `useEffect` to sync the visible checkbox state (`selectedRowKeys`) with the persisted selections for …

preserve selections across pages

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-requests/events-and-logs/hooks/usePrivacyRequestManualTasks.tsx

Fix bug in OSS where visiting any privacy request results in an error toast for the manual task fetching.
* Skip manual task fetching if not running fides plus
Run fides oss
1.  Visit any privacy request detail page
2. Check no error toast message appears
(regression) 
1. Visit https://fides-plus-nightly-git-eng-1022-fix-error-toast-s-a0702b-ethyca.vercel.app/privacy-requests/pri_3fbd42eb-d188-4660-bd64-f8748892cb0b(use Fides nightly build credentials)
2. Check at the bottom of the Activity there is an entry for "Task completed"

ENG-1022 skip fetching manual tasks when not running in plus

---

clients/admin-ui/src/types/api/models/ExecutionApplicationConfig.ts
clients/privacy-center/types/api/models/ExecutionApplicationConfig.ts
src/fides/api/schemas/application_config.py
src/fides/api/service/connectors/bigquery_connector.py
src/fides/api/service/connectors/sql_connector.py
src/fides/config/utils.py
tests/ops/api/v1/endpoints/test_config_endpoints.py
tests/ops/service/connectors/test_bigquery_connector.py
tests/ops/service/connectors/test_sql_connector.py

Closes [ENG-1002](https://ethyca.atlassian.net/browse/ENG-1002)
More complete solution for the "safe mode" feature which has been more accurately renamed to sql_dry_run
* Rename to sql_dry_run
* Updated code to apply to SELECT statements - as part of this change sql_dry_run is en enum with possible values "access", "erasure", and "none". None, default, and null all operate with no change. Access and erasure must be set separately to allow erasure tasks to make their required select statements.
* New tests written for base class and BQ connector
* NOTE: No changes were required in other SQL connectors as they did not override the SQL statement generation of the base class
I think we can rely on automated tests for this one given the established patterns and manual testing on the existing …

ENG-1002 improved safe_mode (now sql_dry_run)

---

CHANGELOG.md
Dockerfile
noxfiles/docker_nox.py

Closes [ENG-1035](https://ethyca.atlassian.net/browse/ENG-1035)
Adds back missing data-testid attributes in FidesJS components for development Docker builds. The issue occurred because FidesJS builds were stripping test IDs even in dev environments, making some e2e Privacy Center tests break.
The solution adds an IS_TEST build argument that preserves test IDs only for dev builds while maintaining the current behavior (stripped test IDs) for all production builds.
* Dockerfile: Added ARG IS_TEST=false and ENV IS_TEST=$IS_TEST to the frontend build stage to accept and propagate the test flag
* docker_nox.py: Modified app_info_map to conditionally pass --build-arg IS_TEST=true for fides and the privacy center when tag == "dev"
1. To test the Dockerfile change, you can locally build the image …

Handle IS_TEST param for fides-js builds to include test ids

---

clients/fides-js/package.json
clients/turbo.json

Closes ENG-1035
This change to the turbo configuration allows it to pass along the IS_TEST env variable.
Turbo is in [strict mode](https://turborepo.com/docs/crafting-your-repository/using-environment-variables#strict-mode) by default, which means that it will filter out all env variables that aren't specified.
We need this variable so we can pass IS_TEST and populate fides-js data-testids as needed.
Also, the npm build script was checking if IS_TEST was set at all, not actually evaluating its contents. So now we're doing that here. Previously it would have left the testids if this were explicitly set to false or anything else.
* Updated turbo.json with the IS_TEST global variable.
* Update npm build script to check value of IS_TEST
Try running `npm run build` with IS_TEST set to `true`, …

Allow turbo to pass env variable

---

src/fides/api/service/privacy_request/dsr_package/templates/welcome.html

Closes [ENG-1057]
Minor update to remove a reference to PDF in the DSR email template.
[ENG-1057]: https://ethyca.atlassian.net/browse/ENG-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-1057: fix email template to remove reference to PDF format

---

CHANGELOG.md
clients/fides-js/__tests__/lib/consent-utils.test.ts
clients/fides-js/__tests__/lib/hooks/use-retryable-fetch.test.ts
clients/fides-js/rollup.config.mjs
clients/fides-js/src/components/ConsentButtons.tsx
clients/fides-js/src/components/InfoBox.tsx
clients/fides-js/src/components/MenuItem.tsx
clients/fides-js/src/components/fides.css
clients/fides-js/src/components/tcf/RecordsListSkeletons.tsx
clients/fides-js/src/components/tcf/TCFBannerSupplemental.tsx
clients/fides-js/src/components/tcf/TcfConsentButtons.tsx
clients/fides-js/src/components/tcf/TcfFeatures.tsx
clients/fides-js/src/components/tcf/TcfLoadingErrorMessage.tsx
clients/fides-js/src/components/tcf/TcfOverlay.tsx
clients/fides-js/src/components/tcf/TcfPurposes.tsx
clients/fides-js/src/components/tcf/TcfTabs.tsx
clients/fides-js/src/components/tcf/TcfVendors.tsx
clients/fides-js/src/lib/consent-utils.ts
clients/fides-js/src/lib/hooks/index.ts
clients/fides-js/src/lib/hooks/useRetryableFetch.ts
clients/fides-js/src/lib/initialize.ts
clients/fides-js/src/lib/preferences.ts
clients/fides-js/src/lib/tcf/constants.ts
clients/fides-js/src/services/api.ts
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts
clients/privacy-center/cypress/e2e/consent-banner.cy.ts
clients/privacy-center/cypress/e2e/consent-events.cy.ts
clients/privacy-center/pages/api/fides-js.ts
clients/privacy-center/public/fides-js-demo.html

Closes [ENG-940]
1. Improved compliance by automatically defaulting any property accessed on `Fides.consent` as `false` in case an experience fails to load or is empty. (ie. `Fides.consent.whatever` will return `false`)
2. Improved TCF (Transparency and Consent Framework) error handling and user experience by implementing retry mechanisms for API calls and better loading states. When the full TCF experience fails to load due to network issues or API failures, users now see appropriate loading indicators and error messages, while still being able to accept/reject consent. The system now uses a retry-able fetch hook with exponential back-off for more reliable API communication.
* Added `useRetryableFetch` hook to `TcfOverlay` with retry logic for fetching full TCF experience
* Created …

Improved API call loading/failure handling

---

tests/ops/service/storage/conftest.py
tests/ops/service/storage/test_s3.py

Adding a missing test case to make sure non-KMS S3 buckets work with the new signature v4
1.  Tests should pass

Adding missing non-KMS S3 test case

---

qa/scenarios/bigquery_table_not_found.py
src/fides/api/service/connectors/sql_connector.py
tests/ops/service/connectors/test_sql_connector.py
tests/ops/service/privacy_request/test_bigquery_privacy_requests.py

Continuation of https://github.com/ethyca/fides/pull/6397. 
* Adding similar missing table checks for `SQLConnector.mask_data`
1.  Start Fides and the Admin UI
2. Run the `python qa bigquery_table_not_found setup` QA scenario
3. Submit an erasure request for `customer-1@example.com`
4. The request should finish, the `customer_profile` collection should be skipped for the access steps and complete (with 0 results) for the erasure steps
5. Run the `python qa bigquery_table_not_found setup --table customer` QA scenario (note the `customer` param)
6. Submit an erasure request for `customer-1@example.com`
7. Verify the access errors and that the erasure doesn't run

Adding missing table detection for erasures

---

CHANGELOG.md
clients/admin-ui/src/features/integrations/add-integration/allIntegrationTypes.tsx
clients/admin-ui/src/features/integrations/hooks/useFeatureBasedTabs.tsx
clients/admin-ui/src/pages/integrations/[id].tsx

Fixes an issue where if you open the integration detail page for a Manual Task integration, the first tab isn't active and the tab content area is empty.
The issue was caused because during loading the EMPTY_TYPE response was being used and the "Connection" tab is shown. After loading the real integration, the "Details" tab is returned instead, but the "Connection" tab was used already to initialized the state. The solution was to set enabledFeatures to undefined, and don't return the tabs until the real integration enabledFeatures is loaded. 
* Changed EMPTY_TYPE.enabledFeatures to undefined
* Don't return tabs array until enabledFeatures is fully loaded
* Move tab calculation code to a new useFeatureBasedTabs hook
1.  Login to admin-ui using the preview link
2. Go to integrations and …

Fix default tab not loading with Manual Task integrations

---

CHANGELOG.md
clients/admin-ui/src/features/integrations/configure-tasks/CreateExternalUserModal.tsx
clients/admin-ui/src/features/integrations/configure-tasks/TaskConfigTab.tsx

Fixes task table showing you cursor: pointer when they're not clickable. Fixes User link in the Manage Access modal not working.
* Removed onRowClick
* Added NextLink to the users page
You can use the preview link: https://fides-plus-nightly-git-eng-1121-ui-bugs-in-manual-a878e1-ethyca.vercel.app/login
with the nightlyBuild credentials for testing.
1.  Login to admin-ui and go to the integrations page
2. Click on a manual task integration and go to the Manual Tasks tab
3. Check if you hover over any row in the manual task table that you don't see a cursor: pointer
4. Open the Manage Secure Access modal
5. Click on the highlighted Users link and check it takes you to the Users Management page

Fix small UI bugs in Manual Task config screen

---

CHANGELOG.md
src/fides/api/models/detection_discovery/core.py
tests/ops/models/detection_discovery/test_core.py

Closes https://ethyca.atlassian.net/browse/ENG-738
Refactored the `StagedResourceAncestor.create_staged_resource_ancestor_links` method to `create_all_staged_resource_ancestor_links` to improve performance when creating ancestor links for multiple staged resources.
The new method takes a dictionary mapping descendant URNs to sets of ancestor URNs, allowing bulk creation of all ancestor links using **batched database operations** instead of requiring multiple method calls. This approach uses configurable batch sizes to handle large datasets efficiently while avoiding PostgreSQL parameter limits.
* Renamed `create_staged_resource_ancestor_links` to `create_all_staged_resource_ancestor_links`
* Changed method signature from (db, resource_urn: str, ancestor_urns: Set[str]) to (db, …

ENG-738 - Performance improvements for data detection - bulk insert ancestor links

---

CHANGELOG.md
src/fides/api/models/detection_discovery/core.py
tests/ops/models/detection_discovery/test_core.py

Closes https://ethyca.atlassian.net/browse/ENG-738
This PR optimizes the ancestors() and descendants() methods in the StagedResource model. 
The original implementation relied on SQLAlchemy relationships (self.ancestor_links and self.descendant_links) which could trigger multiple database queries when accessing related objects. The new implementation uses single, explicit SQL queries with joins to fetch all ancestors or descendants in one database roundtrip.
* Modified StagedResource.ancestors() method to accept a `db: Session` parameter and use explicit SQLAlchemy query with join instead of relationship traversal
* Modified StagedResource.descendants() method to accept a `db: Session` parameter and use explicit SQLAlchemy query with join instead of relationship traversal
* Updated all …

ENG-738 - Update the ancestors and descendants functions to create a single SQL query

---

clients/fidesui/src/ant-theme/global.scss
clients/fidesui/src/hoc/CustomTable.tsx

Closes [ENG-1101]
Lets use the ANT filter and sort icons, selected state should use minos, default should be neutral-300. These icons are useful and have statefulness which is nice.
* Remove custom icon from CustomTable
* Set default color to neutral 300
[ENG-1101]: https://ethyca.atlassian.net/browse/ENG-1101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Revert tables to use Ant filter icon

---

CHANGELOG.md
clients/fides-js/src/lib/gpp/string-to-consent.ts

Closes ENG-812
Fixes a bug where GPP would fail to initialize when some invalid values for `fides_string` were given as an override
1. In `fides-js-demo.html`, set a `window.fides_overrides` value with `fides_string: "\",,DBABLA~BAAaAAAAAABo.QA\""`
2. Set up an experience with a GPP notice
3. View the demo
4. In the console, run `__gpp("ping", console.log)`
5. Should see GPP object in the output
6. Repeat process with any invalid string you can think of; should always see GPP object in the output

Fix bug with GPP API not initializing with invalid Fides string override

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-requests/privacy-requests.slice.ts

Closes [ENG-1151]
Refactored privacy request query parameter construction to use URLSearchParams, ensuring correct encoding and proper handling of repeated parameters. Guarded date filters against invalid values and streamlined CSV download parameter building.
* Updated `mapFiltersToSearchParams` to return `URLSearchParams` and build params via `params.set/append`, including repeated `action_type` and `status` values
* Added date guards to avoid sending invalid `created_gt/created_lt` values
* Standardized boolean and number param serialization with explicit `String(...)`
* Updated `requestCSVDownload` to reuse the shared param builder and append `download_csv=true`
* Simplified `privacyRequestApi` query URL to use `.toString()` without `decodeURIComponent`
1. Filter privacy requests with …

Fix params getting encoded

---

CHANGELOG.md
src/fides/api/models/privacy_request/privacy_request.py
tests/ops/service/privacy_request/test_request_runner_service.py

Closes [ENG-1096](https://ethyca.atlassian.net/browse/ENG-1096)
When a DSR enters the `awaiting_email_send` status there's no execution log added which can sometimes make it confusing for users to understand why the request is waiting. This PR adds an `ExecutionLog` instance before setting the DSR in `awaiting_email_send` status.
1.  Set up an email integration (e.g Generic Erasure Email)
2. Run a DSR
3. You should see this log on the DSR detail page: "Privacy request paused pending batch email send job" 
[ENG-1096]: https://ethyca.atlassian.net/browse/ENG-1096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-1096 Add execution log when DSR enters awaiting_email_send status

---

src/fides/api/schemas/application_config.py
tests/ops/api/v1/endpoints/test_config_endpoints.py

Closes [ENG-1186]
This was a a fix in the NYT prerelease image that addresses a specific issue with a config (safe_mode). Pulling it into main so that the NYT env is ok moving forward
* Allows unknown extra fields in the Execution config to pass through without rejecting the change
1.  Tests included covers the change
[ENG-1186]: https://ethyca.atlassian.net/browse/ENG-1186?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-1186 Fixing issue patching config with legacy values in the DB

---

CHANGELOG.md
clients/admin-ui/src/features/data-discovery-and-detection/action-center/MonitorResult.tsx
src/fides/api/util/connection_type.py
tests/ops/util/test_connection_type.py

Closes [ENG-1122](https://ethyca.atlassian.net/browse/ENG-1122)
This PR consists of two changes: 
- A backend change that allows getting the secrets schema for the `test_website` connection type so that we can return the configured `url` (which the UI uses to pull brand logo) 
- A frontend change that adds the `test monitor` tag to test website monitors in the action center
1. Run a test website monitor for `https://ethyca.com`
2. Look in the action center, both the url and brand image should be present, as well as a tag that reads `test monitor`
[ENG-1122]: https://ethyca.atlassian.net/browse/ENG-1122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-1122 Show brand image and badge for test website monitors

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/action-center/assets-results.cy.ts
clients/admin-ui/cypress/e2e/action-center/systems-aggregate.cy.ts
clients/admin-ui/cypress/e2e/systems/plus/navigation.cy.ts
clients/admin-ui/cypress/support/ant-support.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/ConsentBreakdownModal.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/constants.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useConsentBreakdownTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredSystemAggregateColumns.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredSystemAggregateTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredAssetsTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredSystemAggregateTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetActionsCell.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredSystemAggregateActionsCell.tsx

Closes [ENG-1210]
- Using the new `useTableState` and `useAntTable` hooks, refactored the remaining action center tables.
- Added new Cypress command for consistent tab interaction handling and updated existing tests to use the standardized approach.
* Created `useConsentBreakdownTable` custom hook to manage table state, data fetching, and column configuration
* Added `ConsentBreakdownColumnKeys` and `DiscoveredSystemAggregateColumnKeys` enums for better type safety as per new established pattern
* Refactored `ConsentBreakdownModal` to use the new hook, reducing component complexity
* Added `clickAntTab` Cypress command that handles tab clicking with proper timing
* Updated Cypress tests to use the new `clickAntTab` command instead of manual selectors
* Enhanced `getAntTab` selector to …

Apply new hooks to existing action center tables

---

CHANGELOG.md
clients/fides-js/src/components/tcf/TcfConsentButtons.tsx
clients/fides-js/src/components/tcf/TcfLoadingErrorMessage.tsx
clients/privacy-center/cypress/e2e/consent-banner-tcf.cy.ts

Closes [ENG-1080]
Handle the case where GVL (Global Vendor List) data is missing for a full TCF experience by displaying a loading error message instead of infinitely spinning consent buttons. Updated the error message component to optionally exclude accept/reject actions and adjusted its usage accordingly. Added a Cypress test to verify the error message appears when GVL data is missing.
* Updated `TcfConsentButtons.tsx` to check for missing GVL data and render `TcfLoadingErrorMessage` when appropriate.
* Enhanced `TcfLoadingErrorMessage.tsx` to support optional exclusion of accept/reject actions and improved conditional rendering.
* Added a Cypress test in `consent-banner-tcf.cy.ts` to confirm the error message is shown when GVL data is missing.
1. Configure a TCF experience in Admin UI …

handle missing GVL from full experience

---

clients/admin-ui/src/features/common/dropdown/DataCategorySelect.tsx
clients/admin-ui/src/features/common/dropdown/DataUseSelect.tsx
clients/admin-ui/src/features/common/dropdown/FilterSelect.tsx
clients/admin-ui/src/features/common/dropdown/TaxonomySelect.tsx
clients/admin-ui/src/features/common/form/FormikDateTimeInput.tsx
clients/admin-ui/src/features/common/form/FormikLocationSelect.tsx
clients/admin-ui/src/features/common/form/FormikSelect.tsx
clients/admin-ui/src/features/common/form/FormikTextInput.tsx
clients/admin-ui/src/features/common/form/inputs.tsx
clients/admin-ui/src/features/integrations/configure-monitor/ConfigureWebsiteMonitorForm.tsx
clients/admin-ui/src/features/integrations/configure-monitor/FormikSharedConfigSelect.tsx
clients/fidesui/src/components/data-entry/Form.stories.tsx
clients/fidesui/src/components/select/LocationSelect.stories.ts
clients/fidesui/src/components/select/LocationSelect.tsx
clients/fidesui/src/hoc/CustomSelect.tsx
clients/fidesui/src/index.ts

Closes [ENG-1223]
Fixed the Location Select component from not being wired into formik correctly
- Hooked up the location select component to formik
- Refactored web monitor form too use ant components + use components that aren't heavily tied to formik
- Improved ant's select prop types to use a discriminated union so that values can be more accurately represented
1. Visit `/integrations/ethyca#data-discovery` and go open the edit and create modals
2. Verify that the location select component now correctly submits values
3. Confirm that no functionality has been lost in the refactoring of the form and input components
[ENG-1223]: https://ethyca.atlassian.net/browse/ENG-1223?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTR …

fix: web monitor locations select [ENG-1223]

---

CHANGELOG.md
clients/admin-ui/src/features/datamap/DatamapSystemNode.module.scss

Updated the styling for Data lineage nodes in the datamap to use a neutral color scheme for improved visual consistency and readability. The nodes now have a light gray background with dark text instead of the previous styling.
* Updated `DatamapSystemNode.module.scss` to use neutral color palette for default node state:
* Background color: `neutral-100` (light gray)
* Border color: `neutral-200` (medium gray)
1. Add systems 
2. Navigate to the datamap feature in the admin UI
3. Verify that data lineage nodes display with the new neutral color scheme
4. Confirm that text remains readable and has sufficient contrast
5. Test hover and focus states to ensure they still work correctly

update datamap lineage colors

---

src/fides/api/api/v1/endpoints/user_endpoints.py

Closes [ENG-1282]
Adds scopes to docstrings instead of variable names.
[ENG-1282]: https://ethyca.atlassian.net/browse/ENG-1282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-1282: Update User API docstrings with scopes

---

clients/admin-ui/src/features/datamap/datamap-drawer/DatamapDrawer.tsx

Closes [ENG-491]
Bump drawer z index to show above headers.
[ENG-491]: https://ethyca.atlassian.net/browse/ENG-491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-491: System drawer in datamap report

---

src/fides/api/schemas/saas/connector_template.py
src/fides/api/service/connectors/saas/connector_registry_service.py
src/fides/api/util/connection_type.py
src/fides/api/util/saas_util.py
tests/ops/service/connectors/test_connector_template_loaders.py
tests/ops/util/test_connection_type.py

Fixes a performance issue with the updates to include display_info by reusing the connector template cache.
* Added new properties from display_info (category, tags and enabled features) to the Connector template
* Load the new properties during startup on connector_registry_service.py
* Add new util to extract values from display_info and fallback to None for the values if the is no display_info 
* Removed code in connection type template that used to load the display_info properties separately and replaced it with reading from the connector template
* Update tests
1.  Test passes
2. Login to admin-ui and go to the Settings > Integrations page
3. Make sure you have at least 3-4 integrations, if not, create a few integrations with random information
4. Open browser dev tools and look at …

Update connector template to include cached display_info properties

---

src/fides/config/security_settings.py
tests/ops/api/test_ratelimit.py

Unticketed
https://github.com/ethyca/fides/actions/runs/17407756736/job/49416650377
Merging https://ethyca.atlassian.net/browse/ENG-117 from private fork causes some CI to fail due to differing env vars between local and test.
* Adds check for existence of env var before validating.
1.  Run `nox -s dev` and confirm server starts up correctly

Fix failing cypress tests on main

---

CHANGELOG.md
clients/admin-ui/src/features/user-management/NewPasswordModal.tsx
clients/admin-ui/src/features/user-management/UpdatePasswordModal.tsx
clients/admin-ui/src/features/user-management/logout-helpers.ts
src/fides/api/api/v1/endpoints/user_endpoints.py
src/fides/api/models/client.py
src/fides/api/models/fides_user.py
src/fides/api/oauth/utils.py
tests/ops/api/v1/endpoints/test_user_endpoints.py

Closes [ENG-681]
This is to re-implement ENG-681, which was reverted due to its impact on FidesPlus/unit tests. This has been refactored to not require the changes the the OAuth client test fixture.
Invalidates exisitng sessions for a user when their password has been reset
1.  Login as a user
2. Change the pw for that user
3. Watch the session get invalidated
[ENG-681]: https://ethyca.atlassian.net/browse/ENG-681

ENG-681 Re implement pw reset session invalidation

---

CHANGELOG.md
clients/admin-ui/src/features/integrations/configure-monitor/ConfigureWebsiteMonitorForm.tsx

Closes [ENG-1316]
Re-enables the `exclude domains` field for the website monitor config form
- Remove the disabled prop on `exclude domains` select component
- Fix the value prop on the `exclude domains` select component
- Adding `excludeDomains` initial value
1. Visit `/integrations/ethyca#data-discovery`
2. Edit or create a new monitor
3. Confirm that the `exclude domains` field functions correctly, allows input, and submits
[ENG-1316]: https://ethyca.atlassian.net/browse/ENG-1316?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: website monitor config exclude domains [ENG-1316]

---

CHANGELOG.md
clients/admin-ui/src/features/integrations/configure-monitor/ConfigureWebsiteMonitorForm.tsx
clients/admin-ui/src/features/integrations/configure-monitor/MonitorConfigTab.tsx

Closes [ENG-1305]
Fixing location select props and display within table
1.  Confirm that the location select input no longer accepts any value
2. Confirm that the regions table value displays correctly when values are set
[ENG-1305]: https://ethyca.atlassian.net/browse/ENG-1305?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: location select mode and table display [ENG-1305]

---

CHANGELOG.md
src/fides/api/util/rate_limit.py

Closes https://ethyca.atlassian.net/browse/ENG-1315
Adds safeguards when encountering rate limit errors upon instantiation. Allows rate_limiting to still function given a Redis pass does not include special chars like `[` or `]`
* Uses disabled `Limiter` in the cases where either 1. rate limiting is disabled, or 2. we encounter any errors when instantiating the redis-driven `Limiter`
1.  In `docker_compose.yml`, update `services` -> `redis` -> `command` password to an invalid / unsupported password that contains `[` or `]`, e.g. `command: redis-server --requirepass "passwor[d"`
2. In your `.env`, set the same pass in the `FIDES__REDIS__PASSWORD` var
3. Remove any existing `FIDES__SECURITY__RATE_LIMIT_CLIENT_IP_HEADER` rate limit env var
4. Start up fides using `nox -s dev`
5. Observe …

Adds safeguards when encountering rate limit errors upon instantiation

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-notices/PrivacyNoticeTranslationForm.tsx

For the language picker, the search should filter by the display value instead of the language code.
* Added optionFilterProp="label" (default is "value")
1.  Go to preview url -> https://fides-plus-nightly-git-eng-1322-search-by-languag-4ffb8e-ethyca.vercel.app/consent/privacy-notices/pri_824f8b4f-0cd0-4570-9831-1c3bd8304b87
2. Login using nightly build credentials
3. Try to add a new language translation and search for "Ger"
4. Check German appears in the dropdown as a selectable option
(previously it wouldn't show up because it was searching by the "DE" language code)

Fix search within language picker in admin-ui

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/action-center/assets-results.cy.ts
clients/admin-ui/cypress/e2e/action-center/systems-aggregate.cy.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useActionCenterTabs.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredAssetsTable.tsx

Closes [ENG-1234]
Renamed the "Recent activity" tab in the Action Center to "Added" to better reflect its purpose.
* Updated tab label from "Recent activity" to "Added" in `useActionCenterTabs.tsx`
* Changed enum value from `RECENT_ACTIVITY` to `ADDED` in `ActionCenterTabHash`
* Updated URL hash routing from `#recent-activity` to `#added`
* Modified selection logic in `useDiscoveredAssetsTable.tsx` to reference the new tab hash
* Updated Cypress E2E tests in both `assets-results.cy.ts` and `systems-aggregate.cy.ts` to use new tab name and hash
* Updated test comments to reflect the new "added" tab terminology
1. Navigate to the Action Center in the admin UI
2. Verify the tab is now labeled "Added" instead of "Recent activity"
3. Confirm clicking the tab updates the URL hash to `#added`
4. …

rename tab "Recent activity" -> "Added"

---

CHANGELOG.md
clients/privacy-center/features/external-manual-tasks/components/ExternalAuthLayout.tsx
clients/privacy-center/features/external-manual-tasks/components/ExternalTaskLayout.tsx

Closes ENG-1371
Fix custom logos in external task portal. Using the Next.js Image tag requires to whitelist the domain, which is not something we have implemented. Changing it to a regular img tag just like the one on the homepage fixes the issue.
* Change Next.js image tag to basic html <img> tag
1. Change your config.json logo_path to be an external image url
2. Make sure your clients/privacy-center.env has `FIDES_PRIVACY_CENTER__ENABLE_EXTERNAL_TASK_PORTAL=true `
3. Visit http://localhost:3001/external-tasks and confirm the logo displays correctly

Fix custom logos in external task portal

---

CHANGELOG.md
optional-requirements.txt

Bumps `pymssql` from version `2.3.4` to `2.3.7` in `optional-requirements.txt` to resolve build dependency conflicts on Apple Silicon (ARM64) systems.
The previous version `2.3.4` had incompatible `setuptools_scm` version constraints that prevented installation on macOS devices with Apple Silicon processors. Version `2.3.7` resolves these dependency conflicts.
```
~ ❯ pip install pymssql==2.3.4
Collecting pymssql==2.3.4
Using cached pymssql-2.3.4.tar.gz (184 kB)
Installing build dependencies ... done
Getting requirements to build wheel ... done
ERROR: Some build dependencies for pymssql==2.3.4 from https://files.pythonhosted.org/packages/83/35/5a0b79369e42fffd5c04e4e74fa90ef034cc5c3f314e14f6d58cac646ccf/pymssql-2.3.4.tar.gz conflict with the backend dependencies: …
```

chore: bump pymssql to latest (2.3.7)

---

CHANGELOG.md
clients/admin-ui/src/features/privacy-requests/RequestTable.tsx
clients/admin-ui/src/features/privacy-requests/RequestTableColumns.tsx

Closes ENG-1463
The conditional Source column was causing column width issues, the simplest solution is to make it available for OSS as well and avoid that conditional rendering. The OSS shows the "Privacy Center" value as source correctly.
* Remove checking for hasPlus in the "Source" column of the Request Manager
1.  Open Request Manager in a big resolution browser
2. Check the Source column doesn't have an excessive width
excessive width
correct width

Fix column sizing bug

---

clients/admin-ui/src/features/system/system.slice.ts

Updating `GetSystemsQueryParams` type. It was changed in `main` but not in the release branch so it didn't make it over when we cherry picked https://github.com/ethyca/fides/pull/6603
* Updated `GetSystemsQueryParams` type
1.  Images should build and tests should pass

Fixing get system query params type

---

.fides/db_dataset.yml
src/fides/api/alembic/migrations/versions/e2cda8d6abc3_add_dismissed_in_activity_view_to_.py
src/fides/api/models/detection_discovery/monitor_task.py

Closes [ENG-1236]
Adds a new boolean field dismissed_in_activity_view to the monitortask model to support the in-progress/“dismissed” state for the Action Center. Includes an Alembic migration to add/drop the column. The migration’s down_revision is set to the current main head (0eef0016cf06).
* Migration
1.  Not needed
[ENG-1236]: https://ethyca.atlassian.net/browse/ENG-1236?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

ENG-1236 add migration for dismissed column in monitor tasks

---

CHANGELOG.md
src/fides/service/privacy_request/privacy_request_service.py
tests/service/test_privacy_request_service.py

Closes [ENG-1347]
API error when privacy request is made with no location and location is required
Adds the error response and tests to confirm
1.  Need to run fidesplus with this (your property ID), and update you config like this
❗ this will overwrite your PC config ❗ 
```
curl -X PUT http://localhost:3000/api/v1/plus/property/FDS-YOURS \
-H "Authorization: Bearer $YOUR_TOKEN" \
-H "Content-Type: application/json" \
-d '{
"name": "Default Property Autogenerated",
"type": "Website",
"experiences": [],
"paths": [],
"privacy_center_config": {
"title": "Take control of your data",
"description": "When you use our services, you're trusting us with your information. We understand this is a big responsibility and work hard to protect your information and put you in control.", …
```

ENG-1347 - show error when privacy request is made with no location and location is required

---

tests/ctl/core/test_dataset.py
tests/ops/service/connectors/test_bigquery_queryconfig.py

These tests have been flaky in `main` (presumably because of many parallel CI jobs hitting the same snowflake instance): https://github.com/ethyca/fides/actions/runs/17986669831/job/51167996075#step:9:934
So we'll remove them, which should be fine, because this codepath for CLI-based database detection is basically deprecated and Helios is our supported path for doing this.
Also `xfail`ing some bigquery connector tests that were also flaky
* comment out snowflake db scan tests
* `xfail` more bigquery connector tests

bypass some flaky external BE tests (snowflake DB scan, bigquery connector)

---

clients/admin-ui/cypress/e2e/custom-fields.cy.ts
clients/admin-ui/src/features/custom-fields/CustomFieldForm.tsx
clients/admin-ui/src/pages/settings/custom-fields/[id].tsx
clients/admin-ui/src/pages/settings/custom-fields/new.tsx

Closes ENG-1526
Fixes an issue where, when editing a select or multi-select custom field, the "options" field in the form would fail to populate due the form's initial values being set before the GET allow-list query resolved.  The form should now show a skeletal form while the allow list is loading.
1. Go to "custom fields"
2. Create a new single- or multi-select custom field or use an existing
3. Edit the field
4. Should see the "options" populated in the form on load

Fix bug where select options wouldn't populate in edit custom field form 

---

CHANGELOG.md
clients/admin-ui/src/features/common/dropdown/TaxonomySelect.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/AddDataUsesModal.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/ConsentCategorySelect.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetDataUseCell.tsx
clients/admin-ui/src/features/system/system-groups/components/CreateSystemGroupForm.tsx
clients/admin-ui/src/features/system/system-groups/components/DataUseSelectWithSuggestions.tsx
clients/admin-ui/src/features/system/table/useSystemsTable.tsx
clients/admin-ui/src/features/taxonomy/components/SystemGroupEditForm.tsx
clients/admin-ui/src/features/taxonomy/components/TaxonomyEditForm.tsx
clients/fidesui/src/ant-theme/global.scss
clients/fidesui/src/hoc/CustomTag.tsx

Closes [ENG-1434]
Enhanced the taxonomy selection components to support grouped options, allowing for better organization and discoverability of data uses. The consent category selector now displays all available data uses with "Categories of consent" grouped as recommended options at the top, rather than limiting the selection to only consent categories.
* Enhanced `TaxonomySelect` component to support option groups with new `TaxonomySelectOptionGroup` interface and helper functions
* Refactored `ConsentCategorySelect` to display all data uses with consent categories grouped as "Recommended" and other data uses in a separate group
* Updated `DiscoveredAssetDataUseCell` to display all assigned data uses instead of filtering to only consent categories
* Added keyboard support (Escape key) …

Support more specific data uses in Categories of consent

---

clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredAssetsTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetActionsCell.tsx

Closes ENG-1540
Fix compliance issue warning button showing when you don't have the Consent status featured flag enabled
* Add flag check on the condition to show the button
1.  Go to [this preview link](https://fides-plus-nightly-git-eng-1540-fe-consent-compli-d8f818-ethyca.vercel.app/settings/about)
2. Confirm the "Asset consent status labels" flag is off and "Web monitor" is on
3. Go to [this results page](https://fides-plus-nightly-git-eng-1540-fe-consent-compli-d8f818-ethyca.vercel.app/data-discovery/action-center/test_monitor_results/gvl.804#attention-required)
4. Check the warning icon doesn't show in the actions column
5. Now, turn the flag on
6. Go to [this results page](https://fides-plus-nightly-git-eng-1540-fe-consent-compli-d8f818-ethyca.vercel.app/data-discovery/action-center …

Fix compliance issue warning showing without corresponding feature flag enabled

---

src/fides/api/models/__init__.py
src/fides/api/models/privacy_notice.py
tests/ops/models/test_privacy_notice.py

Unticketed
Fixes a crash when creating `PrivacyNoticeHistory` after accessing `PrivacyNotice.cookies`. The `cookies` property on `PrivacyNotice` was [recently updated](https://github.com/ethyca/fides/pull/6593/files#diff-163f9e368e31215ee24ddaed03376f07313bea4488f74387edd0393bd958c334R285) to be a `@cached_property`. This causes cookies to be stored on the instance and included when cloning `__dict__`, which didn't happen before with a normal `@property` annotation. 
Our PrivacyNoticeHistory builder clones the model `__dict__`, so cookies leaked into the payload and caused `TypeError: 'cookies' is an invalid keyword argument for PrivacyNoticeHistory`. 
We now clone only SQLAlchemy-mapped columns instead of copying `__dict__`.
* `fides/src/fides/api/models/__init__.py`:
Replace …

Explicitly drop cookies prop when creating historical preferences

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/action-center/assets-results.cy.ts
clients/admin-ui/cypress/fixtures/detection-discovery/activity-center/system-asset-results-with-consent.json
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetActionsCell.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetDataUseCell.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/SystemCell.tsx
clients/admin-ui/src/features/system/tabs/system-assets/AssetSystemCell.tsx

Closes [ENG-1445]
Truncated long asset and system names in toast notifications to prevent the dismiss button from being pushed off-screen. Asset and system names are now limited to 50 characters with ellipsis when displayed in success and error toasts throughout the Action Center.
* Imported `truncate` from lodash in affected cell components
* Truncated asset names to 50 characters in `DiscoveredAssetActionsCell`, `DiscoveredAssetDataUseCell`, and `SystemCell` components
* Truncated both asset and system names to 50 characters in `AssetSystemCell` component
* Updated Cypress test fixture with a long asset name to validate truncation
* Updated Cypress test expectations to match truncated output
* Added `{ force: true }` to Cypress click action for taxonomy add button
1. Navigate to Action …

Handle long cookie or system names in toasts

---

CHANGELOG.md
clients/admin-ui/cypress/e2e/integration-management.cy.ts
clients/admin-ui/src/features/common/table/cells/EnableCell.tsx
clients/admin-ui/src/features/common/table/v2/cells.tsx
clients/admin-ui/src/features/integrations/configure-monitor/ConfigureWebsiteMonitorForm.tsx
clients/admin-ui/src/features/integrations/configure-monitor/MonitorConfigActionsCell.tsx
clients/admin-ui/src/features/integrations/configure-monitor/MonitorConfigEnableCell.tsx
clients/admin-ui/src/features/integrations/configure-monitor/MonitorConfigTab.tsx
clients/admin-ui/src/features/integrations/hooks/useMonitorConfigTable.tsx
clients/admin-ui/src/pages/integrations/[id].tsx

Closes [ENG-1302], [ENG-709], [ENG-1187]
Migrated the Monitor Configuration table to Ant Design. Extracted table logic into a reusable hook (`useMonitorConfigTable`) and created an Ant Design version of the `EnableCell` component. Deprecated the old Chakra-based `EnableCell` to align with the ongoing migration from Chakra to Ant Design.
* Migrated `MonitorConfigTab` from TanStack Table v2 to Ant Design Table
* Created `useMonitorConfigTable` hook to encapsulate table state, data fetching, and column definitions
* Created Ant Design version of `EnableCell` component in `~/features/common/table/cells/`
* Deprecated Chakra-based `EnableCell` in `~/features/common/table/v2/cells.tsx`
* Refactored `MonitorConfigEnableCell` to use the new Ant `EnableCell` and accept `record` prop instead of …

Migrate Monitor Config Table to Ant

---

CHANGELOG.md
clients/admin-ui/src/features/common/table/cells/TagExpandableCell.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetDataUseCell.tsx

Closes [ENG-1319]
Fixed an issue where expanded table cells would automatically collapse when the parent component rerenders. Also added auto-collapse logic for cells with fewer items than the display threshold.
* Added `onStateChange` callback prop to `TagExpandableCell` to notify parent components of expansion state changes
* Lifted `isExpanded` state to `DiscoveredAssetDataUseCell` to persist across component rerenders
* Added separate `useEffect` in `TagExpandableCell` to auto-collapse cells when values are below the display threshold
* Updated `handleCollapse` and `handleExpand` callbacks to invoke `onStateChange` with the new state
* Synchronized parent `isExpanded` state with `columnState?.isExpanded` via `useEffect`
* Passed lifted `isExpanded` state to `TagExpandableCell` in …

Track expanded state between renders

---

clients/admin-ui/src/features/data-discovery-and-detection/action-center/fields/page.tsx

Small change to correct the mapping of diff status and the resource status label

fix: diff status mapping

---

.github/workflows/cypress_admin-ui.yml
CHANGELOG.md
clients/admin-ui/cypress/e2e/action-center/assets-results.cy.ts
clients/admin-ui/cypress/support/stubs.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/ConsentCategorySelect.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/action-center.slice.ts
clients/admin-ui/src/features/data-discovery-and-detection/action-center/hooks/useDiscoveredAssetsTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/DiscoveredAssetsTable.tsx
clients/admin-ui/src/features/data-discovery-and-detection/action-center/tables/cells/DiscoveredAssetDataUseCell.tsx
clients/admin-ui/src/pages/data-discovery/action-center/[monitorId]/[systemId]/index.tsx

Closes [ENG-1132], [ENG-1519]
Changed the default sort order for discovered assets from "Compliance + URN" to "Asset name". Added support for filtering system aggregate results by `resolved_system_id` which helped improve the consent status handling by passing consent alert information from the system aggregate query to the table component, eliminating local state management and ensuring the compliance column header icon remains visible regardless of pagination.
Enhanced the consent category select dropdown by filtering out already-selected taxonomies and sorting the data uses alphabetically. (ENG-1519)
* Updated default sort in `getDiscoveredAssetsQuery` from `[CONSENT_AGGREGATED, "urn"]` to `[NAME]`
* Added `resolved_system_id` parameter to `getDiscoveredSystemAggregateQuery` endpoint
* …

Website monitor assets default sort
